#pragma once
class IGameEvents
{
public:

	static IGameEvents g_gameEvents;
	static bool g_logGameEventMessages;

	virtual void EventWriteAchievementEarned(LPWSTR UserID, GUID PlayerSessionID, LPWSTR HaloTitleID, INT32 AchievementID);
	virtual void EventWriteAshesToAshes(LPWSTR UserID, GUID PlayerSessionID);
	virtual void EventWriteAssist(LPWSTR UserID, INT32 SectionID, GUID PlayerSessionID, LPWSTR MultiplayerCorrelationID, INT32 GameplayModeID, INT32 DifficultyLevelID, GUID RoundID, INT32 PlayerRoleID, INT32 PlayerWeaponID, INT32 EnemyRoleID, INT32 KillTypeID, float LocationX, float LocationY, float LocationZ, INT32 EnemyWeaponID, LPWSTR HaloTitleID, INT32 MapID, INT32 EnemyClassID, INT32 GameCategoryID, bool MatchMade);
	virtual void EventWriteAudioLogClaimed(LPWSTR UserID, GUID PlayerSessionID, INT32 AudioLogID);
	virtual void EventWriteBase(LPWSTR UserID, GUID PlayerSessionID);
	virtual void EventWriteBetrayal(LPWSTR UserID, INT32 SectionID, GUID PlayerSessionID, LPWSTR MultiplayerCorrelationID, INT32 GameplayModeID, INT32 DifficultyLevelID, GUID RoundID, INT32 PlayerRoleID, INT32 PlayerWeaponID, INT32 EnemyRoleID, INT32 KillTypeID, float LocationX, float LocationY, float LocationZ, INT32 EnemyWeaponID, LPWSTR HaloTitleID, INT32 MapID, INT32 EnemyClassID, INT32 GameCategoryID, bool MatchMade);
	virtual void EventWriteBIFactControllerSettings(LPWSTR UserID, GUID PlayerSessionID, bool IsGuest, LPWSTR HaloTitleID, INT32 GameCategoryID, INT32 ControllerConfigurationID, bool LookInverted);
	virtual void EventWriteBIFactDeepLink(LPWSTR UserID, GUID PlayerSessionID);
	virtual void EventWriteBIFactDeepLinkRecieve(LPWSTR UserID, GUID PlayerSessionID, LPWSTR DeepLinkCorrelationID, LPWSTR DeepLinkURL);
	virtual void EventWriteBIFactDeepLinkSend(LPWSTR UserID, GUID PlayerSessionID, LPWSTR DeepLinkCorrelationID, LPWSTR DeepLinkURL);
	virtual void EventWriteBIFactDualWield(LPWSTR UserID, GUID PlayerSessionID, bool IsGuest, LPWSTR HaloTitleID, INT32 GameCategoryID, INT32 LeftWeaponID, INT32 RightWeaponID, FILETIME DualWieldTimeStamp);
	virtual void EventWriteBIFactGameSession(LPWSTR UserID, GUID PlayerSessionID, FILETIME SessionStartTimeStamp, FILETIME SessionEndTimeStamp, LPWSTR HaloTitleID, FILETIME SubTitleStartTimeStamp, FILETIME SubTitleEndTimeStamp, INT32 GameCategoryID, LPWSTR LocaleID, INT32 MapID, INT32 ArmorID, UINT64 SkullsUsed, LPWSTR HopperID, INT32 PlayerCount, bool Matchmade, INT32 MatchmakingRank, double MatchmakingRating, INT32 MatchmakingXP, bool Won, UINT64 Score, UINT64 TeamScore, INT32 Standing, bool FirstPlace, INT32 Kills, INT32 Deaths, INT32 Assists, INT32 Betrayals, INT32 Suicides);
	virtual void EventWriteBIFactLoadout(LPWSTR UserID, GUID PlayerSessionID, bool IsGuest, LPWSTR HaloTitleID, INT32 GameCategoryID, INT32 PrimaryWeaponID, INT32 SecondaryWeaponID, INT32 GrenadeID, INT32 ShieldID);
	virtual void EventWriteBIFactMatchmaking(LPWSTR UserID, GUID PlayerSessionID, bool IsGuest, LPWSTR LobbyID, FILETIME LobbyEntryTimeStamp, bool JoinedMatch, FILETIME JoinMatchTimeStamp, INT32 MatchmakingRank, double MatchmakingRating, INT32 MatchmakingXP, INT32 PartySize, GUID PartyID);
	virtual void EventWriteBIFactMatchmakingDetails(LPWSTR UserID, GUID PlayerSessionID, INT32 NumPlayersInParty, bool GSRFired, bool BecameActiveInSession, bool ConnectedToPeerGameHost, bool GameStarted, FILETIME LobbyEntryTimeStamp, FILETIME LobbyExitTimeStamp, INT32 ExitReason, LPWSTR GameUniqiueID, bool IsArbiter, bool IsThunderheadGame, INT32 NumPlayers, INT32 NumPreserveSessionTicketsCreated);
	virtual void EventWriteBIFactMedia(LPWSTR UserID, GUID PlayerSessionID, bool IsGuest, LPWSTR HaloTitleID, FILETIME MediaStartTimeStamp, bool WasSkipped, FILETIME MediaSkipTimeStamp, LPWSTR MediaID);
	virtual void EventWriteBirdOfPrey(LPWSTR UserID, GUID PlayerSessionID);
	virtual void EventWriteBitsAndPiecesDestroyed(LPWSTR UserID, GUID PlayerSessionID);
	virtual void EventWriteBroadcastingAssist(LPWSTR UserID, GUID PlayerSessionID, FILETIME TimeStamp, INT32 CurrentAssists);
	virtual void EventWriteBroadcastingDeath(LPWSTR UserID, GUID PlayerSessionID, FILETIME TimeStamp, LPWSTR VictimXuid, UINT32 VictimTeamID, LPWSTR KillerXuid, UINT32 KillerTeamID, LPWSTR AssistantXuids, UINT32 DamageReportingModifier, INT32 StockID, INT32 AttachmentIDs, INT32 DamageTypeID, INT32 CurrentDeaths);
	virtual void EventWriteBroadcastingHeartbeat(LPWSTR UserID, GUID PlayerSessionID, INT64 Heartbeat);
	virtual void EventWriteBroadcastingKill(LPWSTR UserID, GUID PlayerSessionID, FILETIME TimeStamp, LPWSTR VictimXuid, UINT32 VictimTeamID, LPWSTR KillerXuid, UINT32 KillerTeamID, LPWSTR AssistantXuids, UINT32 DamageReportingModifier, INT32 StockID, INT32 AttachmentIDs, INT32 DamageTypeID, INT32 CurrentKills);
	virtual void EventWriteBroadcastingMatchEnd(LPWSTR UserID, GUID PlayerSessionID, FILETIME TimeStamp);
	virtual void EventWriteBroadcastingMatchRoundEnd(LPWSTR UserID, GUID PlayerSessionID, FILETIME TimeStamp);
	virtual void EventWriteBroadcastingMatchRoundStart(LPWSTR UserID, GUID PlayerSessionID, FILETIME TimeStamp, INT32 RoundNumber);
	virtual void EventWriteBroadcastingMatchStart(LPWSTR UserID, GUID PlayerSessionID, FILETIME TimeStamp, INT32 MapVariantID, INT32 GameVariantID, LPWSTR PlaylistID);
	virtual void EventWriteBroadcastingMedal(LPWSTR UserID, GUID PlayerSessionID, FILETIME TimeStamp, INT32 MedalID);
	virtual void EventWriteBroadcastingPlayerJoined(LPWSTR UserID, GUID PlayerSessionID, FILETIME TimeStamp, INT32 TeamID);
	virtual void EventWriteBroadcastingPlayerLeft(LPWSTR UserID, GUID PlayerSessionID, FILETIME TimeStamp);
	virtual void EventWriteBroadcastingPlayerSpawn(LPWSTR UserID, GUID PlayerSessionID, FILETIME TimeStamp);
	virtual void EventWriteBroadcastingPlayerSwitchedTeams(LPWSTR UserID, GUID PlayerSessionID, FILETIME TimeStamp, INT32 TeamID, LPWSTR WebColor);
	virtual void EventWriteBroadcastingScore(LPWSTR UserID, GUID PlayerSessionID, INT32 ControllerIndex, FILETIME Timestamp, INT32 CurrentRoundScore, INT32 CurrentTotalScore, INT32 CurrentRoundTeamScore, INT32 CurrentTotalTeamScore);
	virtual void EventWriteBroadcastingStart(LPWSTR UserID, GUID PlayerSessionID, UINT32 GameType, UINT32 Map, UINT32 TopPlayerRank, LPWSTR PlayerIDs, GUID MatchID, bool PlayerIsCaster, INT64 MatchStartTime);
	virtual void EventWriteCampaignDifficulty(LPWSTR UserID, GUID PlayerSessionID, LPWSTR HaloTitleID, LPWSTR CampaignDifficulty);
	virtual void EventWriteChallengeCompleted(LPWSTR UserID, GUID PlayerSessionID, LPWSTR HaloTitleID, INT32 ChallengeID);
	virtual void EventWriteClassicModeSwitched(LPWSTR UserID, GUID PlayerSessionID, INT32 MapID);
	virtual void EventWriteCleverGirl(LPWSTR UserID, GUID PlayerSessionID);
	virtual void EventWriteClueClaimed(LPWSTR UserID, GUID PlayerSessionID, INT32 ClueID);
	virtual void EventWriteCoopMissionCompleted(LPWSTR UserID, GUID PlayerSessionID, LPWSTR HaloTitleID, INT32 MissionID, INT32 MapID, INT32 MissionScore, bool IronSkullUsed, bool BlackEyeSkullUsed, bool ToughLuckSkullUsed, bool CatchSkullUsed, bool CloudSkullUsed, bool FamineSkullUsed, bool ThunderstormSkullUsed, bool TiltSkullUsed, bool MythicSkullUsed, bool BlindSkullUsed, INT32 DifficultyID);
	virtual void EventWriteCoopSpartanOpsMissionCompleted(LPWSTR UserID, GUID PlayerSessionID, LPWSTR HaloTitleID, INT32 MapID, INT32 DifficultyID);
	virtual void EventWriteCompletionCount(LPWSTR UserID, GUID PlayerSessionID, INT32 Count);
	virtual void EventWriteCustomization(LPWSTR UserID, GUID PlayerSessionID, INT32 Texture0, INT32 Texture1, INT32 Color0, INT32 Color1, INT32 Color2, LPWSTR ServiceID, LPWSTR ClanID, INT32 AvatarID, INT32 NameplateID);
	virtual void EventWriteDashboardContext(LPWSTR UserID, GUID PlayerSessionID, LPWSTR DashboardContext);
	virtual void EventWriteDeath(LPWSTR UserID, INT32 SectionID, GUID PlayerSessionID, LPWSTR MultiplayerCorrelationID, INT32 GameplayModeID, INT32 DifficultyLevelID, GUID RoundID, INT32 PlayerRoleID, INT32 PlayerWeaponID, INT32 EnemyRoleID, INT32 KillTypeID, float LocationX, float LocationY, float LocationZ, INT32 EnemyWeaponID, LPWSTR HaloTitleID, INT32 MapID, INT32 EnemyClassID, INT32 GameCategoryID, bool MatchMade, bool HeadShot);
	virtual void EventWriteDollFound(LPWSTR UserID, GUID PlayerSessionID, INT32 DollID);
	virtual void EventWriteEliteWin(LPWSTR UserID, GUID PlayerSessionID, LPWSTR HaloTitleID, bool MatchMade);
	virtual void EventWriteEmblem(LPWSTR UserID, GUID PlayerSessionID, INT32 Texture0, INT32 Texture1, INT32 Color0, INT32 Color1, INT32 Color2);
	virtual void EventWriteEnemyDefeated(LPWSTR UserID, INT32 SectionID, GUID PlayerSessionID, LPWSTR MultiplayerCorrelationID, INT32 GameplayModeID, INT32 DifficultyLevelID, GUID RoundID, INT32 PlayerRoleID, INT32 PlayerWeaponID, INT32 EnemyRoleID, INT32 KillTypeID, float LocationX, float LocationY, float LocationZ, INT32 EnemyWeaponID, LPWSTR HaloTitleID, INT32 MapID, INT32 EnemyClassID, INT32 GameCategoryID, bool MatchMade, bool HeadShot);
	virtual void EventWriteFriendsBestedOnHeroLeaderboard(LPWSTR UserID, GUID PlayerSessionID, INT32 LeaderboardID, INT32 LeaderboardRows);
	virtual void EventWriteGameProgress(LPWSTR UserID, GUID PlayerSessionID, float CompletionPercent);
	virtual void EventWriteGameVarSaved(LPWSTR UserID, GUID PlayerSessionID, LPWSTR HaloTitleID, INT32 BaseGameCategory, LPWSTR GameVarName);
	virtual void EventWriteGrenadeStick(LPWSTR UserID, INT32 SectionID, GUID PlayerSessionID, LPWSTR MultiplayerCorrelationID, INT32 GameplayModeID, INT32 DifficultyLevelID, GUID RoundID, INT32 PlayerRoleID, INT32 PlayerWeaponID, INT32 EnemyRoleID, INT32 KillTypeID, float LocationX, float LocationY, float LocationZ, INT32 EnemyWeaponID, INT32 EnemyClassID);
	virtual void EventWriteHelloNurse(LPWSTR UserID, GUID PlayerSessionID);
	virtual void EventWriteInGamePresence(LPWSTR UserID, GUID PlayerSessionID, LPWSTR HaloTitle, INT32 CampaignDifficulty, INT32 MultiplayerMap);
	virtual void EventWriteISeeYou(LPWSTR UserID, GUID PlayerSessionID);
	virtual void EventWriteJoinability(LPWSTR UserID, GUID PlayerSessionID, bool InGame);
	virtual void EventWriteLobby(LPWSTR UserID, GUID PlayerSessionID, LPWSTR HaloTitleID, LPWSTR Lobby);
	virtual void EventWriteMainMenuPresence(LPWSTR UserID, GUID PlayerSessionID, LPWSTR MainMenuPresence);
	virtual void EventWriteMapVarSaved(LPWSTR UserID, GUID PlayerSessionID, LPWSTR HaloTitleID, INT32 BaseMapID, LPWSTR MapVarName);
	virtual void EventWriteMatchmakingHopper(LPWSTR UserID, GUID PlayerSessionID, LPWSTR HaloTitleID, LPWSTR MatchmakingHopper);
	virtual void EventWriteMediaUsage(LPWSTR AppSessionID, LPWSTR AppSessionStartDateTime, UINT32 UserIDType, LPWSTR UserID, LPWSTR SubscriptionTierType, LPWSTR SubscriptionTier, LPWSTR MediaType, LPWSTR ProviderID, LPWSTR ProviderMediaID, LPWSTR ProviderMediaInstanceID, GUID BingID, UINT64 MediaLengthMs, UINT32 MediaControlAction, float PlaybackSpeed, UINT64 MediaPositionMs, UINT64 PlaybackDurationMs, LPWSTR AcquisitionType, LPWSTR AcquisitionContext, LPWSTR AcquisitionContextType, LPWSTR AcquisitionContextID, INT32 PlaybackIsStream, INT32 PlaybackIsTethered, LPWSTR MarketplaceLocation, LPWSTR ContentLocale, float TimeZoneOffset, UINT32 ScreenState);
	virtual void EventWriteMeldOfferPresented(LPWSTR UserID, GUID PlayerSessionID, GUID OfferGuid, GUID ProductGuid, LPWSTR Page, INT32 SourceTileIndex);
	virtual void EventWriteMeldOfferResponded(LPWSTR UserID, GUID PlayerSessionID, GUID OfferGuid, GUID ProductGuid, INT32 UpsellOutcome);
	virtual void EventWriteMeldPageAction(LPWSTR UserID, GUID PlayerSessionID, INT32 ActionTypeID, INT32 ActionInputMethodID, LPWSTR Page, LPWSTR TemplateID, LPWSTR DestinationPage, LPWSTR Content, INT32 SourceTileIndex, INT32 SourceTileX, INT32 SourceTileY, INT32 SourceTileWidth, INT32 SourceTileHeight);
	virtual void EventWriteMeldPageView(LPWSTR UserID, GUID PlayerSessionID, LPWSTR Page, LPWSTR RefererPage, INT32 PageTypeID, LPWSTR PageTags, LPWSTR TemplateID, LPWSTR Content, LPWSTR FilterContext, INT32 FilterDirection);
	virtual void EventWriteMissionCompleted(LPWSTR UserID, GUID PlayerSessionID, LPWSTR HaloTitleID, INT32 MapID, INT32 GameCategoryID, bool Coop, UINT64 TimePlayedMS, UINT64 DatePlayedUTC, INT32 DifficultyID, UINT64 MissionScore64, UINT64 SkullUsedFlags, INT32 NumPlayers, LPWSTR PlayerSectionStats, INT32 Kills, float Multiplier, INT32 Penalties, float SkullMultiplier, INT32 TotalSoloMissionsComplete, INT32 TotalCoopMissionsComplete);
	virtual void EventWriteMortardomWraithsKilled(LPWSTR UserID, GUID PlayerSessionID);
	virtual void EventWriteMultiplayerGameEngine(LPWSTR UserID, GUID PlayerSessionID, LPWSTR HaloTitleID, LPWSTR MultiplayerGameEngine);
	virtual void EventWriteMultiplayerMap(LPWSTR UserID, GUID PlayerSessionID, LPWSTR HaloTitleID, LPWSTR MultiplayerMap);
	virtual void EventWriteMultiplayerRoundEnd(LPWSTR UserID, GUID RoundID, INT32 SectionID, GUID PlayerSessionID, LPWSTR MultiplayerCorrelationID, INT32 GameplayModeID, INT32 MatchTypeID, INT32 DifficultyLevelID, float TimeInSeconds, INT32 ExitStatusID);
	virtual void EventWriteMultiplayerRoundStart(LPWSTR UserID, GUID RoundID, INT32 SectionID, GUID PlayerSessionID, LPWSTR MultiplayerCorrelationID, INT32 GameplayModeID, INT32 MatchTypeID, INT32 DifficultyLevelID);
	virtual void EventWriteNappersCaught(LPWSTR UserID, GUID PlayerSessionID);
	virtual void EventWriteNewsStoryRead(LPWSTR UserID, GUID PlayerSessionID, LPWSTR StoryID);
	virtual void EventWriteObjectiveEnd(LPWSTR UserID, INT32 SectionID, GUID PlayerSessionID, LPWSTR MultiplayerCorrelationID, INT32 GameplayModeID, INT32 DifficultyLevelID, INT32 ObjectiveID, INT32 ExitStatusID);
	virtual void EventWriteObjectiveStart(LPWSTR UserID, INT32 SectionID, GUID PlayerSessionID, LPWSTR MultiplayerCorrelationID, INT32 GameplayModeID, INT32 DifficultyLevelID, INT32 ObjectiveID);
	virtual void EventWritePageAction(LPWSTR UserID, GUID PlayerSessionID, INT32 ActionTypeID, INT32 ActionInputMethodID, LPWSTR Page, LPWSTR TemplateID, LPWSTR DestinationPage, LPWSTR Content);
	virtual void EventWritePageView(LPWSTR UserID, GUID PlayerSessionID, LPWSTR Page, LPWSTR RefererPage, INT32 PageTypeID, LPWSTR PageTags, LPWSTR TemplateID, LPWSTR Content);
	virtual void EventWritePhantomHunter(LPWSTR UserID, GUID PlayerSessionID);
	virtual void EventWritePigsCanFly(LPWSTR UserID, GUID PlayerSessionID);
	virtual void EventWritePlayerCheckedInToday(LPWSTR UserID, GUID PlayerSessionID, LPWSTR HaloTitleID);
	virtual void EventWritePlayerDefeated(LPWSTR UserID, INT32 SectionID, GUID PlayerSessionID, LPWSTR MultiplayerCorrelationID, INT32 GameplayModeID, INT32 DifficultyLevelID, GUID RoundID, INT32 PlayerRoleID, INT32 PlayerWeaponID, INT32 EnemyRoleID, INT32 EnemyWeaponID, float LocationX, float LocationY, float LocationZ);
	virtual void EventWritePlayerGameResults(LPWSTR UserID, GUID PlayerSessionID, LPWSTR HaloTitleID, INT32 GameIndex, INT32 GameIndexByCategory, INT32 GameIndexByTitle, INT32 GameIndexByTitleCategory, INT32 MapID, INT32 GameCategoryID, bool MatchMade, bool Won, UINT64 TimePlayedMS, UINT64 DatePlayedUTC, UINT64 Score64, INT32 Standing, bool FirstPlace, INT32 MedalCount, INT32 Kills, INT32 Deaths, INT32 Assists, INT32 HeadShots, INT32 MostKillsInARow, LPWSTR CustomStat1ID, INT32 CustomStat1, LPWSTR CustomStat2ID, INT32 CustomStat2, LPWSTR CustomStat3ID, INT32 CustomStat3, LPWSTR CustomStat4ID, INT32 CustomStat4, GUID MatchID);
	virtual void EventWritePlayerGameResultsDamageStat(LPWSTR UserID, GUID PlayerSessionID, LPWSTR HaloTitleID, INT32 GameIndex, INT32 MapID, bool MatchMade, INT32 DamageReportingType, INT32 DamageStatisticType, INT32 DamageCount, INT32 GameCategoryID);
	virtual void EventWritePlayerGameResultsGriefingStat(LPWSTR UserID, GUID PlayerSessionID, LPWSTR HaloTitleID, INT32 GameIndex, INT32 MapID, bool MatchMade, float Betrayals, float ShieldDamage, float BodyDamage, float BetrayalPenalty, float ShieldDamagePenalty, float BodyDamagePenalty);
	virtual void EventWritePlayerGameResultsGriefingStats(LPWSTR UserID, GUID PlayerSessionID, LPWSTR HaloTitleID, INT32 GameIndex, INT32 MapID, bool MatchMade, float Betrayals, float ShieldDamage, float BodyDamage, float BetrayalPenalty, float ShieldDamagePenalty, float BodyDamagePenalty);
	virtual void EventWritePlayerGameResultsInterestStats(LPWSTR UserID, GUID PlayerSessionID, LPWSTR HaloTitleID, INT32 GameCategoryID, INT32 GameIndex, INT32 MapID, bool MatchMade, INT32 OrdnanceDrops, INT32 OrdnanceStrikes, UINT64 TimeMSDriven, INT32 UnitsDriven, UINT64 TimeMSPiloted, INT32 UnitsPiloted, UINT64 TimeMSPassenger, INT32 UnitsMovedPassenger, UINT64 TimeMSOnFoot, INT32 UnitsMovedOnFoot, INT32 DriverAssists, INT32 ArmorAbilityUseJetpack, INT32 ArmorAbilityUseHologram, INT32 ArmorAbilityUseReflectiveShield, INT32 ArmorAbilityUseActiveCamo, INT32 ArmorAbilityUseThrusterPack, INT32 ArmorAbilityUseAutoTurret, INT32 ArmorAbilityUseXRay);
	virtual void EventWritePlayerGameResultsMedal(LPWSTR UserID, GUID PlayerSessionID, LPWSTR HaloTitleID, INT32 GameIndex, INT32 MapID, bool MatchMade, INT32 MedalType, INT32 MedalCount);
	virtual void EventWritePlayerSessionEnd(LPWSTR UserID, GUID PlayerSessionID, LPWSTR MultiplayerCorrelationID, INT32 GameplayModeID, INT32 DifficultyLevelID, INT32 ExitStatusID);
	virtual void EventWritePlayerSessionPause(LPWSTR UserID, GUID PlayerSessionID, LPWSTR MultiplayerCorrelationID);
	virtual void EventWritePlayerSessionResume(LPWSTR UserID, GUID PlayerSessionID, LPWSTR MultiplayerCorrelationID, INT32 GameplayModeID, INT32 DifficultyLevelID);
	virtual void EventWritePlayerSessionStart(LPWSTR UserID, GUID PlayerSessionID, LPWSTR MultiplayerCorrelationID, INT32 GameplayModeID, INT32 DifficultyLevelID);
	virtual void EventWritePlayerSpawned(LPWSTR UserID, INT32 SectionID, GUID PlayerSessionID, LPWSTR MultiplayerCorrelationID, INT32 GameplayModeID, INT32 DifficultyLevelID, GUID RoundID, INT32 PlayerRoleID, float LocationX, float LocationY, float LocationZ);
	virtual void EventWritePlaylistCompleted(LPWSTR UserID, GUID PlayerSessionID, LPWSTR HaloTitleID, UINT32 PlaylistID, UINT64 Score64, UINT64 TimeMS, INT32 Penalties, LPWSTR MissionStats, bool IsCoop);
	virtual void EventWritePlaylistProgress(LPWSTR UserID, GUID PlayerSessionID, LPWSTR HaloTitleID, INT32 PlaylistID, INT32 NumMapsCompleted, UINT64 Score64, bool IsCoop, INT32 NumPlayers, bool ShouldPostTime, UINT64 TotalPlayListTimeMS);
	virtual void EventWriteRankedStatsDNFInfo(LPWSTR UserID, GUID PlayerSessionID, LPWSTR HopperName, double FinishesOverStarts, INT32 FinishesMinusStarts, INT32 FinishesPlusPenaltiesMinusStarts, double FinishesPlusPenaltiesOverStarts);
	virtual void EventWriteRankedStatsOverride(LPWSTR UserID, GUID PlayerSessionID, LPWSTR HopperName, double Rating, double Variance, INT32 Halo2Level, INT32 Halo2XP, bool IsRanked);
	virtual void EventWriteRankedStatsPenalty(LPWSTR UserID, GUID PlayerSessionID, LPWSTR HopperName, INT32 NumPenaltiesApplied);
	virtual void EventWriteRankedStatsUpdate(LPWSTR UserID, GUID PlayerSessionID, LPWSTR HopperName, double Rating, double Variance, INT32 Halo2Level, INT32 Halo2XP, bool IsRanked, bool PenaltyApplied);
	virtual void EventWriteRankedUpSpartanIv(LPWSTR UserID, GUID PlayerSessionID, LPWSTR HaloTitleID, INT32 SpartanIvRank, INT32 SpecialisationType);
	virtual void EventWriteRealtimeFlagCaptured(LPWSTR UserID, GUID PlayerSessionID, LPWSTR HaloTitleID, INT32 MapID, bool MatchMade);
	virtual void EventWriteRealtimeMedal(LPWSTR UserID, GUID PlayerSessionID, LPWSTR HaloTitleID, INT32 MapID, INT32 GameCategoryID, INT32 GameMode, bool MatchMade, INT32 MedalType, INT32 MedalCount);
	virtual void EventWriteRealtimePilotedVehicle(LPWSTR UserID, GUID PlayerSessionID, LPWSTR HaloTitleID, INT32 MapID, bool MatchMade, INT32 VehicleID, UINT64 TimeMS, INT32 Distance);
	virtual void EventWriteRivalID(LPWSTR UserID, GUID PlayerSessionID, INT64 RivalID);
	virtual void EventWriteSectionEnd(LPWSTR UserID, INT32 SectionID, GUID PlayerSessionID, LPWSTR MultiplayerCorrelationID, INT32 GameplayModeID, INT32 DifficultyLevelID, INT32 ExitStatusID, INT32 MissionID);
	virtual void EventWriteSectionStart(LPWSTR UserID, INT32 SectionID, GUID PlayerSessionID, LPWSTR MultiplayerCorrelationID, INT32 GameplayModeID, INT32 DifficultyLevelID, INT32 MissionID);
	virtual void EventWriteSectionStats(LPWSTR UserID, GUID PlayerSessionID, INT32 MissionID, INT32 SectionID, INT32 SectionOrdinal, float ScoreWithoutTimeBonus, float ScoreWithTimeBonus, float TimeInSeconds);
	virtual void EventWriteSessionSizeUpdate(LPWSTR UserID, GUID PlayerSessionID, INT32 SessionSize, INT32 SessionSizeMax);
	virtual void EventWriteSizeIsEverything(LPWSTR UserID, GUID PlayerSessionID);
	virtual void EventWriteSkeetShooter(LPWSTR UserID, GUID PlayerSessionID);
	virtual void EventWriteSkullClaimed(LPWSTR UserID, GUID PlayerSessionID, LPWSTR HaloTitleID, INT32 SkullID, INT32 DifficultyID);
	virtual void EventWriteSoloMissionCompleted(LPWSTR UserID, GUID PlayerSessionID, LPWSTR HaloTitleID, INT32 MapID, INT32 DifficultyID, INT32 MissionScore, bool IronSkullUsed, bool BlackEyeSkullUsed, bool ToughLuckSkullUsed, bool CatchSkullUsed, bool CloudSkullUsed, bool FamineSkullUsed, bool ThunderstormSkullUsed, bool TiltSkullUsed, bool MythicSkullUsed, bool BlindSkullUsed);
	virtual void EventWriteSoloSpartanOpsMissionCompleted(LPWSTR UserID, GUID PlayerSessionID, LPWSTR HaloTitleID, INT32 MapID, INT32 DifficultyID);
	virtual void EventWriteSpartanOpsMissionCompleted(LPWSTR UserID, GUID PlayerSessionID, LPWSTR HaloTitleID, INT32 MapID, INT32 MissionID, INT32 DifficultyID, bool IsCoop);
	virtual void EventWriteSupercombine(LPWSTR UserID, INT32 SectionID, GUID PlayerSessionID, LPWSTR MultiplayerCorrelationID, INT32 GameplayModeID, INT32 DifficultyLevelID, GUID RoundID, INT32 PlayerRoleID, INT32 PlayerWeaponID, INT32 EnemyRoleID, INT32 KillTypeID, float LocationX, float LocationY, float LocationZ, INT32 EnemyWeaponID, INT32 EnemyClassID);
	virtual void EventWriteSurvivalSpace(LPWSTR UserID, GUID PlayerSessionID, LPWSTR HaloTitleID, LPWSTR SurvivalSpace);
	virtual void EventWriteTerminalFound(LPWSTR UserID, GUID PlayerSessionID, INT32 TerminalID);
	virtual void EventWriteTerminalID(LPWSTR UserID, GUID PlayerSessionID, LPWSTR HaloTitleID, INT32 SkullID, INT32 DifficultyID);
	virtual void EventWriteTicketsEarned(LPWSTR UserID, GUID PlayerSessionID, INT32 TicketCount);
	virtual void EventWriteTitleCompleted(LPWSTR UserID, GUID PlayerSessionID, LPWSTR HaloTitleID);
	virtual void EventWriteTitleLaunched(LPWSTR UserID, GUID PlayerSessionID, LPWSTR HaloTitleID);
	virtual void EventWriteValhallaSign(LPWSTR UserID, GUID PlayerSessionID, INT32 SignID);
	virtual void EventWriteViewOffer(LPWSTR UserID, GUID PlayerSessionID, GUID OfferGuid, GUID ProductGuid);
	virtual void EventWriteVIPStatusEarned(LPWSTR UserID, GUID PlayerSessionID);
	virtual void EventWriteWhatAboutTanksDestroyed(LPWSTR UserID, GUID PlayerSessionID);
	virtual void EventWriteWonWarGame(LPWSTR UserID, GUID PlayerSessionID, LPWSTR HaloTitleID);
	virtual void EventWriteZanzibarSign(LPWSTR UserID, GUID PlayerSessionID, INT32 SignID);
	virtual void EventWriteFirefightGameResults(LPWSTR UserID, GUID PlayerSessionID, LPWSTR HaloTitleID, bool MatchMade, UINT64 TimePlayedMS, UINT32 Kills, UINT32 MostKillsInARow, UINT32 SetsCompleted, UINT32 WavesCompleted, UINT32 GeneratorsDestroyed);
	virtual void EventWriteEnemyDefeated_0(); // probably zombie defeated as these are in alphabetical order
	virtual void Member128();
	virtual void Member129();
	virtual void Member130();
	virtual void Member131();
	virtual void Member132();
	virtual void Member133();
	virtual INT64 Member134(INT64);
	virtual INT64 Member135();
	virtual LPGUID GetSessionID();
	virtual void Member137();
	virtual void CheckpointSaved();
	virtual void Member139();

	struct __declspec(align(8)) UnknownType
	{
		QWORD qword0;
		QWORD* qword1;
		QWORD* qword2;
		DWORD dword0;
		DWORD dword1;
		QWORD qword4;
		QWORD* qword5;
		QWORD* qword6;
		DWORD dword2;
		DWORD dword3;
		DWORD dword4;
		DWORD dword5;
	};

	_WORD word0;
	_WORD word1;
	GUID playerSessionId;
	__unaligned __declspec(align(1)) _QWORD qword0;
	__unaligned __declspec(align(1)) _QWORD qword1;
	__unaligned __declspec(align(1)) _QWORD qword2;
	__unaligned __declspec(align(1)) _QWORD qword3;
	__unaligned __declspec(align(1)) _QWORD qword4;
	__unaligned __declspec(align(1)) _QWORD qword5;
	__unaligned __declspec(align(1)) _QWORD qword6;
	__unaligned __declspec(align(1)) _QWORD qword7;
	_DWORD dword0;
	_DWORD dword1;
	_DWORD dword2;
	_RTL_CRITICAL_SECTION rtlCriticalSection;
	_QWORD qword8;
	UnknownType unknownStruct;
	_QWORD qword9;
	_QWORD qwordA;
	_QWORD qwordB;


};


/* functions defs also in `ecellcategory_services.bond`
virtual void ConnectedToLobbyHost(GUID MatchmakingAttemptId, GUID MpsdId);
virtual void ControlSchemeChanged(GUID MatchId, uint64 PlayerXuid, int32 ControlScheme);
virtual void CoopMissionCompleted(wchar_t* UserId, GUID PlayerSessionId, wchar_t* HaloTitleId, int32 MissionId, int32 MapId, int32 MissionScore, bool IronSkullUsed, bool BlackEyeSkullUsed, bool ToughLuckSkullUsed, bool CatchSkullUsed, bool CloudSkullUsed, bool FamineSkullUsed, bool ThunderstormSkullUsed, bool TiltSkullUsed, bool MythicSkullUsed, bool BlindSkullUsed, int32 DifficultyId);
virtual void CoopSpartanOpsMissionCompleted(wchar_t* UserId, GUID PlayerSessionId, wchar_t* HaloTitleId, int32 MapId, int32 DifficultyId);
virtual void GameplayEnd(GUID MatchId);
virtual void GameplayStart(GUID MatchId);
virtual void GraphicsConfiguration(int32 GpuDeviceId, std::string GpuName, std::string GpuVendor, std::string GpuAdapterDescription, std::string GpuDriverName, std::string GpuDriverVersion, int64 DedicatedVideoMemoryMB, int64 ShaderSystemMemory, int32 MonitorResolutionX, int32 MonitorResolutionY, std::string GpuNodeCount, std::string MonitorHdrCapabilities, bool IsHdr, int32 MonitorIndex, std::string MonitorModel);
virtual void GraphicsConfigurationUE(int32 GpuVendorId, int32 GpuDeviceId, int32 GpuDeviceRevision, std::string GpuVendor, std::string GpuAdapterDescription, std::string GpuDriverVersion, std::string GpuInternalDriverVersion, std::string GpuDriverDate, int64 DedicatedVideoMemoryMB, int32 MonitorResolutionX, int32 MonitorResolutionY, int32 MonitorDPI, std::string MonitorName, bool SupportsHdr, bool IsHdr, int32 DesktopResolutionX, int32 DesktopResolutionY, int32 MonitorCount);
virtual void HitchDetected(float BeforeFrameTime, float AfterFrameTime);
virtual void HostMigration(GUID MatchId, GUID PriorMatchId, GUID OriginalMatchId, int32 HostMigrationReasonId);
virtual void InstallState(int32 InstallStateIndex, uint32 ChunkId);
virtual void LogMessage(GUID LogSessionId, wchar_t* Category, wchar_t* Message);
virtual void MatchEnd(GUID MatchId, int32 EndReasonId);
virtual void MatchmakingStateChange(GUID MatchmakingAttemptId, std::string HopperName, GUID MpsdId, std::string OldStateName, std::string NewStateName, int32 RetryIndex, int32 ErrorId, int32 TimeFromPreviousInSeconds, int32 PartyStateIndex, int32 InstallStateIndex, GUID MatchId, std::string HopperStatName, bool IsMixTape);
virtual void MatchStart(GUID MatchId, std::string HopperName, int32 EngineTitleId, int32 GameBaseVariantId, wchar_t* GameVariantName, int32 MapId, std::string MapName, int32 CampaignDifficultyIndex, std::string CampaignSkulls, GUID PriorMatchId, GUID OriginalMatchId, int32 MatchTypeId, uint64 GameVariantHash, wchar_t* MapVariantName, uint64 MapVariantHash, std::string HopperStatName, int32 RewardsMatchType, std::string ClearanceId);
virtual void MixTapeParameters(GUID MatchmakingAttemptId, std::string MixTapeParams);
virtual void PartyStateChange(GUID MpsdId, uint64 PlayerXuid, bool IsFireteamLeader, int32 PartyStateIndex, int32 PlayerTypeId, bool IsPosseMember);
virtual void PerformanceSummary(GUID MatchId, float AverageFPS, std::vector<uint32> FrameRateBuckets, uint32 AverageMemoryUsedBytes, double AverageCpuLoadPercent, bool IsCinematic, uint64 AverageMemoryUsedBytesV2);
virtual void PerformanceSummaryEx(GUID MatchId, float AverageFPS, std::vector<uint32> FrameRateBuckets, uint64 AverageMemoryUsedBytes, double AverageCpuLoadPercent, uint32 MonitorIndex, uint32 MaxResolutionX, uint32 MaxResolutionY, uint32 AverageResolutionX, uint32 AverageResolutionY, bool IsWindowed);
virtual void PlayerJoinedMatch(uint64 PlayerXuid, GUID MatchId, int32 TeamId, bool IsJip, int32 PlayerId);
virtual void PlayerLeftMatch(GUID MatchId, int32 PlayerLeftReasonId, int32 PlayerId);
virtual void PlayerMatchSummary(uint64 PlayerXuid, GUID MatchId, int32 TeamId, bool IsJoinInProgress, int32 PlayerId, uint32 MatchDurationInSeconds, uint32 AveragePlayerLifetime, uint32 PlayerRank, int32 PlayerScore, uint32 PlayerKills, uint32 PlayerDeaths, uint32 PlayerHeadshotKills, int32 TeamRank, int32 TeamScore, bool IsDnf, int32 PlayerMatchDurationInSeconds, int32 MatchOutcomeId, std::vector<std::string> WeaponKillCount, std::vector<std::string> EnemiesKilled, std::vector<std::string> DeathSources, std::vector<std::string> MedalsEarned, int64 LevelsReached, std::string EventCounts);
virtual void PlayerStartingRankedStats(uint64 PlayerXuid, GUID MatchId, double StartingRating);
virtual void PlayerTeamChanged(uint64 PlayerXuid, int32 TeamId, int32 OldTeamId, int32 PlayerId);
virtual void PostMatchMmrUpdate(uint64 PlayerXuid, int32 PlayerId, double MmrRating, GUID MatchId);
virtual void SelectedLobbyHost(GUID MatchmakingAttemptId, GUID MpsdId, GUID MatchId);
virtual void SessionMetrics(std::string SessionTag, std::string Json);
virtual void SystemConfiguration(std::string OperatingSystemVersion, std::string ProcessorVendor, std::string ProcessorBrand, int64 SystemMemoryMB, int32 PhysicalCpuCount, int32 LogicalCpuCount);
virtual void TeamMatchSummary(GUID MatchId, int32 TeamId, int32 TeamRank, int32 TeamScore, int32 MatchOutcomeId);
virtual void TelemetrySessionStart(std::string MachineName, std::string BuildConfiguration, int32 ApplicationTypeId, bool IsThunderhead, std::string BuildVersion, int32 BuildChangelist, std::string BuildBranch, uint64 BuildDateTime, std::string CommandLine, wchar_t* SandboxId, std::string ExecutionPlatform, std::string SessionTag, int32 BuildSku);
virtual void UserEngaged(uint64 PlayerXuid, wchar_t* GamerTag);
*/