#include <tagdefinitions-private-pch.h>
#include <macaque_field_type_override.h>

namespace blofeld
{



	STRINGS(global_damage_reporting_enum_definition)
	{
		"unknown",
		"teh guardians",
		"scripting",
		"ai suicide",
		"forerunner smg",
		"spread gun",
		"forerunner rifle",
		"forerunner sniper",
		"bishop beam",
		"bolt pistol",
		"pulse grenade",
		"incineration launcher",
		"magnum pistol",
		"assault rifle",
		"marksman rifle",
		"shotgun",
		"battle rifle",
		"sniper rifle",
		"rocket launcher",
		"spartan laser",
		"frag grenade",
		"sticky grenade launcher",
		"light machine gun",
		"rail gun",
		"plasma pistol",
		"needler",
		"gravity hammer",
		"energy sword",
		"plasma grenade",
		"carbine",
		"beam rifle",
		"assault carbine",
		"concussion rifle",
		"fuel rod cannon",
		"ghost",
		"revenant driver",
		"revenant gunner",
		"wraith",
		"wraith anti-infantry",
		"banshee",
		"banshee bomb",
		"seraph",
		"revenant deux driver",
		"revenant deux gunner",
		"lich driver",
		"lich gunner",
		"mongoose",
		"warthog driver",
		"warthog gunner",
		"warthog gunner gauss",
		"warthog gunner rocket",
		"scorpion",
		"scorpion gunner",
		"falcon driver",
		"falcon gunner",
		"wasp driver",
		"wasp gunner",
		"wasp gunner heavy",
		"mech melee",
		"mech chaingun",
		"mech cannon",
		"mech rocket",
		"broadsword",
		"broadsword missile",
		"tortoise driver",
		"tortoise gunner",
		"MAC cannon",
		"Target designator",
		"Ordnance drop pod",
		"Orbital cruise missile",
		"Portable shield",
		"Personal auto turret",
		"Thruster pack",
		"falling damage",
		"generic collision damage",
		"generic melee damage",
		"generic explosion",
		"fire damage",
		"birthday party explosion",
		"flag melee damage",
		"bomb melee damage",
		"bomb explosion damage",
		"ball melee damage",
		"teleporter",
		"transfer damage",
		"armor lock crush",
		"human turret",
		"plasma cannon",
		"plasma mortar",
		"plasma turret",
		"shade turret",
		"forerunner turret",
		"tank",
		"chopper",
		"hornet",
		"mantis",
		"magnum pistol ctf",
		"flood prongs"
	};
	STRING_LIST(global_damage_reporting_enum_definition, global_damage_reporting_enum_definition_strings, _countof(global_damage_reporting_enum_definition_strings));



} // namespace blofeld

