#pragma once

namespace blofeld
{


	extern s_tag_struct_definition health_transfers_block_struct_definition;

	extern s_tag_block_definition new_global_damage_section_block;
	extern s_tag_struct_definition new_global_damage_section_block_struct_definition; // new_global_damage_section_block
	extern s_tag_block_definition damage_section_recharge_speed_curve_block;
	extern s_tag_struct_definition damage_section_recharge_speed_curve_block_struct_definition; // damage_section_recharge_speed_curve_block
	extern s_tag_block_definition damage_section_segmented_recharge_fraction_block;
	extern s_tag_struct_definition damage_section_segmented_recharge_fraction_block_struct_definition; // damage_section_segmented_recharge_fraction_block
	extern s_tag_block_definition new_instantaneous_damage_response_block;
	extern s_tag_struct_definition new_instantaneous_damage_response_block_struct_definition; // new_instantaneous_damage_response_block
	extern s_tag_block_definition damage_response_region_transition_block;
	extern s_tag_struct_definition damage_response_region_transition_block_struct_definition; // damage_response_region_transition_block
	extern s_tag_block_definition damage_transfer_block;
	extern s_tag_struct_definition damage_transfer_block_struct_definition; // damage_transfer_block
	extern s_tag_block_definition seat_ejection_block;
	extern s_tag_struct_definition seat_ejection_block_struct_definition; // seat_ejection_block
	extern s_tag_block_definition damage_section_rendering_paramters_block;
	extern s_tag_struct_definition damage_section_rendering_paramters_block_struct_definition; // damage_section_rendering_paramters_block
	extern s_tag_block_definition global_damage_info_block;
	extern s_tag_struct_definition global_damage_info_block_struct_definition; // global_damage_info_block
	extern s_tag_block_definition global_damage_section_block;
	extern s_tag_struct_definition global_damage_section_block_struct_definition; // global_damage_section_block
	extern s_tag_block_definition instantaneous_damage_repsonse_block;
	extern s_tag_struct_definition instantaneous_damage_repsonse_block_struct_definition; // instantaneous_damage_repsonse_block
	extern s_tag_block_definition global_damage_nodes_block;
	extern s_tag_struct_definition global_damage_nodes_block_struct_definition; // global_damage_nodes_block
	extern s_tag_block_definition damage_seat_info_block;
	extern s_tag_struct_definition damage_seat_info_block_struct_definition; // damage_seat_info_block
	extern s_tag_block_definition damage_seat_region_setting_block;
	extern s_tag_struct_definition damage_seat_region_setting_block_struct_definition; // damage_seat_region_setting_block
	extern s_tag_block_definition damage_constraint_info_block;
	extern s_tag_struct_definition damage_constraint_info_block_struct_definition; // damage_constraint_info_block

	extern s_tag_struct_definition instantaneous_response_damage_effect_struct;
	extern s_tag_struct_definition instantaneous_response_damage_effect_marker_struct;
	extern s_tag_struct_definition damage_body_parameters_struct;
	extern s_tag_struct_definition damage_shield_parameters_struct;
	extern s_tag_struct_definition model_damage_info_struct;

	extern s_string_list_definition model_state_enum_definition;
	extern s_string_list_definition object_damage_aftermath_special_damage_type_enum;
	extern s_string_list_definition model_damage_info_flags_definition;
	extern s_string_list_definition damage_section_flags_definition;
	extern s_string_list_definition damage_response_type_enum_definition;
	extern s_string_list_definition damage_response_constraint_damage_type_enum_definition;
	extern s_string_list_definition damage_response_set1;
	extern s_string_list_definition damage_response_set2;
	extern s_string_list_definition damage_response_body_threshold_flags_definition;
	extern s_string_list_definition damage_response_custom_response_behavior_enum_definition;
	extern s_string_list_definition new_model_damage_info_flags_definition;
	extern s_string_list_definition new_damage_section_flags_definition;
	extern s_string_list_definition newDamageResponseFlagsPart1;
	extern s_string_list_definition newDamageResponseFlagsPart2;
	extern s_string_list_definition damage_transfer_flags_definition;
	extern s_string_list_definition damage_transfer_function_enum_definition;



} // namespace blofeld

