#pragma once

namespace blofeld
{



	constexpr unsigned long MODEL_TAG = 'hlmt';
	extern s_tag_group model_group; // model_block
	extern s_tag_block_definition model_block;
	extern s_tag_struct_definition model_block_struct_definition; // model_block

	extern s_tag_struct_definition model_object_data_block_struct_definition;
	extern s_tag_block_definition model_object_data_block;

	extern s_tag_block_definition model_variant_block;
	extern s_tag_struct_definition model_variant_block_struct_definition; // model_variant_block
	extern s_tag_block_definition model_variant_region_block;
	extern s_tag_struct_definition model_variant_region_block_struct_definition; // model_variant_region_block
	extern s_tag_block_definition model_variant_permutation_block;
	extern s_tag_struct_definition model_variant_permutation_block_struct_definition; // model_variant_permutation_block
	extern s_tag_block_definition model_variant_state_block;
	extern s_tag_struct_definition model_variant_state_block_struct_definition; // model_variant_state_block
	extern s_tag_block_definition model_variant_object_block;
	extern s_tag_struct_definition model_variant_object_block_struct_definition; // model_variant_object_block
	extern s_tag_block_definition global_model_instance_group_block;
	extern s_tag_struct_definition global_model_instance_group_block_struct_definition; // global_model_instance_group_block
	extern s_tag_block_definition model_instance_group_member_block;
	extern s_tag_struct_definition model_instance_group_member_block_struct_definition; // model_instance_group_member_block
	extern s_tag_block_definition model_variant_muted_node_block;
	extern s_tag_struct_definition model_variant_muted_node_block_struct_definition; // model_variant_muted_node_block
	extern s_tag_block_definition region_name_block;
	extern s_tag_struct_definition region_name_block_struct_definition; // region_name_block
	extern s_tag_block_definition model_material_block_new_block;
	extern s_tag_struct_definition model_material_block_new_block_struct_definition; // model_material_block_new_block
	extern s_tag_block_definition model_target_block_old_block;
	extern s_tag_struct_definition model_target_block_old_block_struct_definition; // model_target_block_old_block
	extern s_tag_block_definition model_target_block_new_block;
	extern s_tag_struct_definition model_target_block_new_block_struct_definition; // model_target_block_new_block
	extern s_tag_block_definition model_region_block;
	extern s_tag_struct_definition model_region_block_struct_definition; // model_region_block
	extern s_tag_block_definition model_permutation_block;
	extern s_tag_struct_definition model_permutation_block_struct_definition; // model_permutation_block
	extern s_tag_block_definition model_node_block;
	extern s_tag_struct_definition model_node_block_struct_definition; // model_node_block
	extern s_tag_block_definition model_game_mode_render_model_override_block;
	extern s_tag_struct_definition model_game_mode_render_model_override_block_struct_definition; // model_game_mode_render_model_override_block
	extern s_tag_block_definition model_self_shadow_region_cast_override_block;
	extern s_tag_struct_definition model_self_shadow_region_cast_override_block_struct_definition; // model_self_shadow_region_cast_override_block
	extern s_tag_block_definition model_self_shadow_region_receive_override_block;
	extern s_tag_struct_definition model_self_shadow_region_receive_override_block_struct_definition; // model_self_shadow_region_receive_override_block
	extern s_tag_block_definition model_occlusion_sphere_block;
	extern s_tag_struct_definition model_occlusion_sphere_block_struct_definition; // model_occlusion_sphere_block

	extern s_tag_struct_definition runtime_region_index_array_struct_definition;
	extern s_tag_array_definition runtime_region_index_array;
	extern s_tag_struct_definition model_state_permutation_index_array_struct_definition;
	extern s_tag_array_definition model_state_permutation_index_array;
	extern s_tag_struct_definition model_target_lock_on_data_struct;

	extern s_string_list_definition model_flags_definition;
	extern s_string_list_definition model_private_flags_definition;
	extern s_string_list_definition model_lightmap_flags_definition;
	extern s_string_list_definition model_lod_resource_distance_flags_definition;
	extern s_string_list_definition imposter_quality_definition;
	extern s_string_list_definition imposter_policy_definition;
	extern s_string_list_definition model_game_mode_types;
	extern s_string_list_definition model_variant_permutation_flags_definition;
	extern s_string_list_definition model_state_property_flags_definition;
	extern s_string_list_definition region_sort_enum;
	extern s_string_list_definition ModelVariantObjectFlagsDefinition;
	extern s_string_list_definition model_instance_group_choice_enum;
	extern s_string_list_definition model_target_lock_on_flags_definition;
	extern s_string_list_definition model_target_flags_definition;
	extern s_string_list_definition model_permutation_flags_definition;
	extern s_string_list_definition model_self_shadow_detail_definition;
	extern s_string_list_definition model_self_shadow_bounces_definition;
	extern s_string_list_definition model_prt_shadow_receive_mode_definition;



} // namespace blofeld

