#pragma once

namespace blofeld
{

	extern s_tag_struct_definition breakable_surface_key_table_block_block_struct;
	extern s_tag_block_definition breakable_surface_key_table_block_block;
	extern s_tag_struct_definition soft_surfaces_definition_block_block_struct;
	extern s_tag_block_definition soft_surfaces_definition_block_block;
	extern s_tag_struct_definition structure_soft_ceiling_triangle_block_block_struct;
	extern s_tag_block_definition structure_soft_ceiling_triangle_block_block;
	extern s_tag_struct_definition structure_soft_ceiling_block_block_struct;
	extern s_tag_block_definition structure_soft_ceiling_block_block;
	extern s_tag_struct_definition structure_water_groups_block_block_struct;
	extern s_tag_block_definition structure_water_groups_block_block;
	extern s_tag_struct_definition structure_water_instance_planes_block_block_struct;
	extern s_tag_block_definition structure_water_instance_planes_block_block;
	extern s_tag_struct_definition structure_water_instance_debug_triangles_block_block_struct;
	extern s_tag_block_definition structure_water_instance_debug_triangles_block_block;
	extern s_tag_struct_definition structure_water_instances_block_block_struct;
	extern s_tag_block_definition structure_water_instances_block_block;

	extern s_tag_struct_definition global_structure_physics_struct_struct_definition;
	extern s_tag_struct_definition global_structure_physics_design_struct_struct_definition;

	extern const char* soft_ceiling_type_enum_strings[];
	extern s_string_list_definition soft_ceiling_type_enum;

} // namespace blofeld

