#pragma once

namespace blofeld
{

	constexpr unsigned long SCENARIO_STRUCTURE_LIGHTING_INFO_TAG = 'stli';

	extern s_tag_group scenario_structure_lighting_info_group;

	extern s_tag_struct_definition structure_lighting_generic_light_definition_block_block_struct;
	extern s_tag_block_definition structure_lighting_generic_light_definition_block_block;
	extern s_tag_struct_definition structure_lighting_generic_light_instance_block_block_struct;
	extern s_tag_block_definition structure_lighting_generic_light_instance_block_block;
	extern s_tag_struct_definition screen_space_light_shader_override_block_block_struct;
	extern s_tag_block_definition screen_space_light_shader_override_block_block;
	extern s_tag_struct_definition structureLightingCinematicObjectBlock_block_struct;
	extern s_tag_block_definition structureLightingCinematicObjectBlock_block;
	extern s_tag_block_definition structureLightingCinematicLightInstanceBlock_block;
	extern s_tag_block_definition scenario_structure_lighting_info_block_block;

	extern s_tag_struct_definition scenario_structure_lighting_info_struct_definition_struct_definition; // tag group
	extern s_tag_struct_definition structureLightingCinematicLightInstanceBlock_struct_struct_definition;

	extern const char* structure_lighting_light_mode_enum_strings[];
	extern s_string_list_definition structure_lighting_light_mode_enum;
	extern const char* structure_lighting_generic_light_jitter_quality_enum_strings[];
	extern s_string_list_definition structure_lighting_generic_light_jitter_quality_enum;
	extern const char* structure_lighting_generic_light_flags_strings[];
	extern s_string_list_definition structure_lighting_generic_light_flags;


} // namespace blofeld

