#pragma once

namespace blofeld
{


extern s_tag_struct campaign_metagame_bucket_block_block_struct;
extern s_tag_block_definition campaign_metagame_bucket_block_block;
extern s_tag_struct campaign_metagame_globals_block_block_struct;
extern s_tag_block_definition campaign_metagame_globals_block_block;
extern s_tag_struct campaign_metagame_style_type_block_block_struct;
extern s_tag_block_definition campaign_metagame_style_type_block_block;
extern s_tag_struct campaign_metagame_difficulty_scale_block_block_struct;
extern s_tag_block_definition campaign_metagame_difficulty_scale_block_block;
extern s_tag_struct campaign_metagame_skull_block_block_struct;
extern s_tag_block_definition campaign_metagame_skull_block_block;
extern s_tag_struct campaign_metagame_scenario_block_block_struct;
extern s_tag_block_definition campaign_metagame_scenario_block_block;
extern s_tag_struct campaign_metagame_scenario_bonuses_block_block_struct;
extern s_tag_block_definition campaign_metagame_scenario_bonuses_block_block;


} // namespace blofeld

