#pragma once

namespace blofeld
{


extern s_tag_struct campaign_metagame_bucket_block_struct_definition;
extern s_tag_block_definition campaign_metagame_bucket_block;
extern s_tag_struct campaign_metagame_globals_block_struct_definition;
extern s_tag_block_definition campaign_metagame_globals_block;
extern s_tag_struct campaign_metagame_style_type_block_struct_definition;
extern s_tag_block_definition campaign_metagame_style_type_block;
extern s_tag_struct campaign_metagame_difficulty_scale_block_struct_definition;
extern s_tag_block_definition campaign_metagame_difficulty_scale_block;
extern s_tag_struct campaign_metagame_skull_block_struct_definition;
extern s_tag_block_definition campaign_metagame_skull_block;
extern s_tag_struct campaign_metagame_scenario_block_struct_definition;
extern s_tag_block_definition campaign_metagame_scenario_block;
extern s_tag_struct campaign_metagame_scenario_bonuses_block_struct_definition;
extern s_tag_block_definition campaign_metagame_scenario_bonuses_block;

} // namespace blofeld

