#pragma once

namespace blofeld
{

extern s_tag_struct game_performance_throttle_struct_definition_struct_definition;
extern s_tag_struct game_performance_throttle_filter_struct_struct_definition;
extern s_tag_struct game_performance_throttle_profile_struct_struct_definition;

extern s_tag_struct game_performance_throttle_entries_block_struct_definition;
extern s_tag_block_definition game_performance_throttle_entries_block;

constexpr unsigned long GAME_PERFORMANCE_THROTTLE_TAG = 'gptd';

extern s_tag_block_definition game_performance_throttle_block;
extern s_tag_group game_performance_throttle_group;
} // namespace blofeld

