#pragma once

namespace blofeld
{


extern s_tag_struct game_engine_player_traits_block_block_struct;
extern s_tag_block_definition game_engine_player_traits_block_block;
extern s_tag_struct player_traits_vitality_block_block_struct;
extern s_tag_block_definition player_traits_vitality_block_block;
extern s_tag_struct player_traits_weapons_block_block_struct;
extern s_tag_block_definition player_traits_weapons_block_block;
extern s_tag_struct player_traits_movement_block_block_struct;
extern s_tag_block_definition player_traits_movement_block_block;
extern s_tag_struct player_traits_appearance_block_block_struct;
extern s_tag_block_definition player_traits_appearance_block_block;
extern s_tag_struct player_traits_sensors_block_block_struct;
extern s_tag_block_definition player_traits_sensors_block_block;
extern s_tag_struct game_engine_player_traits_list_block_block_struct;
extern s_tag_block_definition game_engine_player_traits_list_block_block;


} // namespace blofeld

