#pragma once

namespace blofeld
{


extern s_tag_struct game_engine_player_traits_block_struct_definition;
extern s_tag_block_definition game_engine_player_traits_block;
extern s_tag_struct player_traits_vitality_block_struct_definition;
extern s_tag_block_definition player_traits_vitality_block;
extern s_tag_struct player_traits_weapons_block_struct_definition;
extern s_tag_block_definition player_traits_weapons_block;
extern s_tag_struct player_traits_movement_block_struct_definition;
extern s_tag_block_definition player_traits_movement_block;
extern s_tag_struct player_traits_appearance_block_struct_definition;
extern s_tag_block_definition player_traits_appearance_block;
extern s_tag_struct player_traits_sensors_block_struct_definition;
extern s_tag_block_definition player_traits_sensors_block;
extern s_tag_struct game_engine_player_traits_list_block_struct_definition;
extern s_tag_block_definition game_engine_player_traits_list_block;

} // namespace blofeld

