#pragma once

namespace blofeld
{


	extern s_tag_struct_definition input_mapping_function_block_block_struct;
	extern s_tag_block_definition input_mapping_function_block_block;
	extern s_tag_struct_definition gamepad_stick_info_block_block_struct;
	extern s_tag_block_definition gamepad_stick_info_block_block;
	extern s_tag_struct_definition controller_input_block_block_struct;
	extern s_tag_block_definition controller_input_block_block;
	extern s_tag_struct_definition controller_mapping_reference_block_block_struct;
	extern s_tag_block_definition controller_mapping_reference_block_block;
	extern s_tag_struct_definition player_control_block_block_struct;
	extern s_tag_block_definition player_control_block_block;



	extern const char* input_mapping_shape_enum_strings[];
	extern s_string_list_definition input_mapping_shape_enum;

} // namespace blofeld

