#pragma once

namespace blofeld
{

extern s_tag_struct sound_response_definition_struct_struct_definition;

extern s_tag_struct game_engine_event_block_struct_struct_definition;
extern s_tag_block_definition game_engine_event_block;
extern s_tag_struct sound_response_definition_block_struct_definition;
extern s_tag_block_definition sound_response_definition_block;

} // namespace blofeld

