#pragma once

namespace blofeld
{

constexpr unsigned long GAMEENGINEFIREFIGHTVARIANTTAG_TAG = 'ffgt';

extern s_tag_struct GameEngineFirefightVariantTag_block_struct;
extern s_tag_block_definition GameEngineFirefightVariantTag_block;
extern s_tag_group GameEngineFirefightVariantTag_group;
constexpr unsigned long GAME_ENGINE_GLOBALS_TAG = 'gegl';

extern s_tag_group game_engine_globals_group;
constexpr unsigned long GAME_ENGINE_SETTINGS_DEFINITION_TAG = 'wezr';

extern s_tag_group game_engine_settings_definition_group;

extern s_tag_block_definition game_engine_globals_block_block;
extern s_tag_block_definition game_engine_settings_definition_block_block;
extern s_tag_struct game_engine_miscellaneous_options_block_block_struct;
extern s_tag_block_definition game_engine_miscellaneous_options_block_block;
extern s_tag_struct game_engine_prototype_options_block_block_struct;
extern s_tag_block_definition game_engine_prototype_options_block_block;
extern s_tag_struct game_engine_respawn_options_block_block_struct;
extern s_tag_block_definition game_engine_respawn_options_block_block;
extern s_tag_struct game_engine_social_options_block_block_struct;
extern s_tag_block_definition game_engine_social_options_block_block;
extern s_tag_struct game_engine_map_override_options_block_block_struct;
extern s_tag_block_definition game_engine_map_override_options_block_block;
extern s_tag_struct game_engine_team_options_block_block_struct;
extern s_tag_block_definition game_engine_team_options_block_block;
extern s_tag_struct gameEngineOrdnanceOptionsBlock_block_struct;
extern s_tag_block_definition gameEngineOrdnanceOptionsBlock_block;
extern s_tag_struct GameEngineFirefightPlayerGoalPropertiesBlock_block_struct;
extern s_tag_block_definition GameEngineFirefightPlayerGoalPropertiesBlock_block;
extern s_tag_struct GameEngineFirefightWavePropertiesBlock_block_struct;
extern s_tag_block_definition GameEngineFirefightWavePropertiesBlock_block;
extern s_tag_struct game_engine_ai_traits_list_block_block_struct;
extern s_tag_block_definition game_engine_ai_traits_list_block_block;
extern s_tag_struct game_engine_sandbox_variant_block_block_struct;
extern s_tag_block_definition game_engine_sandbox_variant_block_block;
extern s_tag_struct game_engine_survival_variant_block_block_struct;
extern s_tag_block_definition game_engine_survival_variant_block_block;
extern s_tag_struct game_engine_survival_set_properties_block_block_struct;
extern s_tag_block_definition game_engine_survival_set_properties_block_block;
extern s_tag_struct game_engine_survival_round_properties_block_block_struct;
extern s_tag_block_definition game_engine_survival_round_properties_block_block;
extern s_tag_struct survival_wave_squad_block_block_struct;
extern s_tag_block_definition survival_wave_squad_block_block;
extern s_tag_struct game_engine_survival_custom_skull_block_block_struct;
extern s_tag_block_definition game_engine_survival_custom_skull_block_block;
extern s_tag_struct GameEngineFirefightVariantShellBlock_block_struct;
extern s_tag_block_definition GameEngineFirefightVariantShellBlock_block;
extern s_tag_struct game_engine_campaign_variant_block_block_struct;
extern s_tag_block_definition game_engine_campaign_variant_block_block;

extern s_tag_struct game_engine_globals_struct_definition_struct_definition; // tag group
extern s_tag_struct game_engine_settings_definition_struct_definition_struct_definition; // tag group
extern s_tag_struct gameEngineFirefightVariantDefinition_struct_definition;
extern s_tag_struct game_engine_ai_traits_struct_struct_definition;
extern s_tag_struct game_engine_survival_wave_properties_struct_struct_definition;
extern s_tag_struct game_engine_survival_bonus_wave_properties_struct_struct_definition;

} // namespace blofeld

