#pragma once

namespace blofeld
{


extern s_tag_struct gamepad_stick_info_block_struct_definition;
extern s_tag_block_definition gamepad_stick_info_block;
extern s_tag_struct input_mapping_function_block_struct_definition;
extern s_tag_block_definition input_mapping_function_block;
extern s_tag_struct controller_input_block_struct_definition;
extern s_tag_block_definition controller_input_block;
extern s_tag_struct player_control_block_struct_definition;
extern s_tag_block_definition player_control_block;
extern s_tag_struct controller_mapping_reference_block_struct_definition;
extern s_tag_block_definition controller_mapping_reference_block;

} // namespace blofeld

