#pragma once

namespace blofeld
{

extern s_tag_struct damage_decay_struct_struct_definition;

extern s_tag_struct game_globals_damage_block_struct_definition;
extern s_tag_block_definition game_globals_damage_block;
extern s_tag_struct damage_group_block_struct_definition;
extern s_tag_block_definition damage_group_block;
extern s_tag_struct armor_modifier_block_struct_definition;
extern s_tag_block_definition armor_modifier_block;
extern s_tag_struct damage_globals_block_struct_definition;
extern s_tag_block_definition damage_globals_block;
extern s_tag_struct shield_boost_block_struct_definition;
extern s_tag_block_definition shield_boost_block;

} // namespace blofeld

