#pragma once

namespace blofeld
{

extern s_tag_struct player_model_customization_globals_struct_definition_struct_definition;

extern s_tag_struct customized_model_selection_block_struct_definition;
extern s_tag_block_definition customized_model_selection_block;
extern s_tag_struct customized_model_player_bits_block_struct_definition;
extern s_tag_block_definition customized_model_player_bits_block;

constexpr unsigned long PLAYER_MODEL_CUSTOMIZATION_GLOBALS_TAG = 'pmcg';

extern s_tag_block_definition player_model_customization_globals_block;
extern s_tag_group player_model_customization_globals_group;
} // namespace blofeld

