#pragma once
class IGameEvents
{
public:

	static IGameEvents g_gameEvents;
	static bool g_logGameEventMessages;

	virtual void AchievementEarned();
	virtual void AshesToAshes();
	virtual void Assist();
	virtual void AudioLogClaimed();
	virtual void Base();
	virtual void Betrayal();
	virtual void BIFactControllerSettings(unsigned __int64*, GUID*, _QWORD, __int64, _DWORD, int, int);
	virtual void BIFactDeepLink();
	virtual void BIFactDeepLinkRecieve(_QWORD*, GUID*, _QWORD*, __int64*);
	virtual void BIFactDeepLinkSend(_QWORD*, GUID*, _QWORD*, __int64*);
	virtual void BIFactDualWield();
	virtual void BIFactGameSession();
	virtual void BIFactLoadout();
	virtual void BIFactMatchmaking();
	virtual void BIFactMatchmakingDetails();
	virtual void BIFactMedia();
	virtual void BirdOfPrey();
	virtual void BitsAndPiecesDestroyed();
	virtual void BroadcastingAssist();
	virtual void BroadcastingDeath();
	virtual void BroadcastingHeartbeat();
	virtual void BroadcastingKill();
	virtual void BroadcastingMatchEnd();
	virtual void MultiplayerRoundEnd_0(); // these are probably named wrong as these are alphabetical
	virtual void MultiplayerRoundStart_0(); // these are probably named wrong as these are alphabetical
	virtual void BroadcastingMatchStart();
	virtual void BroadcastingMedal();
	virtual void BroadcastingPlayerJoined();
	virtual void BroadcastingPlayerLeft();
	virtual void BroadcastingPlayerSpawn();
	virtual void BroadcastingPlayerSwitchedTeams();
	virtual void BroadcastingScore();
	virtual void BroadcastingStart(_QWORD, _QWORD, _QWORD, _QWORD, _DWORD, _QWORD, _QWORD, _DWORD, _QWORD);
	virtual void CampaignDifficulty();
	virtual void ChallengeCompleted();
	virtual void ClassicModeSwitched();
	virtual void CleverGirl();
	virtual void ClueClaimed();
	virtual void CoopMissionCompleted();
	virtual void CoopSpartanOpsMissionCompleted();
	virtual void CompletionCount();
	virtual void Customization();
	virtual void DashboardContext();
	virtual void Death();
	virtual void DollFound();
	virtual void EliteWin();
	virtual void Emblem();
	virtual void EnemyDefeated();
	virtual void FriendsBestedOnHeroLeaderboard();
	virtual void GameProgress();
	virtual void GameVarSaved();
	virtual void GrenadeStick();
	virtual void HelloNurse();
	virtual void InGamePresence();
	virtual void ISeeYou();
	virtual void Joinability();
	virtual void Lobby();
	virtual void MainMenuPresence();
	virtual void MapVarSaved();
	virtual void MatchmakingHopper();
	virtual void MediaUsage();
	virtual void MeldOfferPresented();
	virtual void MeldOfferResponded();
	virtual void MeldPageAction();
	virtual void MeldPageView();
	virtual void MissionCompleted();
	virtual void MortardomWraithsKilled();
	virtual void MultiplayerGameEngine();
	virtual void MultiplayerMap();
	virtual void MultiplayerRoundEnd();
	virtual void MultiplayerRoundStart();
	virtual void NappersCaught();
	virtual void NewsStoryRead();
	virtual void ObjectiveEnd();
	virtual void ObjectiveStart();
	virtual void PageAction();
	virtual void PageView();
	virtual void PhantomHunter();
	virtual void PigsCanFly();
	virtual void PlayerCheckedInToday();
	virtual void PlayerDefeated();
	virtual void PlayerGameResults();
	virtual void PlayerGameResultsDamageStat();
	virtual void PlayerGameResultsGriefingStat();
	virtual void PlayerGameResultsGriefingStats();
	virtual void PlayerGameResultsInterestStats();
	virtual void PlayerGameResultsMedal();
	virtual void PlayerSessionEnd();
	virtual void PlayerSessionPause();
	virtual void PlayerSessionResume();
	virtual void PlayerSessionStart();
	virtual void PlayerSpawned();
	virtual void PlaylistCompleted();
	virtual void PlaylistProgress();
	virtual void RankedStatsDNFInfo();
	virtual void RankedStatsOverride();
	virtual void RankedStatsPenalty();
	virtual void RankedStatsUpdate();
	virtual void RankedUpSpartanIv();
	virtual void RealtimeFlagCaptured();
	virtual void RealtimeMedal();
	virtual void RealtimePilotedVehicle();
	virtual void RivalID();
	virtual void SectionEnd();
	virtual void SectionStart();
	virtual void SectionStats();
	virtual void SessionSizeUpdate();
	virtual void SizeIsEverything();
	virtual void SkeetShooter();
	virtual void SkullClaimed();
	virtual void SoloMissionCompleted();
	virtual void SoloSpartanOpsMissionCompleted();
	virtual void SpartanOpsMissionCompleted();
	virtual void Supercombine();
	virtual void SurvivalSpace();
	virtual void TerminalFound();
	virtual void TerminalId();
	virtual void TicketsEarned();
	virtual void TitleCompleted();
	virtual void TitleLaunched();
	virtual void ValhallaSign();
	virtual void ViewOffer();
	virtual void VIPStatusEarned();
	virtual void WhatAboutTanksDestroyed();
	virtual void WonWarGame();
	virtual void ZanzibarSign();
	virtual void EnemyDefeated_0(); // probably zombie defeated as these are in alphabetical order
	virtual void Member127();
	virtual void Member128();
	virtual void Member129();
	virtual void Member130();
	virtual void Member131();
	virtual void Member132();
	virtual __int64 Member133(_QWORD);
	virtual void Member134();
	virtual GUID* __fastcall GetGuid(GUID* pGuid);
	virtual void Member136();
	virtual void Member137();
	virtual void Member138();

	struct __declspec(align(8)) UnknownType
	{
		QWORD qword0;
		QWORD* qword1;
		QWORD* qword2;
		DWORD dword0;
		DWORD dword1;
		QWORD qword4;
		QWORD* qword5;
		QWORD* qword6;
		DWORD dword2;
		DWORD dword3;
		DWORD dword4;
		DWORD dword5;
	};

	_WORD word0;
	_WORD word1;
	GUID guid;
	__unaligned __declspec(align(1)) _QWORD qword0;
	__unaligned __declspec(align(1)) _QWORD qword1;
	__unaligned __declspec(align(1)) _QWORD qword2;
	__unaligned __declspec(align(1)) _QWORD qword3;
	__unaligned __declspec(align(1)) _QWORD qword4;
	__unaligned __declspec(align(1)) _QWORD qword5;
	__unaligned __declspec(align(1)) _QWORD qword6;
	__unaligned __declspec(align(1)) _QWORD qword7;
	_DWORD dword0;
	_DWORD dword1;
	_DWORD dword2;
	_RTL_CRITICAL_SECTION rtlCriticalSection;
	_QWORD qword8;
	UnknownType unknownStruct;
	_QWORD qword9;
	_QWORD qwordA;
	_QWORD qwordB;


};

