#pragma once

namespace blofeld
{

	constexpr unsigned long SCENARIO_AI_RESOURCE_TAG = 'ai**';
	constexpr unsigned long SCENARIO_BIPEDS_RESOURCE_TAG = '*ipd';
	constexpr unsigned long SCENARIO_CINEMATICS_RESOURCE_TAG = 'cin*';
	constexpr unsigned long SCENARIO_CLUSTER_DATA_RESOURCE_TAG = 'clu*';
	constexpr unsigned long SCENARIO_COMMENTS_RESOURCE_TAG = '/**/';
	constexpr unsigned long SCENARIO_CREATURE_RESOURCE_TAG = '*rea';
	constexpr unsigned long SCENARIO_CUBEMAP_RESOURCE_TAG = 'cub*';
	constexpr unsigned long SCENARIO_DECALS_RESOURCE_TAG = 'dec*';
	constexpr unsigned long SCENARIO_DECORATORS_RESOURCE_TAG = 'dc*s';
	constexpr unsigned long SCENARIO_DEVICES_RESOURCE_TAG = 'dgr*';
	constexpr unsigned long SCENARIO_DUMPLINGS_RESOURCE_TAG = 'dmp*';
	constexpr unsigned long SCENARIO_EFFECT_SCENERY_RESOURCE_TAG = '*fsc';
	constexpr unsigned long SCENARIO_EQUIPMENT_RESOURCE_TAG = '*qip';
	constexpr unsigned long SCENARIO_LIGHTS_RESOURCE_TAG = '*igh';
	constexpr unsigned long SCENARIO_PERFORMANCES_RESOURCE_TAG = 'prf*';
	constexpr unsigned long SCENARIO_REQUIRED_RESOURCE_TAG = 'sdzg';
	constexpr unsigned long SCENARIO_SCENERY_RESOURCE_TAG = '*cen';
	constexpr unsigned long SCENARIO_SKY_REFERENCES_RESOURCE_TAG = 'sky*';
	constexpr unsigned long SCENARIO_SOUND_SCENERY_RESOURCE_TAG = '*sce';
	constexpr unsigned long SCENARIO_STRUCTURE_LIGHTING_RESOURCE_TAG = 'sslt';
	constexpr unsigned long SCENARIO_TRIGGER_VOLUMES_RESOURCE_TAG = 'trg*';
	constexpr unsigned long SCENARIO_VEHICLES_RESOURCE_TAG = '*ehi';
	constexpr unsigned long SCENARIO_WEAPONS_RESOURCE_TAG = '*eap';



	constexpr unsigned long PERFORMANCE_TEMPLATE_TAG = 'pfmc';
	extern s_tag_group performance_template_group; // performance_template_block
	extern s_tag_block_definition performance_template_block;
	extern s_tag_struct_definition performance_template_block_struct_definition; // performance_template_block

	constexpr unsigned long SCENARIO_TAG = 'scnr';
	extern s_tag_group scenario_group; // scenario_block

	extern s_tag_group scenario_required_resource_group; // scenario_required_resource_block

	extern s_tag_struct_definition cluster_sky_index_block_struct_definition;
	extern s_tag_struct_definition scenario_zone_set_bsp_pvs_unknown_block_struct_definition;
	extern s_tag_struct_definition scenario_unknown_block_struct_definition;
	extern s_tag_struct_definition scenario_resources_reference_block_struct_definition;
	extern s_tag_struct_definition scenario_hs_source_reference_block_struct_definition;
	extern s_tag_struct_definition scenario_ai_resource_reference_block_struct_definition;
	extern s_tag_struct_definition scenario_resources_block_struct_definition;
	extern s_tag_struct_definition scenario_unknown_object_reference_block_struct_definition;
	extern s_tag_struct_definition scenario_structured_buffer_interops_block_struct_definition;

	extern s_tag_block_definition cluster_sky_index_block;
	extern s_tag_block_definition scenario_zone_set_bsp_pvs_unknown_block;
	extern s_tag_block_definition scenario_unknown_block;
	extern s_tag_block_definition scenario_resources_reference_block;
	extern s_tag_block_definition scenario_hs_source_reference_block;
	extern s_tag_block_definition scenario_ai_resource_reference_block;
	extern s_tag_block_definition scenario_resources_block;
	extern s_tag_block_definition scenario_unknown_object_reference_block;
	extern s_tag_block_definition scenario_structured_buffer_interops_block;

	extern s_tag_block_definition scenario_block;
	extern s_tag_block_definition scenario_required_resource_block;
	extern s_tag_block_definition scenario_profiles_block;
	extern s_tag_struct_definition scenario_profiles_block_struct_definition; // scenario_profiles_block
	extern s_tag_block_definition performance_template_actor_block;
	extern s_tag_struct_definition performance_template_actor_block_struct_definition; // performance_template_actor_block
	extern s_tag_block_definition scenario_performance_line_block;
	extern s_tag_struct_definition scenario_performance_line_block_struct_definition; // scenario_performance_line_block
	extern s_tag_block_definition scenario_performance_line_script_fragment_block;
	extern s_tag_struct_definition scenario_performance_line_script_fragment_block_struct_definition; // scenario_performance_line_script_fragment_block
	extern s_tag_block_definition scenario_performance_line_point_interaction_block;
	extern s_tag_struct_definition scenario_performance_line_point_interaction_block_struct_definition; // scenario_performance_line_point_interaction_block
	extern s_tag_block_definition scenario_performance_line_animation_block;
	extern s_tag_struct_definition scenario_performance_line_animation_block_struct_definition; // scenario_performance_line_animation_block
	extern s_tag_block_definition scenario_performance_line_sync_action_block;
	extern s_tag_struct_definition scenario_performance_line_sync_action_block_struct_definition; // scenario_performance_line_sync_action_block
	extern s_tag_block_definition scenario_performance_line_sync_action_actor_block;
	extern s_tag_struct_definition scenario_performance_line_sync_action_actor_block_struct_definition; // scenario_performance_line_sync_action_actor_block
	extern s_tag_block_definition scenario_performance_line_scenery_sync_action_block;
	extern s_tag_struct_definition scenario_performance_line_scenery_sync_action_block_struct_definition; // scenario_performance_line_scenery_sync_action_block
	extern s_tag_block_definition scenario_performance_line_dialog_block;
	extern s_tag_struct_definition scenario_performance_line_dialog_block_struct_definition; // scenario_performance_line_dialog_block
	extern s_tag_block_definition scenario_performance_line_sound_block;
	extern s_tag_struct_definition scenario_performance_line_sound_block_struct_definition; // scenario_performance_line_sound_block
	extern s_tag_block_definition performance_template_point_block;
	extern s_tag_struct_definition performance_template_point_block_struct_definition; // performance_template_point_block
	extern s_tag_block_definition scenario_structure_bsp_reference_block;
	extern s_tag_struct_definition scenario_structure_bsp_reference_block_struct_definition; // scenario_structure_bsp_reference_block
	extern s_tag_block_definition scenario_sky_reference_block;
	extern s_tag_struct_definition scenario_sky_reference_block_struct_definition; // scenario_sky_reference_block
	extern s_tag_block_definition scenario_object_names_block;
	extern s_tag_struct_definition scenario_object_names_block_struct_definition; // scenario_object_names_block
	extern s_tag_block_definition scenarioBspReferenceBlock_block;
	extern s_tag_struct_definition scenarioBspReferenceBlock_block_struct_definition; // scenarioBspReferenceBlock_block
	extern s_tag_block_definition scenario_child_references_block;
	extern s_tag_struct_definition scenario_child_references_block_struct_definition; // scenario_child_references_block
	extern s_tag_block_definition scenario_design_reference_block;
	extern s_tag_struct_definition scenario_design_reference_block_struct_definition; // scenario_design_reference_block
	extern s_tag_block_definition scenario_zone_set_pvs_block;
	extern s_tag_struct_definition scenario_zone_set_pvs_block_struct_definition; // scenario_zone_set_pvs_block
	extern s_tag_block_definition scenario_zone_set_bsp_checksum_block;
	extern s_tag_struct_definition scenario_zone_set_bsp_checksum_block_struct_definition; // scenario_zone_set_bsp_checksum_block
	extern s_tag_block_definition scenario_zone_set_bsp_pvs_block;
	extern s_tag_struct_definition scenario_zone_set_bsp_pvs_block_struct_definition; // scenario_zone_set_bsp_pvs_block
	extern s_tag_block_definition scenario_zone_set_cluster_pvs_block;
	extern s_tag_struct_definition scenario_zone_set_cluster_pvs_block_struct_definition; // scenario_zone_set_cluster_pvs_block
	extern s_tag_block_definition scenario_zone_set_bsp_bits_block;
	extern s_tag_struct_definition scenario_zone_set_bsp_bits_block_struct_definition; // scenario_zone_set_bsp_bits_block
	extern s_tag_block_definition scenario_zone_set_cluster_pvs_bit_vector_block;
	extern s_tag_struct_definition scenario_zone_set_cluster_pvs_bit_vector_block_struct_definition; // scenario_zone_set_cluster_pvs_bit_vector_block
	extern s_tag_block_definition scenario_zone_set_bsp_seam_cluster_mappings_block;
	extern s_tag_struct_definition scenario_zone_set_bsp_seam_cluster_mappings_block_struct_definition; // scenario_zone_set_bsp_seam_cluster_mappings_block
	extern s_tag_block_definition scenario_zone_set_cluster_reference_block;
	extern s_tag_struct_definition scenario_zone_set_cluster_reference_block_struct_definition; // scenario_zone_set_cluster_reference_block
	extern s_tag_block_definition scenario_zone_set_block;
	extern s_tag_struct_definition scenario_zone_set_block_struct_definition; // scenario_zone_set_block
	extern s_tag_block_definition scenario_budget_references_block;
	extern s_tag_struct_definition scenario_budget_references_block_struct_definition; // scenario_budget_references_block
	extern s_tag_block_definition scenario_zone_set_budget_override_block;
	extern s_tag_struct_definition scenario_zone_set_budget_override_block_struct_definition; // scenario_zone_set_budget_override_block
	extern s_tag_block_definition scenario_zone_set_lipsync_block;
	extern s_tag_struct_definition scenario_zone_set_lipsync_block_struct_definition; // scenario_zone_set_lipsync_block
	extern s_tag_block_definition scenario_lighting_zone_set_block;
	extern s_tag_struct_definition scenario_lighting_zone_set_block_struct_definition; // scenario_lighting_zone_set_block
	extern s_tag_block_definition scenario_function_block;
	extern s_tag_struct_definition scenario_function_block_struct_definition; // scenario_function_block
	extern s_tag_block_definition editor_comment_block;
	extern s_tag_struct_definition editor_comment_block_struct_definition; // editor_comment_block
	extern s_tag_block_definition dont_use_me_scenario_environment_object_block;
	extern s_tag_struct_definition dont_use_me_scenario_environment_object_block_struct_definition; // dont_use_me_scenario_environment_object_block
	extern s_tag_block_definition scenarioAttachedEffectsBlock_block;
	extern s_tag_struct_definition scenarioAttachedEffectsBlock_block_struct_definition; // scenarioAttachedEffectsBlock_block
	extern s_tag_block_definition scenarioAttachedLensFlaresBlock_block;
	extern s_tag_struct_definition scenarioAttachedLensFlaresBlock_block_struct_definition; // scenarioAttachedLensFlaresBlock_block
	extern s_tag_block_definition scenarioAttachedLightConesBlock_block;
	extern s_tag_struct_definition scenarioAttachedLightConesBlock_block_struct_definition; // scenarioAttachedLightConesBlock_block
	extern s_tag_block_definition scenario_soft_ceilings_block;
	extern s_tag_struct_definition scenario_soft_ceilings_block_struct_definition; // scenario_soft_ceilings_block
	extern s_tag_block_definition scenario_players_block;
	extern s_tag_struct_definition scenario_players_block_struct_definition; // scenario_players_block
	extern s_tag_block_definition scenario_trigger_volume_block;
	extern s_tag_block_definition trigger_volume_point_block;
	extern s_tag_struct_definition trigger_volume_point_block_struct_definition; // trigger_volume_point_block
	extern s_tag_block_definition trigger_volume_runtime_triangles_block;
	extern s_tag_struct_definition trigger_volume_runtime_triangles_block_struct_definition; // trigger_volume_runtime_triangles_block
	extern s_tag_block_definition scenario_kill_trigger_volumes_block;
	extern s_tag_struct_definition scenario_kill_trigger_volumes_block_struct_definition; // scenario_kill_trigger_volumes_block
	extern s_tag_block_definition scenario_atmosphere_palette_block;
	extern s_tag_struct_definition scenario_atmosphere_palette_block_struct_definition; // scenario_atmosphere_palette_block
	extern s_tag_block_definition scenario_weather_palette_block;
	extern s_tag_struct_definition scenario_weather_palette_block_struct_definition; // scenario_weather_palette_block
	extern s_tag_block_definition scenario_zone_set_switch_trigger_volume_block;
	extern s_tag_struct_definition scenario_zone_set_switch_trigger_volume_block_struct_definition; // scenario_zone_set_switch_trigger_volume_block
	extern s_tag_block_definition scenario_decals_block;
	extern s_tag_struct_definition scenario_decals_block_struct_definition; // scenario_decals_block
	extern s_tag_block_definition scenario_decal_palette_block;
	extern s_tag_struct_definition scenario_decal_palette_block_struct_definition; // scenario_decal_palette_block
	extern s_tag_block_definition scenario_detail_object_collection_palette_block;
	extern s_tag_struct_definition scenario_detail_object_collection_palette_block_struct_definition; // scenario_detail_object_collection_palette_block
	extern s_tag_block_definition scenario_cutscene_flag_block;
	extern s_tag_struct_definition scenario_cutscene_flag_block_struct_definition; // scenario_cutscene_flag_block
	extern s_tag_block_definition scenario_cutscene_camera_point_block;
	extern s_tag_struct_definition scenario_cutscene_camera_point_block_struct_definition; // scenario_cutscene_camera_point_block
	extern s_tag_block_definition scenario_safe_zone_trigger_volumes_block;
	extern s_tag_struct_definition scenario_safe_zone_trigger_volumes_block_struct_definition; // scenario_safe_zone_trigger_volumes_block
	extern s_tag_block_definition trigger_volume_mopp_code_block;
	extern s_tag_struct_definition trigger_volume_mopp_code_block_struct_definition; // trigger_volume_mopp_code_block
	extern s_tag_block_definition scenario_requisition_trigger_volumes_block;
	extern s_tag_struct_definition scenario_requisition_trigger_volumes_block_struct_definition; // scenario_requisition_trigger_volumes_block
	extern s_tag_block_definition scenario_location_name_trigger_volumes_block;
	extern s_tag_struct_definition scenario_location_name_trigger_volumes_block_struct_definition; // scenario_location_name_trigger_volumes_block
	extern s_tag_block_definition scenarioUnsafeSpawnZoneTriggerVolumesBlock_block;
	extern s_tag_struct_definition scenarioUnsafeSpawnZoneTriggerVolumesBlock_block_struct_definition; // scenarioUnsafeSpawnZoneTriggerVolumesBlock_block
	extern s_tag_block_definition scenario_camera_fx_palette_block;
	extern s_tag_struct_definition scenario_camera_fx_palette_block_struct_definition; // scenario_camera_fx_palette_block
	extern s_tag_block_definition scenario_cluster_data_block;
	extern s_tag_struct_definition scenario_cluster_data_block_struct_definition; // scenario_cluster_data_block
	extern s_tag_block_definition scenario_cluster_points_block;
	extern s_tag_struct_definition scenario_cluster_points_block_struct_definition; // scenario_cluster_points_block
	extern s_tag_block_definition scenario_cluster_acoustics_block;
	extern s_tag_struct_definition scenario_cluster_acoustics_block_struct_definition; // scenario_cluster_acoustics_block
	extern s_tag_block_definition scenario_cluster_atmosphere_properties_block;
	extern s_tag_struct_definition scenario_cluster_atmosphere_properties_block_struct_definition; // scenario_cluster_atmosphere_properties_block
	extern s_tag_block_definition scenario_cluster_camera_fx_properties_block;
	extern s_tag_struct_definition scenario_cluster_camera_fx_properties_block_struct_definition; // scenario_cluster_camera_fx_properties_block
	extern s_tag_block_definition scenario_cluster_weather_properties_block;
	extern s_tag_struct_definition scenario_cluster_weather_properties_block_struct_definition; // scenario_cluster_weather_properties_block
	extern s_tag_block_definition scenario_spawn_data_block;
	extern s_tag_struct_definition scenario_spawn_data_block_struct_definition; // scenario_spawn_data_block
	extern s_tag_block_definition SoundSubtitleBlock_block;
	extern s_tag_struct_definition SoundSubtitleBlock_block_struct_definition; // SoundSubtitleBlock_block
	extern s_tag_block_definition scenario_cheap_particle_system_palette_block;
	extern s_tag_struct_definition scenario_cheap_particle_system_palette_block_struct_definition; // scenario_cheap_particle_system_palette_block
	extern s_tag_block_definition scenario_cheap_particle_systems_block;
	extern s_tag_struct_definition scenario_cheap_particle_systems_block_struct_definition; // scenario_cheap_particle_systems_block
	extern s_tag_block_definition scenario_cinematic_lighting_palette_block;
	extern s_tag_struct_definition scenario_cinematic_lighting_palette_block_struct_definition; // scenario_cinematic_lighting_palette_block
	extern s_tag_block_definition scenario_airprobes_block;
	extern s_tag_struct_definition scenario_airprobes_block_struct_definition; // scenario_airprobes_block
	extern s_tag_block_definition model_references_block;
	extern s_tag_struct_definition model_references_block_struct_definition; // model_references_block
	extern s_tag_block_definition scenario_performances_block;
	extern s_tag_struct_definition scenario_performances_block_struct_definition; // scenario_performances_block
	extern s_tag_block_definition scenario_performance_actor_block;
	extern s_tag_struct_definition scenario_performance_actor_block_struct_definition; // scenario_performance_actor_block
	extern s_tag_block_definition scenario_performance_task_block;
	extern s_tag_struct_definition scenario_performance_task_block_struct_definition; // scenario_performance_task_block
	extern s_tag_block_definition scenarioRandomOrdnanceDropSetBlock_block;
	extern s_tag_struct_definition scenarioRandomOrdnanceDropSetBlock_block_struct_definition; // scenarioRandomOrdnanceDropSetBlock_block
	extern s_tag_block_definition scenarioRandomOrdnanceDropPointBlock_block;
	extern s_tag_struct_definition scenarioRandomOrdnanceDropPointBlock_block_struct_definition; // scenarioRandomOrdnanceDropPointBlock_block
	extern s_tag_block_definition ScenarioUnitRecordingBlock_block;
	extern s_tag_block_definition loadScreenReferenceBlock_block;
	extern s_tag_struct_definition loadScreenReferenceBlock_block_struct_definition; // loadScreenReferenceBlock_block

	extern s_tag_struct_definition scenarioFloatingShadowCascadeSettingsArray_array_struct_definition;
	extern s_tag_array_definition scenarioFloatingShadowCascadeSettingsArray_array;
	extern s_tag_struct_definition object_salt_storage_array_struct_definition;
	extern s_tag_array_definition object_salt_storage_array;
	extern s_tag_struct_definition scenario_struct_definition; // tag group
	extern s_tag_struct_definition scenario_required_resource_struct_definition; // tag group
	extern s_tag_struct_definition scenarioVolumetricLightShaftSettingsStruct;
	extern s_tag_struct_definition scenarioFloatingShadowSettingsStruct;
	extern s_tag_struct_definition scenario_lightmap_setting_struct;
	extern s_tag_struct_definition manualBspFlagsReferences;
	extern s_tag_struct_definition scenario_trigger_volume_struct;
	extern s_tag_struct_definition ScenarioUnitRecordingBlock_struct;

	extern s_string_list_definition function_bounds_mode_enum;
	extern s_string_list_definition scenario_function_flags;
	extern s_string_list_definition scenario_soft_ceiling_flags_definition;
	extern s_string_list_definition scenario_player_flags;
	extern s_string_list_definition kill_volume_flags;
	extern s_string_list_definition scenario_requisition_trigger_volume_flags_definition;
	extern s_string_list_definition trigger_volume_type_enum;
	extern s_string_list_definition scenario_zone_set_switch_trigger_volume_flags_definition;
	extern s_string_list_definition scenario_zone_set_pvs_flags;
	extern s_string_list_definition scenario_zone_set_flags_definition;
	extern s_string_list_definition scenario_structure_size_enum;
	extern s_string_list_definition scenario_structure_refinement_size_enum;
	extern s_string_list_definition scenario_structure_bsp_reference_flags_definition;
	extern s_string_list_definition scenarioVolumetricLightShaftSettingsFlags;
	extern s_string_list_definition floatingShadowQualityDefinition;
	extern s_string_list_definition floatingShadowBufferResolution;
	extern s_string_list_definition scenario_lightmap_per_bsp_flags;
	extern s_string_list_definition scenario_performance_actor_flags_definition;
	extern s_string_list_definition scenario_performance_line_animation_flags_definition;
	extern s_string_list_definition scenario_performance_line_sync_action_flag_type_definition;
	extern s_string_list_definition scenario_performance_line_scenery_sync_action_flag_type_definition;
	extern s_string_list_definition scenario_performance_fragment_placement_definition;
	extern s_string_list_definition scenario_performance_fragment_type_definition;
	extern s_string_list_definition scenario_performance_line_point_interaction_type_definition;
	extern s_string_list_definition scenario_performance_line_progress_definition;
	extern s_string_list_definition scenario_performance_line_flags;
	extern s_string_list_definition performance_flags;
	extern s_string_list_definition decal_placement_flags;
	extern s_string_list_definition editor_comment_type_enum_definition;
	extern s_string_list_definition scenario_type_enum;
	extern s_string_list_definition scenario_flags;
	extern s_string_list_definition scenario_runtime_trigger_volume_flags;
	extern s_string_list_definition camera_fx_palette_flags;
	extern s_string_list_definition ordnance_flags;
	extern s_string_list_definition ordnance_dropset_flags;
	extern s_string_list_definition multiplayer_map_size_enum;

	extern s_tag_struct_definition structured_buffer_struct_definition; // #CUSTOM


} // namespace blofeld

