#pragma once

namespace blofeld
{



	extern s_tag_block_definition scenario_decorator_block;
	extern s_tag_struct_definition scenario_decorator_block_struct_definition; // scenario_decorator_block
	extern s_tag_block_definition decorator_palette_block;
	extern s_tag_struct_definition decorator_palette_block_struct_definition; // decorator_palette_block
	extern s_tag_block_definition decorator_scenario_set_block;
	extern s_tag_struct_definition decorator_scenario_set_block_struct_definition; // decorator_scenario_set_block
	extern s_tag_block_definition global_decorator_placement_block;
	extern s_tag_struct_definition global_decorator_placement_block_struct_definition; // global_decorator_placement_block

	extern s_tag_struct_definition decorator_brush_struct;

	extern s_string_list_definition decorator_placement_flags_definition;
	extern s_string_list_definition decorator_left_brush_type_enum_definition;
	extern s_string_list_definition decorator_right_brush_type_enum_definition;
	extern s_string_list_definition decorator_brush_reapply_flags_definition;
	extern s_string_list_definition decorator_brush_render_flags_definition;
	extern s_string_list_definition decorator_brush_action_flags_definition;
	extern s_string_list_definition decorator_brush_shape_enum_definition;



} // namespace blofeld

