#pragma once

namespace blofeld
{

	extern s_tag_struct_definition map_variant_legacy_build_info_block_block_struct;

	extern s_tag_struct_definition mapVariantPaletteDependencyBlock_block_struct;
	extern s_tag_block_definition mapVariantPaletteDependencyBlock_block;
	extern s_tag_struct_definition resourceHandleBlock_block_struct;
	extern s_tag_block_definition resourceHandleBlock_block;
	extern s_tag_struct_definition map_variant_object_variant_block_block_struct;
	extern s_tag_block_definition map_variant_object_variant_block_block;
	extern s_tag_struct_definition map_variant_palette_entry_block_block_struct;
	extern s_tag_block_definition map_variant_palette_entry_block_block;
	extern s_tag_struct_definition map_variant_palette_block_block_struct;
	extern s_tag_block_definition map_variant_palette_block_block;
	extern s_tag_struct_definition map_variant_legacy_palette_info_block_block_struct;
	extern s_tag_block_definition map_variant_legacy_palette_info_block_block;

	extern s_tag_struct_definition mapVariantResourceManifest_struct_definition;

	extern c_versioned_string_list map_variant_palette_flags_strings;
	extern s_string_list_definition map_variant_palette_flags;

} // namespace blofeld

