#pragma once

namespace blofeld
{

	extern s_tag_struct_definition decorator_palette_block_struct;
	extern s_tag_block_definition decorator_palette_block;
	extern s_tag_struct_definition global_decorator_placement_block_block_struct;
	extern s_tag_block_definition global_decorator_placement_block_block;
	extern s_tag_struct_definition decorator_scenario_set_block_block_struct;
	extern s_tag_block_definition decorator_scenario_set_block_block;
	extern s_tag_struct_definition scenario_decorator_block_block_struct;
	extern s_tag_block_definition scenario_decorator_block_block;

	extern s_tag_struct_definition decorator_brush_struct_struct_definition;

	extern const char* decorator_placement_flags_definition_strings[];
	extern s_string_list_definition decorator_placement_flags_definition;
	extern const char* decorator_left_brush_type_enum_definition_strings[];
	extern s_string_list_definition decorator_left_brush_type_enum_definition;
	extern const char* decorator_right_brush_type_enum_definition_strings[];
	extern s_string_list_definition decorator_right_brush_type_enum_definition;
	extern const char* decorator_brush_reapply_flags_definition_strings[];
	extern s_string_list_definition decorator_brush_reapply_flags_definition;
	extern const char* decorator_brush_render_flags_definition_strings[];
	extern s_string_list_definition decorator_brush_render_flags_definition;
	extern const char* decorator_brush_action_flags_definition_strings[];
	extern s_string_list_definition decorator_brush_action_flags_definition;
	extern const char* decorator_brush_shape_enum_definition_strings[];
	extern s_string_list_definition decorator_brush_shape_enum_definition;

} // namespace blofeld

