#pragma once

namespace blofeld
{



	extern s_tag_block_definition map_variant_palette_block;
	extern s_tag_struct_definition map_variant_palette_block_struct_definition; // map_variant_palette_block
	extern s_tag_block_definition map_variant_palette_entry_block;
	extern s_tag_struct_definition map_variant_palette_entry_block_struct_definition; // map_variant_palette_entry_block
	extern s_tag_block_definition map_variant_object_variant_block;
	extern s_tag_struct_definition map_variant_object_variant_block_struct_definition; // map_variant_object_variant_block
	extern s_tag_block_definition mapVariantPaletteDependencyBlock_block;
	extern s_tag_struct_definition mapVariantPaletteDependencyBlock_block_struct_definition; // mapVariantPaletteDependencyBlock_block
	extern s_tag_block_definition resourceHandleBlock_block;
	extern s_tag_struct_definition resourceHandleBlock_block_struct_definition; // resourceHandleBlock_block

	extern s_tag_struct_definition map_variant_legacy_palette_info_block_struct_definition;
	extern s_tag_block_definition map_variant_legacy_palette_info_block;

	extern s_tag_struct_definition mapVariantResourceManifest;

	extern s_string_list_definition map_variant_palette_flags;



} // namespace blofeld

