#pragma once

namespace blofeld
{

	extern s_tag_struct_definition purchase_prerequisite_grade_definition_block_block_struct;
	extern s_tag_block_definition purchase_prerequisite_grade_definition_block_block;
	extern s_tag_struct_definition purchase_prerequisite_commendation_definition_block_block_struct;
	extern s_tag_block_definition purchase_prerequisite_commendation_definition_block_block;
	extern s_tag_struct_definition PurchasePrerequisitePurchasedAppearanceItemDefinitionBlock_block_struct;
	extern s_tag_block_definition PurchasePrerequisitePurchasedAppearanceItemDefinitionBlock_block;
	extern s_tag_struct_definition PurchasePrerequisitePurchasedLoadoutItemDefinitionBlock_block_struct;
	extern s_tag_block_definition PurchasePrerequisitePurchasedLoadoutItemDefinitionBlock_block;
	extern s_tag_struct_definition PurchasePrerequisitePurchasedOrdnanceItemDefinitionBlock_block_struct;
	extern s_tag_block_definition PurchasePrerequisitePurchasedOrdnanceItemDefinitionBlock_block;
	extern s_tag_struct_definition purchase_prerequisites_unlockable_definition_block_block_struct;
	extern s_tag_block_definition purchase_prerequisites_unlockable_definition_block_block;
	extern s_tag_struct_definition purchase_prerequisites_offer_definition_block_block_struct;
	extern s_tag_block_definition purchase_prerequisites_offer_definition_block_block;

	extern s_tag_struct_definition PurchasePrerequisitesUnifiedDefinitionBlock_struct_definition;
	extern s_tag_struct_definition PurchaseAppearanceDefinitionReferenceStruct_struct_definition;
	extern s_tag_struct_definition PurchaseLoadoutDefinitionReferenceStruct_struct_definition;
	extern s_tag_struct_definition PurchaseOrdnanceDefinitionReferenceStruct_struct_definition;

	extern c_versioned_string_list MarketplaceOfferTypeEnum_strings;
	extern s_string_list_definition MarketplaceOfferTypeEnum;

} // namespace blofeld

