#pragma once

#include "tag_definition_library_registry.h"
#include "tagframework.h"
#include "definition_migration.h"
#include "tag_struct_definition_view.h"

#include "types/field_type.h"
#include "types/field_flags.h"
#include "types/field_id.h"
#include "types/tag_field_attributed_definitions.h"
#include "types/tag_field_custom_type.h"
#include "types/tag_group_flags.h"
#include "types/field_set.h"
#include "types/tag_reference_flags.h"
#include "types/tag_versioning.h"

#include "types/tag_field.h"
#include "types/block_index_custom_search_definition.h"
#include "types/memory_attributes.h"
#include "types/persistent_identifier.h"
#include "types/string_list_definition.h"
#include "types/tag_array_definition.h"
#include "types/tag_block_definition.h"
#include "types/tag_data_definition.h"
#include "types/tag_group.h"
#include "types/tag_interop_definition.h"
#include "types/tag_reference_definition.h"
#include "types/tag_resource_definition.h"
#include "types/tag_struct_definition.h"
