version: 1.0.{build}
build_cloud: WIN-6TI85I87TDG
image: Windows
configuration:
- Release
- Test
- Debug
platform:
- Linux x64
- Linux x86
- Windows x64
- Windows x86
- Windows ARM
- Windows ARM64
- WebAssembly WASM32
- WebAssembly WASM64
clone_depth: 1
build_script:
- cmd: >-
    git submodule -q  update --init --recursive
        set MSBUILD_PLATFORM=%PLATFORM%
        set MSBUILD_CONFIGURATION=%CONFIGURATION%
        set BCS_DOWNLOAD_CACHE=C:\DownloadCache
        set BCS_THIRD_PARTY=C:\ThirdPartyCache
        setup.bat
        %BCS_THIRD_PARTY%\EWDK_ni_release_svc_prod1_22621_220804-1759\BuildEnv\SetupBuildEnv.cmd
        rem %NINJA_DIR%\ninja.exe -C solution\windows-debug-x86\ bcs_executable
        echo MSBuild Platform: %MSBUILD_PLATFORM%
        echo MSBuild Configuration: %MSBUILD_CONFIGURATION%
        rem msbuild "solution\BlamCreationSuite.sln" /m /verbosity:minimal /p:Configuration=Debug /p:Platform="Windows x64"
        msbuild "solution\BlamCreationSuite.sln" /m /verbosity:minimal /p:Platform="%MSBUILD_PLATFORM%" /p:Configuration="%MSBUILD_CONFIGURATION%"
test: off
artifacts:
- path: solution/windows-debug-x86/bin/*
  name: Mandrill
