#pragma once

namespace blofeld
{

constexpr unsigned long HSC_TAG = 'hsc*';

extern s_tag_group hsc_group;

extern s_tag_struct hs_source_files_block_block_struct;
extern s_tag_block_definition hs_source_files_block_block;
extern s_tag_struct hs_references_block_block_struct;
extern s_tag_block_definition hs_references_block_block;
extern s_tag_struct hs_scripts_block_block_struct;
extern s_tag_block_definition hs_scripts_block_block;
extern s_tag_struct hs_script_parameters_block_block_struct;
extern s_tag_block_definition hs_script_parameters_block_block;
extern s_tag_struct hs_globals_block_block_struct;
extern s_tag_block_definition hs_globals_block_block;
extern s_tag_struct HSInstancedVariablesBlock_block_struct;
extern s_tag_block_definition HSInstancedVariablesBlock_block;
extern s_tag_struct hs_unit_seat_block_block_struct;
extern s_tag_block_definition hs_unit_seat_block_block;
extern s_tag_struct hs_syntax_datum_block_block_struct;
extern s_tag_block_definition hs_syntax_datum_block_block;
extern s_tag_struct HSImportManifestBlock_block_struct;
extern s_tag_block_definition HSImportManifestBlock_block;
extern s_tag_struct HSImportManifestEntryBlock_block_struct;
extern s_tag_block_definition HSImportManifestEntryBlock_block;


} // namespace blofeld

