#pragma once

namespace blofeld
{

	extern s_tag_struct_definition particle_property_real_point3d_struct_new_struct_definition;
	extern s_tag_struct_definition particle_property_real_euler_angles2d_struct_new_struct_definition;
	extern s_tag_struct_definition particle_property_scalar_struct_new_struct_definition;
	extern s_tag_struct_definition particle_property_real_vector3d_struct_new_struct_definition;
	extern s_tag_struct_definition particle_property_color_struct_new_struct_definition;

	extern c_versioned_string_list game_state_type_enum_strings;
	extern s_string_list_definition game_state_type_enum;
	extern c_versioned_string_list output_mod_enum$3_strings;
	extern s_string_list_definition output_mod_enum$3;
	extern c_versioned_string_list force_flags_definition_strings;
	extern s_string_list_definition force_flags_definition;

} // namespace blofeld

