#pragma once

namespace blofeld
{

	extern s_tag_struct_definition polyartVertexBlock_block_struct;
	extern s_tag_block_definition polyartVertexBlock_block;
	extern s_tag_struct_definition polyartIndexBlock_block_struct;
	extern s_tag_block_definition polyartIndexBlock_block;
	extern s_tag_block_definition vertexBuffersBlock_block;
	extern s_tag_block_definition indexBuffersBlock_block;

	extern s_tag_struct_definition vertexBuffersBlock_struct_struct_definition;
	extern s_tag_struct_definition indexBuffersBlock_struct_struct_definition;

	extern c_versioned_string_list g_polyartAssetStateFlags_strings;
	extern s_string_list_definition g_polyartAssetStateFlags;
	extern c_versioned_string_list PolyartVertexFormatTypeEnum_strings;
	extern s_string_list_definition PolyartVertexFormatTypeEnum;

} // namespace blofeld

