#pragma once

namespace blofeld
{

namespace macaque
{

	extern s_tag_block_definition global_render_model_instance_placement_block;
	extern s_tag_struct_definition global_render_model_instance_placement_block_struct_definition; // global_render_model_instance_placement_block
	extern s_tag_block_definition structure_bsp_instanced_geometry_instances_block;
	extern s_tag_struct_definition structure_bsp_instanced_geometry_instances_block_struct_definition; // structure_bsp_instanced_geometry_instances_block
	extern s_tag_block_definition structure_bsp_instanced_geometry_definition_block;
	extern s_tag_struct_definition structure_bsp_instanced_geometry_definition_block_struct_definition; // structure_bsp_instanced_geometry_definition_block
	extern s_tag_block_definition structure_bsp_instanced_geometry_instances_names_block;
	extern s_tag_struct_definition structure_bsp_instanced_geometry_instances_names_block_struct_definition; // structure_bsp_instanced_geometry_instances_names_block
	extern s_tag_block_definition structureIOHavokDataBlock_block;
	extern s_tag_block_definition SerializedHavokGeometryDataBlock_block;
	extern s_tag_block_definition structure_bsp_instanced_geometry_instances_without_names_block;
	extern s_tag_struct_definition structure_bsp_instanced_geometry_instances_without_names_block_struct_definition; // structure_bsp_instanced_geometry_instances_without_names_block

	extern s_tag_struct_definition structureIOHavokDataBlock_struct;
	extern s_tag_struct_definition SerializedHavokGeometryDataBlock_struct;

	extern s_tag_struct_definition structure_bsp_instanced_geometry_collision_definition_block_block_struct;

	extern c_versioned_string_list instanced_geometry_flags_strings;
	extern s_string_list_definition instanced_geometry_flags;
	extern c_versioned_string_list instanced_geometry_imposter_policy_enum_strings;
	extern s_string_list_definition instanced_geometry_imposter_policy_enum;
	extern c_versioned_string_list instanced_geometry_pathfinding_policy_enum_strings;
	extern s_string_list_definition instanced_geometry_pathfinding_policy_enum;
	extern c_versioned_string_list instanced_geometry_lightmapping_policy_enum_strings;
	extern s_string_list_definition instanced_geometry_lightmapping_policy_enum;
	extern c_versioned_string_list instanced_geometry_streamingpriority_enum_strings;
	extern s_string_list_definition instanced_geometry_streamingpriority_enum;
	extern c_versioned_string_list instanced_geometry_definition_flags_strings;
	extern s_string_list_definition instanced_geometry_definition_flags;

} // namespace macaque

} // namespace blofeld

