#pragma once

namespace blofeld
{

namespace macaque
{

	constexpr unsigned long SCENARIO_STRUCTURE_LIGHTING_INFO_TAG = 'stli';
	extern s_tag_group scenario_structure_lighting_info_group; // scenario_structure_lighting_info_block


	extern s_tag_block_definition scenario_structure_lighting_info_block;
	extern s_tag_block_definition structure_lighting_generic_light_definition_block;
	extern s_tag_struct_definition structure_lighting_generic_light_definition_block_struct_definition; // structure_lighting_generic_light_definition_block
	extern s_tag_block_definition structure_lighting_generic_light_instance_block;
	extern s_tag_struct_definition structure_lighting_generic_light_instance_block_struct_definition; // structure_lighting_generic_light_instance_block
	extern s_tag_block_definition screen_space_light_shader_override_block;
	extern s_tag_struct_definition screen_space_light_shader_override_block_struct_definition; // screen_space_light_shader_override_block
	extern s_tag_block_definition structureLightingCinematicLightInstanceBlock_block;
	extern s_tag_block_definition structureLightingCinematicObjectBlock_block;
	extern s_tag_struct_definition structureLightingCinematicObjectBlock_block_struct_definition; // structureLightingCinematicObjectBlock_block

	extern s_tag_struct_definition scenario_structure_lighting_info_struct_definition; // tag group
	extern s_tag_struct_definition structureLightingCinematicLightInstanceBlock_struct;

	extern c_versioned_string_list structure_lighting_light_mode_enum_strings;
	extern s_string_list_definition structure_lighting_light_mode_enum;
	extern c_versioned_string_list structure_lighting_generic_light_jitter_quality_enum_strings;
	extern s_string_list_definition structure_lighting_generic_light_jitter_quality_enum;
	extern c_versioned_string_list structure_lighting_generic_light_flags_strings;
	extern s_string_list_definition structure_lighting_generic_light_flags;


} // namespace macaque

} // namespace blofeld

