#pragma once

namespace blofeld
{



	extern s_tag_struct game_audibility_block_block_struct;
	extern s_tag_block_definition game_audibility_block_block;
	extern s_tag_struct door_encoded_pas_block_block_struct;
	extern s_tag_block_definition door_encoded_pas_block_block;
	extern s_tag_struct room_door_portal_encoded_pas_block_block_struct;
	extern s_tag_block_definition room_door_portal_encoded_pas_block_block;
	extern s_tag_struct ai_deafening_encoded_pas_block_block_struct;
	extern s_tag_block_definition ai_deafening_encoded_pas_block_block;
	extern s_tag_struct encoded_room_distances_block_block_struct;
	extern s_tag_block_definition encoded_room_distances_block_block;
	extern s_tag_struct game_portal_to_door_occluder_block_block_struct;
	extern s_tag_block_definition game_portal_to_door_occluder_block_block;
	extern s_tag_struct bsp_cluster_to_room_bounds_block_struct;
	extern s_tag_block_definition bsp_cluster_to_room_bounds_block;
	extern s_tag_struct bsp_cluster_to_room_indices_block_struct;
	extern s_tag_block_definition bsp_cluster_to_room_indices_block;


} // namespace blofeld

