#pragma once

namespace blofeld
{

extern s_tag_struct platform_sound_playback_struct_struct_definition;

extern s_tag_struct platform_sound_playback_block_struct_struct_definition;
extern s_tag_block_definition platform_sound_playback_block;
extern s_tag_struct platform_sound_playback_lowpass_block_struct_struct_definition;
extern s_tag_block_definition platform_sound_playback_lowpass_block;
extern s_tag_struct platform_sound_playback_component_block_struct_struct_definition;
extern s_tag_block_definition platform_sound_playback_component_block;

constexpr unsigned long SOUND_EFFECT_COLLECTION_TAG = 'sfx+';

extern s_tag_block_definition sound_effect_collection_block;
extern s_tag_group sound_effect_collection_group;
} // namespace blofeld

