#pragma once

namespace blofeld
{


extern s_tag_struct structure_bsp_sound_cluster_block_struct_definition;
extern s_tag_block_definition structure_bsp_sound_cluster_block;
extern s_tag_struct structure_sound_cluster_portal_designators_struct_definition;
extern s_tag_block_definition structure_sound_cluster_portal_designators;
extern s_tag_struct structure_sound_cluster_interior_cluster_indices_struct_definition;
extern s_tag_block_definition structure_sound_cluster_interior_cluster_indices;

} // namespace blofeld

