#pragma once

namespace blofeld
{

constexpr unsigned long SOUND_EFFECT_TEMPLATE_TAG = '<fx>';

extern s_tag_group sound_effect_template_group;

extern s_tag_block_definition sound_effect_template_block_block;
extern s_tag_struct sound_effect_templates_block_block_struct;
extern s_tag_block_definition sound_effect_templates_block_block;
extern s_tag_struct sound_effect_template_parameter_block_block_struct;
extern s_tag_block_definition sound_effect_template_parameter_block_block;
extern s_tag_struct sound_effect_template_additional_sound_input_block_block_struct;
extern s_tag_block_definition sound_effect_template_additional_sound_input_block_block;

extern s_tag_struct sound_effect_template_struct_definition_struct_definition; // tag group

} // namespace blofeld

