#pragma once

namespace blofeld
{


	extern s_tag_block_definition scenario_acoustics_palette_block_definition_block;
	extern s_tag_struct_definition acoustic_sector_point_block_block_struct;
	extern s_tag_block_definition acoustic_sector_point_block_block;
	extern s_tag_struct_definition scenario_acoustic_sector_block_block_struct;
	extern s_tag_block_definition scenario_acoustic_sector_block_block;
	extern s_tag_struct_definition scenario_acoustic_transition_block_block_struct;
	extern s_tag_block_definition scenario_acoustic_transition_block_block;


	extern s_tag_struct_definition scenario_acoustics_palette_block_definition_struct_struct_definition;
	extern s_tag_struct_definition scenario_acoustics_environment_definition_struct_definition;
	extern s_tag_struct_definition scenario_acoustics_ambience_definition_struct_definition;
	extern s_tag_struct_definition scenario_acoustic_location_definition_struct_definition;
	extern s_tag_struct_definition scenario_acoustic_cluster_reference_definition_struct_definition;

	extern const char* background_sound_scale_flags_definition_strings[];
	extern s_string_list_definition background_sound_scale_flags_definition;
	extern const char* acousticPaletteFlags_strings[];
	extern s_string_list_definition acousticPaletteFlags;

} // namespace blofeld

