#pragma once

namespace blofeld
{

extern s_tag_struct sound_effect_template_struct_definition_struct_definition;

extern s_tag_struct sound_effect_templates_block_struct_definition;
extern s_tag_block_definition sound_effect_templates_block;
extern s_tag_struct sound_effect_template_parameter_block_struct_definition;
extern s_tag_block_definition sound_effect_template_parameter_block;
extern s_tag_struct sound_effect_template_additional_sound_input_block_struct_definition;
extern s_tag_block_definition sound_effect_template_additional_sound_input_block;

constexpr unsigned long SOUND_EFFECT_TEMPLATE_TAG = '<fx>';

extern s_tag_block_definition sound_effect_template_block;
extern s_tag_group sound_effect_template_group;
} // namespace blofeld

