#pragma once

namespace blofeld
{


extern s_tag_struct sound_language_info_block_struct_definition;
extern s_tag_block_definition sound_language_info_block;
extern s_tag_struct sound_permutation_language_info_struct_definition;
extern s_tag_block_definition sound_permutation_language_info;
extern s_tag_struct sound_pitch_range_language_info_struct_definition;
extern s_tag_block_definition sound_pitch_range_language_info;

} // namespace blofeld

