#pragma once

namespace blofeld
{



	extern s_tag_block_definition ai_cue_template_block;
	extern s_tag_struct_definition ai_cue_template_block_struct_definition; // ai_cue_template_block
	extern s_tag_block_definition firing_point_payload_block;
	extern s_tag_struct_definition firing_point_payload_block_struct_definition; // firing_point_payload_block
	extern s_tag_block_definition stimulus_payload_block;
	extern s_tag_struct_definition stimulus_payload_block_struct_definition; // stimulus_payload_block
	extern s_tag_block_definition combat_cue_payload_block;
	extern s_tag_struct_definition combat_cue_payload_block_struct_definition; // combat_cue_payload_block
	extern s_tag_block_definition ai_cue_block;
	extern s_tag_struct_definition ai_cue_block_struct_definition; // ai_cue_block
	extern s_tag_block_definition task_distribution_block;
	extern s_tag_struct_definition task_distribution_block_struct_definition; // task_distribution_block
	extern s_tag_block_definition radial_distribution_block;
	extern s_tag_struct_definition radial_distribution_block_struct_definition; // radial_distribution_block
	extern s_tag_block_definition probability_distribution_block;
	extern s_tag_struct_definition probability_distribution_block_struct_definition; // probability_distribution_block
	extern s_tag_block_definition character_distribution_block;
	extern s_tag_struct_definition character_distribution_block_struct_definition; // character_distribution_block
	extern s_tag_block_definition weapon_distribution_block;
	extern s_tag_struct_definition weapon_distribution_block_struct_definition; // weapon_distribution_block
	extern s_tag_block_definition script_payload_block;
	extern s_tag_struct_definition script_payload_block_struct_definition; // script_payload_block
	extern s_tag_block_definition combat_sync_action_group_payload_block;
	extern s_tag_struct_definition combat_sync_action_group_payload_block_struct_definition; // combat_sync_action_group_payload_block
	extern s_tag_block_definition ai_full_cue_block;
	extern s_tag_struct_definition ai_full_cue_block_struct_definition; // ai_full_cue_block
	extern s_tag_block_definition ai_quick_cue_block;
	extern s_tag_struct_definition ai_quick_cue_block_struct_definition; // ai_quick_cue_block

	extern s_tag_struct_definition cue_distribution_struct;
	extern s_tag_struct_definition cue_stimulus_distribution_struct;
	extern s_tag_struct_definition cue_payload_struct;

	extern s_string_list_definition cue_flags;
	extern s_string_list_definition cue_template_flags;
	extern s_string_list_definition quick_cue_flags;
	extern s_string_list_definition distribution_character_flags;
	extern s_string_list_definition combat_cue_preference_enum;



} // namespace blofeld

