#pragma once

namespace blofeld
{



	constexpr unsigned long CHARACTER_TAG = 'char';
	extern s_tag_group character_group; // character_block


	extern s_tag_block_definition character_block;
	extern s_tag_block_definition character_variants_block;
	extern s_tag_struct_definition character_variants_block_struct_definition; // character_variants_block
	extern s_tag_block_definition character_voice_block;
	extern s_tag_struct_definition character_voice_block_struct_definition; // character_voice_block
	extern s_tag_block_definition character_voice_region_filter_block;
	extern s_tag_struct_definition character_voice_region_filter_block_struct_definition; // character_voice_region_filter_block
	extern s_tag_block_definition character_voice_region_permutation_filter_block;
	extern s_tag_struct_definition character_voice_region_permutation_filter_block_struct_definition; // character_voice_region_permutation_filter_block
	extern s_tag_block_definition character_voice_properties_block;
	extern s_tag_struct_definition character_voice_properties_block_struct_definition; // character_voice_properties_block
	extern s_tag_block_definition character_general_block;
	extern s_tag_struct_definition character_general_block_struct_definition; // character_general_block
	extern s_tag_block_definition disallowed_weapons_for_trading_block;
	extern s_tag_struct_definition disallowed_weapons_for_trading_block_struct_definition; // disallowed_weapons_for_trading_block
	extern s_tag_block_definition character_proto_spawn_block;
	extern s_tag_struct_definition character_proto_spawn_block_struct_definition; // character_proto_spawn_block
	extern s_tag_block_definition character_interact_block;
	extern s_tag_struct_definition character_interact_block_struct_definition; // character_interact_block
	extern s_tag_block_definition character_emotions_block;
	extern s_tag_struct_definition character_emotions_block_struct_definition; // character_emotions_block
	extern s_tag_block_definition character_emotions_situational_danger_block;
	extern s_tag_struct_definition character_emotions_situational_danger_block_struct_definition; // character_emotions_situational_danger_block
	extern s_tag_block_definition character_vitality_block;
	extern s_tag_struct_definition character_vitality_block_struct_definition; // character_vitality_block
	extern s_tag_block_definition character_placement_block;
	extern s_tag_struct_definition character_placement_block_struct_definition; // character_placement_block
	extern s_tag_block_definition character_perception_block;
	extern s_tag_struct_definition character_perception_block_struct_definition; // character_perception_block
	extern s_tag_block_definition character_target_block;
	extern s_tag_struct_definition character_target_block_struct_definition; // character_target_block
	extern s_tag_block_definition character_look_block;
	extern s_tag_struct_definition character_look_block_struct_definition; // character_look_block
	extern s_tag_block_definition character_hopping_block;
	extern s_tag_struct_definition character_hopping_block_struct_definition; // character_hopping_block
	extern s_tag_block_definition characterHopDefinitionBlock_block;
	extern s_tag_struct_definition characterHopDefinitionBlock_block_struct_definition; // characterHopDefinitionBlock_block
	extern s_tag_block_definition character_movement_block;
	extern s_tag_struct_definition character_movement_block_struct_definition; // character_movement_block
	extern s_tag_block_definition movement_stationary_pause_block;
	extern s_tag_struct_definition movement_stationary_pause_block_struct_definition; // movement_stationary_pause_block
	extern s_tag_block_definition movement_throttle_control_block;
	extern s_tag_struct_definition movement_throttle_control_block_struct_definition; // movement_throttle_control_block
	extern s_tag_block_definition movement_throttle_block;
	extern s_tag_struct_definition movement_throttle_block_struct_definition; // movement_throttle_block
	extern s_tag_block_definition character_throttle_style_block;
	extern s_tag_struct_definition character_throttle_style_block_struct_definition; // character_throttle_style_block
	extern s_tag_block_definition character_movement_set_block;
	extern s_tag_struct_definition character_movement_set_block_struct_definition; // character_movement_set_block
	extern s_tag_block_definition movement_mapping_block;
	extern s_tag_struct_definition movement_mapping_block_struct_definition; // movement_mapping_block
	extern s_tag_block_definition character_flocking_block;
	extern s_tag_struct_definition character_flocking_block_struct_definition; // character_flocking_block
	extern s_tag_block_definition character_swarm_block;
	extern s_tag_struct_definition character_swarm_block_struct_definition; // character_swarm_block
	extern s_tag_block_definition character_firing_point_evaluator_block;
	extern s_tag_struct_definition character_firing_point_evaluator_block_struct_definition; // character_firing_point_evaluator_block
	extern s_tag_block_definition evaluator_definition_block;
	extern s_tag_struct_definition evaluator_definition_block_struct_definition; // evaluator_definition_block
	extern s_tag_block_definition character_ready_block;
	extern s_tag_struct_definition character_ready_block_struct_definition; // character_ready_block
	extern s_tag_block_definition character_engage_block;
	extern s_tag_struct_definition character_engage_block_struct_definition; // character_engage_block
	extern s_tag_block_definition character_charge_block;
	extern s_tag_struct_definition character_charge_block_struct_definition; // character_charge_block
	extern s_tag_block_definition character_charge_difficulty_limits_block;
	extern s_tag_struct_definition character_charge_difficulty_limits_block_struct_definition; // character_charge_difficulty_limits_block
	extern s_tag_block_definition character_evasion_block;
	extern s_tag_struct_definition character_evasion_block_struct_definition; // character_evasion_block
	extern s_tag_block_definition character_cover_block;
	extern s_tag_struct_definition character_cover_block_struct_definition; // character_cover_block
	extern s_tag_block_definition character_retreat_block;
	extern s_tag_struct_definition character_retreat_block_struct_definition; // character_retreat_block
	extern s_tag_block_definition character_search_block;
	extern s_tag_struct_definition character_search_block_struct_definition; // character_search_block
	extern s_tag_block_definition character_presearch_block;
	extern s_tag_struct_definition character_presearch_block_struct_definition; // character_presearch_block
	extern s_tag_block_definition character_idle_block;
	extern s_tag_struct_definition character_idle_block_struct_definition; // character_idle_block
	extern s_tag_block_definition character_vocalization_block;
	extern s_tag_struct_definition character_vocalization_block_struct_definition; // character_vocalization_block
	extern s_tag_block_definition character_boarding_block;
	extern s_tag_struct_definition character_boarding_block_struct_definition; // character_boarding_block
	extern s_tag_block_definition character_vehicle_boarding_block;
	extern s_tag_struct_definition character_vehicle_boarding_block_struct_definition; // character_vehicle_boarding_block
	extern s_tag_block_definition character_kungfu_block;
	extern s_tag_struct_definition character_kungfu_block_struct_definition; // character_kungfu_block
	extern s_tag_block_definition character_bunker_block;
	extern s_tag_struct_definition character_bunker_block_struct_definition; // character_bunker_block
	extern s_tag_block_definition character_guardian_block;
	extern s_tag_struct_definition character_guardian_block_struct_definition; // character_guardian_block
	extern s_tag_block_definition character_combatform_block;
	extern s_tag_struct_definition character_combatform_block_struct_definition; // character_combatform_block
	extern s_tag_block_definition character_engineer_block;
	extern s_tag_struct_definition character_engineer_block_struct_definition; // character_engineer_block
	extern s_tag_block_definition character_inspect_block;
	extern s_tag_struct_definition character_inspect_block_struct_definition; // character_inspect_block
	extern s_tag_block_definition character_scarab_block;
	extern s_tag_struct_definition character_scarab_block_struct_definition; // character_scarab_block
	extern s_tag_block_definition character_weapons_block;
	extern s_tag_struct_definition character_weapons_block_struct_definition; // character_weapons_block
	extern s_tag_block_definition character_firing_pattern_properties_block;
	extern s_tag_struct_definition character_firing_pattern_properties_block_struct_definition; // character_firing_pattern_properties_block
	extern s_tag_block_definition character_firing_pattern_block;
	extern s_tag_struct_definition character_firing_pattern_block_struct_definition; // character_firing_pattern_block
	extern s_tag_block_definition character_grenades_block;
	extern s_tag_struct_definition character_grenades_block_struct_definition; // character_grenades_block
	extern s_tag_block_definition character_vehicle_block;
	extern s_tag_struct_definition character_vehicle_block_struct_definition; // character_vehicle_block
	extern s_tag_block_definition character_flying_movement_block;
	extern s_tag_struct_definition character_flying_movement_block_struct_definition; // character_flying_movement_block
	extern s_tag_block_definition character_morph_block;
	extern s_tag_struct_definition character_morph_block_struct_definition; // character_morph_block
	extern s_tag_block_definition character_equipment_block;
	extern s_tag_struct_definition character_equipment_block_struct_definition; // character_equipment_block
	extern s_tag_block_definition character_equipment_usage_block;
	extern s_tag_struct_definition character_equipment_usage_block_struct_definition; // character_equipment_usage_block
	extern s_tag_block_definition character_stimuli_response_block;
	extern s_tag_struct_definition character_stimuli_response_block_struct_definition; // character_stimuli_response_block
	extern s_tag_block_definition character_activity_object_block;
	extern s_tag_struct_definition character_activity_object_block_struct_definition; // character_activity_object_block
	extern s_tag_block_definition character_pain_screen_block;
	extern s_tag_struct_definition character_pain_screen_block_struct_definition; // character_pain_screen_block
	extern s_tag_block_definition character_bishop_block;
	extern s_tag_struct_definition character_bishop_block_struct_definition; // character_bishop_block
	extern s_tag_block_definition character_combotron_parent_block;
	extern s_tag_struct_definition character_combotron_parent_block_struct_definition; // character_combotron_parent_block
	extern s_tag_block_definition character_combotron_child_block;
	extern s_tag_struct_definition character_combotron_child_block_struct_definition; // character_combotron_child_block
	extern s_tag_block_definition character_handle_dismemberment_block;
	extern s_tag_struct_definition character_handle_dismemberment_block_struct_definition; // character_handle_dismemberment_block
	extern s_tag_block_definition character_cover_fight_block;
	extern s_tag_struct_definition character_cover_fight_block_struct_definition; // character_cover_fight_block
	extern s_tag_block_definition character_emerge_block;
	extern s_tag_struct_definition character_emerge_block_struct_definition; // character_emerge_block
	extern s_tag_block_definition dynamic_task_block;
	extern s_tag_struct_definition dynamic_task_block_struct_definition; // dynamic_task_block
	extern s_tag_block_definition character_advance_block;
	extern s_tag_struct_definition character_advance_block_struct_definition; // character_advance_block
	extern s_tag_block_definition character_cover_evasion_block;
	extern s_tag_struct_definition character_cover_evasion_block_struct_definition; // character_cover_evasion_block
	extern s_tag_block_definition character_pack_stalk_block;
	extern s_tag_struct_definition character_pack_stalk_block_struct_definition; // character_pack_stalk_block
	extern s_tag_block_definition character_fight_circle_block;
	extern s_tag_struct_definition character_fight_circle_block_struct_definition; // character_fight_circle_block
	extern s_tag_block_definition character_hamstring_charge_block;
	extern s_tag_struct_definition character_hamstring_charge_block_struct_definition; // character_hamstring_charge_block
	extern s_tag_block_definition character_forerunner_block;
	extern s_tag_struct_definition character_forerunner_block_struct_definition; // character_forerunner_block
	extern s_tag_block_definition character_gravity_jump_block;
	extern s_tag_struct_definition character_gravity_jump_block_struct_definition; // character_gravity_jump_block

	extern s_tag_struct_definition character_struct_definition; // tag group
	extern s_tag_struct_definition active_camo_perception_properties;
	extern s_tag_struct_definition character_hop_struct;
	extern s_tag_struct_definition SmoothThrottleStruct;
	extern s_tag_struct_definition SmoothStoppingStruct;
	extern s_tag_struct_definition character_bunker_timings_struct;

	extern c_versioned_string_list generic_flags_strings;
	extern s_string_list_definition generic_flags;
	extern c_versioned_string_list actor_type_enum_strings;
	extern s_string_list_definition actor_type_enum;
	extern c_versioned_string_list global_ai_grenade_type_enum_strings;
	extern s_string_list_definition global_ai_grenade_type_enum;
	extern c_versioned_string_list behavior_tree_root_enum_strings;
	extern s_string_list_definition behavior_tree_root_enum;
	extern c_versioned_string_list general_flags_strings;
	extern s_string_list_definition general_flags;
	extern c_versioned_string_list combat_positioning_enum_strings;
	extern s_string_list_definition combat_positioning_enum;
	extern c_versioned_string_list proto_spawn_type_enum_strings;
	extern s_string_list_definition proto_spawn_type_enum;
	extern c_versioned_string_list prop_class_enum_strings;
	extern s_string_list_definition prop_class_enum;
	extern c_versioned_string_list vitality_flags_strings;
	extern s_string_list_definition vitality_flags;
	extern c_versioned_string_list perception_flags_strings;
	extern s_string_list_definition perception_flags;
	extern c_versioned_string_list actor_perception_mode_definition_strings;
	extern s_string_list_definition actor_perception_mode_definition;
	extern c_versioned_string_list hopping_flags_strings;
	extern s_string_list_definition hopping_flags;
	extern c_versioned_string_list movement_flags_strings;
	extern s_string_list_definition movement_flags;
	extern c_versioned_string_list obstacle_ignore_enum_strings;
	extern s_string_list_definition obstacle_ignore_enum;
	extern c_versioned_string_list movement_hint_enum_strings;
	extern s_string_list_definition movement_hint_enum;
	extern c_versioned_string_list global_ai_jump_height_enum_strings;
	extern s_string_list_definition global_ai_jump_height_enum;
	extern c_versioned_string_list combat_status_enum_definition_strings;
	extern s_string_list_definition combat_status_enum_definition;
	extern c_versioned_string_list movement_throttle_control_flags_strings;
	extern s_string_list_definition movement_throttle_control_flags;
	extern c_versioned_string_list character_smooth_movement_settings_options_strings;
	extern s_string_list_definition character_smooth_movement_settings_options;
	extern c_versioned_string_list evaluator_enum_strings;
	extern s_string_list_definition evaluator_enum;
	extern c_versioned_string_list evaluation_modes_strings;
	extern s_string_list_definition evaluation_modes;
	extern c_versioned_string_list engage_flags_strings;
	extern s_string_list_definition engage_flags;
	extern c_versioned_string_list cover_flags_strings;
	extern s_string_list_definition cover_flags;
	extern c_versioned_string_list character_search_flags_strings;
	extern s_string_list_definition character_search_flags;
	extern c_versioned_string_list character_retreat_flags_strings;
	extern s_string_list_definition character_retreat_flags;
	extern c_versioned_string_list charge_flags_strings;
	extern s_string_list_definition charge_flags;
	extern c_versioned_string_list actor_special_fire_mode_enum_strings;
	extern s_string_list_definition actor_special_fire_mode_enum;
	extern c_versioned_string_list actor_special_fire_situation_enum_strings;
	extern s_string_list_definition actor_special_fire_situation_enum;
	extern c_versioned_string_list weapon_flags_strings;
	extern s_string_list_definition weapon_flags;
	extern c_versioned_string_list actor_grenade_trajectory_enum_strings;
	extern s_string_list_definition actor_grenade_trajectory_enum;
	extern c_versioned_string_list grenades_flags_strings;
	extern s_string_list_definition grenades_flags;
	extern c_versioned_string_list vehicle_flags$2_strings;
	extern s_string_list_definition vehicle_flags$2;
	extern c_versioned_string_list vehicle_boarding_flags_strings;
	extern s_string_list_definition vehicle_boarding_flags;
	extern c_versioned_string_list boarding_flags_strings;
	extern s_string_list_definition boarding_flags;
	extern c_versioned_string_list rook_flags_strings;
	extern s_string_list_definition rook_flags;
	extern c_versioned_string_list agent_filter_flags_strings;
	extern s_string_list_definition agent_filter_flags;
	extern c_versioned_string_list task_generation_flags_strings;
	extern s_string_list_definition task_generation_flags;
	extern c_versioned_string_list character_advance_type_enum_strings;
	extern s_string_list_definition character_advance_type_enum;
	extern c_versioned_string_list advance_flags_strings;
	extern s_string_list_definition advance_flags;
	extern c_versioned_string_list forerunner_flags_strings;
	extern s_string_list_definition forerunner_flags;
	extern c_versioned_string_list character_equipment_usage_when_enum_strings;
	extern s_string_list_definition character_equipment_usage_when_enum;
	extern c_versioned_string_list character_equipment_usage_how_enum_strings;
	extern s_string_list_definition character_equipment_usage_how_enum;
	extern c_versioned_string_list character_equipment_def_bits_strings;
	extern s_string_list_definition character_equipment_def_bits;
	extern c_versioned_string_list character_flags_strings;
	extern s_string_list_definition character_flags;



} // namespace blofeld

