#pragma once

namespace blofeld
{



	extern s_tag_block_definition PuppetShowsBlock_block;
	extern s_tag_struct_definition PuppetShowsBlock_block_struct_definition; // PuppetShowsBlock_block
	extern s_tag_block_definition PuppetBlock_block;
	extern s_tag_struct_definition PuppetBlock_block_struct_definition; // PuppetBlock_block
	extern s_tag_block_definition PuppetActionBlock_block;
	extern s_tag_struct_definition PuppetActionBlock_block_struct_definition; // PuppetActionBlock_block
	extern s_tag_block_definition PuppetPathPointBlock_block;
	extern s_tag_block_definition PuppetSubActionBlock_block;
	extern s_tag_struct_definition PuppetSubActionBlock_block_struct_definition; // PuppetSubActionBlock_block
	extern s_tag_block_definition PuppetSubActionBranchElementBlock_block;
	extern s_tag_struct_definition PuppetSubActionBranchElementBlock_block_struct_definition; // PuppetSubActionBranchElementBlock_block
	extern s_tag_block_definition PuppetScriptTextBlock_block;
	extern s_tag_struct_definition PuppetScriptTextBlock_block_struct_definition; // PuppetScriptTextBlock_block
	extern s_tag_block_definition SubTracksBlock_block;
	extern s_tag_struct_definition SubTracksBlock_block_struct_definition; // SubTracksBlock_block
	extern s_tag_block_definition PuppetHeaderBlock_block;
	extern s_tag_block_definition PuppetActionHeaderBlock_block;
	extern s_tag_block_definition PuppetSubActionHeaderBlock_block;
	extern s_tag_block_definition PuppetAnimationBlock_block;
	extern s_tag_block_definition PuppetPathBlock_block;
	extern s_tag_block_definition PuppetPointBlock_block;
	extern s_tag_block_definition PuppetBranchBlock_block;
	extern s_tag_block_definition PuppetScriptBlock_block;
	extern s_tag_block_definition CommentsBlock_block;
	extern s_tag_struct_definition CommentsBlock_block_struct_definition; // CommentsBlock_block

	extern s_tag_struct_definition PuppetHeaderStruct;
	extern s_tag_struct_definition PuppetPathPointStruct;
	extern s_tag_struct_definition PuppetActionHeaderStruct;
	extern s_tag_struct_definition PuppetActionAnimationStruct;
	extern s_tag_struct_definition PuppetActionPathStruct;
	extern s_tag_struct_definition PuppetSubActionHeaderStruct;
	extern s_tag_struct_definition PuppetSubActionPointStruct;
	extern s_tag_struct_definition PuppetSubActionBranchStruct;
	extern s_tag_struct_definition PuppetSubActionScriptStruct;

	extern s_string_list_definition PuppetIndexTypeEnum;
	extern s_string_list_definition PuppetActionTypeEnum;
	extern s_string_list_definition PuppetActionBlendTypeEnum;
	extern s_string_list_definition PuppetSubActionTypeEnum;
	extern s_string_list_definition SubActionTimeTypeEnum;
	extern s_string_list_definition PuppetPathPointTypeEnum;
	extern s_string_list_definition AnimPositionTypeEnum;
	extern s_string_list_definition PuppetPathPointFlagsDefinition;
	extern s_string_list_definition PuppetFlagsDefinition;
	extern s_string_list_definition PuppetShowFlagsDefinition;
	extern s_string_list_definition PuppetAnimationFlagsDefinition;
	extern s_string_list_definition SubActionPointFlagsDefinition;
	extern s_string_list_definition PuppetEditorFlagsDefinition;



} // namespace blofeld

