#pragma once

namespace blofeld
{

namespace macaque
{

	extern s_tag_block_definition campaign_metagame_bucket_block;
	extern s_tag_struct_definition campaign_metagame_bucket_block_struct_definition; // campaign_metagame_bucket_block
	extern s_tag_block_definition campaign_metagame_globals_block;
	extern s_tag_struct_definition campaign_metagame_globals_block_struct_definition; // campaign_metagame_globals_block
	extern s_tag_block_definition campaign_metagame_style_type_block;
	extern s_tag_struct_definition campaign_metagame_style_type_block_struct_definition; // campaign_metagame_style_type_block
	extern s_tag_block_definition campaign_metagame_difficulty_scale_block;
	extern s_tag_struct_definition campaign_metagame_difficulty_scale_block_struct_definition; // campaign_metagame_difficulty_scale_block
	extern s_tag_block_definition campaign_metagame_skull_block;
	extern s_tag_struct_definition campaign_metagame_skull_block_struct_definition; // campaign_metagame_skull_block
	extern s_tag_block_definition campaign_metagame_scenario_block;
	extern s_tag_struct_definition campaign_metagame_scenario_block_struct_definition; // campaign_metagame_scenario_block
	extern s_tag_block_definition campaign_metagame_scenario_bonuses_block;
	extern s_tag_struct_definition campaign_metagame_scenario_bonuses_block_struct_definition; // campaign_metagame_scenario_bonuses_block


	extern c_versioned_string_list campaign_metagame_bucket_type_enum_strings;
	extern s_string_list_definition campaign_metagame_bucket_type_enum;
	extern c_versioned_string_list campaign_metagame_bucket_class_enum_strings;
	extern s_string_list_definition campaign_metagame_bucket_class_enum;
	extern c_versioned_string_list campaign_metagame_bucket_type_with_none_enum_strings;
	extern s_string_list_definition campaign_metagame_bucket_type_with_none_enum;
	extern c_versioned_string_list campaign_metagame_bucket_class_with_none_enum_strings;
	extern s_string_list_definition campaign_metagame_bucket_class_with_none_enum;
	extern c_versioned_string_list campaign_metagame_bucket_flags_strings;
	extern s_string_list_definition campaign_metagame_bucket_flags;

} // namespace macaque

} // namespace blofeld

