#pragma once

struct nicename("cheap_particle_emitter") tag_group('cpem') s_cheap_particle_emitter_definition
{
	int16_t nicename("Spray Style") spray_style;
	int16_t __unknown0;
	Undefined32 __unknown1;
	Undefined32 __unknown2;
	int16_t __unknown3;
	int16_t __unknown4;
	DataReference __unknown5;
	float __unknown6;
	float __unknown7;
	DEPRECATED_string_id __unknown8;
	float __unknown9;
	DEPRECATED_string_id __unknown10;
	float __unknown11;
	DEPRECATED_string_id __unknown12;
	float __unknown13;
	DEPRECATED_string_id __unknown14;
	float __unknown15;
	float __unknown16;
	float __unknown17;
	TagReference __unknown18;
	float __unknown19;
	float __unknown20;
	TagReference __unknown21;
	float __unknown22;
	float __unknown23;
	float __unknown24;
	float __unknown25;
	float __unknown26;
	float __unknown27;
	float __unknown28;
	float __unknown29;
	float __unknown30;
	float __unknown31;
	float __unknown32;
	float __unknown33;
	float nicename("Origin Radius?") origin_radius;
	float __unknown34;
	float __unknown35;
	float nicename("Amount?") amount;
	float nicename("Y Scale/Spread Min") y_scale_spread_min;
	float nicename("Y Scale/Spread Max") y_scale_spread_max;
	float nicename("X Scale/Spread Min") x_scale_spread_min;
	float nicename("X Scale/Spread Max") x_scale_spread_max;
	float nicename("Distance From Origin?") distance_from_origin;
	float nicename("Gravity?") gravity;
	float nicename("Fade Time?") fade_time;
	float nicename("Amount?") amount1;
	float nicename("Primary Particle Amount") primary_particle_amount;
	float nicename("Secondary Particle Amount") secondary_particle_amount;
	float nicename("Tertiary Particle Amount") tertiary_particle_amount;
	float nicename("Quaternary Particle Amount") quaternary_particle_amount;
	float nicename("Primary Particle Type?") primary_particle_type;
	float nicename("Secondary Particle Type?") secondary_particle_type;
	float nicename("Tertiary Particle Particle Type?") tertiary_particle_particle_type;
	float nicename("Quaternary Particle Type?") quaternary_particle_type;
	TagReference __unknown36;
};

