#pragma once

struct nicename("communication_sounds") tag_group('coms') s_communication_sounds_definition_legacy
{
	s_tag_reference_legacy nicename("Enemy Mauler") enemy_mauler_reference;
	s_tag_reference_legacy nicename("Alert Holding") alert_holding_reference;
	s_tag_reference_legacy nicename("Single Enemy") single_enemy_reference;
	s_tag_reference_legacy nicename("Two Enemies") two_enemies_reference;
	s_tag_reference_legacy nicename("Three Enemies") three_enemies_reference;
	s_tag_reference_legacy nicename("Many Enemies") many_enemies_reference;
	s_tag_reference_legacy nicename("Enemy Vehicle") enemy_vehicle_reference;
	s_tag_reference_legacy nicename("Many Enemy Vehicles") many_enemy_vehicles_reference;
	s_tag_reference_legacy nicename("Enemy Tank") enemy_tank_reference;
	s_tag_reference_legacy nicename("Many Enemy Tanks") many_enemy_tanks_reference;
	s_tag_reference_legacy nicename("Enemy Banshee") enemy_banshee_reference;
	s_tag_reference_legacy nicename("Flying Enemy") flying_enemy_reference;
	s_tag_reference_legacy nicename("Enemy Ghost") enemy_ghost_reference;
	s_tag_reference_legacy nicename("Enemy Wraith") enemy_wraith_reference;
	s_tag_reference_legacy nicename("Enemy Scorpion") enemy_scorpion_reference;
	s_tag_reference_legacy nicename("Enemy Mongoose") enemy_mongoose_reference;
	s_tag_reference_legacy nicename("Alert Backup") alert_backup_reference;
	s_tag_reference_legacy __unknown0;
	s_tag_reference_legacy nicename("Locations unknown") locations_unknown_reference;
	s_tag_reference_legacy nicename("Locations unknown") locations_unknown1_reference;
	s_tag_reference_legacy nicename("Locations unknown") locations_unknown2_reference;
	s_tag_reference_legacy nicename("Locations unknown") locations_unknown3_reference;
	s_tag_reference_legacy nicename("Locations unknown") locations_unknown4_reference;
	s_tag_reference_legacy nicename("Locations unknown") locations_unknown5_reference;
	s_tag_reference_legacy nicename("Locations unknown") locations_unknown6_reference;
	s_tag_reference_legacy nicename("Locations unknown") locations_unknown7_reference;
	s_tag_reference_legacy nicename("Locations unknown") locations_unknown8_reference;
	s_tag_reference_legacy nicename("Locations unknown") locations_unknown9_reference;
	s_tag_reference_legacy nicename("Locations unknown") locations_unknown10_reference;
	s_tag_reference_legacy nicename("Locations unknown") locations_unknown11_reference;
	s_tag_reference_legacy nicename("Locations unknown") locations_unknown12_reference;
	s_tag_reference_legacy nicename("Locations unknown") locations_unknown13_reference;
	s_tag_reference_legacy nicename("Locations unknown") locations_unknown14_reference;
	s_tag_reference_legacy nicename("Locations unknown") locations_unknown15_reference;
	s_tag_reference_legacy nicename("Locations unknown") locations_unknown16_reference;
	s_tag_reference_legacy nicename("Locations unknown") locations_unknown17_reference;
	s_tag_reference_legacy nicename("Locations unknown") locations_unknown18_reference;
	s_tag_reference_legacy nicename("Locations unknown") locations_unknown19_reference;
	s_tag_reference_legacy nicename("Locations unknown") locations_unknown20_reference;
	s_tag_reference_legacy nicename("Locations unknown") locations_unknown21_reference;
	s_tag_reference_legacy nicename("Locations unknown") locations_unknown22_reference;
	s_tag_reference_legacy nicename("Locations unknown") locations_unknown23_reference;
	s_tag_reference_legacy nicename("Locations unknown") locations_unknown24_reference;
	s_tag_reference_legacy nicename("Locations unknown") locations_unknown25_reference;
	s_tag_reference_legacy nicename("Locations unknown") locations_unknown26_reference;
	s_tag_reference_legacy nicename("Locations unknown") locations_unknown27_reference;
	s_tag_reference_legacy nicename("Locations unknown") locations_unknown28_reference;
	s_tag_reference_legacy nicename("Locations unknown") locations_unknown29_reference;
	s_tag_reference_legacy nicename("Locations unknown") locations_unknown30_reference;
	s_tag_reference_legacy nicename("Locations unknown") locations_unknown31_reference;
	s_tag_reference_legacy nicename("Locations unknown") locations_unknown32_reference;
	s_tag_reference_legacy nicename("Locations unknown") locations_unknown33_reference;
	s_tag_reference_legacy nicename("Locations unknown") locations_unknown34_reference;
	s_tag_reference_legacy nicename("Locations unknown") locations_unknown35_reference;
	s_tag_reference_legacy nicename("Locations unknown") locations_unknown36_reference;
	s_tag_reference_legacy nicename("Locations aftship ") locations_aftship__reference;
	s_tag_reference_legacy nicename("Locations aftship ") locations_aftship_1_reference;
	s_tag_reference_legacy nicename("Locations aftship ") locations_aftship_2_reference;
	s_tag_reference_legacy nicename("Locations aftship ") locations_aftship_3_reference;
	s_tag_reference_legacy nicename("Locations aftship ") locations_aftship_4_reference;
	s_tag_reference_legacy nicename("Locations aftship ") locations_aftship_5_reference;
	s_tag_reference_legacy nicename("Locations aftship ") locations_aftship_6_reference;
	s_tag_reference_legacy nicename("Locations aftship ") locations_aftship_7_reference;
	s_tag_reference_legacy nicename("Locations aftship ") locations_aftship_8_reference;
	s_tag_reference_legacy nicename("Locations aftship ") locations_aftship_9_reference;
	s_tag_reference_legacy nicename("Locations aftship ") locations_aftship_10_reference;
	s_tag_reference_legacy nicename("Locations aftship ") locations_aftship_11_reference;
	s_tag_reference_legacy nicename("Locations aftship ") locations_aftship_12_reference;
	s_tag_reference_legacy nicename("Locations aftship ") locations_aftship_13_reference;
	s_tag_reference_legacy nicename("Locations aftship ") locations_aftship_14_reference;
	s_tag_reference_legacy nicename("Locations aftship ") locations_aftship_15_reference;
	s_tag_reference_legacy nicename("Locations aftship ") locations_aftship_16_reference;
	s_tag_reference_legacy nicename("Locations aftship ") locations_aftship_17_reference;
	s_tag_reference_legacy nicename("Locations aftship ") locations_aftship_18_reference;
	s_tag_reference_legacy nicename("Locations aftship ") locations_aftship_19_reference;
	s_tag_reference_legacy nicename("Locations sword base ") locations_sword_base__reference;
	s_tag_reference_legacy nicename("Locations sword base ") locations_sword_base_1_reference;
	s_tag_reference_legacy nicename("Locations sword base ") locations_sword_base_2_reference;
	s_tag_reference_legacy nicename("Locations sword base ") locations_sword_base_3_reference;
	s_tag_reference_legacy nicename("Locations sword base ") locations_sword_base_4_reference;
	s_tag_reference_legacy nicename("Locations sword base ") locations_sword_base_5_reference;
	s_tag_reference_legacy nicename("Locations sword base ") locations_sword_base_6_reference;
	s_tag_reference_legacy nicename("Locations sword base ") locations_sword_base_7_reference;
	s_tag_reference_legacy nicename("Locations sword base ") locations_sword_base_8_reference;
	s_tag_reference_legacy nicename("Locations sword base ") locations_sword_base_9_reference;
	s_tag_reference_legacy nicename("Locations sword base ") locations_sword_base_10_reference;
	s_tag_reference_legacy nicename("Locations sword base ") locations_sword_base_11_reference;
	s_tag_reference_legacy nicename("Locations sword base ") locations_sword_base_12_reference;
	s_tag_reference_legacy nicename("Locations sword base ") locations_sword_base_13_reference;
	s_tag_reference_legacy nicename("Locations sword base ") locations_sword_base_14_reference;
	s_tag_reference_legacy nicename("Locations sword base ") locations_sword_base_15_reference;
	s_tag_reference_legacy nicename("Locations sword base ") locations_sword_base_16_reference;
	s_tag_reference_legacy nicename("Locations sword base ") locations_sword_base_17_reference;
	s_tag_reference_legacy nicename("Locations sword base ") locations_sword_base_18_reference;
	s_tag_reference_legacy nicename("Locations sword base ") locations_sword_base_19_reference;
	s_tag_reference_legacy nicename("Locations sword base ") locations_sword_base_20_reference;
	s_tag_reference_legacy nicename("Locations sword base ") locations_sword_base_21_reference;
	s_tag_reference_legacy nicename("Locations sword base ") locations_sword_base_22_reference;
	s_tag_reference_legacy nicename("Locations sword base ") locations_sword_base_23_reference;
	s_tag_reference_legacy nicename("Locations sword base ") locations_sword_base_24_reference;
	s_tag_reference_legacy nicename("Locations sword base ") locations_sword_base_25_reference;
	s_tag_reference_legacy nicename("Locations sword base ") locations_sword_base_26_reference;
	s_tag_reference_legacy nicename("Locations sword base ") locations_sword_base_27_reference;
	s_tag_reference_legacy nicename("Locations sword base ") locations_sword_base_28_reference;
	s_tag_reference_legacy nicename("Locations sword base ") locations_sword_base_29_reference;
	s_tag_reference_legacy nicename("Locations sword base ") locations_sword_base_30_reference;
	s_tag_reference_legacy nicename("Locations sword base ") locations_sword_base_31_reference;
	s_tag_reference_legacy nicename("Locations sword base ") locations_sword_base_32_reference;
	s_tag_reference_legacy nicename("Locations settlement ") locations_settlement__reference;
	s_tag_reference_legacy nicename("Locations settlement ") locations_settlement_1_reference;
	s_tag_reference_legacy nicename("Locations settlement ") locations_settlement_2_reference;
	s_tag_reference_legacy nicename("Locations settlement ") locations_settlement_3_reference;
	s_tag_reference_legacy nicename("Locations settlement ") locations_settlement_4_reference;
	s_tag_reference_legacy nicename("Locations settlement ") locations_settlement_5_reference;
	s_tag_reference_legacy nicename("Locations settlement ") locations_settlement_6_reference;
	s_tag_reference_legacy nicename("Locations settlement ") locations_settlement_7_reference;
	s_tag_reference_legacy nicename("Locations settlement ") locations_settlement_8_reference;
	s_tag_reference_legacy nicename("Locations settlement ") locations_settlement_9_reference;
	s_tag_reference_legacy nicename("Locations settlement ") locations_settlement_10_reference;
	s_tag_reference_legacy nicename("Locations settlement ") locations_settlement_11_reference;
	s_tag_reference_legacy nicename("Locations settlement ") locations_settlement_12_reference;
	s_tag_reference_legacy nicename("Locations settlement ") locations_settlement_13_reference;
	s_tag_reference_legacy nicename("Locations settlement ") locations_settlement_14_reference;
	s_tag_reference_legacy nicename("Locations settlement ") locations_settlement_15_reference;
	s_tag_reference_legacy nicename("Locations settlement ") locations_settlement_16_reference;
	s_tag_reference_legacy nicename("Locations settlement ") locations_settlement_17_reference;
	s_tag_reference_legacy nicename("Locations settlement ") locations_settlement_18_reference;
	s_tag_reference_legacy nicename("Locations settlement ") locations_settlement_19_reference;
	s_tag_reference_legacy nicename("Locations settlement ") locations_settlement_20_reference;
	s_tag_reference_legacy nicename("Locations settlement ") locations_settlement_21_reference;
	s_tag_reference_legacy nicename("Locations settlement ") locations_settlement_22_reference;
	s_tag_reference_legacy nicename("Locations settlement ") locations_settlement_23_reference;
	s_tag_reference_legacy nicename("Locations settlement ") locations_settlement_24_reference;
	s_tag_reference_legacy nicename("Locations settlement ") locations_settlement_25_reference;
	s_tag_reference_legacy nicename("Locations settlement ") locations_settlement_26_reference;
	s_tag_reference_legacy nicename("Locations settlement ") locations_settlement_27_reference;
	s_tag_reference_legacy nicename("Locations settlement ") locations_settlement_28_reference;
	s_tag_reference_legacy nicename("Locations settlement ") locations_settlement_29_reference;
	s_tag_reference_legacy nicename("Locations settlement ") locations_settlement_30_reference;
	s_tag_reference_legacy nicename("Locations settlement ") locations_settlement_31_reference;
	s_tag_reference_legacy nicename("Locations settlement ") locations_settlement_32_reference;
	s_tag_reference_legacy nicename("Locations settlement ") locations_settlement_33_reference;
	s_tag_reference_legacy nicename("Locations settlement ") locations_settlement_34_reference;
	s_tag_reference_legacy nicename("Locations settlement ") locations_settlement_35_reference;
	s_tag_reference_legacy nicename("Locations settlement ") locations_settlement_36_reference;
	s_tag_reference_legacy nicename("Locations settlement ") locations_settlement_37_reference;
	s_tag_reference_legacy nicename("Locations settlement ") locations_settlement_38_reference;
	s_tag_reference_legacy nicename("Locations settlement ") locations_settlement_39_reference;
	s_tag_reference_legacy nicename("Locations settlement ") locations_settlement_40_reference;
	s_tag_reference_legacy nicename("Locations settlement ") locations_settlement_41_reference;
	s_tag_reference_legacy nicename("Locations settlement ") locations_settlement_42_reference;
	s_tag_reference_legacy nicename("Locations settlement ") locations_settlement_43_reference;
	s_tag_reference_legacy nicename("Locations settlement ") locations_settlement_44_reference;
	s_tag_reference_legacy nicename("Locations settlement ") locations_settlement_45_reference;
	s_tag_reference_legacy nicename("Locations sword base ") locations_sword_base_33_reference;
	s_tag_reference_legacy nicename("Locations sword base ") locations_sword_base_34_reference;
	s_tag_reference_legacy nicename("Locations sword base ") locations_sword_base_35_reference;
	s_tag_reference_legacy nicename("Locations sword base ") locations_sword_base_36_reference;
	s_tag_reference_legacy nicename("Locations sword base ") locations_sword_base_37_reference;
	s_tag_reference_legacy nicename("Locations launch station ") locations_launch_station__reference;
	s_tag_reference_legacy nicename("Locations launch station ") locations_launch_station_1_reference;
	s_tag_reference_legacy nicename("Locations launch station ") locations_launch_station_2_reference;
	s_tag_reference_legacy nicename("Locations launch station ") locations_launch_station_3_reference;
	s_tag_reference_legacy nicename("Locations launch station ") locations_launch_station_4_reference;
	s_tag_reference_legacy nicename("Locations launch station ") locations_launch_station_5_reference;
	s_tag_reference_legacy nicename("Locations launch station ") locations_launch_station_6_reference;
	s_tag_reference_legacy nicename("Locations launch station ") locations_launch_station_7_reference;
	s_tag_reference_legacy nicename("Locations launch station ") locations_launch_station_8_reference;
	s_tag_reference_legacy nicename("Locations launch station ") locations_launch_station_9_reference;
	s_tag_reference_legacy nicename("Locations launch station ") locations_launch_station_10_reference;
	s_tag_reference_legacy nicename("Locations launch station ") locations_launch_station_11_reference;
	s_tag_reference_legacy nicename("Locations launch station ") locations_launch_station_12_reference;
	s_tag_reference_legacy nicename("Locations launch station ") locations_launch_station_13_reference;
	s_tag_reference_legacy nicename("Locations launch station ") locations_launch_station_14_reference;
	s_tag_reference_legacy nicename("Locations launch station ") locations_launch_station_15_reference;
	s_tag_reference_legacy nicename("Locations launch station ") locations_launch_station_16_reference;
	s_tag_reference_legacy nicename("Locations launch station ") locations_launch_station_17_reference;
	s_tag_reference_legacy nicename("Locations launch station ") locations_launch_station_18_reference;
	s_tag_reference_legacy nicename("Locations launch station ") locations_launch_station_19_reference;
	s_tag_reference_legacy nicename("Locations launch station ") locations_launch_station_20_reference;
	s_tag_reference_legacy nicename("Locations launch station ") locations_launch_station_21_reference;
	s_tag_reference_legacy nicename("Locations launch station ") locations_launch_station_22_reference;
	s_tag_reference_legacy nicename("Locations launch station ") locations_launch_station_23_reference;
	s_tag_reference_legacy nicename("Locations launch station ") locations_launch_station_24_reference;
	s_tag_reference_legacy nicename("Locations launch station ") locations_launch_station_25_reference;
	s_tag_reference_legacy nicename("Locations launch station ") locations_launch_station_26_reference;
	s_tag_reference_legacy nicename("Locations launch station ") locations_launch_station_27_reference;
	s_tag_reference_legacy nicename("Locations launch station ") locations_launch_station_28_reference;
	s_tag_reference_legacy nicename("Locations launch station ") locations_launch_station_29_reference;
	s_tag_reference_legacy nicename("Locations launch station ") locations_launch_station_30_reference;
	s_tag_reference_legacy nicename("Locations launch station ") locations_launch_station_31_reference;
	s_tag_reference_legacy nicename("Locations launch station ") locations_launch_station_32_reference;
	s_tag_reference_legacy nicename("Locations launch station ") locations_launch_station_33_reference;
	s_tag_reference_legacy nicename("Locations launch station ") locations_launch_station_34_reference;
	s_tag_reference_legacy nicename("Locations launch station ") locations_launch_station_35_reference;
	s_tag_reference_legacy nicename("Locations settlement ") locations_settlement_46_reference;
	s_tag_reference_legacy nicename("Locations settlement ") locations_settlement_47_reference;
	s_tag_reference_legacy nicename("Locations settlement ") locations_settlement_48_reference;
	s_tag_reference_legacy nicename("Locations settlement ") locations_settlement_49_reference;
	s_tag_reference_legacy nicename("Locations settlement ") locations_settlement_50_reference;
	s_tag_reference_legacy nicename("Locations settlement ") locations_settlement_51_reference;
	s_tag_reference_legacy nicename("Locations settlement ") locations_settlement_52_reference;
	s_tag_reference_legacy nicename("Locations settlement ") locations_settlement_53_reference;
	s_tag_reference_legacy nicename("Locations settlement ") locations_settlement_54_reference;
	s_tag_reference_legacy nicename("Locations settlement ") locations_settlement_55_reference;
	s_tag_reference_legacy nicename("Locations settlement ") locations_settlement_56_reference;
	s_tag_reference_legacy nicename("Locations settlement ") locations_settlement_57_reference;
};

