#pragma once

struct nicename("megalogamengine_sounds") tag_group('mgls') s_megalogamengine_sounds_definition
{
	s_tag_reference_legacy nicename("Slayer Intro") slayer_intro_reference;
	s_tag_reference_legacy nicename("CTF Intro") ctf_intro_reference;
	s_tag_reference_legacy nicename("CTF Captured") ctf_captured_reference;
	s_tag_reference_legacy nicename("CTF Dropped") ctf_dropped_reference;
	s_tag_reference_legacy nicename("CTF Recovered") ctf_recovered_reference;
	s_tag_reference_legacy nicename("CTF Reset") ctf_reset_reference;
	s_tag_reference_legacy nicename("CTF Stolen") ctf_stolen_reference;
	s_tag_reference_legacy nicename("CTF Taken") ctf_taken_reference;
	s_tag_reference_legacy nicename("VIP Intro") vip_intro_reference;
	s_tag_reference_legacy nicename("VIP New") vip_new_reference;
	s_tag_reference_legacy nicename("VIP Killed") vip_killed_reference;
	s_tag_reference_legacy nicename("Juggernaut Intro") juggernaut_intro_reference;
	s_tag_reference_legacy nicename("Juggernaut New") juggernaut_new_reference;
	s_tag_reference_legacy nicename("Territories Intro") territories_intro_reference;
	s_tag_reference_legacy nicename("Territories Captured") territories_captured_reference;
	s_tag_reference_legacy nicename("Territories Lost") territories_lost_reference;
	s_tag_reference_legacy nicename("Assault Intro") assault_intro_reference;
	s_tag_reference_legacy nicename("Assault Armed") assault_armed_reference;
	s_tag_reference_legacy nicename("Assault Detonated") assault_detonated_reference;
	s_tag_reference_legacy nicename("Assault Disarmed") assault_disarmed_reference;
	s_tag_reference_legacy nicename("Assault Dropped") assault_dropped_reference;
	s_tag_reference_legacy nicename("Assault Reset") assault_reset_reference;
	s_tag_reference_legacy nicename("Assault Returned") assault_returned_reference;
	s_tag_reference_legacy nicename("Assault Taken") assault_taken_reference;
	s_tag_reference_legacy nicename("Infection Intro") infection_intro_reference;
	s_tag_reference_legacy nicename("Infection Infected") infection_infected_reference;
	s_tag_reference_legacy nicename("Infection Last Man Standing") infection_last_man_standing_reference;
	s_tag_reference_legacy nicename("Infection New") infection_new_reference;
	s_tag_reference_legacy nicename("Oddball Intro") oddball_intro_reference;
	s_tag_reference_legacy nicename("Oddball Spawn") oddball_spawn_reference;
	s_tag_reference_legacy nicename("Oddball Taken") oddball_taken_reference;
	s_tag_reference_legacy nicename("Oddball Dropped") oddball_dropped_reference;
	s_tag_reference_legacy nicename("Oddball Reset") oddball_reset_reference;
	s_tag_reference_legacy nicename("KOTH Intro") koth_intro_reference;
	s_tag_reference_legacy nicename("KOTH Controlled") koth_controlled_reference;
	s_tag_reference_legacy nicename("KOTH Contested") koth_contested_reference;
	s_tag_reference_legacy nicename("KOTH Moved") koth_moved_reference;
	s_tag_reference_legacy nicename("Headhunter Intro") headhunter_intro_reference;
	s_tag_reference_legacy nicename("Stockpile Intro") stockpile_intro_reference;
	s_tag_reference_legacy nicename("Race Intro") race_intro_reference;
	s_tag_reference_legacy nicename("CTF Defense") ctf_defense_reference;
	s_tag_reference_legacy nicename("CTF Offense") ctf_offense_reference;
	s_tag_reference_legacy nicename("VIP Goal Moved") vip_goal_moved_reference;
	s_tag_reference_legacy nicename("Assault Armed 2") assault_armed_2_reference;
	s_tag_reference_legacy nicename("Assault Armed 3") assault_armed_3_reference;
	s_tag_reference_legacy nicename("Assault Disarmed 2") assault_disarmed_2_reference;
	s_tag_reference_legacy nicename("Assault Disarmed 3") assault_disarmed_3_reference;
	s_tag_reference_legacy nicename("General Sudden Death") general_sudden_death_reference;
	s_tag_reference_legacy nicename("General Game Over") general_game_over_reference;
	s_tag_reference_legacy nicename("Invasion Boneyard Elite Defeat") invasion_boneyard_elite_defeat_reference;
	s_tag_reference_legacy nicename("Invasion Boneyard Elite Phase 1 Defeat") invasion_boneyard_elite_phase_1_defeat_reference;
	s_tag_reference_legacy nicename("Invasion Boneyard Elite Phase 1 Intro") invasion_boneyard_elite_phase_1_intro_reference;
	s_tag_reference_legacy nicename("Invasion Boneyard Elite Phase 1 Victory") invasion_boneyard_elite_phase_1_victory_reference;
	s_tag_reference_legacy nicename("Invasion Boneyard Elite Phase 2 Defeat") invasion_boneyard_elite_phase_2_defeat_reference;
	s_tag_reference_legacy nicename("Invasion Boneyard Elite Phase 2 Victory") invasion_boneyard_elite_phase_2_victory_reference;
	s_tag_reference_legacy nicename("Invasion Boneyard Elite Phase 3 Victory") invasion_boneyard_elite_phase_3_victory_reference;
	s_tag_reference_legacy nicename("Invasion Boneyard Elite Victory") invasion_boneyard_elite_victory_reference;
	s_tag_reference_legacy nicename("Invasion Boneyard Spartan Defeat") invasion_boneyard_spartan_defeat_reference;
	s_tag_reference_legacy nicename("Invasion Boneyard Spartan Phase 1 Intro") invasion_boneyard_spartan_phase_1_intro_reference;
	s_tag_reference_legacy nicename("Invasion Boneyard Spartan Phase 1 Victory") invasion_boneyard_spartan_phase_1_victory_reference;
	s_tag_reference_legacy nicename("Invasion Boneyard Spartan Phase 2 Intro") invasion_boneyard_spartan_phase_2_intro_reference;
	s_tag_reference_legacy nicename("Invasion Boneyard Spartan Phase 2 Victory") invasion_boneyard_spartan_phase_2_victory_reference;
	s_tag_reference_legacy nicename("Invasion Boneyard Spartan Phase 3 Intro") invasion_boneyard_spartan_phase_3_intro_reference;
	s_tag_reference_legacy nicename("Invasion Boneyard Spartan Phase 3 Victory") invasion_boneyard_spartan_phase_3_victory_reference;
	s_tag_reference_legacy nicename("Invasion Spire Elite Defeat") invasion_spire_elite_defeat_reference;
	s_tag_reference_legacy nicename("Invasion Spire Elite Phase 1 Defeat") invasion_spire_elite_phase_1_defeat_reference;
	s_tag_reference_legacy nicename("Invasion Spire Elite Phase 1 Intro") invasion_spire_elite_phase_1_intro_reference;
	s_tag_reference_legacy nicename("Invasion Spire Elite Phase 2 Intro") invasion_spire_elite_phase_2_intro_reference;
	s_tag_reference_legacy nicename("Invasion Spire Elite Phase 2 Victory") invasion_spire_elite_phase_2_victory_reference;
	s_tag_reference_legacy nicename("Invasion Spire Elite Phase 3 Intro") invasion_spire_elite_phase_3_intro_reference;
	s_tag_reference_legacy nicename("Invasion Spire Elite Phase 3 Victory") invasion_spire_elite_phase_3_victory_reference;
	s_tag_reference_legacy nicename("Invasion Spire Spartan Defeat") invasion_spire_spartan_defeat_reference;
	s_tag_reference_legacy nicename("Invasion Spire Spartan Phase 1 Defeat") invasion_spire_spartan_phase_1_defeat_reference;
	s_tag_reference_legacy nicename("Invasion Spire Spartan Phase 1 Extra") invasion_spire_spartan_phase_1_extra_reference;
	s_tag_reference_legacy nicename("Invasion Spire Spartan Phase 1 Intro") invasion_spire_spartan_phase_1_intro_reference;
	s_tag_reference_legacy nicename("Invasion Spire Spartan Phase 1 Victory") invasion_spire_spartan_phase_1_victory_reference;
	s_tag_reference_legacy nicename("Invasion Spire Spartan Phase 2 Defeat") invasion_spire_spartan_phase_2_defeat_reference;
	s_tag_reference_legacy nicename("Invasion Spire Spartan Phase 2 Victory") invasion_spire_spartan_phase_2_victory_reference;
	s_tag_reference_legacy nicename("Invasion Spire Spartan Phase 3 Victory") invasion_spire_spartan_phase_3_victory_reference;
	s_tag_reference_legacy nicename("Invasion Spire Spartan Victory") invasion_spire_spartan_victory_reference;
	s_tag_reference_legacy nicename("Invasion Boneyard Spartan Phase 3 Defeat") invasion_boneyard_spartan_phase_3_defeat_reference;
	s_tag_reference_legacy nicename("Invasion Spire Elite Phase 3 Defeat") invasion_spire_elite_phase_3_defeat_reference;
	s_tag_reference_legacy nicename("Invasion Elite Big Win Music") invasion_elite_big_win_music_reference;
	s_tag_reference_legacy nicename("Invasion Elite Win 1 Music") invasion_elite_win_1_music_reference;
	s_tag_reference_legacy nicename("Invasion Elite Win 2 Music") invasion_elite_win_2_music_reference;
	s_tag_reference_legacy nicename("Invasion Beginning Music") invasion_beginning_music_reference;
	s_tag_reference_legacy nicename("Invasion Spartan Big Win Music") invasion_spartan_big_win_music_reference;
	s_tag_reference_legacy nicename("Invasion Spartan Win 1 Music") invasion_spartan_win_1_music_reference;
	s_tag_reference_legacy nicename("Invasion Spartan Win 2 Music") invasion_spartan_win_2_music_reference;
	s_tag_reference_legacy nicename("Invasion Boneyard Generator Power Down") invasion_boneyard_generator_power_down_reference;
	s_tag_reference_legacy nicename("Survivial Awarded Lives") survivial_awarded_lives_reference;
	s_tag_reference_legacy nicename("General Timer Beep") general_timer_beep_reference;
	s_tag_reference_legacy nicename("Survival Alpha Point Attack") survival_alpha_point_attack_reference;
	s_tag_reference_legacy nicename("Survival Bravo Point Attack") survival_bravo_point_attack_reference;
	s_tag_reference_legacy nicename("Survival Charlie Point Attack") survival_charlie_point_attack_reference;
};

