#pragma once

struct nicename("user_interface_sounds_definition") tag_group('uise') s_user_interface_sounds_definition_definition
{
	s_tag_reference_legacy nicename("Navigation Up") navigation_up_reference;
	s_tag_reference_legacy nicename("Navigation Left") navigation_left_reference;
	s_tag_reference_legacy nicename("Navigation Right") navigation_right_reference;
	s_tag_reference_legacy nicename("Navigation Down") navigation_down_reference;
	s_tag_reference_legacy __unknown0;
	s_tag_reference_legacy __unknown1;
	s_tag_reference_legacy __unknown2;
	s_tag_reference_legacy __unknown3;
	s_tag_reference_legacy __unknown4;
	s_tag_reference_legacy __unknown5;
	s_tag_reference_legacy __unknown6;
	s_tag_reference_legacy __unknown7;
	s_tag_reference_legacy nicename("A Button") a_button_reference;
	s_tag_reference_legacy nicename("B Button") b_button_reference;
	s_tag_reference_legacy nicename("X Button") x_button_reference;
	s_tag_reference_legacy nicename("Y Button") y_button_reference;
	s_tag_reference_legacy nicename("Left Trigger") left_trigger_reference;
	s_tag_reference_legacy nicename("Right Trigger") right_trigger_reference;
	s_tag_reference_legacy __unknown8;
	s_tag_reference_legacy __unknown9;
	s_tag_reference_legacy __unknown10;
	s_tag_reference_legacy __unknown11;
	s_tag_reference_legacy nicename("Start Button") start_button_reference;
	s_tag_reference_legacy nicename("Back Button") back_button_reference;
	s_tag_reference_legacy __unknown12;
	s_tag_reference_legacy __unknown13;
	s_tag_reference_legacy nicename("Left Bumper") left_bumper_reference;
	s_tag_reference_legacy nicename("Right Bumper") right_bumper_reference;
	s_tag_reference_legacy __unknown14;
	s_tag_reference_legacy __unknown15;
	s_tag_reference_legacy __unknown16;
	s_tag_reference_legacy __unknown17;
	s_tag_reference_legacy __unknown18;
	s_tag_reference_legacy __unknown19;
	s_tag_reference_legacy __unknown20;
	s_tag_reference_legacy __unknown21;
	s_tag_reference_legacy __unknown22;
	s_tag_reference_legacy __unknown23;
	s_tag_reference_legacy __unknown24;
	s_tag_reference_legacy __unknown25;
	s_tag_reference_legacy __unknown26;
	s_tag_reference_legacy __unknown27;
	s_tag_reference_legacy __unknown28;
	s_tag_reference_legacy __unknown29;
	s_tag_reference_legacy __unknown30;
	s_tag_reference_legacy __unknown31;
	s_tag_reference_legacy __unknown32;
	s_tag_reference_legacy __unknown33;
	s_tag_reference_legacy __unknown34;
	s_tag_reference_legacy __unknown35;
	s_tag_reference_legacy __unknown36;
	s_tag_reference_legacy __unknown37;
	s_tag_reference_legacy __unknown38;
	s_tag_reference_legacy __unknown39;
	s_tag_reference_legacy __unknown40;
	s_tag_reference_legacy __unknown41;
	s_tag_reference_legacy __unknown42;
	s_tag_reference_legacy __unknown43;
	s_tag_reference_legacy __unknown44;
	s_tag_reference_legacy __unknown45;
	s_tag_reference_legacy __unknown46;
	s_tag_reference_legacy __unknown47;
	s_tag_reference_legacy __unknown48;
	s_tag_reference_legacy __unknown49;
	s_tag_reference_legacy nicename("Error") error_reference;
	s_tag_reference_legacy nicename("Lobby Initialize") lobby_initialize_reference;
	s_tag_reference_legacy nicename("Lobby Exit") lobby_exit_reference;
	s_tag_reference_legacy nicename("Timer Sound") timer_sound_reference;
	s_tag_reference_legacy nicename("Timer Sound Zero") timer_sound_zero_reference;
	s_tag_reference_legacy nicename("Alt Timer Sound") alt_timer_sound_reference;
	s_tag_reference_legacy nicename("Secondary Alt Timer Sound") secondary_alt_timer_sound_reference;
	s_tag_reference_legacy nicename("Matchmaking Advance Sound") matchmaking_advance_sound_reference;
	s_tag_reference_legacy nicename("Exit Experience Game Completion") exit_experience_game_completion_reference;
	s_tag_reference_legacy nicename("Exit Experience Time Spent Credits") exit_experience_time_spent_credits_reference;
	s_tag_reference_legacy nicename("Exit Experience Winning Bonus") exit_experience_winning_bonus_reference;
	s_tag_reference_legacy nicename("Exit Experience Hopper Bonus") exit_experience_hopper_bonus_reference;
	s_tag_reference_legacy nicename("Exit Experience Invasion Bonus") exit_experience_invasion_bonus_reference;
	s_tag_reference_legacy nicename("Exit Experience Commendation Bonus") exit_experience_commendation_bonus_reference;
	s_tag_reference_legacy nicename("Exit Experience Challenges Bonus") exit_experience_challenges_bonus_reference;
	s_tag_reference_legacy nicename("Exit Experience Achievement Bonus") exit_experience_achievement_bonus_reference;
	s_tag_reference_legacy nicename("Exit Experience Slot Machine") exit_experience_slot_machine_reference;
	s_tag_reference_legacy nicename("Exit Experience Heat Bonus") exit_experience_heat_bonus_reference;
	s_tag_reference_legacy nicename("Exit Experience Totals") exit_experience_totals_reference;
	s_tag_reference_legacy nicename("Exit Experience Rank Up") exit_experience_rank_up_reference;
	s_tag_reference_legacy nicename("Exit Experience Subrank Up") exit_experience_subrank_up_reference;
	s_tag_reference_legacy nicename("Unknown ") unknown__reference;
	s_tag_reference_legacy nicename("Exit Experience Credit Award Loop") exit_experience_credit_award_loop_reference;
};

