#pragma once

struct nicename("Chud Globals Definition") group('chgd') s_chud_globals_definition_definition
{
	struct nicename("HUD Globals") s_hud_global_block_definition;
	struct nicename("Shaders") s_shader_block_definition;
	struct s_unknown_block_definition;
	struct nicename("Player Training Data") s_player_training_datum_block_definition;
	struct nicename("State Triggers") s_state_trigger_block_definition;

	s_tag_block_definition<s_hud_global_block_definition> nicename("HUD Globals") hud_globals_block; 
	s_tag_block_definition<s_shader_block_definition> nicename("Shaders") shaders_block; 
	s_tag_block_definition<s_unknown_block_definition> __unknown_block; 
	s_tag_block_definition<s_player_training_datum_block_definition> nicename("Player Training Data") player_training_data_block; 
	TagReference nicename("Common Emblems") common_emblems_reference; 
	signed char __unknown2; 
	signed char __unknown3; 
	signed char __unknown4; 
	signed char __unknown5; 
	float nicename("Campaign Medal Scale") campaign_medal_scale; 
	float nicename("Campaign Medal Spacing") campaign_medal_spacing; 
	float nicename("Campaign Medal Offset X") campaign_medal_offset_x; 
	float nicename("Campaign Medal Offset Y") campaign_medal_offset_y; 
	float nicename("Metagame Scoreboard Top Y") metagame_scoreboard_top_y; 
	float nicename("Metagame Scoreboard Spacing") metagame_scoreboard_spacing; 
	TagReference __unknown6_reference; 
	Unknown32 __unknown7; 
	signed char __unknown8; 
	signed char __unknown9; 
	signed char __unknown10; 
	signed char __unknown11; 
	float nicename("Medium Sensor Blip Scale") medium_sensor_blip_scale; 
	float nicename("Small Sensor Blip Scale") small_sensor_blip_scale; 
	float nicename("Large Sensor Blip Scale") large_sensor_blip_scale; 
	float nicename("Vehicle Sensor Range") vehicle_sensor_range; 
	float nicename("Sensor Angle") sensor_angle; 
	float __unknown12; 
	float __unknown13; 
	float __unknown14; 
	float __unknown15; 
	float __unknown16; 
	float __unknown17; 
	DataReference __unknown18_data_reference; 
	DataReference __unknown19_data_reference; 
	float __unknown20; 
	float __unknown21; 
	float __unknown22; 
	float __unknown23; 
	TagReference nicename("Motion Sensor Triangulation Field") motion_sensor_triangulation_field_reference; 
	TagReference nicename("Motion Sensor Blip") motion_sensor_blip_reference; 
	signed char __unknown24; 
	signed char __unknown25; 
	signed char __unknown26; 
	signed char __unknown27; 
	float __unknown28; 
	TagReference __unknown29_reference; 
	Unknown32 __unknown30; 
	float __unknown31; 
	float __unknown32; 
	float __unknown33; 
	Unknown32 __unknown34; 
	float __unknown35; 
	Unknown32 __unknown36; 
	float __unknown37; 
	float __unknown38; 
	float __unknown39; 
	float __unknown40; 
	Unknown32 __unknown41; 
	float __unknown42; 
	float __unknown43; 
	float __unknown44; 
	float __unknown45; 
	float __unknown46; 
	Unknown32 __unknown47; 
	Unknown32 __unknown48; 
	float __unknown49; 
	Unknown32 __unknown50; 
	float __unknown51; 
	float __unknown52; 
	Unknown32 __unknown53; 
	float __unknown54; 
	Unknown32 __unknown55; 
	float __unknown56; 
	float __unknown57; 
	float __unknown58; 
	float nicename("Alpha?") alpha; 
	float nicename("R?") r; 
	float nicename("G?") g; 
	float nicename("B?") b; 
	float __unknown59; 
	Unknown32 __unknown60; 
	float __unknown61; 
	float __unknown62; 
	float __unknown63; 
	Unknown32 __unknown64; 
	Unknown32 __unknown65; 
	float __unknown66; 
	Unknown32 __unknown67; 
	float __unknown68; 
	float __unknown69; 
	float __unknown70; 
	float __unknown71; 
	float __unknown72; 
	float __unknown73; 
	Unknown32 __unknown74; 
	Unknown32 __unknown75; 
	Unknown32 __unknown76; 
	Unknown32 __unknown77; 
	Unknown32 __unknown78; 
	Unknown32 __unknown79; 
	Unknown32 __unknown80; 
	Unknown32 __unknown81; 
	TagReference __unknown_waypoint_bitmap_reference; 
	signed char nicename("Sequence Index") sequence_index; 
	signed char nicename("Sprite Index") sprite_index; 
	signed char __unknown82; 
	signed char __unknown83; 
	signed char __unknown84; 
	signed char __unknown85; 
	signed char __unknown86; 
	signed char __unknown87; 
	TagReference __unknown_waypoint_bitmap2_reference; 
	signed char nicename("Sequence Index") sequence_index2; 
	signed char nicename("Sprite Index") sprite_index2; 
	signed char __unknown88; 
	signed char __unknown89; 
	signed char __unknown90; 
	signed char __unknown91; 
	signed char __unknown92; 
	signed char __unknown93; 
	TagReference __unknown_waypoint_bitmap3_reference; 
	signed char nicename("Sequence Index") sequence_index3; 
	signed char nicename("Sprite Index") sprite_index3; 
	signed char __unknown94; 
	signed char __unknown95; 
	signed char __unknown96; 
	signed char __unknown97; 
	signed char __unknown98; 
	signed char __unknown99; 
	TagReference __unknown_waypoint_bitmap4_reference; 
	signed char nicename("Sequence Index") sequence_index4; 
	signed char nicename("Sprite Index") sprite_index4; 
	signed char __unknown100; 
	signed char __unknown101; 
	signed char __unknown102; 
	signed char __unknown103; 
	signed char __unknown104; 
	signed char __unknown105; 
	TagReference __unknown_waypoint_bitmap5_reference; 
	signed char nicename("Sequence Index") sequence_index5; 
	signed char nicename("Sprite Index") sprite_index5; 
	signed char __unknown106; 
	signed char __unknown107; 
	signed char __unknown108; 
	signed char __unknown109; 
	signed char __unknown110; 
	signed char __unknown111; 
	TagReference __unknown_waypoint_bitmap6_reference; 
	signed char nicename("Sequence Index") sequence_index6; 
	signed char nicename("Sprite Index") sprite_index6; 
	signed char __unknown112; 
	signed char __unknown113; 
	signed char __unknown114; 
	signed char __unknown115; 
	signed char __unknown116; 
	signed char __unknown117; 
	TagReference __unknown_waypoint_bitmap7_reference; 
	signed char nicename("Sequence Index") sequence_index7; 
	signed char nicename("Sprite Index") sprite_index7; 
	signed char __unknown118; 
	signed char __unknown119; 
	signed char __unknown120; 
	signed char __unknown121; 
	signed char __unknown122; 
	signed char __unknown123; 
	TagReference __unknown_waypoint_bitmap8_reference; 
	signed char nicename("Sequence Index") sequence_index8; 
	signed char nicename("Sprite Index") sprite_index8; 
	signed char __unknown124; 
	signed char __unknown125; 
	signed char __unknown126; 
	signed char __unknown127; 
	signed char __unknown128; 
	signed char __unknown129; 
	TagReference __unknown_waypoint_bitmap9_reference; 
	signed char nicename("Sequence Index") sequence_index9; 
	signed char nicename("Sprite Index") sprite_index9; 
	signed char __unknown130; 
	signed char __unknown131; 
	signed char __unknown132; 
	signed char __unknown133; 
	signed char __unknown134; 
	signed char __unknown135; 
	TagReference __unknown_waypoint_bitmap10_reference; 
	signed char nicename("Sequence Index") sequence_index10; 
	signed char nicename("Sprite Index") sprite_index10; 
	signed char __unknown136; 
	signed char __unknown137; 
	signed char __unknown138; 
	signed char __unknown139; 
	signed char __unknown140; 
	signed char __unknown141; 
	TagReference __unknown_waypoint_bitmap11_reference; 
	signed char nicename("Sequence Index") sequence_index11; 
	signed char nicename("Sprite Index") sprite_index11; 
	signed char __unknown142; 
	signed char __unknown143; 
	signed char __unknown144; 
	signed char __unknown145; 
	signed char __unknown146; 
	signed char __unknown147; 
	TagReference __unknown_waypoint_bitmap12_reference; 
	signed char nicename("Sequence Index") sequence_index12; 
	signed char nicename("Sprite Index") sprite_index12; 
	signed char __unknown148; 
	signed char __unknown149; 
	signed char __unknown150; 
	signed char __unknown151; 
	signed char __unknown152; 
	signed char __unknown153; 
	TagReference __unknown_waypoint_bitmap13_reference; 
	signed char nicename("Sequence Index") sequence_index13; 
	signed char nicename("Sprite Index") sprite_index13; 
	signed char __unknown154; 
	signed char __unknown155; 
	signed char __unknown156; 
	signed char __unknown157; 
	signed char __unknown158; 
	signed char __unknown159; 
	TagReference __unknown_waypoint_bitmap14_reference; 
	signed char nicename("Sequence Index") sequence_index14; 
	signed char nicename("Sprite Index") sprite_index14; 
	signed char __unknown160; 
	signed char __unknown161; 
	signed char __unknown162; 
	signed char __unknown163; 
	signed char __unknown164; 
	signed char __unknown165; 
	TagReference __unknown_waypoint_bitmap15_reference; 
	signed char nicename("Sequence Index") sequence_index15; 
	signed char nicename("Sprite Index") sprite_index15; 
	signed char __unknown166; 
	signed char __unknown167; 
	signed char __unknown168; 
	signed char __unknown169; 
	signed char __unknown170; 
	signed char __unknown171; 
	TagReference __unknown_waypoint_bitmap16_reference; 
	signed char nicename("Sequence Index") sequence_index16; 
	signed char nicename("Sprite Index") sprite_index16; 
	signed char __unknown172; 
	signed char __unknown173; 
	signed char __unknown174; 
	signed char __unknown175; 
	signed char __unknown176; 
	signed char __unknown177; 
	TagReference __unknown_waypoint_bitmap17_reference; 
	signed char nicename("Sequence Index") sequence_index17; 
	signed char nicename("Sprite Index") sprite_index17; 
	signed char __unknown178; 
	signed char __unknown179; 
	signed char __unknown180; 
	signed char __unknown181; 
	signed char __unknown182; 
	signed char __unknown183; 
	TagReference __unknown_waypoint_bitmap18_reference; 
	signed char nicename("Sequence Index") sequence_index18; 
	signed char nicename("Sprite Index") sprite_index18; 
	signed char __unknown184; 
	signed char __unknown185; 
	signed char __unknown186; 
	signed char __unknown187; 
	signed char __unknown188; 
	signed char __unknown189; 
	TagReference __unknown_waypoint_bitmap19_reference; 
	signed char nicename("Sequence Index") sequence_index19; 
	signed char nicename("Sprite Index") sprite_index19; 
	signed char __unknown190; 
	signed char __unknown191; 
	signed char __unknown192; 
	signed char __unknown193; 
	signed char __unknown194; 
	signed char __unknown195; 
	TagReference __unknown_waypoint_bitmap20_reference; 
	signed char nicename("Sequence Index") sequence_index20; 
	signed char nicename("Sprite Index") sprite_index20; 
	signed char __unknown196; 
	signed char __unknown197; 
	signed char __unknown198; 
	signed char __unknown199; 
	signed char __unknown200; 
	signed char __unknown201; 
	TagReference __unknown_waypoint_bitmap21_reference; 
	signed char nicename("Sequence Index") sequence_index21; 
	signed char nicename("Sprite Index") sprite_index21; 
	signed char __unknown202; 
	signed char __unknown203; 
	signed char __unknown204; 
	signed char __unknown205; 
	signed char __unknown206; 
	signed char __unknown207; 
	TagReference __unknown_waypoint_bitmap22_reference; 
	signed char nicename("Sequence Index") sequence_index22; 
	signed char nicename("Sprite Index") sprite_index22; 
	signed char __unknown208; 
	signed char __unknown209; 
	signed char __unknown210; 
	signed char __unknown211; 
	signed char __unknown212; 
	signed char __unknown213; 
	TagReference __unknown_waypoint_bitmap23_reference; 
	signed char nicename("Sequence Index") sequence_index23; 
	signed char nicename("Sprite Index") sprite_index23; 
	signed char __unknown214; 
	signed char __unknown215; 
	signed char __unknown216; 
	signed char __unknown217; 
	signed char __unknown218; 
	signed char __unknown219; 
	TagReference __unknown_waypoint_bitmap24_reference; 
	signed char nicename("Sequence Index") sequence_index24; 
	signed char nicename("Sprite Index") sprite_index24; 
	signed char __unknown220; 
	signed char __unknown221; 
	signed char __unknown222; 
	signed char __unknown223; 
	signed char __unknown224; 
	signed char __unknown225; 
	TagReference __unknown_waypoint_bitmap25_reference; 
	signed char nicename("Sequence Index") sequence_index25; 
	signed char nicename("Sprite Index") sprite_index25; 
	signed char __unknown226; 
	signed char __unknown227; 
	signed char __unknown228; 
	signed char __unknown229; 
	signed char __unknown230; 
	signed char __unknown231; 
	TagReference __unknown_waypoint_bitmap26_reference; 
	signed char nicename("Sequence Index") sequence_index26; 
	signed char nicename("Sprite Index") sprite_index26; 
	signed char __unknown232; 
	signed char __unknown233; 
	signed char __unknown234; 
	signed char __unknown235; 
	signed char __unknown236; 
	signed char __unknown237; 
	// comment
	s_tag_block_definition<s_state_trigger_block_definition> nicename("State Triggers") state_triggers_block; 

	struct nicename("hud_global") s_hud_global_block_definition
	{
		struct nicename("HUD Attributes") s_hud_attribute_block_definition;
		struct nicename("HUD Sounds") s_hud_sound_block_definition;
		struct nicename("Waypoint Blips") s_waypoint_blip_block_definition;

		signed int nicename("Biped") biped; 
		// comment
		float nicename("__0 Alpha") __0_alpha; 
		float nicename("__0 [HUD Disabled] r") __0_hud_disabled_r; 
		float nicename("__0 [HUD Disabled] g") __0_hud_disabled_g; 
		float nicename("__0 [HUD Disabled] b") __0_hud_disabled_b; 
		float nicename("__1 Alpha") __1_alpha; 
		float nicename("__1 [HUD Primary] r") __1_hud_primary_r; 
		float nicename("__1 [HUD Primary] g") __1_hud_primary_g; 
		float nicename("__1 [HUD Primary] b") __1_hud_primary_b; 
		float nicename("__2 Alpha") __2_alpha; 
		float nicename("__2 [HUD Foreground] r") __2_hud_foreground_r; 
		float nicename("__2 [HUD Foreground] g") __2_hud_foreground_g; 
		float nicename("__2 [HUD Foreground] b") __2_hud_foreground_b; 
		float nicename("__3 Alpha") __3_alpha; 
		float nicename("__3 [HUD Warning] r") __3_hud_warning_r; 
		float nicename("__3 [HUD Warning] g") __3_hud_warning_g; 
		float nicename("__3 [HUD Warning] b") __3_hud_warning_b; 
		float nicename("__4 Alpha") __4_alpha; 
		float nicename("__4 [Neutral Reticule] r") __4_neutral_reticule_r; 
		float nicename("__4 [Neutral Reticule] g") __4_neutral_reticule_g; 
		float nicename("__4 [Neutral Reticule] b") __4_neutral_reticule_b; 
		float nicename("__5 Alpha") __5_alpha; 
		float nicename("__5 [Hostile Reticule] r") __5_hostile_reticule_r; 
		float nicename("__5 [Hostile Reticule] g") __5_hostile_reticule_g; 
		float nicename("__5 [Hostile Reticule] b") __5_hostile_reticule_b; 
		float nicename("__6 Alpha") __6_alpha; 
		float nicename("__6 [Friendly Reticule] r") __6_friendly_reticule_r; 
		float nicename("__6 [Friendly Reticule] g") __6_friendly_reticule_g; 
		float nicename("__6 [Friendly Reticule] b") __6_friendly_reticule_b; 
		float nicename("__7 Alpha") __7_alpha; 
		float nicename("__7 r") __7_r; 
		float nicename("__7 g") __7_g; 
		float nicename("__7 b") __7_b; 
		float nicename("__8 Alpha") __8_alpha; 
		float nicename("__8 r") __8_r; 
		float nicename("__8 g") __8_g; 
		float nicename("__8 b") __8_b; 
		float nicename("__9 Alpha") __9_alpha; 
		float nicename("__9 r") __9_r; 
		float nicename("__9 g") __9_g; 
		float nicename("__9 b") __9_b; 
		float nicename("__10 Alpha") __10_alpha; 
		float nicename("__10 r") __10_r; 
		float nicename("__10 g") __10_g; 
		float nicename("__10 b") __10_b; 
		float nicename("__11 Alpha") __11_alpha; 
		float nicename("__11 r") __11_r; 
		float nicename("__11 g") __11_g; 
		float nicename("__11 b") __11_b; 
		float nicename("__12 Alpha") __12_alpha; 
		float nicename("__12 r") __12_r; 
		float nicename("__12 g") __12_g; 
		float nicename("__12 b") __12_b; 
		float nicename("__13 Alpha") __13_alpha; 
		float nicename("__13 r") __13_r; 
		float nicename("__13 g") __13_g; 
		float nicename("__13 b") __13_b; 
		float nicename("__14 Alpha") __14_alpha; 
		float nicename("__14 r") __14_r; 
		float nicename("__14 g") __14_g; 
		float nicename("__14 b") __14_b; 
		float nicename("__15 Alpha") __15_alpha; 
		float nicename("__15 r") __15_r; 
		float nicename("__15 g") __15_g; 
		float nicename("__15 b") __15_b; 
		float nicename("__16 Alpha") __16_alpha; 
		float nicename("__16 r") __16_r; 
		float nicename("__16 g") __16_g; 
		float nicename("__16 b") __16_b; 
		float nicename("__17 Alpha") __17_alpha; 
		float nicename("__17 r") __17_r; 
		float nicename("__17 g") __17_g; 
		float nicename("__17 b") __17_b; 
		float nicename("__18 Alpha") __18_alpha; 
		float nicename("__18 r") __18_r; 
		float nicename("__18 g") __18_g; 
		float nicename("__18 b") __18_b; 
		float nicename("__19 Alpha") __19_alpha; 
		float nicename("__19 r") __19_r; 
		float nicename("__19 g") __19_g; 
		float nicename("__19 b") __19_b; 
		float nicename("__20 Alpha") __20_alpha; 
		float nicename("__20 r") __20_r; 
		float nicename("__20 g") __20_g; 
		float nicename("__20 b") __20_b; 
		float nicename("__21 Alpha") __21_alpha; 
		float nicename("__21 r") __21_r; 
		float nicename("__21 g") __21_g; 
		float nicename("__21 b") __21_b; 
		float nicename("__22 Alpha") __22_alpha; 
		float nicename("__22 r") __22_r; 
		float nicename("__22 g") __22_g; 
		float nicename("__22 b") __22_b; 
		float nicename("__23 Alpha") __23_alpha; 
		float nicename("__23 r") __23_r; 
		float nicename("__23 g") __23_g; 
		float nicename("__23 b") __23_b; 
		float nicename("__24 Alpha") __24_alpha; 
		float nicename("__24 r") __24_r; 
		float nicename("__24 g") __24_g; 
		float nicename("__24 b") __24_b; 
		float nicename("__25 Alpha") __25_alpha; 
		float nicename("__25 r") __25_r; 
		float nicename("__25 g") __25_g; 
		float nicename("__25 b") __25_b; 
		float nicename("__26 Alpha") __26_alpha; 
		float nicename("__26 r") __26_r; 
		float nicename("__26 g") __26_g; 
		float nicename("__26 b") __26_b; 
		float nicename("__27 Alpha") __27_alpha; 
		float nicename("__27 r") __27_r; 
		float nicename("__27 g") __27_g; 
		float nicename("__27 b") __27_b; 
		float nicename("__28 Alpha") __28_alpha; 
		float nicename("__28 r") __28_r; 
		float nicename("__28 g") __28_g; 
		float nicename("__28 b") __28_b; 
		float nicename("__29 Alpha") __29_alpha; 
		float nicename("__29 r") __29_r; 
		float nicename("__29 g") __29_g; 
		float nicename("__29 b") __29_b; 
		float nicename("__30 Alpha") __30_alpha; 
		float nicename("__30 r") __30_r; 
		float nicename("__30 g") __30_g; 
		float nicename("__30 b") __30_b; 
		float nicename("__31 Alpha") __31_alpha; 
		float nicename("__31 r") __31_r; 
		float nicename("__31 g") __31_g; 
		float nicename("__31 b") __31_b; 
		DataReference nicename("__32") __32_data_reference; 
		DataReference nicename("__33 [Neutral Blip]") __33_neutral_blip_data_reference; 
		DataReference nicename("__34 [Hostile Blip]") __34_hostile_blip_data_reference; 
		DataReference nicename("__35 [Friendly Blip]") __35_friendly_blip_data_reference; 
		DataReference nicename("__36") __36_data_reference; 
		DataReference nicename("__37") __37_data_reference; 
		DataReference nicename("__38") __38_data_reference; 
		DataReference nicename("__39") __39_data_reference; 
		DataReference nicename("__40") __40_data_reference; 
		DataReference nicename("__41") __41_data_reference; 
		float nicename("Blip Above Threshold max") blip_above_threshold_max; 
		float nicename("Blip Above Threshold min") blip_above_threshold_min; 
		float nicename("Blip Below Threshold min") blip_below_threshold_min; 
		float nicename("Blip Below Threshold max") blip_below_threshold_max; 
		s_tag_block_definition<s_hud_attribute_block_definition> nicename("HUD Attributes") hud_attributes_block; 
		s_tag_block_definition<s_hud_sound_block_definition> nicename("HUD Sounds") hud_sounds_block; 
		Unknown32 __unknown; 
		TagReference __unknown2_reference; 
		TagReference nicename("Frag Grenade Swap Sound") frag_grenade_swap_sound_reference; 
		TagReference nicename("Plasma Grenade Swap Sound") plasma_grenade_swap_sound_reference; 
		signed char __unknown3; 
		signed char __unknown4; 
		signed char __unknown5; 
		signed char __unknown6; 
		TagReference nicename("Damage Microtexture") damage_microtexture_reference; 
		float nicename("Microtexture Tile Scale") microtexture_tile_scale; 
		float nicename("Microtexture Screen Fraction") microtexture_screen_fraction; 
		float nicename("Microtexture Inner Intensity") microtexture_inner_intensity; 
		float nicename("Microtexture Center Screen Fraction") microtexture_center_screen_fraction; 
		float nicename("Microtexture Outer Intensity") microtexture_outer_intensity; 
		TagReference __unknown7_reference; 
		TagReference nicename("Directional Arrow") directional_arrow_reference; 
		TagReference nicename("Directional Fast Forward Arrow") directional_fast_forward_arrow_reference; 
		TagReference __unknown8_reference; 
		TagReference __unknown9_reference; 
		float __unknown10; 
		float __unknown11; 
		float __unknown12; 
		float __unknown13; 
		float __unknown14; 
		float __unknown15; 
		float __unknown16; 
		DataReference __unknown17_data_reference; 
		TagReference nicename("Waypoints") waypoints_reference; 
		TagReference nicename("Scoreboard HUD") scoreboard_hud_reference; 
		TagReference nicename("Uber Scoreboard HUD") uber_scoreboard_hud_reference; 
		TagReference nicename("Metagame Scoreboard HUD") metagame_scoreboard_hud_reference; 
		TagReference nicename("Survival Scoreboard HUD") survival_scoreboard_hud_reference; 
		TagReference nicename("Theater HUD") theater_hud_reference; 
		TagReference nicename("Forge HUD") forge_hud_reference; 
		TagReference nicename("HUD Strings") hud_strings_reference; 
		TagReference nicename("Medals") medals_reference; 
		TagReference nicename("Medal HUD Animation") medal_hud_animation_reference; 
		TagReference nicename("Cortana Channel") cortana_channel_reference; 
		TagReference __unknown18_reference; 
		TagReference __unknown19_reference; 
		TagReference nicename("Jammer Response") jammer_response_reference; 
		TagReference nicename("Jammer Shield Hit") jammer_shield_hit_reference; 
		float nicename("Grenade Scematics Spacing") grenade_scematics_spacing; 
		float nicename("Equipment Scematic Offset Y") equipment_scematic_offset_y; 
		float nicename("Dual Equipment Scematic Offset Y") dual_equipment_scematic_offset_y; 
		float __unknown20; 
		float __unknown21; 
		float nicename("Scoreboard Leader Offset Y") scoreboard_leader_offset_y; 
		float __unknown22; 
		float nicename("Waypoint Scale") waypoint_scale; 
		// comment
		float __unknown23; 
		float __unknown24; 
		float nicename("Color a") color_a; 
		float nicename("Color r") color_r; 
		float nicename("Color g") color_g; 
		float nicename("Color b") color_b; 
		float nicename("Minor Threshold") minor_threshold; 
		float nicename("Major Threshold") major_threshold; 
		float nicename("Critical Threshold") critical_threshold; 
		DataReference nicename("Function") function_data_reference; 
		DataReference nicename("Function") function2_data_reference; 
		// comment
		float __unknown25; 
		float __unknown26; 
		float nicename("Color a") color_a2; 
		float nicename("Color r") color_r2; 
		float nicename("Color g") color_g2; 
		float nicename("Color b") color_b2; 
		float nicename("Minor Threshold") minor_threshold2; 
		float nicename("Major Threshold") major_threshold2; 
		float nicename("Critical Threshold") critical_threshold2; 
		DataReference nicename("Function") function3_data_reference; 
		DataReference nicename("Function") function4_data_reference; 
		s_tag_block_definition<s_waypoint_blip_block_definition> nicename("Waypoint Blips") waypoint_blips_block; 

		struct nicename("hud_attribute") s_hud_attribute_block_definition
		{
			unsigned char nicename("Resolution Flags") resolution_flags; 
			signed char __unknown; 
			signed char __unknown2; 
			signed char __unknown3; 
			float __unknown4; 
			float __unknown5; 
			float __unknown6; 
			float __unknown7; 
			float __unknown8; 
			float __unknown9; 
			float __unknown10; 
			float __unknown11; 
			float __unknown12; 
			float __unknown13; 
			float __unknown14; 
			float __unknown15; 
			float __unknown16; 
			float __unknown17; 
			float __unknown18; 
			float __unknown19; 
			float __unknown20; 
			float __unknown21; 
			// comment
			float nicename("Horizontal Roll") horizontal_roll; 
			float nicename("Vertical Bow") vertical_bow; 
			float nicename("Inverse Horizontal Roll") inverse_horizontal_roll; 
			float nicename("Inverse Vertical Bow") inverse_vertical_bow; 
			float nicename("Horizontal Roll 2") horizontal_roll_2; 
			float nicename("Vertical Bow 2") vertical_bow_2; 
			float nicename("Horizontal Twist") horizontal_twist; 
			float nicename("Vertical Twist") vertical_twist; 
			float nicename("Horizontal Twist 2") horizontal_twist_2; 
			float nicename("Vertical Twist 2") vertical_twist_2; 
			float nicename("Vertical Scale") vertical_scale; 
			float nicename("Vertical Twist 3") vertical_twist_3; 
			float nicename("Horizontal Skew") horizontal_skew; 
			float nicename("Vertical Flip") vertical_flip; 
			float nicename("Inverse Horizontal Skew") inverse_horizontal_skew; 
			float nicename("Vertical Flip 2") vertical_flip_2; 
			float nicename("HUD Offset X") hud_offset_x; 
			float nicename("HUD Offset Y") hud_offset_y; 
			// comment
			unsigned int nicename("Resolution Width") resolution_width; 
			unsigned int nicename("Resolution Height") resolution_height; 
			float nicename("Motion Sensor Offset X") motion_sensor_offset_x; 
			float nicename("Motion Sensor Offset Y") motion_sensor_offset_y; 
			float __unknown22; 
			float nicename("Motion Sensor Radius") motion_sensor_radius; 
			float nicename("Motion Sensor Scale") motion_sensor_scale; 
			Unknown32 __unknown23; 
			Unknown32 __unknown24; 
			Unknown32 __unknown25; 
			Unknown32 __unknown26; 
			Unknown32 __unknown27; 
			Unknown32 __unknown28; 
			Unknown32 __unknown29; 
			Unknown32 __unknown30; 
			float nicename("Horizontal Scale") horizontal_scale; 
			float nicename("Vertical Scale") vertical_scale2; 
			float nicename("Horizontal Stretch") horizontal_stretch; 
			float nicename("Vertical Stretch") vertical_stretch; 
			float nicename("Notification Offset X") notification_offset_x; 
			float nicename("Notification Offset Y") notification_offset_y; 
			float nicename("State Left/Right Offset Y") state_left_right_offset_y; 
			float nicename("State Center Offset Y") state_center_offset_y; 
			float __unknown31; 
			float __unknown32; 
			float __unknown33; 
			float nicename("State Scale") state_scale; 
			float nicename("Notification Scale") notification_scale; 
			float nicename("Notification Line Spacing") notification_line_spacing; 
			signed short __unknown34; 
			signed short __unknown35; 
		};

		struct nicename("hud_sound") s_hud_sound_block_definition
		{
			TagReference nicename("Sound") sound_reference; 
			signed int nicename("Latched To") latched_to; 
			float nicename("Scale") scale; 
		};

		struct nicename("waypoint_blip") s_waypoint_blip_block_definition
		{
			string_id nicename("Title") title; 
			string_id nicename("Description") description; 
			signed char nicename("Icon") icon; 
			signed char __unknown; 
			signed short __unknown2; 
			float nicename("Primary Alpha") primary_alpha; 
			float nicename("Primary Color r") primary_color_r; 
			float nicename("Primary Color g") primary_color_g; 
			float nicename("Primary Color b") primary_color_b; 
			float nicename("Secondary Alpha") secondary_alpha; 
			float nicename("Secondary Color r") secondary_color_r; 
			float nicename("Secondary Color g") secondary_color_g; 
			float nicename("Secondary Color b") secondary_color_b; 
		};
	};

	struct nicename("shader") s_shader_block_definition
	{
		TagReference nicename("Vertex Shader") vertex_shader_reference; 
		TagReference nicename("Pixel Shader") pixel_shader_reference; 
	};

	struct s_unknown_block_definition
	{
		float __unknown; 
		float __unknown2; 
		float __unknown3; 
		float __unknown4; 
		float __unknown5; 
		float __unknown6; 
		float __unknown7; 
		float __unknown8; 
		float __unknown9; 
		float __unknown10; 
		float __unknown11; 
		float __unknown12; 
		float __unknown13; 
		float __unknown14; 
		float __unknown15; 
		float __unknown16; 
	};

	struct nicename("player_training_datum") s_player_training_datum_block_definition
	{
		string_id nicename("Display String") display_string; 
		signed short nicename("Max Display Time") max_display_time; 
		signed short nicename("Display Count") display_count; 
		signed short nicename("Disappear Delay") disappear_delay; 
		signed short nicename("Redisplay Delay") redisplay_delay; 
		float nicename("Display Delay") display_delay; 
		unsigned short nicename("Flags") flags; 
		signed short __unknown; 
	};

	struct nicename("state_trigger") s_state_trigger_block_definition
	{
		signed int nicename("Trigger Index") trigger_index; 
		char nicename("Type") type[256];
	};
};
