#pragma once

#define INT32 int
#define UINT32 unsigned int
#define INT16 short
#define UINT16 unsigned short

/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'haloreach.dll'
*/

/* 387 */
enum e_map_type : __int16
{
    _map_type_singleplayer = 0x0,
    _map_type_multiplayer = 0x1,
    _map_type_mainmenu = 0x2,
    k_number_of_map_types = 0x3,
};

/* 386 */
#pragma pack(push, 4)
struct s_scenario_definition
{
    static constexpr TagGroupName kTagGroupName = TagGroupName::Scenario;

    e_map_type map_type;
    UINT16 flags;
    UINT32 __unknown4;
    UINT32 campaign_id;
    UINT32 map_id;
    StringID scenario_name;
    INT16 campaign_level_index;
    INT16 __unknown16;
    INT32 __unknown18;
    float local_north;
    float __unknown20;
    float __unknown24;
    UINT32 __unknown28;
    UINT32 __unknown2C;
    float __unknown30;
    float sandbox_budget;
    StringID default_vehicle_filter;
    TagReference performance_throttle_profile_reference;
    TagBlock structure_sbsps_block;
    TagBlock structure_design_block;
    TagReference __unknown64_reference;
    TagReference __unknown74_reference;
    TagBlock sky_references_block;
    TagBlock bsp_groups_block;
    TagBlock scenario_bsp_audibility_block;
    TagBlock scenario_zoneset_groups_block;
    UINT32 __unknownB4;
    UINT32 __unknownB8;
    UINT32 __unknownBC;
    UINT32 __unknownC0;
    UINT32 __unknownC4;
    UINT32 __unknownC8;
    UINT32 __unknownCC;
    UINT32 __unknownD0;
    UINT32 __unknownD4;
    UINT32 __unknownD8;
    UINT32 __unknownDC;
    UINT32 __unknownE0;
    DataReference editor_scenario_data_data_reference;
    UINT32 __unknownF8;
    UINT32 __unknownFC;
    UINT32 __unknown100;
    TagBlock object_names_block;
    TagBlock scenery_block;
    TagBlock scenery_palette_block;
    TagBlock bipeds_block;
    TagBlock biped_palette_block;
    TagBlock vehicles_block;
    TagBlock vehicle_palette_block;
    TagBlock equipment_block;
    TagBlock equipment_palette_block;
    TagBlock weapons_block;
    TagBlock weapon_palette_block;
    TagBlock device_groups_block;
    TagBlock machines_block;
    TagBlock machine_palette_block;
    TagBlock terminals_block;
    TagBlock terminal_palette_block;
    TagBlock controls_block;
    TagBlock control_palette_block;
    TagBlock sound_scenery_block;
    TagBlock sound_scenery_palette_block;
    TagBlock giants_block;
    TagBlock giant_palette_block;
    TagBlock effect_scenery_block;
    TagBlock effect_scenery_palette_block;
    TagBlock light_volumes_block;
    TagBlock light_volumes_palette_block;
    TagBlock sandbox_palette_block;
    TagBlock legacy_sandbox_info_block;
    TagReference __unknown254_reference;
    UINT32 __unknown264;
    UINT32 __unknown268;
    UINT32 __unknown26C;
    TagBlock soft_ceilings_block;
    TagBlock player_starting_profile_block;
    TagBlock player_starting_locations_block;
    TagBlock trigger_volumes_block;
    TagBlock __unknown2A0_block;
    TagBlock __unknown2AC_block;
    TagBlock __unknown2B8_block;
    UINT32 __unknown2C4;
    UINT32 __unknown2C8;
    UINT32 __unknown2CC;
    UINT32 __unknown2D0;
    UINT32 __unknown2D4;
    UINT32 __unknown2D8;
    TagBlock zoneset_switch_trigger_volumes_block;
    TagBlock location_name_callouts_block;
    TagReference airstrike_globals_reference;
    UINT32 __unknown304;
    UINT32 __unknown308;
    UINT32 __unknown30C;
    TagBlock __unknown310_block;
    TagBlock __unknown31C_block;
    TagBlock __unknown328_block;
    TagBlock __unknown334_block;
    UINT32 __unknown340;
    UINT32 __unknown344;
    UINT32 __unknown348;
    UINT32 __unknown34C;
    UINT32 __unknown350;
    UINT32 __unknown354;
    UINT32 __unknown358;
    UINT32 __unknown35C;
    UINT32 __unknown360;
    UINT32 __unknown364;
    UINT32 __unknown368;
    UINT32 __unknown36C;
    UINT32 __unknown370;
    UINT32 __unknown374;
    UINT32 __unknown378;
    TagBlock decals_block;
    TagBlock decal_palette_block;
    UINT32 __unknown394;
    UINT32 __unknown398;
    UINT32 __unknown39C;
    UINT32 __unknown3A0;
    UINT32 __unknown3A4;
    UINT32 __unknown3A8;
    TagBlock squad_groups_block;
    TagBlock squads_block;
    TagBlock zones_block;
    TagBlock __unknown3D0_block;
    TagBlock ai_cues_block;
    UINT32 __unknown3E8;
    UINT32 __unknown3EC;
    UINT32 __unknown3F0;
    UINT32 __unknown3F4;
    UINT32 __unknown3F8;
    UINT32 __unknown3FC;
    UINT32 __unknown400;
    UINT32 __unknown404;
    UINT32 __unknown408;
    TagBlock character_palette_block;
    UINT32 __unknown418;
    UINT32 __unknown41C;
    UINT32 __unknown420;
    TagBlock ai_pathfinding_data_block;
    UINT32 __unknown430;
    UINT32 __unknown434;
    UINT32 __unknown438;
    DataReference script_strings_data_reference;
    TagBlock scripts_block;
    TagBlock globals_block;
    TagBlock script_references_block;
    UINT32 __unknown474;
    UINT32 __unknown478;
    UINT32 __unknown47C;
    TagBlock scripting_data_block;
    TagBlock cutscene_flags_block;
    TagBlock cutscene_camera_points_block;
    TagBlock cutscene_titles_block;
    TagReference custom_object_name_strings_reference;
    TagReference chapter_title_strings_reference;
    TagBlock scenario_resources_block;
    TagBlock unit_seats_mapping_block;
    TagBlock scenario_kill_triggers_block;
    TagBlock scenario_safe_triggers_block;
    TagBlock scenario_mopp_triggers_block;
    UINT32 __unknown50C;
    UINT32 __unknown510;
    UINT32 __unknown514;
    UINT32 __unknown518;
    UINT32 __unknown51C;
    UINT32 __unknown520;
    TagBlock script_expressions_block;
    UINT32 __unknown530;
    UINT32 __unknown534;
    UINT32 __unknown538;
    UINT32 __unknown53C;
    UINT32 __unknown540;
    UINT32 __unknown544;
    TagBlock background_sound_environment_palette_block;
    TagBlock fog_block;
    TagBlock camera_fx_block;
    TagBlock weather_block;
    TagBlock scenario_cluster_data_block;
    INT32 object_salts_array[32];
    TagBlock spawn_data_block;
    TagReference sound_effects_collection_reference;
    TagBlock crates_block;
    TagBlock crate_palette_block;
    TagBlock flock_palette_block;
    TagBlock flocks_block;
    TagReference subtitle_strings_reference;
    UINT32 __unknown660;
    UINT32 __unknown664;
    UINT32 __unknown668;
    TagBlock creature_palette_block;
    TagBlock big_battle_creatures_block;
    TagBlock editor_folders_block;
    TagReference territory_location_name_strings_reference;
    UINT32 __unknown6A0;
    UINT32 __unknown6A4;
    TagBlock mission_dialogue_block;
    TagReference objective_strings_reference;
    TagReference scenario_interpolator_reference;
    UINT32 __unknown6D4;
    UINT32 __unknown6D8;
    UINT32 __unknown6DC;
    TagReference default_camera_fx_reference;
    TagReference default_screen_fx_reference;
    TagReference ambient_occlusion_profile_reference;
    TagReference sky_parameters_reference;
    TagReference fog_parameters_reference;
    TagReference global_lighting_reference;
    TagReference lightmap_reference;
    TagReference performance_throttles_reference;
    TagBlock __unknown760_block;
    TagBlock ai_objectives_block;
    TagBlock designer_zonesets_block;
    TagBlock __unknown784_block;
    UINT32 __unknown790;
    UINT32 __unknown794;
    UINT32 __unknown798;
    TagBlock particle_emitters_block;
    TagBlock __unknown7A8_block;
    TagBlock cinematics_block;
    TagBlock cinematic_lights_block;
    UINT32 __unknown7CC;
    UINT32 __unknown7D0;
    UINT32 __unknown7D4;
    TagBlock scenario_metagame_block;
    TagBlock __unknown7E4_block;
    TagBlock __unknown7F0_block;
    UINT32 __unknown7FC;
    UINT32 __unknown800;
    UINT32 __unknown804;
    UINT32 __unknown808;
    UINT32 __unknown80C;
    UINT32 __unknown810;
    UINT32 __unknown814;
    UINT32 __unknown818;
    UINT32 __unknown81C;
    TagBlock vignettes_block;
    TagReference map_location_globals_reference;
    TagBlock __unknown83C_block;
    TagReference mission_hud_reference;
    TagReference required_resources_reference;
    TagReference variant_globals_reference;
    TagBlock compiled_data_block;
};
#pragma pack(pop)
