#pragma once

#define INT32 int
#define UINT32 unsigned int
#define INT16 short
#define UINT16 unsigned short

/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'haloreach.dll'
*/

/* 387 */
enum e_map_type : __int16
{
    _map_type_singleplayer = 0x0,
    _map_type_multiplayer = 0x1,
    _map_type_mainmenu = 0x2,
    k_number_of_map_types = 0x3,
};

/* 551 */
struct real_point3d
{
	float x;
	float y;
	float z;
};

/* 550 */
struct s_scenario_trigger_volumes_block_definition
{
	string_id name;
	INT16 object_name;
	INT16 __unknown6;
	string_id node_name;
	INT16 __unknownC;
	INT16 __unknownE;
	float __unknown10;
	float __unknown14;
	float __unknown18;
	float __unknown1C;
	float __unknown20;
	float __unknown24;
	real_point3d position;
	real_point3d extents;
	float __unknown40;
	s_tag_block_definition<> __unknown44_block;
	s_tag_block_definition<> __unknown50_block;
	float __unknown5C;
	float __unknown60;
	float __unknown64;
	float __unknown68;
	float __unknown6C;
	float __unknown70;
	float __unknown74;
	INT16 kill_volume;
	INT16 editor_folder_index;
};

struct s_scenario_ai_objectives_block_definition
{
	string_id name;
	s_tag_block_definition<> __unknown4_block;
	INT16 __unknown10;
	INT16 zone;
	INT16 unknown_editor_role_index;
	INT16 editor_folder_index;
	s_tag_block_definition<> roles_block;
};

#define tag_block_type(type) <type>

/* 398 */
struct s_scenario_scripts_parameters_block_definition
{
	char script_name[32];
	__int16 type;
	__int16 __unknown22;
};

/* 397 */
struct s_scenario_scripts_block_definition
{
	string_id name;
	__int16 script_type;
	__int16 return_type;
	unsigned __int16 root_expression_index;
	unsigned __int16 root_expression_salt;
	s_tag_block_definition<s_scenario_scripts_parameters_block_definition> parameters;
};

/* 386 */
#pragma pack(push, 4)
struct s_scenario_definition
{
    static constexpr TagGroupName kTagGroupName = TagGroupName::Scenario;
    e_map_type map_type;
    UINT16 flags;
    UINT32 __unknown4;
    UINT32 campaign_id;
    UINT32 map_id;
    string_id scenario_name;
    INT16 campaign_level_index;
    INT16 __unknown16;
    INT32 __unknown18;
    float local_north;
    float __unknown20;
    float __unknown24;
    UINT32 __unknown28;
    UINT32 __unknown2C;
    float __unknown30;
    float sandbox_budget;
    string_id default_vehicle_filter;
    TagReference performance_throttle_profile_reference;
    s_tag_block_definition<> structure_sbsps_block;
    s_tag_block_definition<> structure_design_block;
    TagReference __unknown64_reference;
    TagReference __unknown74_reference;
    s_tag_block_definition<> sky_references_block;
    s_tag_block_definition<> bsp_groups_block;
    s_tag_block_definition<> scenario_bsp_audibility_block;
    s_tag_block_definition<> scenario_zoneset_groups_block;
    UINT32 __unknownB4;
    UINT32 __unknownB8;
    UINT32 __unknownBC;
    UINT32 __unknownC0;
    UINT32 __unknownC4;
    UINT32 __unknownC8;
    UINT32 __unknownCC;
    UINT32 __unknownD0;
    UINT32 __unknownD4;
    UINT32 __unknownD8;
    UINT32 __unknownDC;
    UINT32 __unknownE0;
    DataReference editor_scenario_data_data_reference;
    UINT32 __unknownF8;
    UINT32 __unknownFC;
    UINT32 __unknown100;
    s_tag_block_definition<> object_names_block;
    s_tag_block_definition<> scenery_block;
    s_tag_block_definition<> scenery_palette_block;
    s_tag_block_definition<> bipeds_block;
    s_tag_block_definition<> biped_palette_block;
    s_tag_block_definition<> vehicles_block;
    s_tag_block_definition<> vehicle_palette_block;
    s_tag_block_definition<> equipment_block;
    s_tag_block_definition<> equipment_palette_block;
    s_tag_block_definition<> weapons_block;
    s_tag_block_definition<> weapon_palette_block;
    s_tag_block_definition<> device_groups_block;
    s_tag_block_definition<> machines_block;
    s_tag_block_definition<> machine_palette_block;
    s_tag_block_definition<> terminals_block;
    s_tag_block_definition<> terminal_palette_block;
    s_tag_block_definition<> controls_block;
    s_tag_block_definition<> control_palette_block;
    s_tag_block_definition<> sound_scenery_block;
    s_tag_block_definition<> sound_scenery_palette_block;
    s_tag_block_definition<> giants_block;
    s_tag_block_definition<> giant_palette_block;
    s_tag_block_definition<> effect_scenery_block;
    s_tag_block_definition<> effect_scenery_palette_block;
    s_tag_block_definition<> light_volumes_block;
    s_tag_block_definition<> light_volumes_palette_block;
    s_tag_block_definition<> sandbox_palette_block;
    s_tag_block_definition<> legacy_sandbox_info_block;
    TagReference __unknown254_reference;
    UINT32 __unknown264;
    UINT32 __unknown268;
    UINT32 __unknown26C;
    s_tag_block_definition<> soft_ceilings_block;
    s_tag_block_definition<> player_starting_profile_block;
    s_tag_block_definition<> player_starting_locations_block;
    s_tag_block_definition<> trigger_volumes_block;
    s_tag_block_definition<> __unknown2A0_block;
    s_tag_block_definition<> __unknown2AC_block;
    s_tag_block_definition<> __unknown2B8_block;
    UINT32 __unknown2C4;
    UINT32 __unknown2C8;
    UINT32 __unknown2CC;
    UINT32 __unknown2D0;
    UINT32 __unknown2D4;
    UINT32 __unknown2D8;
    s_tag_block_definition<> zoneset_switch_trigger_volumes_block;
    s_tag_block_definition<> location_name_callouts_block;
    TagReference airstrike_globals_reference;
    UINT32 __unknown304;
    UINT32 __unknown308;
    UINT32 __unknown30C;
    s_tag_block_definition<> __unknown310_block;
    s_tag_block_definition<> __unknown31C_block;
    s_tag_block_definition<> __unknown328_block;
    s_tag_block_definition<> __unknown334_block;
    UINT32 __unknown340;
    UINT32 __unknown344;
    UINT32 __unknown348;
    UINT32 __unknown34C;
    UINT32 __unknown350;
    UINT32 __unknown354;
    UINT32 __unknown358;
    UINT32 __unknown35C;
    UINT32 __unknown360;
    UINT32 __unknown364;
    UINT32 __unknown368;
    UINT32 __unknown36C;
    UINT32 __unknown370;
    UINT32 __unknown374;
    UINT32 __unknown378;
    s_tag_block_definition<> decals_block;
    s_tag_block_definition<> decal_palette_block;
    UINT32 __unknown394;
    UINT32 __unknown398;
    UINT32 __unknown39C;
    UINT32 __unknown3A0;
    UINT32 __unknown3A4;
    UINT32 __unknown3A8;
    s_tag_block_definition<> squad_groups_block;
    s_tag_block_definition<> squads_block;
    s_tag_block_definition<> zones_block;
    s_tag_block_definition<> __unknown3D0_block;
    s_tag_block_definition<> ai_cues_block;
    UINT32 __unknown3E8;
    UINT32 __unknown3EC;
    UINT32 __unknown3F0;
    UINT32 __unknown3F4;
    UINT32 __unknown3F8;
    UINT32 __unknown3FC;
    UINT32 __unknown400;
    UINT32 __unknown404;
    UINT32 __unknown408;
    s_tag_block_definition<> character_palette_block;
    UINT32 __unknown418;
    UINT32 __unknown41C;
    UINT32 __unknown420;
    s_tag_block_definition<> ai_pathfinding_data_block;
    UINT32 __unknown430;
    UINT32 __unknown434;
    UINT32 __unknown438;
    DataReference script_strings_data_reference;
    s_tag_block_definition<s_scenario_scripts_block_definition> scripts_block;
    s_tag_block_definition<> globals_block;
    s_tag_block_definition<> script_references_block;
    UINT32 __unknown474;
    UINT32 __unknown478;
    UINT32 __unknown47C;
    s_tag_block_definition<> scripting_data_block;
    s_tag_block_definition<> cutscene_flags_block;
    s_tag_block_definition<> cutscene_camera_points_block;
    s_tag_block_definition<> cutscene_titles_block;
    TagReference custom_object_name_strings_reference;
    TagReference chapter_title_strings_reference;
    s_tag_block_definition<> scenario_resources_block;
    s_tag_block_definition<> unit_seats_mapping_block;
    s_tag_block_definition<> scenario_kill_triggers_block;
    s_tag_block_definition<> scenario_safe_triggers_block;
    s_tag_block_definition<> scenario_mopp_triggers_block;
    UINT32 __unknown50C;
    UINT32 __unknown510;
    UINT32 __unknown514;
    UINT32 __unknown518;
    UINT32 __unknown51C;
    UINT32 __unknown520;
    s_tag_block_definition<> script_expressions_block;
    UINT32 __unknown530;
    UINT32 __unknown534;
    UINT32 __unknown538;
    UINT32 __unknown53C;
    UINT32 __unknown540;
    UINT32 __unknown544;
    s_tag_block_definition<> background_sound_environment_palette_block;
    s_tag_block_definition<> fog_block;
    s_tag_block_definition<> camera_fx_block;
    s_tag_block_definition<> weather_block;
    s_tag_block_definition<> scenario_cluster_data_block;
    INT32 object_salts_array[32];
    s_tag_block_definition<> spawn_data_block;
    TagReference sound_effects_collection_reference;
    s_tag_block_definition<> crates_block;
    s_tag_block_definition<> crate_palette_block;
    s_tag_block_definition<> flock_palette_block;
    s_tag_block_definition<> flocks_block;
    TagReference subtitle_strings_reference;
    UINT32 __unknown660;
    UINT32 __unknown664;
    UINT32 __unknown668;
    s_tag_block_definition<> creature_palette_block;
    s_tag_block_definition<> big_battle_creatures_block;
    s_tag_block_definition<> editor_folders_block;
    TagReference territory_location_name_strings_reference;
    UINT32 __unknown6A0;
    UINT32 __unknown6A4;
    s_tag_block_definition<> mission_dialogue_block;
    TagReference objective_strings_reference;
    TagReference scenario_interpolator_reference;
    UINT32 __unknown6D4;
    UINT32 __unknown6D8;
    UINT32 __unknown6DC;
    TagReference default_camera_fx_reference;
    TagReference default_screen_fx_reference;
    TagReference ambient_occlusion_profile_reference;
    TagReference sky_parameters_reference;
    TagReference fog_parameters_reference;
    TagReference global_lighting_reference;
    TagReference lightmap_reference;
    TagReference performance_throttles_reference;
    s_tag_block_definition<> __unknown760_block;
    s_tag_block_definition<> ai_objectives_block;
    s_tag_block_definition<> designer_zonesets_block;
    s_tag_block_definition<> __unknown784_block;
    UINT32 __unknown790;
    UINT32 __unknown794;
    UINT32 __unknown798;
    s_tag_block_definition<> particle_emitters_block;
    s_tag_block_definition<> __unknown7A8_block;
    s_tag_block_definition<> cinematics_block;
    s_tag_block_definition<> cinematic_lights_block;
    UINT32 __unknown7CC;
    UINT32 __unknown7D0;
    UINT32 __unknown7D4;
    s_tag_block_definition<> scenario_metagame_block;
    s_tag_block_definition<> __unknown7E4_block;
    s_tag_block_definition<> __unknown7F0_block;
    UINT32 __unknown7FC;
    UINT32 __unknown800;
    UINT32 __unknown804;
    UINT32 __unknown808;
    UINT32 __unknown80C;
    UINT32 __unknown810;
    UINT32 __unknown814;
    UINT32 __unknown818;
    UINT32 __unknown81C;
    s_tag_block_definition<> vignettes_block;
    TagReference map_location_globals_reference;
    s_tag_block_definition<> __unknown83C_block;
    TagReference mission_hud_reference;
    TagReference required_resources_reference;
    TagReference variant_globals_reference;
    s_tag_block_definition<> compiled_data_block;
};
#pragma pack(pop)
