#pragma once

struct nicename("user_interface_sounds_definition") group('uise') s_user_interface_sounds_definition_definition
{
	TagReference nicename("Navigation Up") navigation_up_reference;
	TagReference nicename("Navigation Left") navigation_left_reference;
	TagReference nicename("Navigation Right") navigation_right_reference;
	TagReference nicename("Navigation Down") navigation_down_reference;
	TagReference __unknown0;
	TagReference __unknown1;
	TagReference __unknown2;
	TagReference __unknown3;
	TagReference __unknown4;
	TagReference __unknown5;
	TagReference __unknown6;
	TagReference __unknown7;
	TagReference nicename("A Button") a_button_reference;
	TagReference nicename("B Button") b_button_reference;
	TagReference nicename("X Button") x_button_reference;
	TagReference nicename("Y Button") y_button_reference;
	TagReference nicename("Left Trigger") left_trigger_reference;
	TagReference nicename("Right Trigger") right_trigger_reference;
	TagReference __unknown8;
	TagReference __unknown9;
	TagReference __unknown10;
	TagReference __unknown11;
	TagReference nicename("Start Button") start_button_reference;
	TagReference nicename("Back Button") back_button_reference;
	TagReference __unknown12;
	TagReference __unknown13;
	TagReference nicename("Left Bumper") left_bumper_reference;
	TagReference nicename("Right Bumper") right_bumper_reference;
	TagReference __unknown14;
	TagReference __unknown15;
	TagReference __unknown16;
	TagReference __unknown17;
	TagReference __unknown18;
	TagReference __unknown19;
	TagReference __unknown20;
	TagReference __unknown21;
	TagReference __unknown22;
	TagReference __unknown23;
	TagReference __unknown24;
	TagReference __unknown25;
	TagReference __unknown26;
	TagReference __unknown27;
	TagReference __unknown28;
	TagReference __unknown29;
	TagReference __unknown30;
	TagReference __unknown31;
	TagReference __unknown32;
	TagReference __unknown33;
	TagReference __unknown34;
	TagReference __unknown35;
	TagReference __unknown36;
	TagReference __unknown37;
	TagReference __unknown38;
	TagReference __unknown39;
	TagReference __unknown40;
	TagReference __unknown41;
	TagReference __unknown42;
	TagReference __unknown43;
	TagReference __unknown44;
	TagReference __unknown45;
	TagReference __unknown46;
	TagReference __unknown47;
	TagReference __unknown48;
	TagReference __unknown49;
	TagReference nicename("Error") error_reference;
	TagReference nicename("Lobby Initialize") lobby_initialize_reference;
	TagReference nicename("Lobby Exit") lobby_exit_reference;
	TagReference nicename("Timer Sound") timer_sound_reference;
	TagReference nicename("Timer Sound Zero") timer_sound_zero_reference;
	TagReference nicename("Alt Timer Sound") alt_timer_sound_reference;
	TagReference nicename("Secondary Alt Timer Sound") secondary_alt_timer_sound_reference;
	TagReference nicename("Matchmaking Advance Sound") matchmaking_advance_sound_reference;
	TagReference nicename("Exit Experience Game Completion") exit_experience_game_completion_reference;
	TagReference nicename("Exit Experience Time Spent Credits") exit_experience_time_spent_credits_reference;
	TagReference nicename("Exit Experience Winning Bonus") exit_experience_winning_bonus_reference;
	TagReference nicename("Exit Experience Hopper Bonus") exit_experience_hopper_bonus_reference;
	TagReference nicename("Exit Experience Invasion Bonus") exit_experience_invasion_bonus_reference;
	TagReference nicename("Exit Experience Commendation Bonus") exit_experience_commendation_bonus_reference;
	TagReference nicename("Exit Experience Challenges Bonus") exit_experience_challenges_bonus_reference;
	TagReference nicename("Exit Experience Achievement Bonus") exit_experience_achievement_bonus_reference;
	TagReference nicename("Exit Experience Slot Machine") exit_experience_slot_machine_reference;
	TagReference nicename("Exit Experience Heat Bonus") exit_experience_heat_bonus_reference;
	TagReference nicename("Exit Experience Totals") exit_experience_totals_reference;
	TagReference nicename("Exit Experience Rank Up") exit_experience_rank_up_reference;
	TagReference nicename("Exit Experience Subrank Up") exit_experience_subrank_up_reference;
	TagReference nicename("Unknown ") unknown__reference;
	TagReference nicename("Exit Experience Credit Award Loop") exit_experience_credit_award_loop_reference;
};

