#pragma once

struct nicename("User Interface Sounds Definition") group('uise') s_user_interface_sounds_definition_definition
{
	TagReference nicename("Navigation Up") navigation_up_reference; 
	TagReference nicename("Navigation Left") navigation_left_reference; 
	TagReference nicename("Navigation Right") navigation_right_reference; 
	TagReference nicename("Navigation Down") navigation_down_reference; 
	TagReference __unknown_reference; 
	TagReference __unknown2_reference; 
	TagReference __unknown3_reference; 
	TagReference __unknown4_reference; 
	TagReference __unknown5_reference; 
	TagReference __unknown6_reference; 
	TagReference __unknown7_reference; 
	TagReference __unknown8_reference; 
	TagReference nicename("A Button") a_button_reference; 
	TagReference nicename("B Button") b_button_reference; 
	TagReference nicename("X Button") x_button_reference; 
	TagReference nicename("Y Button") y_button_reference; 
	TagReference nicename("Left Trigger") left_trigger_reference; 
	TagReference nicename("Right Trigger") right_trigger_reference; 
	TagReference __unknown9_reference; 
	TagReference __unknown10_reference; 
	TagReference __unknown11_reference; 
	TagReference __unknown12_reference; 
	TagReference nicename("Start Button") start_button_reference; 
	TagReference nicename("Back Button") back_button_reference; 
	TagReference __unknown13_reference; 
	TagReference __unknown14_reference; 
	TagReference nicename("Left Bumper") left_bumper_reference; 
	TagReference nicename("Right Bumper") right_bumper_reference; 
	TagReference __unknown15_reference; 
	TagReference __unknown16_reference; 
	TagReference __unknown17_reference; 
	TagReference __unknown18_reference; 
	TagReference __unknown19_reference; 
	TagReference __unknown20_reference; 
	TagReference __unknown21_reference; 
	TagReference __unknown22_reference; 
	TagReference __unknown23_reference; 
	TagReference __unknown24_reference; 
	TagReference __unknown25_reference; 
	TagReference __unknown26_reference; 
	TagReference __unknown27_reference; 
	TagReference __unknown28_reference; 
	TagReference __unknown29_reference; 
	TagReference __unknown30_reference; 
	TagReference __unknown31_reference; 
	TagReference __unknown32_reference; 
	TagReference __unknown33_reference; 
	TagReference __unknown34_reference; 
	TagReference __unknown35_reference; 
	TagReference __unknown36_reference; 
	TagReference __unknown37_reference; 
	TagReference __unknown38_reference; 
	TagReference __unknown39_reference; 
	TagReference __unknown40_reference; 
	TagReference __unknown41_reference; 
	TagReference __unknown42_reference; 
	TagReference __unknown43_reference; 
	TagReference __unknown44_reference; 
	TagReference __unknown45_reference; 
	TagReference __unknown46_reference; 
	TagReference __unknown47_reference; 
	TagReference __unknown48_reference; 
	TagReference __unknown49_reference; 
	TagReference __unknown50_reference; 
	TagReference nicename("Error") error_reference; 
	TagReference nicename("Lobby Initialize") lobby_initialize_reference; 
	TagReference nicename("Lobby Exit") lobby_exit_reference; 
	TagReference nicename("Timer Sound") timer_sound_reference; 
	TagReference nicename("Timer Sound Zero") timer_sound_zero_reference; 
	TagReference nicename("Alt Timer Sound") alt_timer_sound_reference; 
	TagReference nicename("Secondary Alt Timer Sound") secondary_alt_timer_sound_reference; 
	TagReference nicename("Matchmaking Advance Sound") matchmaking_advance_sound_reference; 
	TagReference nicename("Exit Experience Game Completion") exit_experience_game_completion_reference; 
	TagReference nicename("Exit Experience Time Spent Credits") exit_experience_time_spent_credits_reference; 
	TagReference nicename("Exit Experience Winning Bonus") exit_experience_winning_bonus_reference; 
	TagReference nicename("Exit Experience Hopper Bonus") exit_experience_hopper_bonus_reference; 
	TagReference nicename("Exit Experience Invasion Bonus") exit_experience_invasion_bonus_reference; 
	TagReference nicename("Exit Experience Commendation Bonus") exit_experience_commendation_bonus_reference; 
	TagReference nicename("Exit Experience Challenges Bonus") exit_experience_challenges_bonus_reference; 
	TagReference nicename("Exit Experience Achievement Bonus") exit_experience_achievement_bonus_reference; 
	TagReference nicename("Exit Experience Slot Machine") exit_experience_slot_machine_reference; 
	TagReference nicename("Exit Experience Heat Bonus") exit_experience_heat_bonus_reference; 
	TagReference nicename("Exit Experience Totals") exit_experience_totals_reference; 
	TagReference nicename("Exit Experience Rank Up") exit_experience_rank_up_reference; 
	TagReference nicename("Exit Experience Subrank Up") exit_experience_subrank_up_reference; 
	TagReference __unknown__reference; 
	TagReference nicename("Exit Experience Credit Award Loop") exit_experience_credit_award_loop_reference; 
};
