#pragma once

namespace blofeld
{

constexpr unsigned long EMBLEM_LIBRARY_TAG = 'mlib';

extern s_tag_group emblem_library_group;

extern s_tag_block_definition emblem_library_block_block;
extern s_tag_struct emblem_bitmap_list_block_struct;
extern s_tag_block_definition emblem_bitmap_list_block;
extern s_tag_struct emblem_shape_list_block_struct;
extern s_tag_block_definition emblem_shape_list_block;
extern s_tag_struct emblem_front_list_block_struct;
extern s_tag_block_definition emblem_front_list_block;
extern s_tag_struct emblem_back_list_block_struct;
extern s_tag_block_definition emblem_back_list_block;
extern s_tag_struct emblem_runtime_front_list_block_struct;
extern s_tag_block_definition emblem_runtime_front_list_block;
extern s_tag_struct emblem_runtime_back_list_block_struct;
extern s_tag_block_definition emblem_runtime_back_list_block;

extern s_tag_struct emblem_library_struct_definition_struct_definition; // tag group
extern s_tag_struct emblem_transform_struct_definition;
extern s_tag_struct emblem_layer_struct_definition;

} // namespace blofeld

