#pragma once

namespace blofeld
{
	namespace halo2
	{
		namespace pc64
		{

			const s_tag_group* tag_groups[] =
			{
				&cache_file_sound_group,
				&scenario_scenery_resource_group,
				&scenario_weapons_resource_group,
				&scenario_vehicles_resource_group,
				&scenario_lights_resource_group,
				&scenario_bipeds_resource_group,
				&scenario_equipment_resource_group,
				&scenario_creature_resource_group,
				&scenario_sound_scenery_resource_group,
				&scenario_comments_resource_group,
				&sound_effect_template_group,
				&stereo_system_group,
				&decorators_group,
				&decorator_set_group,
				&light_volume_group,
				&particle_model_group,
				&ai_dialogue_globals_group,
				&scenario_ai_resource_group,
				&antenna_group,
				&biped_group,
				&bitmap_group,
				&crate_group,
				&breakable_surface_group,
				&character_group,
				&scenario_cinematics_resource_group,
				&scenario_cluster_data_resource_group,
				&cloth_group,
				&collision_model_group,
				&colony_group,
				&color_table_group,
				&contrail_group,
				&creature_group,
				&device_control_group,
				&scenario_decorators_resource_group,
				&scenario_decals_resource_group,
				&decal_group,
				&device_group,
				&cellular_automata_group,
				&scenario_devices_resource_group,
				&detail_object_collection_group,
				&effect_group,
				&screen_effect_group,
				&equipment_group,
				&planar_fog_group,
				&material_effects_group,
				&patchy_fog_group,
				&garbage_group,
				&chocolate_mountain_group,
				&multiplayer_variant_settings_interface_definition_group,
				&grenade_hud_interface_group,
				&model_group,
				&hud_message_text_group,
				&scenario_hs_source_file_group,
				&hud_number_group,
				&hud_globals_group,
				&item_group,
				&item_collection_group,
				&model_animation_graph_group,
				&damage_effect_group,
				&lens_flare_group,
				&device_light_fixture_group,
				&light_group,
				&sound_looping_group,
				&scenario_structure_lightmap_group,
				&device_machine_group,
				&globals_group,
				&mouse_cursor_definition_group,
				&ai_mission_dialogue_group,
				&meter_group,
				&render_model_group,
				&material_physics_group,
				&multiplayer_scenario_description_group,
				&multiplayer_globals_group,
				&new_hud_definition_group,
				&object_group,
				&physics_model_group,
				&physics_group,
				&pixel_shader_group,
				&particle_physics_group,
				&point_physics_group,
				&projectile_group,
				&particle_group,
				&scenario_structure_bsp_group,
				&scenery_group,
				&scenario_group,
				&sound_effect_collection_group,
				&shader_group,
				&text_value_pair_definition_group,
				&user_interface_list_skin_definition_group,
				&sky_group,
				&shader_light_response_group,
				&sound_classes_group,
				&sound_group,
				&sound_environment_group,
				&sound_mix_group,
				&shader_pass_group,
				&sound_dialogue_constants_group,
				&sound_scenery_group,
				&scenario_structure_lighting_resource_group,
				&shader_template_group,
				&style_group,
				&liquid_group,
				&camera_track_group,
				&scenario_trigger_volumes_resource_group,
				&dialogue_group,
				&sound_cache_file_gestalt_group,
				&unit_hud_interface_group,
				&multilingual_unicode_string_list_group,
				&unit_group,
				&vehicle_collection_group,
				&vehicle_group,
				&vertex_shader_group,
				&weapon_group,
				&weather_system_group,
				&user_interface_screen_widget_definition_group,
				&user_interface_globals_definition_group,
				&cellular_automata2d_group,
				&user_interface_shared_globals_definition_group,
				&wind_group,
				&weapon_hud_interface_group,
			};

		} // namespace pc64

	} // namespace halo2

} // namespace blofeld

