#pragma once

#define _field_string _field_string, __FILE__, __LINE__
#define _field_long_string _field_long_string, __FILE__, __LINE__
#define _field_string_id _field_string_id, __FILE__, __LINE__
#define _field_old_string_id _field_old_string_id, __FILE__, __LINE__
#define _field_char_integer _field_char_integer, __FILE__, __LINE__
#define _field_short_integer _field_short_integer, __FILE__, __LINE__
#define _field_long_integer _field_long_integer, __FILE__, __LINE__
#define _field_int64_integer _field_int64_integer, __FILE__, __LINE__
#define _field_angle _field_angle, __FILE__, __LINE__
#define _field_tag _field_tag, __FILE__, __LINE__
#define _field_char_enum _field_char_enum, __FILE__, __LINE__
#define _field_enum _field_enum, __FILE__, __LINE__
#define _field_long_enum _field_long_enum, __FILE__, __LINE__
#define _field_long_flags _field_long_flags, __FILE__, __LINE__
#define _field_word_flags _field_word_flags, __FILE__, __LINE__
#define _field_byte_flags _field_byte_flags, __FILE__, __LINE__
#define _field_point_2d _field_point_2d, __FILE__, __LINE__
#define _field_rectangle_2d _field_rectangle_2d, __FILE__, __LINE__
#define _field_rgb_color _field_rgb_color, __FILE__, __LINE__
#define _field_argb_color _field_argb_color, __FILE__, __LINE__
#define _field_real _field_real, __FILE__, __LINE__
#define _field_real_fraction _field_real_fraction, __FILE__, __LINE__
#define _field_real_point_2d _field_real_point_2d, __FILE__, __LINE__
#define _field_real_point_3d _field_real_point_3d, __FILE__, __LINE__
#define _field_real_vector_2d _field_real_vector_2d, __FILE__, __LINE__
#define _field_real_vector_3d _field_real_vector_3d, __FILE__, __LINE__
#define _field_real_quaternion _field_real_quaternion, __FILE__, __LINE__
#define _field_real_euler_angles_2d _field_real_euler_angles_2d, __FILE__, __LINE__
#define _field_real_euler_angles_3d _field_real_euler_angles_3d, __FILE__, __LINE__
#define _field_real_plane_2d _field_real_plane_2d, __FILE__, __LINE__
#define _field_real_plane_3d _field_real_plane_3d, __FILE__, __LINE__
#define _field_real_rgb_color _field_real_rgb_color, __FILE__, __LINE__
#define _field_real_argb_color _field_real_argb_color, __FILE__, __LINE__
#define _field_real_hsv_color _field_real_hsv_color, __FILE__, __LINE__
#define _field_real_ahsv_color _field_real_ahsv_color, __FILE__, __LINE__
#define _field_short_bounds _field_short_bounds, __FILE__, __LINE__
#define _field_angle_bounds _field_angle_bounds, __FILE__, __LINE__
#define _field_real_bounds _field_real_bounds, __FILE__, __LINE__
#define _field_real_fraction_bounds _field_real_fraction_bounds, __FILE__, __LINE__
#define _field_tag_reference _field_tag_reference, __FILE__, __LINE__
#define _field_block _field_block, __FILE__, __LINE__
#define _field_long_block_flags _field_long_block_flags, __FILE__, __LINE__
#define _field_word_block_flags _field_word_block_flags, __FILE__, __LINE__
#define _field_byte_block_flags _field_byte_block_flags, __FILE__, __LINE__
#define _field_char_block_index _field_char_block_index, __FILE__, __LINE__
#define _field_custom_char_block_index _field_custom_char_block_index, __FILE__, __LINE__
#define _field_short_block_index _field_short_block_index, __FILE__, __LINE__
#define _field_custom_short_block_index _field_custom_short_block_index, __FILE__, __LINE__
#define _field_long_block_index _field_long_block_index, __FILE__, __LINE__
#define _field_custom_long_block_index _field_custom_long_block_index, __FILE__, __LINE__
#define _field_data _field_data, __FILE__, __LINE__
#define _field_vertex_buffer _field_vertex_buffer, __FILE__, __LINE__
#define _field_pad _field_pad, __FILE__, __LINE__
#define _field_useless_pad _field_useless_pad, __FILE__, __LINE__
#define _field_skip _field_skip, __FILE__, __LINE__
#define _field_non_cache_runtime_value _field_non_cache_runtime_value, __FILE__, __LINE__
#define _field_explanation _field_explanation, __FILE__, __LINE__
#define _field_custom _field_custom, __FILE__, __LINE__
#define _field_struct _field_struct, __FILE__, __LINE__
#define _field_array _field_array, __FILE__, __LINE__
#define _field_pageable _field_pageable, __FILE__, __LINE__
#define _field_api_interop _field_api_interop, __FILE__, __LINE__
#define _field_terminator _field_terminator, __FILE__, __LINE__
#define _field_byte_integer _field_byte_integer, __FILE__, __LINE__
#define _field_word_integer _field_word_integer, __FILE__, __LINE__
#define _field_dword_integer _field_dword_integer, __FILE__, __LINE__
#define _field_qword_integer _field_qword_integer, __FILE__, __LINE__

#define _field_pointer _field_pointer, __FILE__, __LINE__
#define _field_version_equal _field_version_equal, __FILE__, __LINE__
#define _field_version_not_equal _field_version_not_equal, __FILE__, __LINE__
#define _field_version_less _field_version_less, __FILE__, __LINE__
#define _field_version_greater _field_version_greater, __FILE__, __LINE__
#define _field_version_less_or_equal _field_version_less_or_equal, __FILE__, __LINE__
#define _field_version_greater_or_equal _field_version_greater_or_equal, __FILE__, __LINE__
#define _field_version_custom _field_version_custom, __FILE__, __LINE__
#define _field_version_platform_include _field_version_platform_include, __FILE__, __LINE__
#define _field_version_platform_exclude _field_version_platform_exclude, __FILE__, __LINE__
