#pragma once

namespace blofeld
{

namespace macaque
{

	extern s_tag_block_definition area_reference_block;
	extern s_tag_struct_definition area_reference_block_struct_definition; // area_reference_block
	extern s_tag_block_definition objectives_block;
	extern s_tag_struct_definition objectives_block_struct_definition; // objectives_block
	extern s_tag_block_definition opposing_objective_block;
	extern s_tag_struct_definition opposing_objective_block_struct_definition; // opposing_objective_block
	extern s_tag_block_definition tasks_block;
	extern s_tag_struct_definition tasks_block_struct_definition; // tasks_block
	extern s_tag_block_definition script_fragment_block;
	extern s_tag_struct_definition script_fragment_block_struct_definition; // script_fragment_block
	extern s_tag_block_definition task_direction_block_v2_block;
	extern s_tag_block_definition task_direction_point_block;
	extern s_tag_struct_definition task_direction_point_block_struct_definition; // task_direction_point_block

	extern s_tag_struct_definition task_direction_block_v2_struct;

	extern c_versioned_string_list fragment_state_enum_strings;
	extern s_string_list_definition fragment_state_enum;
	extern c_versioned_string_list task_flags_definition_strings;
	extern s_string_list_definition task_flags_definition;
	extern c_versioned_string_list filter_flags_strings;
	extern s_string_list_definition filter_flags;
	extern c_versioned_string_list objective_flags_strings;
	extern s_string_list_definition objective_flags;
	extern c_versioned_string_list inhibit_behavior_flags_strings;
	extern s_string_list_definition inhibit_behavior_flags;
	extern c_versioned_string_list filter_enum_strings;
	extern s_string_list_definition filter_enum;
	extern c_versioned_string_list task_follow_enum_strings;
	extern s_string_list_definition task_follow_enum;
	extern c_versioned_string_list task_follow_player_flags_strings;
	extern s_string_list_definition task_follow_player_flags;
	extern c_versioned_string_list task_movement_enum_strings;
	extern s_string_list_definition task_movement_enum;
	extern c_versioned_string_list task_dialogue_enum_strings;
	extern s_string_list_definition task_dialogue_enum;
	extern c_versioned_string_list zone_set_type_enum_strings;
	extern s_string_list_definition zone_set_type_enum;
	extern c_versioned_string_list zone_set_flags_strings;
	extern s_string_list_definition zone_set_flags;
	extern c_versioned_string_list task_runtime_flags_strings;
	extern s_string_list_definition task_runtime_flags;
	extern c_versioned_string_list task_attitude_enum_strings;
	extern s_string_list_definition task_attitude_enum;

} // namespace macaque

} // namespace blofeld

