#pragma once

namespace blofeld
{

extern s_tag_struct material_struct_struct_definition;

extern s_tag_struct material_postprocess_block_struct_definition;
extern s_tag_block_definition material_postprocess_block;
extern s_tag_struct material_postprocess_texture_block_struct_definition;
extern s_tag_block_definition material_postprocess_texture_block;
extern s_tag_struct real_vector4d_block_struct_definition;
extern s_tag_block_definition real_vector4d_block$3;
extern s_tag_struct int_block_struct_definition;
extern s_tag_block_definition int_block$3;
extern s_tag_struct functionParameterBlock_struct_definition;
extern s_tag_block_definition functionParameterBlock;
extern s_tag_struct externParameterBlock_struct_definition;
extern s_tag_block_definition externParameterBlock;

constexpr unsigned long MATERIAL_TAG = 'mat ';

extern s_tag_block_definition material_block;
extern s_tag_group material_group;
} // namespace blofeld

