#pragma once

namespace blofeld
{

	extern s_tag_struct_definition character_physics_struct_struct_definition;
	extern s_tag_struct_definition character_physics_ground_struct_struct_definition;
	extern s_tag_struct_definition character_physics_flying_struct_struct_definition;

	extern c_versioned_string_list flying_physics_flags_strings;
	extern s_string_list_definition flying_physics_flags;
	extern c_versioned_string_list character_physics_flags_strings;
	extern s_string_list_definition character_physics_flags;

} // namespace blofeld

