#pragma once

namespace blofeld
{



	extern s_tag_block_definition anti_gravity_point_definition_block;
	extern s_tag_struct_definition anti_gravity_point_definition_block_struct_definition; // anti_gravity_point_definition_block
	extern s_tag_block_definition friction_point_definition_block;
	extern s_tag_struct_definition friction_point_definition_block_struct_definition; // friction_point_definition_block

	extern s_tag_struct_definition havok_vehicle_physics_struct;

	extern s_string_list_definition anti_gravity_point_definition_flags;
	extern s_string_list_definition anti_gravity_point_definition_damping;
	extern s_string_list_definition friction_point_definition_flags;
	extern s_string_list_definition havok_vehicle_physics_definition_flags;
	extern s_string_list_definition physics_update_period_enum;
	extern s_string_list_definition friction_type_enum;

} // namespace blofeld

