#pragma once

#include "cache_utilities.h"
#include "tag_group_interface.h"
#include "tag_interface.h"
#include "cache_file_string_id_guesstimator.h"
#include "cache_file.h"
#include "virtual_tag_block.h"
#include "virtual_tag.h"

//#include "CacheVersions\eldorado_tag_interface.h"
#include "CacheVersions\haloreach_tag_interface.h"
//#include "CacheVersions\halo1_tag_interface.h"
//#include "CacheVersions\halo2_tag_interface.h"
//#include "CacheVersions\halo3_tag_interface.h"
//#include "CacheVersions\halo3odst_tag_interface.h"
//#include "CacheVersions\halo4_tag_interface.h"
//#include "CacheVersions\groundhog_tag_interface.h"

//#include "CacheVersions\eldorado_tag_group_interface.h"
#include "CacheVersions\haloreach_tag_group_interface.h"
//#include "CacheVersions\halo1_tag_group_interface.h"
//#include "CacheVersions\halo2_tag_group_interface.h"
//#include "CacheVersions\halo3_tag_group_interface.h"
//#include "CacheVersions\halo3odst_tag_group_interface.h"
//#include "CacheVersions\halo4_tag_group_interface.h"
//#include "CacheVersions\groundhog_tag_group_interface.h"

#include "CacheVersions\eldorado_cache_file.h"
#include "CacheVersions\haloreach_cache_file.h"
#include "CacheVersions\halo1_cache_file.h"
#include "CacheVersions\halo2_cache_file.h"
#include "CacheVersions\halo3_cache_file.h"
#include "CacheVersions\halo3odst_cache_file.h"
#include "CacheVersions\halo4_cache_file.h"
#include "CacheVersions\groundhog_cache_file.h"
#include "CacheVersions\halo5_cache_file.h"
