#pragma once


/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'MCC-Win64-Shipping.exe'
*/

#define __int8 char
#define __int16 short
#define __int32 int
#define __int64 long long

struct _RTL_CRITICAL_SECTION_DEBUG;
struct IGameEngine;
struct GameEvents_vftbl;
struct GameEvents;

/* 514 */
struct __declspec(align(8)) IGameEngine_vftbl
{
	void(__fastcall* init_graphics)(IGameEngine*, __int64, __int64, __int64, __int64);
	void(__fastcall* init_thread)(IGameEngine*, GameEvents*, __int64);
	void* function3;
	void* function4;
	void* function5;
	void* function6;
	void* function7;
	void* function8;
	void* function9;
	void* function10;
	void* function11;
};

/* 17 */
//typedef unsigned int DWORD;

/* 515 */
struct IGameEngine
{
	IGameEngine_vftbl* vftbl;
	DWORD unknown0;
	float unknown1;
	char unknown2[454];
};

/* 516 */
struct GameEngineHostCallback_vftbl
{
	void* function1;
	void* function2;
	void* function3;
	void* function4;
	void* function5;
	void* function6;
	void* function7;
	void* function8;
	void* function9;
	void* function10;
	void* function11;
	void* function12;
	void* function13;
	void* function14;
	void* function15;
	void* function16;
	void* function17;
	void* function18;
	void* function19;
	void* function20;
	void* function21;
	void* function22;
	void* function23;
	void* function24;
	void* function25;
	void* function26;
	void* function27;
	void* function28;
	void* function29;
	void* function30;
	void* function31;
	void* function32;
	void* function33;
	void* function34;
	void* function35;
	void* function36;
	void* function37;
	void* function38;
	void* function39;
	void* function40;
	void* function41;
	void* function42;
	void* function43;
};

/* 517 */
struct __declspec(align(8)) GameEngineHostCallback
{
	GameEngineHostCallback_vftbl* vftbl;
	GameEvents* pGameEvents;
	QWORD data1[5863];
};


/* 4 */
typedef struct _GUID GUID;

/* 23 */
typedef _RTL_CRITICAL_SECTION_DEBUG* PRTL_CRITICAL_SECTION_DEBUG;


/* 28 */
typedef void* HANDLE;

/* 29 */
typedef unsigned __int64 ULONG_PTR;


/* 520 */
struct __declspec(align(8)) UnknownType0
{
	QWORD qword0;
	QWORD* qword1;
	QWORD* qword2;
	DWORD dword0;
	DWORD dword1;
	QWORD qword4;
	QWORD* qword5;
	QWORD* qword6;
	DWORD dword2;
	DWORD dword3;
	DWORD dword4;
	DWORD dword5;
};

/* 519 */
struct GameEvents
{
	GameEvents_vftbl* vftbl;
	_WORD word0;
	_WORD word1;
	GUID guid;
	__unaligned __declspec(align(1)) _QWORD qword0;
	__unaligned __declspec(align(1)) _QWORD qword1;
	__unaligned __declspec(align(1)) _QWORD qword2;
	__unaligned __declspec(align(1)) _QWORD qword3;
	__unaligned __declspec(align(1)) _QWORD qword4;
	__unaligned __declspec(align(1)) _QWORD qword5;
	__unaligned __declspec(align(1)) _QWORD qword6;
	__unaligned __declspec(align(1)) _QWORD qword7;
	_DWORD dword0;
	_DWORD dword1;
	_DWORD dword2;
	_RTL_CRITICAL_SECTION rtlCriticalSection;
	_QWORD qword8;
	UnknownType0 unknownStruct;
	_QWORD qword9;
	_QWORD qwordA;
	_QWORD qwordB;
};

typedef void(NullSubFunc)();

/* 518 */
struct __declspec(align(8)) GameEvents_vftbl
{
	NullSubFunc* function1;
	NullSubFunc* function2;
	NullSubFunc* function3;
	NullSubFunc* function4;
	NullSubFunc* function5;
	NullSubFunc* function6;
	NullSubFunc* function7;
	NullSubFunc* function8;
	NullSubFunc* function9;
	NullSubFunc* function10;
	NullSubFunc* function11;
	NullSubFunc* function12;
	NullSubFunc* function13;
	NullSubFunc* function14;
	NullSubFunc* function15;
	NullSubFunc* function16;
	NullSubFunc* function17;
	NullSubFunc* function18;
	NullSubFunc* function19;
	NullSubFunc* function20;
	NullSubFunc* function21;
	NullSubFunc* function22;
	NullSubFunc* function23;
	NullSubFunc* function24;
	NullSubFunc* function25;
	NullSubFunc* function26;
	NullSubFunc* function27;
	NullSubFunc* function28;
	NullSubFunc* function29;
	NullSubFunc* function30;
	NullSubFunc* function31;
	void(__fastcall* function32)(GameEvents*, _QWORD, _QWORD, _QWORD, _QWORD, _DWORD, _QWORD, _QWORD, _DWORD, _QWORD);
	NullSubFunc* function33;
	NullSubFunc* function34;
	NullSubFunc* function35;
	NullSubFunc* function36;
	NullSubFunc* function37;
	NullSubFunc* function38;
	NullSubFunc* function39;
	NullSubFunc* function40;
	NullSubFunc* function41;
	NullSubFunc* function42;
	NullSubFunc* function43;
	NullSubFunc* function44;
	NullSubFunc* function45;
	NullSubFunc* function46;
	NullSubFunc* function47;
	NullSubFunc* function48;
	NullSubFunc* function49;
	NullSubFunc* function50;
	NullSubFunc* function51;
	NullSubFunc* function52;
	NullSubFunc* function53;
	NullSubFunc* function54;
	NullSubFunc* function55;
	NullSubFunc* function56;
	NullSubFunc* function57;
	NullSubFunc* function58;
	NullSubFunc* function59;
	NullSubFunc* function60;
	NullSubFunc* function61;
	NullSubFunc* function62;
	NullSubFunc* function63;
	NullSubFunc* function64;
	NullSubFunc* function65;
	NullSubFunc* function66;
	NullSubFunc* function67;
	NullSubFunc* function68;
	NullSubFunc* function69;
	NullSubFunc* function70;
	NullSubFunc* function71;
	NullSubFunc* function72;
	NullSubFunc* function73;
	NullSubFunc* function74;
	NullSubFunc* function75;
	NullSubFunc* function76;
	NullSubFunc* function77;
	NullSubFunc* function78;
	NullSubFunc* function79;
	NullSubFunc* function80;
	NullSubFunc* function81;
	NullSubFunc* function82;
	NullSubFunc* function83;
	NullSubFunc* function84;
	NullSubFunc* function85;
	NullSubFunc* function86;
	NullSubFunc* function87;
	NullSubFunc* function88;
	NullSubFunc* function89;
	NullSubFunc* function90;
	NullSubFunc* function91;
	NullSubFunc* function92;
	NullSubFunc* function93;
	NullSubFunc* function94;
	NullSubFunc* function95;
	NullSubFunc* function96;
	NullSubFunc* function97;
	NullSubFunc* function98;
	NullSubFunc* function99;
	NullSubFunc* function100;
	NullSubFunc* function101;
	NullSubFunc* function102;
	NullSubFunc* function103;
	NullSubFunc* function104;
	NullSubFunc* function105;
	NullSubFunc* function106;
	NullSubFunc* function107;
	NullSubFunc* function108;
	NullSubFunc* function109;
	NullSubFunc* function110;
	NullSubFunc* function111;
	NullSubFunc* function112;
	NullSubFunc* function113;
	NullSubFunc* function114;
	NullSubFunc* function115;
	NullSubFunc* function116;
	NullSubFunc* function117;
	NullSubFunc* function118;
	NullSubFunc* function119;
	NullSubFunc* function120;
	NullSubFunc* function121;
	NullSubFunc* function122;
	GUID* (__fastcall* GetGuid)(GameEvents*, GUID*);
	NullSubFunc* function124;
	NullSubFunc* function125;
	NullSubFunc* function126;
};

/* 20 */
typedef unsigned __int16 WORD;


/* 25 */
typedef _LIST_ENTRY LIST_ENTRY;



/* 522 */
struct UnknownStringType
{
	char data[48];
};

/* 523 */
#pragma pack(push, 1)
struct GameLauncher
{
	_DWORD dword0;
	_DWORD dword1;
	char unknownStruct0[177976];
	_DWORD dword2;
	_DWORD dword3;
	_QWORD qword0;
	_QWORD qword1;
	char unknownStruct1[48];
	_QWORD qword2;
	_QWORD qword3;
	_QWORD qword4;
	_DWORD dword4;
	_DWORD dword5;
	_QWORD qword5;
	_QWORD qword6;
	_WORD word0;
	_WORD word1;
	_WORD word2;
	_WORD word3;
	_QWORD qword7;
	_DWORD dword6;
	_DWORD dword7;
};
#pragma pack(pop)

