#pragma once

namespace blofeld
{

extern s_tag_struct collision_kd_hierarchy_static_struct_struct_definition;

extern s_tag_struct collision_kd_hierarchy_static_hash_table_data_block_struct_definition;
extern s_tag_block_definition collision_kd_hierarchy_static_hash_table_data_block;
extern s_tag_struct collision_kd_hierarchy_static_hash_table_short_block_struct_definition;
extern s_tag_block_definition collision_kd_hierarchy_static_hash_table_short_block;
extern s_tag_struct collision_kd_hierarchy_static_nodes_block_struct_definition;
extern s_tag_block_definition collision_kd_hierarchy_static_nodes_block;
extern s_tag_struct collision_kd_hierarchy_static_hash_table_headers_block_struct_definition;
extern s_tag_block_definition collision_kd_hierarchy_static_hash_table_headers_block;
extern s_tag_struct collision_kd_hierarchy_static_in_use_masks_block_struct_definition;
extern s_tag_block_definition collision_kd_hierarchy_static_in_use_masks_block;
extern s_tag_struct cluster_table_block_struct_definition;
extern s_tag_block_definition cluster_table_block;
extern s_tag_struct super_node_mappings_block_struct_definition;
extern s_tag_block_definition super_node_mappings_block$3;

} // namespace blofeld

