#pragma once

namespace blofeld
{

	extern const char* collision_kd_hierarchy_static_hash_table_cull_flags_strings[];
	extern s_string_list_definition collision_kd_hierarchy_static_hash_table_cull_flags;


	extern s_tag_struct collision_kd_hierarchy_static_hash_table_data_block_block_struct;
	extern s_tag_block_definition collision_kd_hierarchy_static_hash_table_data_block_block;
	extern s_tag_struct collision_kd_hierarchy_static_hash_table_short_block_block_struct;
	extern s_tag_block_definition collision_kd_hierarchy_static_hash_table_short_block_block;
	extern s_tag_struct collision_kd_hierarchy_static_nodes_block_block_struct;
	extern s_tag_block_definition collision_kd_hierarchy_static_nodes_block_block;
	extern s_tag_struct collision_kd_hierarchy_static_hash_table_headers_block_block_struct;
	extern s_tag_block_definition collision_kd_hierarchy_static_hash_table_headers_block_block;
	extern s_tag_struct collision_kd_hierarchy_static_in_use_masks_block_block_struct;
	extern s_tag_block_definition collision_kd_hierarchy_static_in_use_masks_block_block;
	extern s_tag_struct cluster_table_block_block_struct;
	extern s_tag_block_definition cluster_table_block_block;
	extern s_tag_struct super_node_mappings_block$3_block_struct;
	extern s_tag_block_definition super_node_mappings_block$3_block;

	extern s_tag_struct collision_kd_hierarchy_static_struct_struct_definition;

} // namespace blofeld

