#pragma once

namespace blofeld
{

extern s_tag_struct collision_model_bsp_struct_struct_definition;

extern s_tag_struct collision_model_material_block_struct_definition;
extern s_tag_block_definition collision_model_material_block;
extern s_tag_struct collision_model_region_block_struct_definition;
extern s_tag_block_definition collision_model_region_block;
extern s_tag_struct collision_model_permutation_block_struct_definition;
extern s_tag_block_definition collision_model_permutation_block;
extern s_tag_block_definition collision_model_bsp_block;
extern s_tag_struct collision_model_pathfinding_sphere_block_struct_definition;
extern s_tag_block_definition collision_model_pathfinding_sphere_block;
extern s_tag_struct collision_model_node_block_struct_definition;
extern s_tag_block_definition collision_model_node_block;

constexpr unsigned long COLLISION_MODEL_TAG = 'coll';

extern s_tag_block_definition collision_model_block;
extern s_tag_group collision_model_group;
} // namespace blofeld

