#pragma once

namespace blofeld
{

extern s_tag_struct camera_fx_exposure_struct_struct_definition;
extern s_tag_struct camera_fx_exposure_sensitivity_struct_struct_definition;
extern s_tag_struct camera_fx_bloom_highlight_struct_struct_definition;
extern s_tag_struct camera_fx_bloom_inherent_struct_struct_definition;
extern s_tag_struct camera_fx_bloom_self_illum_struct_struct_definition;
extern s_tag_struct camera_fx_bloom_intensity_struct_struct_definition;
extern s_tag_struct camera_fx_bloom_large_color_struct_struct_definition;
extern s_tag_struct camera_fx_bloom_medium_color_struct_struct_definition;
extern s_tag_struct camera_fx_bloom_small_color_struct_struct_definition;
extern s_tag_struct camera_fx_bling_intensity_struct_struct_definition;
extern s_tag_struct camera_fx_bling_size_struct_struct_definition;
extern s_tag_struct camera_fx_bling_angle_struct_struct_definition;
extern s_tag_struct camera_fx_bling_count_struct_struct_definition;
extern s_tag_struct camera_fx_self_illum_preferred_struct_struct_definition;
extern s_tag_struct camera_fx_self_illum_scale_struct_struct_definition;
extern s_tag_struct camera_fx_color_grading_struct_struct_definition;
extern s_tag_struct camera_fx_filmic_tone_curve_struct_struct_definition;


constexpr unsigned long CAMERA_FX_SETTINGS_TAG = 'cfxs';

extern s_tag_block_definition camera_fx_settings_block;
extern s_tag_group camera_fx_settings_group;
} // namespace blofeld

