#pragma once

namespace blofeld
{

extern s_tag_block optionalUnitCameraBlock_block;
extern s_tag_block equipmentAbilityDatum_block;
extern s_tag_block equipmentAbilityTypeMultiplayerPowerupBlock_block;
extern s_tag_block equipmentAbilityTypeSpawnerBlock_block;
extern s_tag_block equipmentAbilityTypeAiSpawnerBlock_block;
extern s_tag_block equipmentAbilityTypeProximityMineBlock_block;
extern s_tag_block equipmentAbilityTypeMotionTrackerNoiseBlock_block;
extern s_tag_block equipmentAbilityTypeInvincibilityBlock_block;
extern s_tag_block equipmentEffectWithThresholdBlock_block;
extern s_tag_block equipmentAbilityTypeTreeOfLifeBlock_block;
extern s_tag_block equipmentAbilityTypeShapeshifterBlock_block;
extern s_tag_block equipmentAbilityTypePlayerTraitFieldBlock_block;
extern s_tag_block equipmentAbilityTypeAiTraitFieldBlock_block;
extern s_tag_block aiEquipmentTraitsBlock_block;
extern s_tag_block aiEquipmentTraitAppearanceBlock_block;
extern s_tag_block equipmentAbilityTypeRepulsorFieldBlock_block;
extern s_tag_block equipmentAbilityTypeStasisFieldBlock_block;
extern s_tag_block equipmentAbilityTypeBallLightningBlock_block;
extern s_tag_block equipmentAbilityTypeDaddyBlock_block;
extern s_tag_block equipmentAbilityTypeLaserDesignationBlock_block;
extern s_tag_block equipmentAbilityTypeSuperJumpBlock_block;
extern s_tag_block equipmentAbilityTypeAmmoPackBlock_block;
extern s_tag_block equipmentAbilityTypePowerFistBlock_block;
extern s_tag_block equipmentAbilityTypeHealthPackBlock_block;
extern s_tag_block equipmentAbilityTypeJetPackBlock_block;
extern s_tag_block equipmentAbilityPartCowCatcherBlock_block;
extern s_tag_block equipmentAbilityTypeHologramBlock_block;
extern s_tag_block equipmentAbilityTypeSpecialWeaponBlock_block;
extern s_tag_block equipmentAbilityTypeSpecialMoveBlock_block;
extern s_tag_block equipmentAbilityTypeEngineerShieldsBlock_block;
extern s_tag_block equipmentAbilityTypeSprintBlock_block;
extern s_tag_block equipmentAbilityTypeTeleporterBlock_block;
extern s_tag_block equipmentAbilityTypeAutoTurretBlock_block;
extern s_tag_block equipmentAbilityTypeVisionModeBlock_block;
extern s_tag_block equipmentAbilityTypeShieldProjectorBlock_block;
extern s_tag_block equipmentAbilityTypeProjectileCollectorBlock_block;
extern s_tag_block equipmentAbilityTypeRemoteStrikeBlock_block;
extern s_tag_block equipmentAbilityTypeEquipmentHackerBlock_block;
extern s_tag_block equipmentHackerDrainLevel_block;
extern s_tag_block equipmentAbilityTypeRemoteVehicleBlock_block;
extern s_tag_block equipmentAbilityTypeSuicideBombBlock_block;
extern s_tag_block equipmentAbilityTypeActiveShieldBlock_block;
extern s_tag_block EquipmentSoundRTPCBlock_block;
extern s_tag_block EquipmentSoundSweetenerBlock_block;

constexpr unsigned long EQUIPMENT_TAG = 'eqip';

extern s_tag_block equipment_block;
extern s_tag_group equipment_group;
} // namespace blofeld

