#pragma once

namespace blofeld
{

extern s_tag_struct equipment_struct_definition_struct_definition;

extern s_tag_struct optionalUnitCameraBlock_struct_definition;
extern s_tag_block_definition optionalUnitCameraBlock;
extern s_tag_struct equipmentAbilityDatum_struct_definition;
extern s_tag_block_definition equipmentAbilityDatum;
extern s_tag_struct equipmentAbilityTypeMultiplayerPowerupBlock_struct_definition;
extern s_tag_block_definition equipmentAbilityTypeMultiplayerPowerupBlock;
extern s_tag_struct equipmentAbilityTypeSpawnerBlock_struct_definition;
extern s_tag_block_definition equipmentAbilityTypeSpawnerBlock;
extern s_tag_struct equipmentAbilityTypeAiSpawnerBlock_struct_definition;
extern s_tag_block_definition equipmentAbilityTypeAiSpawnerBlock;
extern s_tag_struct equipmentAbilityTypeProximityMineBlock_struct_definition;
extern s_tag_block_definition equipmentAbilityTypeProximityMineBlock;
extern s_tag_struct equipmentAbilityTypeMotionTrackerNoiseBlock_struct_definition;
extern s_tag_block_definition equipmentAbilityTypeMotionTrackerNoiseBlock;
extern s_tag_struct equipmentAbilityTypeInvincibilityBlock_struct_definition;
extern s_tag_block_definition equipmentAbilityTypeInvincibilityBlock;
extern s_tag_struct equipmentEffectWithThresholdBlock_struct_definition;
extern s_tag_block_definition equipmentEffectWithThresholdBlock;
extern s_tag_struct equipmentAbilityTypeTreeOfLifeBlock_struct_definition;
extern s_tag_block_definition equipmentAbilityTypeTreeOfLifeBlock;
extern s_tag_struct equipmentAbilityTypeShapeshifterBlock_struct_definition;
extern s_tag_block_definition equipmentAbilityTypeShapeshifterBlock;
extern s_tag_struct equipmentAbilityTypePlayerTraitFieldBlock_struct_definition;
extern s_tag_block_definition equipmentAbilityTypePlayerTraitFieldBlock;
extern s_tag_struct equipmentAbilityTypeAiTraitFieldBlock_struct_definition;
extern s_tag_block_definition equipmentAbilityTypeAiTraitFieldBlock;
extern s_tag_struct aiEquipmentTraitsBlock_struct_definition;
extern s_tag_block_definition aiEquipmentTraitsBlock;
extern s_tag_struct aiEquipmentTraitAppearanceBlock_struct_definition;
extern s_tag_block_definition aiEquipmentTraitAppearanceBlock;
extern s_tag_struct equipmentAbilityTypeRepulsorFieldBlock_struct_definition;
extern s_tag_block_definition equipmentAbilityTypeRepulsorFieldBlock;
extern s_tag_struct equipmentAbilityTypeStasisFieldBlock_struct_definition;
extern s_tag_block_definition equipmentAbilityTypeStasisFieldBlock;
extern s_tag_struct equipmentAbilityTypeBallLightningBlock_struct_definition;
extern s_tag_block_definition equipmentAbilityTypeBallLightningBlock;
extern s_tag_struct equipmentAbilityTypeDaddyBlock_struct_definition;
extern s_tag_block_definition equipmentAbilityTypeDaddyBlock;
extern s_tag_struct equipmentAbilityTypeLaserDesignationBlock_struct_definition;
extern s_tag_block_definition equipmentAbilityTypeLaserDesignationBlock;
extern s_tag_struct equipmentAbilityTypeSuperJumpBlock_struct_definition;
extern s_tag_block_definition equipmentAbilityTypeSuperJumpBlock;
extern s_tag_struct equipmentAbilityTypeAmmoPackBlock_struct_definition;
extern s_tag_block_definition equipmentAbilityTypeAmmoPackBlock;
extern s_tag_struct equipmentAbilityTypePowerFistBlock_struct_definition;
extern s_tag_block_definition equipmentAbilityTypePowerFistBlock;
extern s_tag_struct equipmentAbilityTypeHealthPackBlock_struct_definition;
extern s_tag_block_definition equipmentAbilityTypeHealthPackBlock;
extern s_tag_struct equipmentAbilityTypeJetPackBlock_struct_definition;
extern s_tag_block_definition equipmentAbilityTypeJetPackBlock;
extern s_tag_struct equipmentAbilityPartCowCatcherBlock_struct_definition;
extern s_tag_block_definition equipmentAbilityPartCowCatcherBlock;
extern s_tag_struct equipmentAbilityTypeHologramBlock_struct_definition;
extern s_tag_block_definition equipmentAbilityTypeHologramBlock;
extern s_tag_struct equipmentAbilityTypeSpecialWeaponBlock_struct_definition;
extern s_tag_block_definition equipmentAbilityTypeSpecialWeaponBlock;
extern s_tag_struct equipmentAbilityTypeSpecialMoveBlock_struct_definition;
extern s_tag_block_definition equipmentAbilityTypeSpecialMoveBlock;
extern s_tag_struct equipmentAbilityTypeEngineerShieldsBlock_struct_definition;
extern s_tag_block_definition equipmentAbilityTypeEngineerShieldsBlock;
extern s_tag_struct equipmentAbilityTypeSprintBlock_struct_definition;
extern s_tag_block_definition equipmentAbilityTypeSprintBlock;
extern s_tag_struct equipmentAbilityTypeTeleporterBlock_struct_definition;
extern s_tag_block_definition equipmentAbilityTypeTeleporterBlock;
extern s_tag_struct equipmentAbilityTypeAutoTurretBlock_struct_definition;
extern s_tag_block_definition equipmentAbilityTypeAutoTurretBlock;
extern s_tag_struct equipmentAbilityTypeVisionModeBlock_struct_definition;
extern s_tag_block_definition equipmentAbilityTypeVisionModeBlock;
extern s_tag_struct equipmentAbilityTypeShieldProjectorBlock_struct_definition;
extern s_tag_block_definition equipmentAbilityTypeShieldProjectorBlock;
extern s_tag_struct equipmentAbilityTypeProjectileCollectorBlock_struct_definition;
extern s_tag_block_definition equipmentAbilityTypeProjectileCollectorBlock;
extern s_tag_struct equipmentAbilityTypeRemoteStrikeBlock_struct_definition;
extern s_tag_block_definition equipmentAbilityTypeRemoteStrikeBlock;
extern s_tag_struct equipmentAbilityTypeEquipmentHackerBlock_struct_definition;
extern s_tag_block_definition equipmentAbilityTypeEquipmentHackerBlock;
extern s_tag_struct equipmentHackerDrainLevel_struct_definition;
extern s_tag_block_definition equipmentHackerDrainLevel;
extern s_tag_struct equipmentAbilityTypeRemoteVehicleBlock_struct_definition;
extern s_tag_block_definition equipmentAbilityTypeRemoteVehicleBlock;
extern s_tag_struct equipmentAbilityTypeSuicideBombBlock_struct_definition;
extern s_tag_block_definition equipmentAbilityTypeSuicideBombBlock;
extern s_tag_struct equipmentAbilityTypeActiveShieldBlock_struct_definition;
extern s_tag_block_definition equipmentAbilityTypeActiveShieldBlock;
extern s_tag_struct EquipmentSoundRTPCBlock_struct_definition;
extern s_tag_block_definition EquipmentSoundRTPCBlock;
extern s_tag_struct EquipmentSoundSweetenerBlock_struct_definition;
extern s_tag_block_definition EquipmentSoundSweetenerBlock;

constexpr unsigned long EQUIPMENT_TAG = 'eqip';

extern s_tag_block_definition equipment_block;
extern s_tag_group equipment_group;
} // namespace blofeld

