#pragma once

namespace blofeld
{

extern s_tag_struct aim_assist_struct_struct_definition;
extern s_tag_struct WeaponBarrelIronSightsStruct_struct_definition;
extern s_tag_struct weapon_interface_struct_struct_definition;
extern s_tag_struct weapon_shared_interface_struct_struct_definition;
extern s_tag_struct weapon_trigger_autofire_struct_struct_definition;
extern s_tag_struct weapon_trigger_charging_struct_struct_definition;
extern s_tag_struct weapon_barrel_firing_parameters_struct_struct_definition;
extern s_tag_struct weapon_barrel_firing_error_struct_struct_definition;
extern s_tag_struct weapon_barrel_projectile_accuracy_penalty_struct_struct_definition;
extern s_tag_struct weapon_barrel_projectile_accuracy_penalty_function_struct_struct_definition;
extern s_tag_struct weapon_barrel_damage_effect_struct_struct_definition;

extern s_tag_struct melee_damage_parameters_block_struct_definition;
extern s_tag_block_definition melee_damage_parameters_block;
extern s_tag_struct globalAimAssistBlock_struct_definition;
extern s_tag_block_definition globalAimAssistBlock;
extern s_tag_struct globalAimSwimBlock_struct_definition;
extern s_tag_block_definition globalAimSwimBlock;
extern s_tag_struct weapon_first_person_interface_block_struct_definition;
extern s_tag_block_definition weapon_first_person_interface_block;
extern s_tag_struct magazines_struct_definition;
extern s_tag_block_definition magazines;
extern s_tag_struct magazine_objects_struct_definition;
extern s_tag_block_definition magazine_objects;
extern s_tag_struct weapon_triggers_struct_definition;
extern s_tag_block_definition weapon_triggers;
extern s_tag_struct weapon_trigger_charging_fire_fraction_struct_definition;
extern s_tag_block_definition weapon_trigger_charging_fire_fraction;
extern s_tag_struct weapon_barrels_struct_definition;
extern s_tag_block_definition weapon_barrels;
extern s_tag_struct projectileDistributionCustomVector_struct_definition;
extern s_tag_block_definition projectileDistributionCustomVector;
extern s_tag_struct weapon_barrel_first_person_offset_block_struct_definition;
extern s_tag_block_definition weapon_barrel_first_person_offset_block;
extern s_tag_struct barrel_firing_effect_block_struct_definition;
extern s_tag_block_definition barrel_firing_effect_block;
extern s_tag_struct weaponScaleshotStruct_struct_definition;
extern s_tag_block_definition weaponScaleshotStruct;
extern s_tag_struct weaponScaleshotLevelStruct_struct_definition;
extern s_tag_block_definition weaponScaleshotLevelStruct;
extern s_tag_struct weapon_screen_effect_block_struct_definition;
extern s_tag_block_definition weapon_screen_effect_block;
extern s_tag_struct WeaponSoundRTPCBlock_struct_definition;
extern s_tag_block_definition WeaponSoundRTPCBlock;
extern s_tag_struct WeaponSoundSweetenerBlock_struct_definition;
extern s_tag_block_definition WeaponSoundSweetenerBlock;

constexpr unsigned long WEAPON_TAG = 'weap';

extern s_tag_block_definition weapon_block;
extern s_tag_group weapon_group;
} // namespace blofeld

