#pragma once

namespace blofeld
{



	extern s_tag_block_definition g_compositeTag_block;
	extern s_tag_block_definition CompositeAxisDefinition_block;
	extern s_tag_struct_definition CompositeAxisDefinition_block_struct_definition; // CompositeAxisDefinition_block
	extern s_tag_block_definition CompositeDeadZoneDefinition_block;
	extern s_tag_struct_definition CompositeDeadZoneDefinition_block_struct_definition; // CompositeDeadZoneDefinition_block
	extern s_tag_block_definition CompositeEntryDefinition_block;
	extern s_tag_struct_definition CompositeEntryDefinition_block_struct_definition; // CompositeEntryDefinition_block
	extern s_tag_block_definition CompositeEntryValueDefinition_block;
	extern s_tag_struct_definition CompositeEntryValueDefinition_block_struct_definition; // CompositeEntryValueDefinition_block
	extern s_tag_block_definition CompositePhaseSetDefinition_block;
	extern s_tag_struct_definition CompositePhaseSetDefinition_block_struct_definition; // CompositePhaseSetDefinition_block
	extern s_tag_block_definition SyncKeyBlock_block;
	extern s_tag_struct_definition SyncKeyBlock_block_struct_definition; // SyncKeyBlock_block
	extern s_tag_block_definition StringBlock_block;
	extern s_tag_struct_definition StringBlock_block_struct_definition; // StringBlock_block

	extern s_tag_struct_definition g_compositeTag_struct;

	extern s_string_list_definition CompositeAxisFlags;



} // namespace blofeld

