#pragma once

namespace blofeld
{



	extern s_tag_block_definition game_engine_player_traits_block;
	extern s_tag_struct_definition game_engine_player_traits_block_struct_definition; // game_engine_player_traits_block
	extern s_tag_block_definition player_traits_vitality_block;
	extern s_tag_struct_definition player_traits_vitality_block_struct_definition; // player_traits_vitality_block
	extern s_tag_block_definition player_traits_weapons_block;
	extern s_tag_struct_definition player_traits_weapons_block_struct_definition; // player_traits_weapons_block
	extern s_tag_block_definition player_traits_movement_block;
	extern s_tag_struct_definition player_traits_movement_block_struct_definition; // player_traits_movement_block
	extern s_tag_block_definition player_traits_appearance_block;
	extern s_tag_struct_definition player_traits_appearance_block_struct_definition; // player_traits_appearance_block
	extern s_tag_block_definition player_traits_sensors_block;
	extern s_tag_struct_definition player_traits_sensors_block_struct_definition; // player_traits_sensors_block
	extern s_tag_block_definition game_engine_player_traits_list_block;
	extern s_tag_struct_definition game_engine_player_traits_list_block_struct_definition; // game_engine_player_traits_list_block


	extern s_string_list_definition player_trait_bool_enum;
	extern s_string_list_definition player_trait_initial_grenade_count_enum;
	extern s_string_list_definition player_trait_infinite_ammo_enum;
	extern s_string_list_definition player_trait_equipment_usage_enum;
	extern s_string_list_definition player_trait_vehicle_usage;
	extern s_string_list_definition player_trait_double_jump;
	extern s_string_list_definition player_trait_active_camo;
	extern s_string_list_definition player_trait_waypoint;
	extern s_string_list_definition player_trait_aura;
	extern s_string_list_definition player_trait_motion_tracker;
	extern s_string_list_definition player_trait_motion_tracker_range;
	extern s_string_list_definition player_trait_powerup_cancellation_enum;
	extern s_string_list_definition player_traits_vitality_float_flags;
	extern s_string_list_definition player_traits_weapons_float_flags;
	extern s_string_list_definition player_traits_movement_float_flags;
	extern s_string_list_definition player_traits_sensors_float_flags;



} // namespace blofeld

