#pragma once

namespace blofeld
{

	constexpr unsigned long GAMEENGINEFIREFIGHTVARIANTTAG_TAG = 'ffgt';

	extern s_tag_struct_definition GameEngineFirefightVariantTag_block_struct;
	extern s_tag_block_definition GameEngineFirefightVariantTag_block;
	extern s_tag_group GameEngineFirefightVariantTag_group;
	constexpr unsigned long GAME_ENGINE_GLOBALS_TAG = 'gegl';

	extern s_tag_group game_engine_globals_group;
	constexpr unsigned long GAME_ENGINE_SETTINGS_DEFINITION_TAG = 'wezr';

	extern s_tag_group game_engine_settings_definition_group;

	extern s_tag_struct_definition game_engine_miscellaneous_options_block_block_struct;
	extern s_tag_block_definition game_engine_miscellaneous_options_block_block;
	extern s_tag_struct_definition game_engine_prototype_options_block_block_struct;
	extern s_tag_block_definition game_engine_prototype_options_block_block;
	extern s_tag_struct_definition game_engine_respawn_options_block_block_struct;
	extern s_tag_block_definition game_engine_respawn_options_block_block;
	extern s_tag_struct_definition game_engine_social_options_block_block_struct;
	extern s_tag_block_definition game_engine_social_options_block_block;
	extern s_tag_struct_definition game_engine_map_override_options_block_block_struct;
	extern s_tag_block_definition game_engine_map_override_options_block_block;
	extern s_tag_struct_definition game_engine_team_options_block_block_struct;
	extern s_tag_block_definition game_engine_team_options_block_block;
	extern s_tag_struct_definition gameEngineOrdnanceOptionsBlock_block_struct;
	extern s_tag_block_definition gameEngineOrdnanceOptionsBlock_block;
	extern s_tag_struct_definition GameEngineFirefightWavePropertiesBlock_block_struct;
	extern s_tag_block_definition GameEngineFirefightWavePropertiesBlock_block;
	extern s_tag_struct_definition GameEngineFirefightPlayerGoalPropertiesBlock_block_struct;
	extern s_tag_block_definition GameEngineFirefightPlayerGoalPropertiesBlock_block;
	extern s_tag_block_definition game_engine_globals_block_block;
	extern s_tag_struct_definition game_engine_ai_traits_list_block_block_struct;
	extern s_tag_block_definition game_engine_ai_traits_list_block_block;
	extern s_tag_struct_definition game_engine_sandbox_variant_block_block_struct;
	extern s_tag_block_definition game_engine_sandbox_variant_block_block;
	extern s_tag_struct_definition game_engine_survival_set_properties_block_block_struct;
	extern s_tag_block_definition game_engine_survival_set_properties_block_block;
	extern s_tag_struct_definition survival_wave_squad_block_block_struct;
	extern s_tag_block_definition survival_wave_squad_block_block;
	extern s_tag_struct_definition game_engine_survival_round_properties_block_block_struct;
	extern s_tag_block_definition game_engine_survival_round_properties_block_block;
	extern s_tag_struct_definition game_engine_survival_custom_skull_block_block_struct;
	extern s_tag_block_definition game_engine_survival_custom_skull_block_block;
	extern s_tag_struct_definition game_engine_survival_variant_block_block_struct;
	extern s_tag_block_definition game_engine_survival_variant_block_block;
	extern s_tag_struct_definition GameEngineFirefightVariantShellBlock_block_struct;
	extern s_tag_block_definition GameEngineFirefightVariantShellBlock_block;
	extern s_tag_struct_definition game_engine_campaign_variant_block_block_struct;
	extern s_tag_block_definition game_engine_campaign_variant_block_block;
	extern s_tag_block_definition game_engine_settings_definition_block_block;

	extern s_tag_struct_definition game_engine_team_options_team_block_struct_definition;
	extern s_tag_array_definition game_engine_team_options_team_block_array;
	extern s_tag_struct_definition gameEngineFirefightVariantDefinition_struct_definition;
	extern s_tag_struct_definition game_engine_globals_struct_definition_struct_definition; // tag group
	extern s_tag_struct_definition game_engine_settings_definition_struct_definition_struct_definition; // tag group
	extern s_tag_struct_definition game_engine_ai_traits_struct_struct_definition;
	extern s_tag_struct_definition game_engine_survival_wave_properties_struct_struct_definition;
	extern s_tag_struct_definition game_engine_survival_bonus_wave_properties_struct_struct_definition;

	extern c_versioned_string_list ai_trait_vision_settings_strings;
	extern s_string_list_definition ai_trait_vision_settings;
	extern c_versioned_string_list ai_trait_sound_settings_strings;
	extern s_string_list_definition ai_trait_sound_settings;
	extern c_versioned_string_list ai_trait_luck_settings_strings;
	extern s_string_list_definition ai_trait_luck_settings;
	extern c_versioned_string_list global_ai_trait_weapon_settings_strings;
	extern s_string_list_definition global_ai_trait_weapon_settings;
	extern c_versioned_string_list ai_trait_grenade_settings_strings;
	extern s_string_list_definition ai_trait_grenade_settings;
	extern c_versioned_string_list game_engine_miscellaneous_options_flags_strings;
	extern s_string_list_definition game_engine_miscellaneous_options_flags;
	extern c_versioned_string_list mosh_difficulty_strings;
	extern s_string_list_definition mosh_difficulty;
	extern c_versioned_string_list game_engine_respawn_options_flags_strings;
	extern s_string_list_definition game_engine_respawn_options_flags;
	extern c_versioned_string_list game_engine_social_options_flags_strings;
	extern s_string_list_definition game_engine_social_options_flags;
	extern c_versioned_string_list game_engine_map_override_options_flags_strings;
	extern s_string_list_definition game_engine_map_override_options_flags;
	extern c_versioned_string_list game_engine_team_options_team_flags_strings;
	extern s_string_list_definition game_engine_team_options_team_flags;
	extern c_versioned_string_list game_engine_team_options_player_model_choice_strings;
	extern s_string_list_definition game_engine_team_options_player_model_choice;
	extern c_versioned_string_list game_engine_team_options_model_override_type_strings;
	extern s_string_list_definition game_engine_team_options_model_override_type;
	extern c_versioned_string_list game_engine_team_options_designator_switch_type_strings;
	extern s_string_list_definition game_engine_team_options_designator_switch_type;
	extern c_versioned_string_list gameEngineOrdnanceOptionsFlags_strings;
	extern s_string_list_definition gameEngineOrdnanceOptionsFlags;
	extern c_versioned_string_list sandbox_flags_strings;
	extern s_string_list_definition sandbox_flags;
	extern c_versioned_string_list sandbox_editing_mode_strings;
	extern s_string_list_definition sandbox_editing_mode;
	extern c_versioned_string_list sandbox_respawn_time_strings;
	extern s_string_list_definition sandbox_respawn_time;
	extern c_versioned_string_list skull_flags_strings;
	extern s_string_list_definition skull_flags;
	extern c_versioned_string_list survival_wave_squad_advance_type_enum_strings;
	extern s_string_list_definition survival_wave_squad_advance_type_enum;
	extern c_versioned_string_list survival_wave_properties_flags_strings;
	extern s_string_list_definition survival_wave_properties_flags;
	extern c_versioned_string_list game_engine_survival_variant_flags_strings;
	extern s_string_list_definition game_engine_survival_variant_flags;
	extern c_versioned_string_list FirefightWaveDeliveryMethod_strings;
	extern s_string_list_definition FirefightWaveDeliveryMethod;
	extern c_versioned_string_list FirefightWaveDifficulty_strings;
	extern s_string_list_definition FirefightWaveDifficulty;
	extern c_versioned_string_list FirefightGoal_strings;
	extern s_string_list_definition FirefightGoal;
	extern c_versioned_string_list GameEnginePlayerGoalFlags_strings;
	extern s_string_list_definition GameEnginePlayerGoalFlags;
	extern c_versioned_string_list GameEngineFirefightVariantFlags_strings;
	extern s_string_list_definition GameEngineFirefightVariantFlags;
	extern c_versioned_string_list game_engine_settings_flags_strings;
	extern s_string_list_definition game_engine_settings_flags;

	extern s_tag_reference_definition GameEngineFirefightVariantReference;

} // namespace blofeld

