#pragma once

namespace blofeld
{



	constexpr unsigned long GAMEENGINEFIREFIGHTVARIANTTAG_TAG = 'ffgt';
	extern s_tag_group GameEngineFirefightVariantTag_group; // GameEngineFirefightVariantTag_block
	extern s_tag_block_definition GameEngineFirefightVariantTag_block;
	extern s_tag_struct_definition GameEngineFirefightVariantTag_block_struct_definition; // GameEngineFirefightVariantTag_block

	constexpr unsigned long GAME_ENGINE_GLOBALS_TAG = 'gegl';
	extern s_tag_group game_engine_globals_group; // game_engine_globals_block

	constexpr unsigned long GAME_ENGINE_SETTINGS_DEFINITION_TAG = 'wezr';
	extern s_tag_group game_engine_settings_definition_group; // game_engine_settings_definition_block


	extern s_tag_block_definition game_engine_globals_block;
	extern s_tag_block_definition game_engine_settings_definition_block;
	extern s_tag_block_definition game_engine_miscellaneous_options_block;
	extern s_tag_struct_definition game_engine_miscellaneous_options_block_struct_definition; // game_engine_miscellaneous_options_block
	extern s_tag_block_definition game_engine_prototype_options_block;
	extern s_tag_struct_definition game_engine_prototype_options_block_struct_definition; // game_engine_prototype_options_block
	extern s_tag_block_definition game_engine_respawn_options_block;
	extern s_tag_struct_definition game_engine_respawn_options_block_struct_definition; // game_engine_respawn_options_block
	extern s_tag_block_definition game_engine_social_options_block;
	extern s_tag_struct_definition game_engine_social_options_block_struct_definition; // game_engine_social_options_block
	extern s_tag_block_definition game_engine_map_override_options_block;
	extern s_tag_struct_definition game_engine_map_override_options_block_struct_definition; // game_engine_map_override_options_block
	extern s_tag_block_definition game_engine_team_options_block;
	extern s_tag_struct_definition game_engine_team_options_block_struct_definition; // game_engine_team_options_block
	extern s_tag_block_definition gameEngineOrdnanceOptionsBlock_block;
	extern s_tag_struct_definition gameEngineOrdnanceOptionsBlock_block_struct_definition; // gameEngineOrdnanceOptionsBlock_block
	extern s_tag_block_definition GameEngineFirefightPlayerGoalPropertiesBlock_block;
	extern s_tag_struct_definition GameEngineFirefightPlayerGoalPropertiesBlock_block_struct_definition; // GameEngineFirefightPlayerGoalPropertiesBlock_block
	extern s_tag_block_definition GameEngineFirefightWavePropertiesBlock_block;
	extern s_tag_struct_definition GameEngineFirefightWavePropertiesBlock_block_struct_definition; // GameEngineFirefightWavePropertiesBlock_block
	extern s_tag_block_definition game_engine_ai_traits_list_block;
	extern s_tag_struct_definition game_engine_ai_traits_list_block_struct_definition; // game_engine_ai_traits_list_block
	extern s_tag_block_definition game_engine_sandbox_variant_block;
	extern s_tag_struct_definition game_engine_sandbox_variant_block_struct_definition; // game_engine_sandbox_variant_block
	extern s_tag_block_definition game_engine_survival_variant_block;
	extern s_tag_struct_definition game_engine_survival_variant_block_struct_definition; // game_engine_survival_variant_block
	extern s_tag_block_definition game_engine_survival_set_properties_block;
	extern s_tag_struct_definition game_engine_survival_set_properties_block_struct_definition; // game_engine_survival_set_properties_block
	extern s_tag_block_definition game_engine_survival_round_properties_block;
	extern s_tag_struct_definition game_engine_survival_round_properties_block_struct_definition; // game_engine_survival_round_properties_block
	extern s_tag_block_definition survival_wave_squad_block;
	extern s_tag_struct_definition survival_wave_squad_block_struct_definition; // survival_wave_squad_block
	extern s_tag_block_definition game_engine_survival_custom_skull_block;
	extern s_tag_struct_definition game_engine_survival_custom_skull_block_struct_definition; // game_engine_survival_custom_skull_block
	extern s_tag_block_definition GameEngineFirefightVariantShellBlock_block;
	extern s_tag_struct_definition GameEngineFirefightVariantShellBlock_block_struct_definition; // GameEngineFirefightVariantShellBlock_block
	extern s_tag_block_definition game_engine_campaign_variant_block;
	extern s_tag_struct_definition game_engine_campaign_variant_block_struct_definition; // game_engine_campaign_variant_block

	extern s_tag_struct_definition game_engine_team_options_team_block_array_struct_definition;
	extern s_tag_array_definition game_engine_team_options_team_block_array;
	extern s_tag_struct_definition game_engine_globals_struct_definition; // tag group
	extern s_tag_struct_definition game_engine_settings_definition_struct_definition; // tag group
	extern s_tag_struct_definition gameEngineFirefightVariantDefinition;
	extern s_tag_struct_definition game_engine_ai_traits_struct;
	extern s_tag_struct_definition game_engine_survival_wave_properties_struct;
	extern s_tag_struct_definition game_engine_survival_bonus_wave_properties_struct;

	extern s_string_list_definition ai_trait_vision_settings;
	extern s_string_list_definition ai_trait_sound_settings;
	extern s_string_list_definition ai_trait_luck_settings;
	extern s_string_list_definition global_ai_trait_weapon_settings;
	extern s_string_list_definition ai_trait_grenade_settings;
	extern s_string_list_definition game_engine_miscellaneous_options_flags;
	extern s_string_list_definition mosh_difficulty;
	extern s_string_list_definition game_engine_respawn_options_flags;
	extern s_string_list_definition game_engine_social_options_flags;
	extern s_string_list_definition game_engine_map_override_options_flags;
	extern s_string_list_definition game_engine_team_options_team_flags;
	extern s_string_list_definition game_engine_team_options_player_model_choice;
	extern s_string_list_definition game_engine_team_options_model_override_type;
	extern s_string_list_definition game_engine_team_options_designator_switch_type;
	extern s_string_list_definition gameEngineOrdnanceOptionsFlags;
	extern s_string_list_definition sandbox_flags;
	extern s_string_list_definition sandbox_editing_mode;
	extern s_string_list_definition sandbox_respawn_time;
	extern s_string_list_definition skull_flags;
	extern s_string_list_definition survival_wave_squad_advance_type_enum;
	extern s_string_list_definition survival_wave_properties_flags;
	extern s_string_list_definition game_engine_survival_variant_flags;
	extern s_string_list_definition FirefightWaveDeliveryMethod;
	extern s_string_list_definition FirefightWaveDifficulty;
	extern s_string_list_definition FirefightGoal;
	extern s_string_list_definition GameEnginePlayerGoalFlags;
	extern s_string_list_definition GameEngineFirefightVariantFlags;
	extern s_string_list_definition game_engine_settings_flags;
	extern s_string_list_definition game_engine_survival_generator_count;

	extern s_tag_reference_definition GameEngineFirefightVariantReference;



} // namespace blofeld

