#pragma once

namespace blofeld
{



	extern s_tag_block_definition game_engine_event_block;
	extern s_tag_struct_definition game_engine_event_block_struct_definition; // game_engine_event_block
	extern s_tag_block_definition sound_response_definition_block;
	extern s_tag_struct_definition sound_response_definition_block_struct_definition; // sound_response_definition_block

	extern s_tag_struct_definition sound_response_definition_struct;

	extern s_string_list_definition game_engine_event_flags_definition;
	extern s_string_list_definition game_engine_event_audience_enum_definition;
	extern s_string_list_definition game_engine_event_input_enum_definition;
	extern s_string_list_definition game_engine_event_splitscreen_suppression_enum_definition;
	extern s_string_list_definition game_engine_sound_response_flags_definition;



} // namespace blofeld

