#pragma once

namespace blofeld
{

	extern s_tag_struct_definition unit_trick_definition_block_block_struct;
	extern s_tag_block_definition unit_trick_definition_block_block;


	extern c_versioned_string_list unit_trick_activation_type_enum_strings;
	extern s_string_list_definition unit_trick_activation_type_enum;
	extern c_versioned_string_list unit_trick_velocity_preservation_mode_enum_strings;
	extern s_string_list_definition unit_trick_velocity_preservation_mode_enum;
	extern c_versioned_string_list unit_trick_flags_strings;
	extern s_string_list_definition unit_trick_flags;

} // namespace blofeld

