#pragma once

namespace blofeld
{

namespace macaque
{

	constexpr unsigned long GAME_COMPLETION_REWARDS_GLOBALS_TAG = 'gcrg';
	extern s_tag_group game_completion_rewards_globals_group; // game_completion_rewards_globals_block


	extern s_tag_block_definition game_completion_rewards_globals_block;
	extern s_tag_block_definition game_completion_rewards_difficulty_block;
	extern s_tag_struct_definition game_completion_rewards_difficulty_block_struct_definition; // game_completion_rewards_difficulty_block
	extern s_tag_block_definition game_completion_rewards_definition_block;
	extern s_tag_struct_definition game_completion_rewards_definition_block_struct_definition; // game_completion_rewards_definition_block
	extern s_tag_block_definition game_completion_rewards_falloff_point_block;
	extern s_tag_struct_definition game_completion_rewards_falloff_point_block_struct_definition; // game_completion_rewards_falloff_point_block
	extern s_tag_block_definition game_completion_rewards_multiplayer_block;
	extern s_tag_struct_definition game_completion_rewards_multiplayer_block_struct_definition; // game_completion_rewards_multiplayer_block

	extern s_tag_struct_definition game_completion_rewards_globals_struct_definition; // tag group

} // namespace macaque

} // namespace blofeld

