#pragma once

namespace blofeld
{

namespace macaque
{

	extern s_tag_block_definition purchase_prerequisite_grade_definition_block;
	extern s_tag_struct_definition purchase_prerequisite_grade_definition_block_struct_definition; // purchase_prerequisite_grade_definition_block
	extern s_tag_block_definition purchase_prerequisite_commendation_definition_block;
	extern s_tag_struct_definition purchase_prerequisite_commendation_definition_block_struct_definition; // purchase_prerequisite_commendation_definition_block
	extern s_tag_block_definition PurchasePrerequisitePurchasedAppearanceItemDefinitionBlock_block;
	extern s_tag_struct_definition PurchasePrerequisitePurchasedAppearanceItemDefinitionBlock_block_struct_definition; // PurchasePrerequisitePurchasedAppearanceItemDefinitionBlock_block
	extern s_tag_block_definition PurchasePrerequisitePurchasedLoadoutItemDefinitionBlock_block;
	extern s_tag_struct_definition PurchasePrerequisitePurchasedLoadoutItemDefinitionBlock_block_struct_definition; // PurchasePrerequisitePurchasedLoadoutItemDefinitionBlock_block
	extern s_tag_block_definition PurchasePrerequisitePurchasedOrdnanceItemDefinitionBlock_block;
	extern s_tag_struct_definition PurchasePrerequisitePurchasedOrdnanceItemDefinitionBlock_block_struct_definition; // PurchasePrerequisitePurchasedOrdnanceItemDefinitionBlock_block
	extern s_tag_block_definition purchase_prerequisites_unlockable_definition_block;
	extern s_tag_struct_definition purchase_prerequisites_unlockable_definition_block_struct_definition; // purchase_prerequisites_unlockable_definition_block
	extern s_tag_block_definition purchase_prerequisites_offer_definition_block;
	extern s_tag_struct_definition purchase_prerequisites_offer_definition_block_struct_definition; // purchase_prerequisites_offer_definition_block

	extern s_tag_struct_definition PurchasePrerequisitesUnifiedDefinitionBlock;
	extern s_tag_struct_definition PurchaseAppearanceDefinitionReferenceStruct;
	extern s_tag_struct_definition PurchaseLoadoutDefinitionReferenceStruct;
	extern s_tag_struct_definition PurchaseOrdnanceDefinitionReferenceStruct;

	extern c_versioned_string_list MarketplaceOfferTypeEnum_strings;
	extern s_string_list_definition MarketplaceOfferTypeEnum;

} // namespace macaque

} // namespace blofeld

