#pragma once

namespace blofeld
{

extern s_tag_struct cheap_particle_emitter_struct_definition_struct_definition;
extern s_tag_struct cheap_particle_type_library_struct_definition_struct_definition;
extern s_tag_struct cheap_particle_scalar_object_function_struct_struct_definition;

extern s_tag_struct cheap_particle_type_block_struct_definition;
extern s_tag_block_definition cheap_particle_type_block;
extern s_tag_struct cheap_particle_bitmap_reference_block_struct_definition;
extern s_tag_block_definition cheap_particle_bitmap_reference_block;
extern s_tag_struct cheapParticleTurbulenceTypeBlock_struct_definition;
extern s_tag_block_definition cheapParticleTurbulenceTypeBlock;

constexpr unsigned long CHEAP_PARTICLE_EMITTER_TAG = 'cpem';

extern s_tag_block_definition cheap_particle_emitter_block;
extern s_tag_group cheap_particle_emitter_group;
constexpr unsigned long CHEAP_PARTICLE_TYPE_LIBRARY_TAG = 'cptl';

extern s_tag_block_definition cheap_particle_type_library_block;
extern s_tag_group cheap_particle_type_library_group;
} // namespace blofeld

