#pragma once

namespace blofeld
{

constexpr unsigned long EFFECT_TAG = 'effe';

extern s_tag_struct effect_block_struct;
extern s_tag_block_definition effect_block;
extern s_tag_group effect_group;

extern s_tag_struct effect_locations_block_block_struct;
extern s_tag_block_definition effect_locations_block_block;
extern s_tag_struct effect_event_block_block_struct;
extern s_tag_block_definition effect_event_block_block;
extern s_tag_struct effect_part_block_block_struct;
extern s_tag_block_definition effect_part_block_block;
extern s_tag_struct effect_accelerations_block_block_struct;
extern s_tag_block_definition effect_accelerations_block_block;
extern s_tag_struct effect_looping_sound_block_block_struct;
extern s_tag_block_definition effect_looping_sound_block_block;
extern s_tag_struct effect_conical_distribution_block_block_struct;
extern s_tag_block_definition effect_conical_distribution_block_block;


} // namespace blofeld

