#pragma once

namespace blofeld
{

extern s_tag_struct effect_globals_struct_definition_struct_definition;

extern s_tag_struct effect_component_holdbacks_block_struct_definition;
extern s_tag_block_definition effect_component_holdbacks_block;
extern s_tag_struct effect_component_holdback_block_struct_definition;
extern s_tag_block_definition effect_component_holdback_block;
extern s_tag_struct effect_global_spawn_effects_block_struct_definition;
extern s_tag_block_definition effect_global_spawn_effects_block;

constexpr unsigned long EFFECT_GLOBALS_TAG = 'effg';

extern s_tag_block_definition effect_globals_block;
extern s_tag_group effect_globals_group;
} // namespace blofeld

