#pragma once

namespace blofeld
{

extern s_tag_struct model_dissolve_definition_struct_definition_struct_definition;

extern s_tag_struct modelDissolveDataBlock_struct_definition;
extern s_tag_block_definition modelDissolveDataBlock;
extern s_tag_struct modelDissolvePerRegionTimeOffsetBlock_struct_definition;
extern s_tag_block_definition modelDissolvePerRegionTimeOffsetBlock;

constexpr unsigned long MODEL_DISSOLVE_DEFINITION_TAG = 'mdsv';

extern s_tag_block_definition model_dissolve_definition_block;
extern s_tag_group model_dissolve_definition_group;
} // namespace blofeld

