#pragma once

namespace blofeld
{


extern s_tag_struct particle_system_definition_block_new_block_struct;
extern s_tag_block_definition particle_system_definition_block_new_block;
extern s_tag_struct particle_system_emitter_definition_block_block_struct;
extern s_tag_block_definition particle_system_emitter_definition_block_block;
extern s_tag_struct emitterGlobalForceBlock_block_struct;
extern s_tag_block_definition emitterGlobalForceBlock_block;
extern s_tag_struct emitterClipSphereBlock_block_struct;
extern s_tag_block_definition emitterClipSphereBlock_block;
extern s_tag_struct gpu_property_block_block_struct;
extern s_tag_block_definition gpu_property_block_block;
extern s_tag_struct gpu_function_block_block_struct;
extern s_tag_block_definition gpu_function_block_block;
extern s_tag_struct gpu_color_block_block_struct;
extern s_tag_block_definition gpu_color_block_block;

extern s_tag_struct gpu_property_function_color_struct_struct_definition;

} // namespace blofeld

