#pragma once

namespace blofeld
{



extern s_tag_struct particle_property_real_point3d_struct_new_struct_definition;
extern s_tag_struct particle_property_real_euler_angles2d_struct_new_struct_definition;
extern s_tag_struct particle_property_scalar_struct_new_struct_definition;
extern s_tag_struct particle_property_real_vector3d_struct_new_struct_definition;
extern s_tag_struct particle_property_color_struct_new_struct_definition;

} // namespace blofeld

