#pragma once

namespace blofeld
{

extern s_tag_struct tracer_system_struct_definition_struct_definition;
extern s_tag_struct tracerProperty_real_Struct_struct_definition;
extern s_tag_struct tracerProperty_real_vector3d_Struct_struct_definition;
extern s_tag_struct tracerProperty_real_point2d_Struct_struct_definition;
extern s_tag_struct tracerProperty_real_rgb_color_Struct_struct_definition;

extern s_tag_struct tracerDefinitionBlock_struct_definition;
extern s_tag_block_definition tracerDefinitionBlock;

constexpr unsigned long TRACER_SYSTEM_TAG = 'trac';

extern s_tag_block_definition tracer_system_block;
extern s_tag_group tracer_system_group;
} // namespace blofeld

