#pragma once

namespace blofeld
{

extern s_tag_struct g_compositeTag_struct_struct_definition;

extern s_tag_block_definition g_compositeTag;
extern s_tag_struct CompositeAxisDefinition_struct_definition;
extern s_tag_block_definition CompositeAxisDefinition;
extern s_tag_struct CompositeDeadZoneDefinition_struct_definition;
extern s_tag_block_definition CompositeDeadZoneDefinition;
extern s_tag_struct CompositeEntryDefinition_struct_definition;
extern s_tag_block_definition CompositeEntryDefinition;
extern s_tag_struct CompositeEntryValueDefinition_struct_definition;
extern s_tag_block_definition CompositeEntryValueDefinition;
extern s_tag_struct CompositePhaseSetDefinition_struct_definition;
extern s_tag_block_definition CompositePhaseSetDefinition;
extern s_tag_struct SyncKeyBlock_struct_definition;
extern s_tag_block_definition SyncKeyBlock;
extern s_tag_struct StringBlock_struct_definition;
extern s_tag_block_definition StringBlock;

} // namespace blofeld

