#pragma once

namespace blofeld
{


extern s_tag_struct global_damage_info_block_block_struct;
extern s_tag_block_definition global_damage_info_block_block;
extern s_tag_struct global_damage_section_block_block_struct;
extern s_tag_block_definition global_damage_section_block_block;
extern s_tag_struct instantaneous_damage_repsonse_block_block_struct;
extern s_tag_block_definition instantaneous_damage_repsonse_block_block;
extern s_tag_struct global_damage_nodes_block_block_struct;
extern s_tag_block_definition global_damage_nodes_block_block;
extern s_tag_struct damage_seat_info_block_block_struct;
extern s_tag_block_definition damage_seat_info_block_block;
extern s_tag_struct damage_seat_region_setting_block_block_struct;
extern s_tag_block_definition damage_seat_region_setting_block_block;
extern s_tag_struct damage_constraint_info_block_block_struct;
extern s_tag_block_definition damage_constraint_info_block_block;
extern s_tag_struct new_global_damage_section_block_block_struct;
extern s_tag_block_definition new_global_damage_section_block_block;
extern s_tag_struct damage_section_recharge_speed_curve_block_block_struct;
extern s_tag_block_definition damage_section_recharge_speed_curve_block_block;
extern s_tag_struct damage_section_segmented_recharge_fraction_block_struct;
extern s_tag_block_definition damage_section_segmented_recharge_fraction_block;
extern s_tag_struct new_instantaneous_damage_response_block_block_struct;
extern s_tag_block_definition new_instantaneous_damage_response_block_block;
extern s_tag_struct damage_response_region_transition_block_block_struct;
extern s_tag_block_definition damage_response_region_transition_block_block;
extern s_tag_struct damage_transfer_block_block_struct;
extern s_tag_block_definition damage_transfer_block_block;
extern s_tag_struct seat_ejection_block_block_struct;
extern s_tag_block_definition seat_ejection_block_block;
extern s_tag_struct damage_section_rendering_paramters_block_struct;
extern s_tag_block_definition damage_section_rendering_paramters_block;

extern s_tag_struct damage_body_parameters_struct_struct_definition;
extern s_tag_struct damage_shield_parameters_struct_struct_definition;
extern s_tag_struct instantaneous_response_damage_effect_struct_struct_definition;
extern s_tag_struct instantaneous_response_damage_effect_marker_struct_struct_definition;
extern s_tag_struct model_damage_info_struct_struct_definition;

} // namespace blofeld

