#pragma once

namespace blofeld
{

extern s_tag_struct model_target_lock_on_data_struct_struct_definition;

extern s_tag_struct model_variant_block_struct_definition;
extern s_tag_block_definition model_variant_block;
extern s_tag_struct model_variant_region_block_struct_definition;
extern s_tag_block_definition model_variant_region_block;
extern s_tag_struct model_variant_permutation_block_struct_definition;
extern s_tag_block_definition model_variant_permutation_block;
extern s_tag_struct model_variant_state_block_struct_definition;
extern s_tag_block_definition model_variant_state_block;
extern s_tag_struct model_variant_object_block_struct_definition;
extern s_tag_block_definition model_variant_object_block;
extern s_tag_struct model_variant_muted_node_block_struct_definition;
extern s_tag_block_definition model_variant_muted_node_block;
extern s_tag_struct region_name_block_struct_definition;
extern s_tag_block_definition region_name_block;
extern s_tag_struct global_model_instance_group_block_struct_definition;
extern s_tag_block_definition global_model_instance_group_block;
extern s_tag_struct model_instance_group_member_block_struct_definition;
extern s_tag_block_definition model_instance_group_member_block;
extern s_tag_struct model_material_block_new_struct_definition;
extern s_tag_block_definition model_material_block_new;
extern s_tag_struct model_target_block_old_struct_definition;
extern s_tag_block_definition model_target_block_old;
extern s_tag_struct model_target_block_new_struct_definition;
extern s_tag_block_definition model_target_block_new;
extern s_tag_struct model_region_block_struct_definition;
extern s_tag_block_definition model_region_block;
extern s_tag_struct model_permutation_block_struct_definition;
extern s_tag_block_definition model_permutation_block;
extern s_tag_struct model_node_block_struct_definition;
extern s_tag_block_definition model_node_block;
extern s_tag_struct model_game_mode_render_model_override_struct_definition;
extern s_tag_block_definition model_game_mode_render_model_override;
extern s_tag_struct model_self_shadow_region_cast_override_block_struct_definition;
extern s_tag_block_definition model_self_shadow_region_cast_override_block;
extern s_tag_struct model_self_shadow_region_receive_override_block_struct_definition;
extern s_tag_block_definition model_self_shadow_region_receive_override_block;
extern s_tag_struct model_occlusion_sphere_block_struct_definition;
extern s_tag_block_definition model_occlusion_sphere_block;

constexpr unsigned long MODEL_TAG = 'hlmt';

extern s_tag_block_definition model_block;
extern s_tag_group model_group;
} // namespace blofeld

