#include "blamtoozle-private-pch.h"

c_blamtoozle_tag_block_index_custom_search_definition::c_blamtoozle_tag_block_index_custom_search_definition(c_blamtoozle_tag_definition_manager& _tag_definition_manager) :
	tag_definition_manager(_tag_definition_manager)
{
}

c_blamtoozle_tag_block_index_custom_search_definition::~c_blamtoozle_tag_block_index_custom_search_definition()
{
}
