#pragma once

namespace blofeld
{



	extern s_tag_block_definition breakable_surface_key_table_block;
	extern s_tag_struct_definition breakable_surface_key_table_block_struct_definition; // breakable_surface_key_table_block
	extern s_tag_block_definition soft_surfaces_definition_block;
	extern s_tag_struct_definition soft_surfaces_definition_block_struct_definition; // soft_surfaces_definition_block
	extern s_tag_block_definition structure_soft_ceiling_block;
	extern s_tag_struct_definition structure_soft_ceiling_block_struct_definition; // structure_soft_ceiling_block
	extern s_tag_block_definition structure_soft_ceiling_triangle_block;
	extern s_tag_struct_definition structure_soft_ceiling_triangle_block_struct_definition; // structure_soft_ceiling_triangle_block
	extern s_tag_block_definition structure_water_groups_block;
	extern s_tag_struct_definition structure_water_groups_block_struct_definition; // structure_water_groups_block
	extern s_tag_block_definition structure_water_instances_block;
	extern s_tag_struct_definition structure_water_instances_block_struct_definition; // structure_water_instances_block
	extern s_tag_block_definition structure_water_instance_planes_block;
	extern s_tag_struct_definition structure_water_instance_planes_block_struct_definition; // structure_water_instance_planes_block
	extern s_tag_block_definition structure_water_instance_debug_triangles_block;
	extern s_tag_struct_definition structure_water_instance_debug_triangles_block_struct_definition; // structure_water_instance_debug_triangles_block

	extern s_tag_struct_definition global_structure_physics_struct;
	extern s_tag_struct_definition global_structure_physics_design_struct;

	extern s_string_list_definition soft_ceiling_type_enum;



} // namespace blofeld

