#pragma once

namespace blofeld
{

	extern const char* part_flags_strings[];
	extern s_string_list_definition part_flags;
	extern const char* tessellation_mode_definition_strings[];
	extern s_string_list_definition tessellation_mode_definition;
	extern const char* specialized_render_definition_strings[];
	extern s_string_list_definition specialized_render_definition;
	extern const char* compression_flags_strings[];
	extern s_string_list_definition compression_flags;
	extern const char* mesh_flags_strings[];
	extern s_string_list_definition mesh_flags;
	extern const char* mesh_vertex_type_definition_strings[];
	extern s_string_list_definition mesh_vertex_type_definition;
	extern const char* mesh_transfer_vertex_type_definition_strings[];
	extern s_string_list_definition mesh_transfer_vertex_type_definition;
	extern const char* mesh_lighting_policy_type_definition_strings[];
	extern s_string_list_definition mesh_lighting_policy_type_definition;
	extern const char* mesh_index_buffer_type_definition_strings[];
	extern s_string_list_definition mesh_index_buffer_type_definition;
	extern const char* per_mesh_raw_data_flags_strings[];
	extern s_string_list_definition per_mesh_raw_data_flags;
	extern const char* render_geometry_user_data_type_definition_strings[];
	extern s_string_list_definition render_geometry_user_data_type_definition;
	extern const char* render_geometry_flags_strings[];
	extern s_string_list_definition render_geometry_flags;


	extern s_tag_struct global_mesh_block_block_struct;
	extern s_tag_block_definition global_mesh_block_block;
	extern s_tag_struct part_block_block_struct;
	extern s_tag_block_definition part_block_block;
	extern s_tag_struct subpart_block_block_struct;
	extern s_tag_block_definition subpart_block_block;
	extern s_tag_struct global_instance_bucket_block_block_struct;
	extern s_tag_block_definition global_instance_bucket_block_block;
	extern s_tag_struct instance_index_word_block_block_struct;
	extern s_tag_block_definition instance_index_word_block_block;
	extern s_tag_struct indices_word_block_block_struct;
	extern s_tag_block_definition indices_word_block_block;
	extern s_tag_struct vertexKeyBlock_block_struct;
	extern s_tag_block_definition vertexKeyBlock_block;
	extern s_tag_struct PCAMeshIndexBlock_block_struct;
	extern s_tag_block_definition PCAMeshIndexBlock_block;
	extern s_tag_struct compression_info_block_block_struct;
	extern s_tag_block_definition compression_info_block_block;
	extern s_tag_struct sorting_position_block_block_struct;
	extern s_tag_block_definition sorting_position_block_block;
	extern s_tag_struct user_data_block_block_struct;
	extern s_tag_block_definition user_data_block_block;
	extern s_tag_struct per_mesh_raw_data_block_block_struct;
	extern s_tag_block_definition per_mesh_raw_data_block_block;
	extern s_tag_struct raw_vertex_block_block_struct;
	extern s_tag_block_definition raw_vertex_block_block;
	extern s_tag_struct indices_dword_block_block_struct;
	extern s_tag_block_definition indices_dword_block_block;
	extern s_tag_struct raw_water_block_block_struct;
	extern s_tag_block_definition raw_water_block_block;
	extern s_tag_struct raw_water_append_block_block_struct;
	extern s_tag_block_definition raw_water_append_block_block;
	extern s_tag_struct raw_imposter_brdf_block_block_struct;
	extern s_tag_block_definition raw_imposter_brdf_block_block;
	extern s_tag_struct raw_instance_imposter_block_block_struct;
	extern s_tag_block_definition raw_instance_imposter_block_block;
	extern s_tag_struct raw_blendshape_block_block_struct;
	extern s_tag_block_definition raw_blendshape_block_block;
	extern s_tag_struct per_mesh_node_map_block_block_struct;
	extern s_tag_block_definition per_mesh_node_map_block_block;
	extern s_tag_struct node_map_byte_block_block_struct;
	extern s_tag_block_definition node_map_byte_block_block;
	extern s_tag_struct per_mesh_subpart_visibility_block_block_struct;
	extern s_tag_block_definition per_mesh_subpart_visibility_block_block;
	extern s_tag_struct per_mesh_prt_data_block_block_struct;
	extern s_tag_block_definition per_mesh_prt_data_block_block;
	extern s_tag_struct per_instance_prt_data_block_block_struct;
	extern s_tag_block_definition per_instance_prt_data_block_block;
	extern s_tag_struct per_instance_lightmap_texcoords_block_block_struct;
	extern s_tag_block_definition per_instance_lightmap_texcoords_block_block;
	extern s_tag_struct raw_texcoord_block_block_struct;
	extern s_tag_block_definition raw_texcoord_block_block;
	extern s_tag_struct water_bounding_box_block_block_struct;
	extern s_tag_block_definition water_bounding_box_block_block;
	extern s_tag_struct render_geometry_pvs_data_block_block_struct;
	extern s_tag_block_definition render_geometry_pvs_data_block_block;
	extern s_tag_struct render_geometry_pvs_data_visibility_value_block_block_struct;
	extern s_tag_block_definition render_geometry_pvs_data_visibility_value_block_block;
	extern s_tag_struct render_geometry_pvs_data_visibility_index_block_block_struct;
	extern s_tag_block_definition render_geometry_pvs_data_visibility_index_block_block;
	extern s_tag_struct shapeNameBlock_block_struct;
	extern s_tag_block_definition shapeNameBlock_block;

	extern s_tag_struct global_render_geometry_struct_struct_definition;
	extern s_tag_struct global_render_geometry_user_data_header_struct_struct_definition;

} // namespace blofeld

