#pragma once

namespace blofeld
{

extern s_tag_struct global_render_geometry_struct_struct_definition;
extern s_tag_struct global_render_geometry_user_data_header_struct_struct_definition;

extern s_tag_struct global_mesh_block_struct_definition;
extern s_tag_block_definition global_mesh_block;
extern s_tag_struct part_block_struct_definition;
extern s_tag_block_definition part_block;
extern s_tag_struct subpart_block_struct_definition;
extern s_tag_block_definition subpart_block;
extern s_tag_struct global_instance_bucket_block_struct_definition;
extern s_tag_block_definition global_instance_bucket_block;
extern s_tag_struct instance_index_word_block_struct_definition;
extern s_tag_block_definition instance_index_word_block;
extern s_tag_struct indices_word_block_struct_definition;
extern s_tag_block_definition indices_word_block;
extern s_tag_struct vertexKeyBlock_struct_definition;
extern s_tag_block_definition vertexKeyBlock;
extern s_tag_struct PCAMeshIndexBlock_struct_definition;
extern s_tag_block_definition PCAMeshIndexBlock;
extern s_tag_struct compression_info_block_struct_definition;
extern s_tag_block_definition compression_info_block;
extern s_tag_struct sorting_position_block_struct_definition;
extern s_tag_block_definition sorting_position_block;
extern s_tag_struct user_data_block_struct_definition;
extern s_tag_block_definition user_data_block;
extern s_tag_struct per_mesh_raw_data_block_struct_definition;
extern s_tag_block_definition per_mesh_raw_data_block;
extern s_tag_struct raw_vertex_block_struct_definition;
extern s_tag_block_definition raw_vertex_block;
extern s_tag_struct indices_dword_block_struct_definition;
extern s_tag_block_definition indices_dword_block;
extern s_tag_struct raw_water_block_struct_definition;
extern s_tag_block_definition raw_water_block;
extern s_tag_struct raw_water_append_block_struct_definition;
extern s_tag_block_definition raw_water_append_block;
extern s_tag_struct raw_imposter_brdf_block_struct_definition;
extern s_tag_block_definition raw_imposter_brdf_block;
extern s_tag_struct raw_instance_imposter_block_struct_definition;
extern s_tag_block_definition raw_instance_imposter_block;
extern s_tag_struct raw_blendshape_block_struct_definition;
extern s_tag_block_definition raw_blendshape_block;
extern s_tag_struct per_mesh_node_map_block_struct_definition;
extern s_tag_block_definition per_mesh_node_map_block;
extern s_tag_struct node_map_byte_block_struct_definition;
extern s_tag_block_definition node_map_byte_block;
extern s_tag_struct per_mesh_subpart_visibility_block_struct_definition;
extern s_tag_block_definition per_mesh_subpart_visibility_block;
extern s_tag_struct per_mesh_prt_data_block_struct_definition;
extern s_tag_block_definition per_mesh_prt_data_block;
extern s_tag_struct per_instance_prt_data_block_struct_definition;
extern s_tag_block_definition per_instance_prt_data_block;
extern s_tag_struct per_instance_lightmap_texcoords_block_struct_definition;
extern s_tag_block_definition per_instance_lightmap_texcoords_block;
extern s_tag_struct raw_texcoord_block_struct_definition;
extern s_tag_block_definition raw_texcoord_block;
extern s_tag_struct water_bounding_box_block_struct_definition;
extern s_tag_block_definition water_bounding_box_block;
extern s_tag_struct render_geometry_pvs_data_block_struct_definition;
extern s_tag_block_definition render_geometry_pvs_data_block;
extern s_tag_struct render_geometry_pvs_data_visibility_value_block_struct_definition;
extern s_tag_block_definition render_geometry_pvs_data_visibility_value_block;
extern s_tag_struct render_geometry_pvs_data_visibility_index_block_struct_definition;
extern s_tag_block_definition render_geometry_pvs_data_visibility_index_block;
extern s_tag_struct shapeNameBlock_struct_definition;
extern s_tag_block_definition shapeNameBlock;

} // namespace blofeld

