#pragma once

namespace blofeld
{

extern s_tag_struct player_enlistment_globals_definition_struct_definition_struct_definition;

extern s_tag_struct playerEnlistmentDefinitionBlock_struct_definition;
extern s_tag_block_definition playerEnlistmentDefinitionBlock;

constexpr unsigned long PLAYER_ENLISTMENT_GLOBALS_DEFINITION_TAG = 'pegd';

extern s_tag_block_definition player_enlistment_globals_definition_block;
extern s_tag_group player_enlistment_globals_definition_group;
} // namespace blofeld

