#pragma once

namespace blofeld
{

	constexpr unsigned long STYLE_SHEET_LIST_TAG = 'uiss';

	extern s_tag_group style_sheet_list_group;

	extern s_tag_struct_definition UserInterfaceStyleSheetFontIdBlock_block_struct;
	extern s_tag_block_definition UserInterfaceStyleSheetFontIdBlock_block;
	extern s_tag_struct_definition UserInterfaceStyleSheetTextCaseBlock_block_struct;
	extern s_tag_block_definition UserInterfaceStyleSheetTextCaseBlock_block;
	extern s_tag_struct_definition UserInterfaceStyleSheetJustificationBlock_block_struct;
	extern s_tag_block_definition UserInterfaceStyleSheetJustificationBlock_block;
	extern s_tag_struct_definition UserInterfaceStyleSheetAlignmentBlock_block_struct;
	extern s_tag_block_definition UserInterfaceStyleSheetAlignmentBlock_block;
	extern s_tag_struct_definition UserInterfaceStyleSheetScaleBlock_block_struct;
	extern s_tag_block_definition UserInterfaceStyleSheetScaleBlock_block;
	extern s_tag_struct_definition UserInterfaceStyleSheetFixedHeightBlock_block_struct;
	extern s_tag_block_definition UserInterfaceStyleSheetFixedHeightBlock_block;
	extern s_tag_struct_definition UserInterfaceStyleSheetsFontBlock_block_struct;
	extern s_tag_block_definition UserInterfaceStyleSheetsFontBlock_block;
	extern s_tag_struct_definition UserInterfaceStyleSheetDropShadowStyleBlock_block_struct;
	extern s_tag_block_definition UserInterfaceStyleSheetDropShadowStyleBlock_block;
	extern s_tag_struct_definition UserInterfaceStyleSheetColorBlock_block_struct;
	extern s_tag_block_definition UserInterfaceStyleSheetColorBlock_block;
	extern s_tag_struct_definition UserInterfaceStyleSheetsVisualBlock_block_struct;
	extern s_tag_block_definition UserInterfaceStyleSheetsVisualBlock_block;
	extern s_tag_struct_definition UserInterfaceStyleSheetLanguagesBlock_block_struct;
	extern s_tag_block_definition UserInterfaceStyleSheetLanguagesBlock_block;
	extern s_tag_struct_definition UserInterfaceStyleSheetGradientBlock_block_struct;
	extern s_tag_block_definition UserInterfaceStyleSheetGradientBlock_block;
	extern s_tag_struct_definition UserInterfaceStyleSheetDropshadowBlock_block_struct;
	extern s_tag_block_definition UserInterfaceStyleSheetDropshadowBlock_block;
	extern s_tag_struct_definition UserInterfaceStyleSheetOuterGlowBlock_block_struct;
	extern s_tag_block_definition UserInterfaceStyleSheetOuterGlowBlock_block;
	extern s_tag_block_definition style_sheet_list_block_block;

	extern s_tag_struct_definition style_sheet_list_struct_definition_struct_definition; // tag group

	extern c_versioned_string_list text_case_enum_strings;
	extern s_string_list_definition text_case_enum;
	extern c_versioned_string_list justification_enum_strings;
	extern s_string_list_definition justification_enum;
	extern c_versioned_string_list alignment_enum_strings;
	extern s_string_list_definition alignment_enum;
	extern c_versioned_string_list drop_shadow_style_enum_strings;
	extern s_string_list_definition drop_shadow_style_enum;
	extern c_versioned_string_list style_sheet_language_enum_definition_strings;
	extern s_string_list_definition style_sheet_language_enum_definition;
	extern c_versioned_string_list gradient_shape_enum_strings;
	extern s_string_list_definition gradient_shape_enum;

	extern s_tag_reference_definition style_sheets_global_reference;

} // namespace blofeld

