#pragma once

namespace blofeld
{

extern s_tag_struct game_completion_rewards_globals_struct_definition_struct_definition;

extern s_tag_struct game_completion_rewards_difficulty_block_struct_definition;
extern s_tag_block_definition game_completion_rewards_difficulty_block;
extern s_tag_struct game_completion_rewards_definition_block_struct_definition;
extern s_tag_block_definition game_completion_rewards_definition_block;
extern s_tag_struct game_completion_rewards_falloff_point_block_struct_definition;
extern s_tag_block_definition game_completion_rewards_falloff_point_block;
extern s_tag_struct game_completion_rewards_multiplayer_block_struct_definition;
extern s_tag_block_definition game_completion_rewards_multiplayer_block;

constexpr unsigned long GAME_COMPLETION_REWARDS_GLOBALS_TAG = 'gcrg';

extern s_tag_block_definition game_completion_rewards_globals_block;
extern s_tag_group game_completion_rewards_globals_group;
} // namespace blofeld

