#pragma once

namespace blofeld
{


	constexpr unsigned long GAME_COMPLETION_REWARDS_GLOBALS_TAG = 'gcrg';

	extern s_tag_group game_completion_rewards_globals_group;

	extern s_tag_block_definition game_completion_rewards_globals_block_block;
	extern s_tag_struct game_completion_rewards_difficulty_block_block_struct;
	extern s_tag_block_definition game_completion_rewards_difficulty_block_block;
	extern s_tag_struct game_completion_rewards_definition_block_block_struct;
	extern s_tag_block_definition game_completion_rewards_definition_block_block;
	extern s_tag_struct game_completion_rewards_falloff_point_block_block_struct;
	extern s_tag_block_definition game_completion_rewards_falloff_point_block_block;
	extern s_tag_struct game_completion_rewards_multiplayer_block_block_struct;
	extern s_tag_block_definition game_completion_rewards_multiplayer_block_block;

	extern s_tag_struct game_completion_rewards_globals_struct_definition_struct_definition; // tag group

} // namespace blofeld

