#pragma once

namespace blofeld
{

extern s_tag_struct cookie_purchase_globals_struct_definition_struct_definition;
extern s_tag_struct PurchasePlayerAppearanceStruct_struct_definition;
extern s_tag_struct PurchasePlayerLoadoutStruct_struct_definition;
extern s_tag_struct PurchasePlayerOrdnanceStruct_struct_definition;

extern s_tag_struct CookiePurchaseFamilyAppearanceDefinitionBlock_struct_definition;
extern s_tag_block_definition CookiePurchaseFamilyAppearanceDefinitionBlock;
extern s_tag_struct CookiePurchaseAppearanceDefinitionReferenceBlock_struct_definition;
extern s_tag_block_definition CookiePurchaseAppearanceDefinitionReferenceBlock;
extern s_tag_struct CookiePurchaseFamilyLoadoutDefinitionBlock_struct_definition;
extern s_tag_block_definition CookiePurchaseFamilyLoadoutDefinitionBlock;
extern s_tag_struct CookiePurchaseLoadoutDefinitionReferenceBlock_struct_definition;
extern s_tag_block_definition CookiePurchaseLoadoutDefinitionReferenceBlock;
extern s_tag_struct CookiePurchaseFamilyOrdnanceDefinitionBlock_struct_definition;
extern s_tag_block_definition CookiePurchaseFamilyOrdnanceDefinitionBlock;
extern s_tag_struct CookiePurchaseOrdnanceDefinitionReferenceBlock_struct_definition;
extern s_tag_block_definition CookiePurchaseOrdnanceDefinitionReferenceBlock;
extern s_tag_struct CookiePurchaseAppearanceDefinitionBlock_struct_definition;
extern s_tag_block_definition CookiePurchaseAppearanceDefinitionBlock;
extern s_tag_struct purchase_player_appearance_effect_model_permutation_block_struct_definition;
extern s_tag_block_definition purchase_player_appearance_effect_model_permutation_block;
extern s_tag_struct purchase_player_appearance_effect_non_model_permutation_block_struct_definition;
extern s_tag_block_definition purchase_player_appearance_effect_non_model_permutation_block;
extern s_tag_struct purchase_player_appearance_effect_visor_tint_block_struct_definition;
extern s_tag_block_definition purchase_player_appearance_effect_visor_tint_block;
extern s_tag_struct purchase_player_appearance_effect_emblem_index_block_struct_definition;
extern s_tag_block_definition purchase_player_appearance_effect_emblem_index_block;
extern s_tag_struct PurchasePlayerAppearancePoseBlock_struct_definition;
extern s_tag_block_definition PurchasePlayerAppearancePoseBlock;
extern s_tag_struct CookiePurchaseExternalUnlockableBlockAppearanceDefinition_struct_definition;
extern s_tag_block_definition CookiePurchaseExternalUnlockableBlockAppearanceDefinition;
extern s_tag_struct CookiePurchaseLoadoutDefinitionBlock_struct_definition;
extern s_tag_block_definition CookiePurchaseLoadoutDefinitionBlock;
extern s_tag_struct purchase_player_item_block_struct_definition;
extern s_tag_block_definition purchase_player_item_block;
extern s_tag_struct purchase_player_app_block_struct_definition;
extern s_tag_block_definition purchase_player_app_block;
extern s_tag_struct purchase_player_loadout_slot_block_struct_definition;
extern s_tag_block_definition purchase_player_loadout_slot_block;
extern s_tag_struct purchase_player_app_mod_slot_block_struct_definition;
extern s_tag_block_definition purchase_player_app_mod_slot_block;
extern s_tag_struct CookiePurchaseExternalUnlockableBlockLoadoutDefinition_struct_definition;
extern s_tag_block_definition CookiePurchaseExternalUnlockableBlockLoadoutDefinition;
extern s_tag_struct CookiePurchaseOrdnanceDefinitionBlock_struct_definition;
extern s_tag_block_definition CookiePurchaseOrdnanceDefinitionBlock;
extern s_tag_struct PurchasePlayerOrdnanceItemBlock_struct_definition;
extern s_tag_block_definition PurchasePlayerOrdnanceItemBlock;
extern s_tag_struct PurchasePlayerOrdnanceSlotBlock_struct_definition;
extern s_tag_block_definition PurchasePlayerOrdnanceSlotBlock;
extern s_tag_struct CookiePurchaseExternalUnlockableBlockOrdnanceDefinition_struct_definition;
extern s_tag_block_definition CookiePurchaseExternalUnlockableBlockOrdnanceDefinition;

constexpr unsigned long COOKIE_PURCHASE_GLOBALS_TAG = 'cpgd';

extern s_tag_block_definition cookie_purchase_globals_block;
extern s_tag_group cookie_purchase_globals_group;
} // namespace blofeld

