#pragma once

namespace blofeld
{

	constexpr unsigned long COOKIE_PURCHASE_GLOBALS_TAG = 'cpgd';

	extern s_tag_group cookie_purchase_globals_group;

	extern s_tag_struct_definition CookiePurchaseAppearanceDefinitionReferenceBlock_block_struct;
	extern s_tag_block_definition CookiePurchaseAppearanceDefinitionReferenceBlock_block;
	extern s_tag_struct_definition CookiePurchaseFamilyAppearanceDefinitionBlock_block_struct;
	extern s_tag_block_definition CookiePurchaseFamilyAppearanceDefinitionBlock_block;
	extern s_tag_struct_definition CookiePurchaseLoadoutDefinitionReferenceBlock_block_struct;
	extern s_tag_block_definition CookiePurchaseLoadoutDefinitionReferenceBlock_block;
	extern s_tag_struct_definition CookiePurchaseFamilyLoadoutDefinitionBlock_block_struct;
	extern s_tag_block_definition CookiePurchaseFamilyLoadoutDefinitionBlock_block;
	extern s_tag_struct_definition CookiePurchaseOrdnanceDefinitionReferenceBlock_block_struct;
	extern s_tag_block_definition CookiePurchaseOrdnanceDefinitionReferenceBlock_block;
	extern s_tag_struct_definition CookiePurchaseFamilyOrdnanceDefinitionBlock_block_struct;
	extern s_tag_block_definition CookiePurchaseFamilyOrdnanceDefinitionBlock_block;
	extern s_tag_struct_definition purchase_player_appearance_effect_model_permutation_block_block_struct;
	extern s_tag_block_definition purchase_player_appearance_effect_model_permutation_block_block;
	extern s_tag_struct_definition purchase_player_appearance_effect_non_model_permutation_block_block_struct;
	extern s_tag_block_definition purchase_player_appearance_effect_non_model_permutation_block_block;
	extern s_tag_struct_definition purchase_player_appearance_effect_visor_tint_block_block_struct;
	extern s_tag_block_definition purchase_player_appearance_effect_visor_tint_block_block;
	extern s_tag_struct_definition purchase_player_appearance_effect_emblem_index_block_block_struct;
	extern s_tag_block_definition purchase_player_appearance_effect_emblem_index_block_block;
	extern s_tag_struct_definition PurchasePlayerAppearancePoseBlock_block_struct;
	extern s_tag_block_definition PurchasePlayerAppearancePoseBlock_block;
	extern s_tag_struct_definition CookiePurchaseAppearanceDefinitionBlock_block_struct;
	extern s_tag_block_definition CookiePurchaseAppearanceDefinitionBlock_block;
	extern s_tag_struct_definition CookiePurchaseExternalUnlockableBlockAppearanceDefinition_block_struct;
	extern s_tag_block_definition CookiePurchaseExternalUnlockableBlockAppearanceDefinition_block;
	extern s_tag_struct_definition purchase_player_item_block_block_struct;
	extern s_tag_block_definition purchase_player_item_block_block;
	extern s_tag_struct_definition purchase_player_app_block_block_struct;
	extern s_tag_block_definition purchase_player_app_block_block;
	extern s_tag_struct_definition purchase_player_loadout_slot_block_block_struct;
	extern s_tag_block_definition purchase_player_loadout_slot_block_block;
	extern s_tag_struct_definition purchase_player_app_mod_slot_block_block_struct;
	extern s_tag_block_definition purchase_player_app_mod_slot_block_block;
	extern s_tag_struct_definition CookiePurchaseLoadoutDefinitionBlock_block_struct;
	extern s_tag_block_definition CookiePurchaseLoadoutDefinitionBlock_block;
	extern s_tag_struct_definition CookiePurchaseExternalUnlockableBlockLoadoutDefinition_block_struct;
	extern s_tag_block_definition CookiePurchaseExternalUnlockableBlockLoadoutDefinition_block;
	extern s_tag_struct_definition PurchasePlayerOrdnanceItemBlock_block_struct;
	extern s_tag_block_definition PurchasePlayerOrdnanceItemBlock_block;
	extern s_tag_struct_definition PurchasePlayerOrdnanceSlotBlock_block_struct;
	extern s_tag_block_definition PurchasePlayerOrdnanceSlotBlock_block;
	extern s_tag_struct_definition CookiePurchaseOrdnanceDefinitionBlock_block_struct;
	extern s_tag_block_definition CookiePurchaseOrdnanceDefinitionBlock_block;
	extern s_tag_struct_definition CookiePurchaseExternalUnlockableBlockOrdnanceDefinition_block_struct;
	extern s_tag_block_definition CookiePurchaseExternalUnlockableBlockOrdnanceDefinition_block;
	extern s_tag_block_definition cookie_purchase_globals_block_block;

	extern s_tag_struct_definition cookie_purchase_globals_struct_definition_struct_definition; // tag group
	extern s_tag_struct_definition PurchasePlayerAppearanceStruct_struct_definition;
	extern s_tag_struct_definition PurchasePlayerLoadoutStruct_struct_definition;
	extern s_tag_struct_definition PurchasePlayerOrdnanceStruct_struct_definition;

	extern const char* player_model_customization_area_enum_strings[];
	extern s_string_list_definition player_model_customization_area_enum;
	extern const char* player_non_model_customization_area_enum_strings[];
	extern s_string_list_definition player_non_model_customization_area_enum;
	extern const char* player_item_category_enum_strings[];
	extern s_string_list_definition player_item_category_enum;
	extern const char* cookie_purchase_flags_strings[];
	extern s_string_list_definition cookie_purchase_flags;

} // namespace blofeld

