#pragma once

namespace blofeld
{

extern s_tag_struct PurchaseAppearanceDefinitionReferenceStruct_struct_definition;
extern s_tag_struct PurchaseLoadoutDefinitionReferenceStruct_struct_definition;
extern s_tag_struct PurchaseOrdnanceDefinitionReferenceStruct_struct_definition;
extern s_tag_struct PurchasePrerequisitesUnifiedDefinitionBlock_struct_definition;

extern s_tag_struct purchase_prerequisite_grade_definition_block_struct_definition;
extern s_tag_block_definition purchase_prerequisite_grade_definition_block;
extern s_tag_struct purchase_prerequisite_commendation_definition_block_struct_definition;
extern s_tag_block_definition purchase_prerequisite_commendation_definition_block;
extern s_tag_struct PurchasePrerequisitePurchasedAppearanceItemDefinitionBlock_struct_definition;
extern s_tag_block_definition PurchasePrerequisitePurchasedAppearanceItemDefinitionBlock;
extern s_tag_struct PurchasePrerequisitePurchasedLoadoutItemDefinitionBlock_struct_definition;
extern s_tag_block_definition PurchasePrerequisitePurchasedLoadoutItemDefinitionBlock;
extern s_tag_struct PurchasePrerequisitePurchasedOrdnanceItemDefinitionBlock_struct_definition;
extern s_tag_block_definition PurchasePrerequisitePurchasedOrdnanceItemDefinitionBlock;
extern s_tag_struct purchase_prerequisites_unlockable_definition_block_struct_definition;
extern s_tag_block_definition purchase_prerequisites_unlockable_definition_block;
extern s_tag_struct purchase_prerequisites_offer_definition_block_struct_definition;
extern s_tag_block_definition purchase_prerequisites_offer_definition_block;

} // namespace blofeld

