#pragma once

namespace blofeld
{


extern s_tag_struct purchase_prerequisite_grade_definition_block_block_struct;
extern s_tag_block_definition purchase_prerequisite_grade_definition_block_block;
extern s_tag_struct purchase_prerequisite_commendation_definition_block_block_struct;
extern s_tag_block_definition purchase_prerequisite_commendation_definition_block_block;
extern s_tag_struct PurchasePrerequisitePurchasedAppearanceItemDefinitionBlock_block_struct;
extern s_tag_block_definition PurchasePrerequisitePurchasedAppearanceItemDefinitionBlock_block;
extern s_tag_struct PurchasePrerequisitePurchasedLoadoutItemDefinitionBlock_block_struct;
extern s_tag_block_definition PurchasePrerequisitePurchasedLoadoutItemDefinitionBlock_block;
extern s_tag_struct PurchasePrerequisitePurchasedOrdnanceItemDefinitionBlock_block_struct;
extern s_tag_block_definition PurchasePrerequisitePurchasedOrdnanceItemDefinitionBlock_block;
extern s_tag_struct purchase_prerequisites_unlockable_definition_block_block_struct;
extern s_tag_block_definition purchase_prerequisites_unlockable_definition_block_block;
extern s_tag_struct purchase_prerequisites_offer_definition_block_block_struct;
extern s_tag_block_definition purchase_prerequisites_offer_definition_block_block;

extern s_tag_struct PurchaseAppearanceDefinitionReferenceStruct_struct_definition;
extern s_tag_struct PurchaseLoadoutDefinitionReferenceStruct_struct_definition;
extern s_tag_struct PurchaseOrdnanceDefinitionReferenceStruct_struct_definition;
extern s_tag_struct PurchasePrerequisitesUnifiedDefinitionBlock_struct_definition;

} // namespace blofeld

