#pragma once

namespace blofeld
{

extern s_tag_struct biped_group_struct_definition;
extern s_tag_struct biped_leaping_data_struct_struct_definition;
extern s_tag_struct biped_vaulting_data_struct_struct_definition;
extern s_tag_struct biped_grab_biped_data_struct_struct_definition;
extern s_tag_struct biped_grab_object_data_struct_struct_definition;
extern s_tag_struct biped_ground_fitting_data_struct_struct_definition;
extern s_tag_struct BipedMovementHipLeaningStruct_struct_definition;

extern s_tag_struct biped_camera_height_block_struct_definition;
extern s_tag_block_definition biped_camera_height_block;
extern s_tag_struct biped_wall_proximity_block_struct_definition;
extern s_tag_block_definition biped_wall_proximity_block;
extern s_tag_struct biped_movement_gate_block_struct_definition;
extern s_tag_block_definition biped_movement_gate_block;
extern s_tag_struct contact_point_block_struct_definition;
extern s_tag_block_definition contact_point_block;
extern s_tag_struct biped_grab_object_animation_set_block_struct_definition;
extern s_tag_block_definition biped_grab_object_animation_set_block;
extern s_tag_struct BipedSoundRTPCBlock_struct_definition;
extern s_tag_block_definition BipedSoundRTPCBlock;
extern s_tag_struct BipedSoundSweetenerBlock_struct_definition;
extern s_tag_block_definition BipedSoundSweetenerBlock;
extern s_tag_struct BipedAimingJointFixupBlock_struct_definition;
extern s_tag_block_definition BipedAimingJointFixupBlock;

constexpr unsigned long BIPED_TAG = 'bipd';

extern s_tag_block_definition biped_block;
extern s_tag_group biped_group;
} // namespace blofeld

