#pragma once

namespace blofeld
{

extern s_tag_struct death_program_selector_struct_definition_struct_definition;

extern s_tag_struct death_program_special_block_struct_definition;
extern s_tag_block_definition death_program_special_block;
extern s_tag_struct death_program_damage_reporting_block_struct_definition;
extern s_tag_block_definition death_program_damage_reporting_block;
extern s_tag_struct death_program_velocity_gate_block_struct_definition;
extern s_tag_block_definition death_program_velocity_gate_block;

constexpr unsigned long DEATH_PROGRAM_SELECTOR_TAG = 'bdpd';

extern s_tag_block_definition death_program_selector_block;
extern s_tag_group death_program_selector_group;
} // namespace blofeld

