#include <blofeld-private-pch.h>

namespace blofeld
{

TAG_BLOCK(unit_screen_effect, 4)
{
	{ _field_tag_reference, "screen effect^" },
	{ _field_terminator },
};

TAG_BLOCK(unit_postures, MAXIMUM_POSTURES_PER_UNIT)
{
	{ _field_string_id, "name^" },
	{ _field_useless_pad },
	{ _field_real_vector_3d, "pill offset" },
	{ _field_terminator },
};

TAG_BLOCK(dialogue_variant, MAXIMUM_DIALOGUE_VARIANTS_PER_UNIT)
{
	{ _field_short_integer, "variant number#variant number to use this dialogue with (must match the suffix in the permutations on the unit\'s model)" },
	{ _field_pad, "BQCVEMF", 2 },
	{ _field_useless_pad },
	{ _field_tag_reference, "dialogue" },
	{ _field_terminator },
};

TAG_BLOCK(powered_seat, k_powered_seats_count)
{
	{ _field_real, "driver powerup time:seconds" },
	{ _field_real, "driver powerdown time:seconds" },
	{ _field_terminator },
};

TAG_BLOCK(unit_weapon, MAXIMUM_INITIAL_WEAPONS_PER_UNIT)
{
	{ _field_tag_reference, "weapon^" },
	{ _field_string_id, "variant name" },
	{ _field_long_enum, "position" },
	{ _field_real, "maximum firing cone angle:degrees#must be greater than zero for turret to fire" },
	{ _field_real, "minimum retarget time:seconds#minimum time before autoturret will change targets" },
	{ _field_real, "blind fire time:seconds#time after losing a target before turret stops blind firing" },
	{ _field_real, "lead fraction#0.0 = no lead, 1.0 = perfect lead" },
	{ _field_real_bounds, "engagement range:units#when non-zero, turret will not prioritize targets above or below this range" },
	{ _field_real, "proximity score multiplier#0.0 = no importance, 2.0 = things that are close are twice as important" },
	{ _field_real, "direction score multiplier#0.0 = no importance, 2.0 = things in front of you are twice as important" },
	{ _field_real, "attacker score multiplier#0.0 = no importance, 2.0 = things that attacked you last are twice as important" },
	{ _field_real, "targeting weight hologram#multiplier" },
	{ _field_real, "targeting weight auto turret#multiplier" },
	{ _field_real, "primary fire delay from idle:seconds" },
	{ _field_real, "secondary fire delay from idle:seconds" },
	{ _field_real, "caution duration:seconds#how long the turret stays alert after losing a target" },
	{ _field_real, "alert angular speed max:radians per second#0 = infinite" },
	{ _field_real, "idle angular speed max:radians per second#0 = infinite" },
	{ _field_real, "targeting yaw min:degrees#(-180 to 0) how far it can rotate past its initial rotation" },
	{ _field_real, "targeting yaw max:degrees#(0 to 180) how far it can rotate past its initial rotation" },
	{ _field_real, "targeting pitch min:degrees#(-180 to 0) how far it can rotate past its initial rotation" },
	{ _field_real, "targeting pitch max:degrees#(0 to 180) how far it can rotate past its initial rotation" },
	{ _field_real, "idle scanning yaw min:degrees#(-180 to 0) how far it will look around past its initial rotation" },
	{ _field_real, "idle scanning yaw max:degrees#(0 to 180) how far it will look around past its initial rotation" },
	{ _field_real, "idle scanning pitch min:degrees#(-180 to 0) how far it will look around past its initial rotation" },
	{ _field_real, "idle scanning pitch max:degrees#(0 to 180) how far it will look around past its initial rotation" },
	{ _field_real, "idle scanning min interest distance:world units#0 = infinite.  Idle scanning won\'t look at something that is closer than this distance" },
	{ _field_tag_reference, "alert mode effect#effect played on the turret when it goes into alert mode" },
	{ _field_custom },
	{ _field_string_id, "alert mode effect marker" },
	{ _field_string_id, "alert mode effect primary scale" },
	{ _field_string_id, "alert mode effect secondary scale" },
	{ _field_block, "sentry properties", &SentryPropertiesBlock_block },
	{ _field_real, "target camouflage threshold# 0 - 1 : target when players camo level falls below this threshold, full camo = 1" },
	{ _field_terminator },
};

TAG_BLOCK(SentryPropertiesBlock, 1)
{
	{ _field_byte_flags, "behavior" },
	{ _field_pad, "flagPad", 3 },
	{ _field_real, "sight cone angle:degrees#the cone that this sentry actually sees with; only used when scanning" },
	{ _field_real, "alert range:world units#how far the sentry can see (sentry will track enemies within alert range, but not necessarily fire)" },
	{ _field_real, "attack range:world units#how far the sentry can shoot" },
	{ _field_real, "attack range score multiplier#0 = No preference to targets in attack range; 0.5 = Targets in attack range get 50% score bonus" },
	{ _field_real, "light vehicle range scale#0 = Default of 1; 1.5 = light vehicles are attacked at 1.5x attack range" },
	{ _field_real, "heavy vehicle range scale#0 = Default of 1; 1.5 = light vehicles are attacked at 1.5x attack range" },
	{ _field_real, "flying vehicle range scale#0 = Default of 1; 1.5 = light vehicles are attacked at 1.5x attack range" },
	{ _field_real, "light vehicle score bonus#0 = No bonus preference for light vehicles; 0.5 = 50% score bonus for light vehicles" },
	{ _field_real, "heavy vehicle score bonus#0 = No bonus preference for heavy vehicles; 0.5 = 50% score bonus for heavy vehicles" },
	{ _field_real, "flying vehicle score bonus#0 = No bonus preference for flying vehicles; 0.5 = 50% score bonus for flying vehicles" },
	{ _field_real, "primary fire time:seconds#how long the sentry waits before using its primary weapon barrel" },
	{ _field_real, "secondary fire time:seconds#how long the sentry waits before using its secondary weapon barrel" },
	{ _field_tag_reference, "player entered alert range sound#1st person sound to play when targeted player enters sentry\'s alert range" },
	{ _field_tag_reference, "player exited alert range sound#1st person sound to play when targeted player leaves sentry\'s alert range" },
	{ _field_terminator },
};

TAG_BLOCK(unit_seat, MAXIMUM_SEATS_PER_UNIT_DEFINITION)
{
	{ _field_long_flags, "flags" },
	{ _field_long_flags, "secondary flags" },
	{ _field_old_string_id, "label^" },
	{ _field_custom },
	{ _field_old_string_id, "marker name" },
	{ _field_custom },
	{ _field_string_id, "entry marker(s) name" },
	{ _field_custom },
	{ _field_string_id, "ui marker name" },
	{ _field_string_id, "ui navpoint name" },
	{ _field_custom },
	{ _field_string_id, "boarding grenade marker" },
	{ _field_string_id, "boarding grenade string" },
	{ _field_string_id, "boarding melee string" },
	{ _field_string_id, "in-seat string" },
	{ _field_real_fraction, "ping scale#nathan is too lazy to make pings for each seat." },
	{ _field_useless_pad },
	{ _field_real, "turnover time:seconds#how much time it takes to evict a rider from a flipped vehicle" },
	{ _field_explanation, "seat acceleration spring" },
	{ _field_tag_reference, "seat acceleration" },
	{ _field_real, "AI scariness" },
	{ _field_enum, "ai seat type" },
	{ _field_short_block_index, "boarding seat" },
	{ _field_block, "additional boarding seats#additional seats to eject", &boarding_seat_block },
	{ _field_real_fraction, "listener interpolation factor#how far to interpolate listener position from camera to occupant\'s head" },
	{ _field_explanation, "speed dependant turn rates" },
	{ _field_real_bounds, "yaw rate bounds:degrees per second" },
	{ _field_real_bounds, "pitch rate bounds:degrees per second" },
	{ _field_real, "pitch interpolation time:seconds to interpolate#0 means use default 17" },
	{ _field_real, "min speed reference:world units/sec#Initial t is computed from velocity/(max speed - min speed)" },
	{ _field_real, "max speed reference" },
	{ _field_real, "speed exponent#if >0, t is then modified by raising to this exponent and result is used to linearly interpolate yaw/pitch rates" },
	{ _field_useless_pad },
	{ _field_explanation, "camera fields" },
	{ _field_struct, "unit camera" },
	{ _field_tag_reference, "hud screen reference" },
	{ _field_string_id, "enter seat string" },
	{ _field_useless_pad },
	{ _field_angle, "yaw minimum" },
	{ _field_angle, "yaw maximum" },
	{ _field_angle, "yaw minimum for AI operator#only applies when an NPC is considering using this seat" },
	{ _field_angle, "yaw maximum for AI operator#only applies when an NPC is considering using this seat" },
	{ _field_tag_reference, "built-in gunner" },
	{ _field_useless_pad },
	{ _field_explanation, "entry fields" },
	{ _field_real, "entry radius#how close to the entry marker a unit must be" },
	{ _field_angle, "entry marker cone angle#angle from marker forward the unit must be" },
	{ _field_angle, "entry marker facing angle#angle from unit facing the marker must be" },
	{ _field_real, "maximum relative velocity" },
	{ _field_useless_pad },
	{ _field_real, "open time:seconds" },
	{ _field_real, "close time:seconds" },
	{ _field_string_id, "open function name#creates an object function with this name that you can use to query the open state of this seat" },
	{ _field_string_id, "opening function name#goes from 0 to 1 over the course of opening and stays at 1 while open.  Drops to 0 immediately when closing starts" },
	{ _field_string_id, "closing function name#goes from 0 to 1 over the course of closing and stays at 1 while closed.  Drops to 0 immediately when opening starts" },
	{ _field_string_id, "invisible seat region" },
	{ _field_long_integer, "runtime invisible seat region index*" },
	{ _field_explanation, "seat death grab crate" },
	{ _field_tag_reference, "seat death grab crate" },
	{ _field_string_id, "Seat Selection String" },
	{ _field_real, "bailout velocity:wu/s#if exiting in bailout fashion, how much velocity to add in the entry_marker\'s forward direction" },
	{ _field_terminator },
};

TAG_BLOCK(boarding_seat, MAXIMUM_SEATS_PER_UNIT_DEFINITION)
{
	{ _field_short_block_index, "seat^" },
	{ _field_pad, "PAD", 2 },
	{ _field_terminator },
};

TAG_GROUP_INHERIT(unit, UNIT_TAG, object, OBJECT_TAG)
{
	{ _field_struct, "object" },
	{ _field_custom, "$$$ UNIT $$$" },
	{ _field_long_flags, "flags" },
	{ _field_long_flags, "flags2" },
	{ _field_enum, "default team" },
	{ _field_enum, "constant sound volume" },
	{ _field_tag_reference, "hologram unit reference" },
	{ _field_block, "campaign metagame bucket", &campaign_metagame_bucket_block },
	{ _field_block, "screen effects", &unit_screen_effect_block },
	{ _field_real, "camera stiffness" },
	{ _field_struct, "unit camera" },
	{ _field_explanation, "sync action camera fields" },
	{ _field_struct, "sync action camera" },
	{ _field_tag_reference, "assasination start damage response" },
	{ _field_tag_reference, "assassination weapon" },
	{ _field_custom },
	{ _field_string_id, "assassination weapon stow marker#the anchor we attach the knife to when we stow it" },
	{ _field_custom },
	{ _field_string_id, "assassination weapon out marker#the anchor we attach the knife to when we pull it out" },
	{ _field_custom },
	{ _field_string_id, "assassination weapon anchor marker#the marker on the knife that we anchor to the biped" },
	{ _field_tag_reference, "seat acceleration" },
	{ _field_custom, "pings" },
	{ _field_real, "soft ping threshold:[0,1]" },
	{ _field_real, "soft ping interrupt time:seconds" },
	{ _field_real, "hard ping threshold:[0,1]" },
	{ _field_real, "hard ping interrupt time:seconds" },
	{ _field_real, "soft death direction speed threshold:wu/s#moving faster than this means you will soft death in the movement direction. zero defaults to damage direction." },
	{ _field_real, "hard death threshold:[0,1]" },
	{ _field_real, "feign death threshold:[0,1]" },
	{ _field_real, "feign death time:seconds" },
	{ _field_real, "pain screen duration:seconds|CCBBAA#The duration of the pain function\n0 defaults to 0.5" },
	{ _field_real, "pain screen region fade out duration:seconds|CCBBAA#The time it takes to fade out a damage region that is no longer the most recent damage region to be hit" },
	{ _field_real_fraction, "pain screen region fade out weight threshold:[0,1]#The threshold weight below which the focus channel must fall before we can cross fade to another region." },
	{ _field_angle, "pain screen angle tolerance:degrees|CCBBAA#The tolerance angle between next and previous damage directions, below which we randomly vary the ping direction." },
	{ _field_angle, "pain screen angle randomness:degrees|CCBBAA#The maximum random angle to vary the incoming ping direction by if it\'s too close to the previous ping." },
	{ _field_real, "defensive screen duration:seconds#The duration of the defensive function\n0 defaults to 2.0" },
	{ _field_real_fraction, "defensive screen scrub fallback fraction:[0,1]#When receiving multiple pings, this is the min percentage of the defensive screen scrub value will fallback to." },
	{ _field_custom },
	{ _field_real, "distance of dive anim:world units#this must be set to tell the AI how far it should expect our dive animation to move us" },
	{ _field_real_fraction, "terminal velocity fall ratio#ratio of airborne_arc animation to switch off falling overlay" },
	{ _field_custom, "stun" },
	{ _field_real, "stun movement penalty:[0,1]#1.0 prevents moving while stunned" },
	{ _field_real, "stun turning penalty:[0,1]#1.0 prevents turning while stunned" },
	{ _field_real, "stun jumping penalty:[0,1]#1.0 prevents jumping while stunned" },
	{ _field_real, "minimum stun time:seconds#all stunning damage will last for at least this long" },
	{ _field_real, "maximum stun time:seconds#no stunning damage will last for longer than this" },
	{ _field_custom },
	{ _field_real, "feign death chance:[0,1]" },
	{ _field_real, "feign repeat chance:[0,1]" },
	{ _field_tag_reference, "spawned turret character#automatically created character when this unit is driven" },
	{ _field_short_bounds, "spawned actor count#number of actors which we spawn" },
	{ _field_real, "spawned velocity#velocity at which we throw spawned actors" },
	{ _field_custom, "aiming/looking" },
	{ _field_string_id, "target aiming pivot marker name#set this to have your weapon barrel point at its calcualed target instead of matching the aiming of the unit controlling it.  This marker should be along the barrel at point that doesn\'t move when the barrel pitches up and down." },
	{ _field_angle, "aiming velocity maximum:degrees per second" },
	{ _field_angle, "aiming acceleration maximum:degrees per second squared" },
	{ _field_real_fraction, "casual aiming modifier:[0,1]" },
	{ _field_angle, "looking velocity maximum:degrees per second" },
	{ _field_angle, "looking acceleration maximum:degrees per second squared" },
	{ _field_custom },
	{ _field_real, "object velocity maximum!:world units per second#Debug value for object velocity that corresponds to a blend screen weight of 1, 0 defaults to 5.0" },
	{ _field_string_id, "right_hand_node#where the primary weapon is attached" },
	{ _field_string_id, "left_hand_node#where the seconday weapon is attached (for dual-pistol modes)" },
	{ _field_struct, "more damn nodes" },
	{ _field_enum, "melee damage class" },
	{ _field_pad, "PAD", 2 },
	{ _field_custom, "melee damage" },
	{ _field_tag_reference, "melee damage" },
	{ _field_tag_reference, "native melee override#when set, characters will melee with these settings rather than their actual held weapon. (for characters that melee with an off hand)" },
	{ _field_struct, "your momma" },
	{ _field_custom },
	{ _field_enum, "motion sensor blip size" },
	{ _field_enum, "item owner size" },
	{ _field_string_id, "equipment variant name" },
	{ _field_string_id, "grounded equipment variant name" },
	{ _field_block, "postures", &unit_postures_block },
	{ _field_block, "Hud audio cues", &hud_unit_sound_block },
	{ _field_block, "dialogue variants", &dialogue_variant_block },
	{ _field_custom, "standard grenade throw" },
	{ _field_real, "grenade angle:degrees" },
	{ _field_real, "grenade angle max elevation:degrees" },
	{ _field_real, "grenade angle min elevation:degrees" },
	{ _field_real, "grenade velocity:world units per second" },
	{ _field_custom },
	{ _field_custom, "sprinting grenade throw" },
	{ _field_real, "grenade angle (sprinting):degrees" },
	{ _field_real, "grenade angle max elevation (sprinting):degrees" },
	{ _field_real, "grenade angle min elevation (sprinting):degrees" },
	{ _field_real, "grenade velocity (sprinting):world units per second" },
	{ _field_custom },
	{ _field_custom, "primary weapon toss" },
	{ _field_real, "weapon angle:degrees" },
	{ _field_real, "weapon angle max elevation:degrees" },
	{ _field_real, "weapon angle min elevation:degrees" },
	{ _field_real, "weapon velocity:world units per second" },
	{ _field_custom },
	{ _field_enum, "grenade type" },
	{ _field_short_integer, "grenade count" },
	{ _field_block, "powered seats", &powered_seat_block },
	{ _field_block, "weapons", &unit_weapon_block },
	{ _field_block, "target tracking", &global_target_tracking_parameters_block },
	{ _field_block, "seats", &unit_seat_block },
	{ _field_custom, "open/close" },
	{ _field_real, "opening time:s#how long the unit takes to open when the hs_function unit_open is called\nThe current open state can be retrieved from the object function unit_open" },
	{ _field_real, "closing time:s#you don\'t have to go home, but you can\'t stay here" },
	{ _field_custom },
	{ _field_custom, "EMP Disabling" },
	{ _field_real, "emp disabled time:seconds" },
	{ _field_real, "emp disabled time (PVP):seconds #Set to -1 for not disabled in MP but disabled in SP" },
	{ _field_tag_reference, "emp disabled effect" },
	{ _field_custom },
	{ _field_custom, "Boost" },
	{ _field_struct, "boost" },
	{ _field_custom },
	{ _field_explanation, "Lipsync" },
	{ _field_struct, "lipsync" },
	{ _field_explanation, "Exit and Detach" },
	{ _field_tag_reference, "exit and detach damage" },
	{ _field_tag_reference, "exit and detach weapon" },
	{ _field_explanation, "Experience" },
	{ _field_short_integer, "experience for kill" },
	{ _field_short_integer, "experience for assist" },
	{ _field_tag_reference, "hero assist equipment#this is where you stick an equipment that the biped will always have, to implement the bizarrely named hero assist" },
	{ _field_real, "bailout threshold:wu/s#the speed above which units will bail out of a vehicle instead of just exiting" },
	{ _field_custom },
	{ _field_real_fraction, "iron sight weapon dampening:(0-1)#when using iron sights, how much to scale the weapon overlays to steady the gun (0 = rock steady, 1= no dampening)" },
	{ _field_custom, "Birthing" },
	{ _field_struct, "birth" },
	{ _field_custom },
	{ _field_terminator },
};

} // namespace blofeld

