#include "tagframework-private-pch.h"

const char* blofeld::tag_field_attributed_definition_to_string(e_tag_field_attributed_definition tag_field_attributed_definitions)
{
	using namespace blofeld;
#define TAG_FIELD_ATTRIBUTED_DEFINITION_TO_STRING(_tag_field_attributed_definitions) \
	if(tag_field_attributed_definitions == blofeld::e_tag_field_attributed_definition::_tag_field_attributed_definitions) return #_tag_field_attributed_definitions;

	TAG_FIELD_ATTRIBUTED_DEFINITION_TO_STRING(_tag_field_attributed_definition_unknown_type);
	TAG_FIELD_ATTRIBUTED_DEFINITION_TO_STRING(_tag_field_attributed_definition_position);
	TAG_FIELD_ATTRIBUTED_DEFINITION_TO_STRING(_tag_field_attributed_definition_orientation);
	TAG_FIELD_ATTRIBUTED_DEFINITION_TO_STRING(_tag_field_attributed_definition_scale);
	TAG_FIELD_ATTRIBUTED_DEFINITION_TO_STRING(_tag_field_attributed_definition_block_wide_field_default);
	TAG_FIELD_ATTRIBUTED_DEFINITION_TO_STRING(_tag_field_attributed_definition_block_collapsed_field_default);
	TAG_FIELD_ATTRIBUTED_DEFINITION_TO_STRING(_tag_field_attributed_definition_block_name_sorted);
	TAG_FIELD_ATTRIBUTED_DEFINITION_TO_STRING(_tag_field_attributed_definition_block_grid_view_by_default);
	TAG_FIELD_ATTRIBUTED_DEFINITION_TO_STRING(_tag_field_attributed_definition_template_refresh_field);
	TAG_FIELD_ATTRIBUTED_DEFINITION_TO_STRING(_tag_field_attributed_definition_custom_block_filter_field);
	TAG_FIELD_ATTRIBUTED_DEFINITION_TO_STRING(_tag_field_attributed_definition_string_editor);
	TAG_FIELD_ATTRIBUTED_DEFINITION_TO_STRING(_tag_field_attributed_definition_update_layout_field);
	TAG_FIELD_ATTRIBUTED_DEFINITION_TO_STRING(_tag_field_attributed_definition_scenario_object_manual_bsp_flags);
	TAG_FIELD_ATTRIBUTED_DEFINITION_TO_STRING(_tag_field_attributed_definition_scenario_folder_field);

#undef TAG_FIELD_ATTRIBUTED_DEFINITION_TO_STRING

	return nullptr;
}
