#pragma once

namespace blofeld
{

extern s_tag_struct object_struct_definition_struct_definition;
extern s_tag_struct object_abandonment_struct_struct_definition;

extern s_tag_struct sidecarBlock_struct_definition;
extern s_tag_block_definition sidecarBlock;
extern s_tag_struct object_early_mover_obb_block_struct_definition;
extern s_tag_block_definition object_early_mover_obb_block;
extern s_tag_struct object_ai_properties_block_struct_definition;
extern s_tag_block_definition object_ai_properties_block;
extern s_tag_struct object_function_block_struct_definition;
extern s_tag_block_definition object_function_block;
extern s_tag_struct object_function_interpolation_block_struct_definition;
extern s_tag_block_definition object_function_interpolation_block;
extern s_tag_struct object_runtime_interpolator_functions_block_struct_definition;
extern s_tag_block_definition object_runtime_interpolator_functions_block;
extern s_tag_struct objectFunctionSwitchBlock_struct_definition;
extern s_tag_block_definition objectFunctionSwitchBlock;
extern s_tag_struct objectFunctionSwitchFunctionBlock_struct_definition;
extern s_tag_block_definition objectFunctionSwitchFunctionBlock;
extern s_tag_struct global_object_attachment_block_struct_definition;
extern s_tag_block_definition global_object_attachment_block;
extern s_tag_struct object_widget_block_struct_definition;
extern s_tag_block_definition object_widget_block;
extern s_tag_struct object_change_colors_struct_definition;
extern s_tag_block_definition object_change_colors;
extern s_tag_struct object_change_color_initial_permutation_struct_definition;
extern s_tag_block_definition object_change_color_initial_permutation;
extern s_tag_struct object_change_color_function_struct_definition;
extern s_tag_block_definition object_change_color_function;
extern s_tag_struct multiplayer_object_block_struct_definition;
extern s_tag_block_definition multiplayer_object_block;
extern s_tag_struct object_spawn_effects_block_struct_definition;
extern s_tag_block_definition object_spawn_effects_block;

constexpr unsigned long OBJECT_TAG = 'obje';

extern s_tag_block_definition object_block;
extern s_tag_group object_group;
} // namespace blofeld

