#pragma once

namespace blofeld
{

constexpr unsigned long OBJECT_TAG = 'obje';

extern s_tag_group object_group;

extern s_tag_block_definition object_block_block;
extern s_tag_struct sidecarBlock_block_struct;
extern s_tag_block_definition sidecarBlock_block;
extern s_tag_struct object_early_mover_obb_block_block_struct;
extern s_tag_block_definition object_early_mover_obb_block_block;
extern s_tag_struct object_ai_properties_block_block_struct;
extern s_tag_block_definition object_ai_properties_block_block;
extern s_tag_struct object_function_block_block_struct;
extern s_tag_block_definition object_function_block_block;
extern s_tag_struct object_function_interpolation_block_block_struct;
extern s_tag_block_definition object_function_interpolation_block_block;
extern s_tag_struct object_runtime_interpolator_functions_block_block_struct;
extern s_tag_block_definition object_runtime_interpolator_functions_block_block;
extern s_tag_struct objectFunctionSwitchBlock_block_struct;
extern s_tag_block_definition objectFunctionSwitchBlock_block;
extern s_tag_struct objectFunctionSwitchFunctionBlock_block_struct;
extern s_tag_block_definition objectFunctionSwitchFunctionBlock_block;
extern s_tag_struct global_object_attachment_block_block_struct;
extern s_tag_block_definition global_object_attachment_block_block;
extern s_tag_struct object_widget_block_block_struct;
extern s_tag_block_definition object_widget_block_block;
extern s_tag_struct object_change_colors_block_struct;
extern s_tag_block_definition object_change_colors_block;
extern s_tag_struct object_change_color_initial_permutation_block_struct;
extern s_tag_block_definition object_change_color_initial_permutation_block;
extern s_tag_struct object_change_color_function_block_struct;
extern s_tag_block_definition object_change_color_function_block;
extern s_tag_struct multiplayer_object_block_block_struct;
extern s_tag_block_definition multiplayer_object_block_block;
extern s_tag_struct object_spawn_effects_block_block_struct;
extern s_tag_block_definition object_spawn_effects_block_block;

extern s_tag_struct object_struct_definition_struct_definition; // tag group
extern s_tag_struct object_abandonment_struct_struct_definition;

} // namespace blofeld

