#pragma once

namespace blofeld
{

extern s_tag_struct style_sheet_list_struct_definition_struct_definition;

extern s_tag_struct UserInterfaceStyleSheetLanguagesBlock_struct_definition;
extern s_tag_block_definition UserInterfaceStyleSheetLanguagesBlock;
extern s_tag_struct UserInterfaceStyleSheetsFontBlock_struct_definition;
extern s_tag_block_definition UserInterfaceStyleSheetsFontBlock;
extern s_tag_struct UserInterfaceStyleSheetFontIdBlock_struct_definition;
extern s_tag_block_definition UserInterfaceStyleSheetFontIdBlock;
extern s_tag_struct UserInterfaceStyleSheetTextCaseBlock_struct_definition;
extern s_tag_block_definition UserInterfaceStyleSheetTextCaseBlock;
extern s_tag_struct UserInterfaceStyleSheetJustificationBlock_struct_definition;
extern s_tag_block_definition UserInterfaceStyleSheetJustificationBlock;
extern s_tag_struct UserInterfaceStyleSheetAlignmentBlock_struct_definition;
extern s_tag_block_definition UserInterfaceStyleSheetAlignmentBlock;
extern s_tag_struct UserInterfaceStyleSheetScaleBlock_struct_definition;
extern s_tag_block_definition UserInterfaceStyleSheetScaleBlock;
extern s_tag_struct UserInterfaceStyleSheetFixedHeightBlock_struct_definition;
extern s_tag_block_definition UserInterfaceStyleSheetFixedHeightBlock;
extern s_tag_struct UserInterfaceStyleSheetsVisualBlock_struct_definition;
extern s_tag_block_definition UserInterfaceStyleSheetsVisualBlock;
extern s_tag_struct UserInterfaceStyleSheetDropShadowStyleBlock_struct_definition;
extern s_tag_block_definition UserInterfaceStyleSheetDropShadowStyleBlock;
extern s_tag_struct UserInterfaceStyleSheetColorBlock_struct_definition;
extern s_tag_block_definition UserInterfaceStyleSheetColorBlock;
extern s_tag_struct UserInterfaceStyleSheetGradientBlock_struct_definition;
extern s_tag_block_definition UserInterfaceStyleSheetGradientBlock;
extern s_tag_struct UserInterfaceStyleSheetDropshadowBlock_struct_definition;
extern s_tag_block_definition UserInterfaceStyleSheetDropshadowBlock;
extern s_tag_struct UserInterfaceStyleSheetOuterGlowBlock_struct_definition;
extern s_tag_block_definition UserInterfaceStyleSheetOuterGlowBlock;

constexpr unsigned long STYLE_SHEET_LIST_TAG = 'uiss';

extern s_tag_block_definition style_sheet_list_block;
extern s_tag_group style_sheet_list_group;
} // namespace blofeld

