#include <blofeld-private-pch.h>

namespace blofeld
{

	TAG_ENUM(game_engine_settings, 205)
	{
		OPTION("game base misc"),
		OPTION("game base respawn"),
		OPTION("game base social"),
		OPTION("game base map"),
		OPTION("game base prototype"),
		OPTION("powerup duration"),
		OPTION("ctf top level options"),
		OPTION("slayer top level options"),
		OPTION("oddball top level options"),
		OPTION("king top level options"),
		OPTION("sandbox top level options"),
		OPTION("sandbox in-forge options"),
		OPTION("juggernaut top level options"),
		OPTION("territories top level options"),
		OPTION("assault top level options"),
		OPTION("infection top level options"),
		OPTION("vip top level options"),
		OPTION("training top level options"),
		OPTION("mosh top level options"),
		OPTION("custom top level options"),
		OPTION("map override advanced options"),
		OPTION("respawn advanced options"),
		OPTION("respawn modifiers"),
		OPTION("slayer primary options"),
		OPTION("slayer advanced options"),
		OPTION("slayer scoring options"),
		OPTION("oddball primary options"),
		OPTION("oddball advanced options"),
		OPTION("assault primary options"),
		OPTION("assault advanced options"),
		OPTION("ctf primary options"),
		OPTION("ctf advanced options"),
		OPTION("juggernaut primary options"),
		OPTION("juggernaut advanced options"),
		OPTION("king primary options"),
		OPTION("king advanced options"),
		OPTION("infection primary options"),
		OPTION("infection advanced options"),
		OPTION("infection scoring options"),
		OPTION("target training primary options"),
		OPTION("training advanced options"),
		OPTION("target 1 setup"),
		OPTION("target 2 setup"),
		OPTION("target 3 setup"),
		OPTION("target 4 setup"),
		OPTION("target 5 setup"),
		OPTION("target 6 setup"),
		OPTION("target 7 setup"),
		OPTION("target 8 setup"),
		OPTION("target 9 setup"),
		OPTION("target 10 setup"),
		OPTION("vip primary options"),
		OPTION("vip advanced options"),
		OPTION("territories primary options"),
		OPTION("territories advanced options"),
		OPTION("ai template traits"),
		OPTION("campaign top level options"),
		OPTION("survival top level options"),
		OPTION("firefight top level options"),
		OPTION("megalo options submenu trigger"),
		OPTION("survival primary options"),
		OPTION("survival scenario settings options"),
		OPTION("survival set options"),
		OPTION("survival round options"),
		OPTION("survival round 0 category options"),
		OPTION("survival round 0 skulls category options"),
		OPTION("survival round_0_initial_wave options"),
		OPTION("survival round_0_primary_wave options"),
		OPTION("survival round_0_boss_wave options"),
		OPTION("survival round 1 category options"),
		OPTION("survival round 1 skulls category options"),
		OPTION("survival round_1_initial_wave options"),
		OPTION("survival round_1_primary_wave options"),
		OPTION("survival round_1_boss_wave options"),
		OPTION("survival round 2 category options"),
		OPTION("survival round 2 skulls category options"),
		OPTION("survival round_2_initial_wave options"),
		OPTION("survival round_2_primary_wave options"),
		OPTION("survival round_2_boss_wave options"),
		OPTION("survival round template category options"),
		OPTION("survival round template skulls category options"),
		OPTION("survival round_template_initial_wave options"),
		OPTION("survival round_template_primary_wave options"),
		OPTION("survival round_template_boss_wave options"),
		OPTION("survival bonus_wave skulls category options"),
		OPTION("survival bonus_wave options"),
		OPTION("survival spartan options"),
		OPTION("survival elite options"),
		OPTION("survival_ai_traits traits"),
		OPTION("survival_ai_traits templated"),
		OPTION("survival lives options"),
		OPTION("survival loadout options"),
		OPTION("survival objective options"),
		OPTION("survival custom skull options"),
		OPTION("custom skull red options"),
		OPTION("custom skull yellow options"),
		OPTION("custom skull blue options"),
		OPTION("red_skull_ai_traits traits"),
		OPTION("red_skull_ai_traits templated"),
		OPTION("yellow_skull_ai_traits traits"),
		OPTION("yellow_skull_ai_traits templated"),
		OPTION("blue_skull_ai_traits traits"),
		OPTION("blue_skull_ai_traits templated"),
		OPTION("spartan loadouts"),
		OPTION("spartan_loadouts_tier1"),
		OPTION("spartan_loadouts_tier1_loadout0"),
		OPTION("spartan_loadouts_tier1_loadout1"),
		OPTION("spartan_loadouts_tier1_loadout2"),
		OPTION("spartan_loadouts_tier1_loadout3"),
		OPTION("spartan_loadouts_tier1_loadout4"),
		OPTION("spartan_loadouts_tier2"),
		OPTION("spartan_loadouts_tier2_loadout0"),
		OPTION("spartan_loadouts_tier2_loadout1"),
		OPTION("spartan_loadouts_tier2_loadout2"),
		OPTION("spartan_loadouts_tier2_loadout3"),
		OPTION("spartan_loadouts_tier2_loadout4"),
		OPTION("spartan_loadouts_tier3"),
		OPTION("spartan_loadouts_tier3_loadout0"),
		OPTION("spartan_loadouts_tier3_loadout1"),
		OPTION("spartan_loadouts_tier3_loadout2"),
		OPTION("spartan_loadouts_tier3_loadout3"),
		OPTION("spartan_loadouts_tier3_loadout4"),
		OPTION("elite loadouts"),
		OPTION("elite_loadouts_tier1"),
		OPTION("elite_loadouts_tier1_loadout0"),
		OPTION("elite_loadouts_tier1_loadout1"),
		OPTION("elite_loadouts_tier1_loadout2"),
		OPTION("elite_loadouts_tier1_loadout3"),
		OPTION("elite_loadouts_tier1_loadout4"),
		OPTION("elite_loadouts_tier2"),
		OPTION("elite_loadouts_tier2_loadout0"),
		OPTION("elite_loadouts_tier2_loadout1"),
		OPTION("elite_loadouts_tier2_loadout2"),
		OPTION("elite_loadouts_tier2_loadout3"),
		OPTION("elite_loadouts_tier2_loadout4"),
		OPTION("elite_loadouts_tier3"),
		OPTION("elite_loadouts_tier3_loadout0"),
		OPTION("elite_loadouts_tier3_loadout1"),
		OPTION("elite_loadouts_tier3_loadout2"),
		OPTION("elite_loadouts_tier3_loadout3"),
		OPTION("elite_loadouts_tier3_loadout4"),
		OPTION("infinity settings"),
		OPTION("ordnance"),
		OPTION("personal ordnance"),
		OPTION("personal ordnance - left bank"),
		OPTION("personal ordnance - middle bank"),
		OPTION("personal ordnance - right bank"),
		OPTION("red powerup"),
		OPTION("yellow powerup"),
		OPTION("blue powerup"),
		OPTION("traits"),
		OPTION("kill rewards"),
		OPTION("player traits base player"),
		OPTION("player traits respawn"),
		OPTION("player traits red powerup primary"),
		OPTION("player traits blue powerup primary"),
		OPTION("player traits yellow powerup primary"),
		OPTION("player traits custom powerup primary"),
		OPTION("player traits survival spartan player"),
		OPTION("player traits survival elite player"),
		OPTION("player traits elite respawn"),
		OPTION("player traits red skull spartan"),
		OPTION("player traits red skull elite"),
		OPTION("player traits yellow skull spartan"),
		OPTION("player traits yellow skull elite"),
		OPTION("player traits blue skull spartan"),
		OPTION("player traits blue skull elite"),
		OPTION("player traits sandbox editor"),
		OPTION("player traits megalo custom 1"),
		OPTION("player traits megalo custom 2"),
		OPTION("player traits megalo custom 3"),
		OPTION("player traits megalo custom 4"),
		OPTION("player traits megalo custom dynamic 1"),
		OPTION("player traits megalo custom dynamic 2"),
		OPTION("player traits megalo custom dynamic 3"),
		OPTION("player traits megalo custom dynamic 4"),
		OPTION("player traits red powerup secondary"),
		OPTION("player traits blue powerup secondary"),
		OPTION("player traits yellow powerup secondary"),
		OPTION("player traits custom powerup secondary"),
		OPTION("trait zone alpha player traits"),
		OPTION("trait zone bravo player traits"),
		OPTION("trait zone charlie player traits"),
		OPTION("trait zone delta player traits"),
		OPTION("player template traits"),
		OPTION("player template traits shields"),
		OPTION("player template traits weapons"),
		OPTION("player template traits movement"),
		OPTION("player template traits sensors"),
		OPTION("player template traits appearance"),
		OPTION("player template traits abilities"),
		OPTION("editor template traits"),
		OPTION("editor template traits shields"),
		OPTION("editor template traits weapons"),
		OPTION("editor template traits movement"),
		OPTION("editor template traits sensors"),
		OPTION("editor template traits appearance"),
		OPTION("editor template traits abilities"),
		OPTION("run-time template traits"),
		OPTION("run-time template traits shields"),
		OPTION("run-time template traits weapons"),
		OPTION("run-time template traits movement"),
		OPTION("run-time template traits sensors"),
		OPTION("run-time template traits appearance"),
		OPTION("run-time template traits abilities"),
	};

	TAG_ENUM(game_variant_parameters, 807)
	{
		OPTION("game misc score to win round"),
		OPTION("game misc teams"),
		OPTION("game misc mosh"),
		OPTION("game misc mosh difficulty"),
		OPTION("game misc drop weapons on death"),
		OPTION("game misc round reset map"),
		OPTION("game misc round time limit"),
		OPTION("game misc perfection enabled"),
		OPTION("game misc round limit"),
		OPTION("game misc early win count"),
		OPTION("game misc killcam enabled"),
		OPTION("game misc medal scoring enabled"),
		OPTION("game misc defenders use last round score"),
		OPTION("game misc overshield deplete time"),
		OPTION("game prototype mode"),
		OPTION("game prototype promethean kill mult."),
		OPTION("game prototype promethean time mult."),
		OPTION("game prototype promethean medal mult."),
		OPTION("game prototype promethean duration"),
		OPTION("game prototype class color override"),
		OPTION("game respawn inherit timer"),
		OPTION("game respawn with teammate"),
		OPTION("game respawn at location"),
		OPTION("game respawn on kill"),
		OPTION("game respawn early spawn allowed"),
		OPTION("game respawn lives per round"),
		OPTION("game respawn team lives per round"),
		OPTION("game respawn min respawn time"),
		OPTION("game respawn respawn time"),
		OPTION("game respawn suicide penalty"),
		OPTION("game respawn betrayal penalty"),
		OPTION("game respawn growth"),
		OPTION("game respawn initial loadout selection time"),
		OPTION("game respawn traits duration"),
		OPTION("game social observers"),
		OPTION("game social team changing"),
		OPTION("game social friendly fire"),
		OPTION("game social betrayal booting"),
		OPTION("game social enemy voice"),
		OPTION("game social open channel voice"),
		OPTION("game social dead player voice"),
		OPTION("game map grenades"),
		OPTION("game map equipment"),
		OPTION("game map turrets"),
		OPTION("game map shortcuts"),
		OPTION("game map powerups"),
		OPTION("game map indestructible vehicles"),
		OPTION("game map weapon set"),
		OPTION("game map vehicle set"),
		OPTION("game map equipment set"),
		OPTION("game map red powerup primary duration"),
		OPTION("game map blue powerup primary duration"),
		OPTION("game map yellow powerup primary duration"),
		OPTION("game map custom powerup primary duration"),
		OPTION("game map red powerup secondary duration"),
		OPTION("game map blue powerup secondary duration"),
		OPTION("game map yellow powerup secondary duration"),
		OPTION("game map custom powerup secondary duration"),
		OPTION("sandbox open voice channel"),
		OPTION("sandbox enter editor mode"),
		OPTION("sandbox respawn time"),
		OPTION("template vision"),
		OPTION("template hearing"),
		OPTION("template luck"),
		OPTION("template weapon"),
		OPTION("template grenades"),
		OPTION("template equipment drop"),
		OPTION("template ai assassination immunity"),
		OPTION("template ai headshot immunity"),
		OPTION("template ai damage resistance"),
		OPTION("template ai damage modifier"),
		OPTION("survival enable scenario hazards"),
		OPTION("survival enable weapon drops"),
		OPTION("survival enable ammo crates"),
		OPTION("survival generator defend all"),
		OPTION("survival generator random spawn"),
		OPTION("survival game difficulty"),
		OPTION("survival set count"),
		OPTION("survival bonus lives awarded"),
		OPTION("survival bonus target"),
		OPTION("survival spartan lives on elite death"),
		OPTION("survival extra life score target"),
		OPTION("survival shared team life count"),
		OPTION("survival elite life count"),
		OPTION("survival maximum lives"),
		OPTION("survival generator count"),
		OPTION("game elite_respawn inherit timer"),
		OPTION("game elite_respawn with teammate"),
		OPTION("game elite_respawn at location"),
		OPTION("game elite_respawn on kill"),
		OPTION("game elite_respawn early spawn allowed"),
		OPTION("game elite_respawn lives per round"),
		OPTION("game elite_respawn team lives per round"),
		OPTION("game elite_respawn min respawn time"),
		OPTION("game elite_respawn respawn time"),
		OPTION("game elite_respawn suicide penalty"),
		OPTION("game elite_respawn betrayal penalty"),
		OPTION("game elite_respawn growth"),
		OPTION("game elite_respawn initial loadout selection time"),
		OPTION("game elite_respawn traits duration"),
		OPTION("survival_ai_traits vision"),
		OPTION("survival_ai_traits hearing"),
		OPTION("survival_ai_traits luck"),
		OPTION("survival_ai_traits weapon"),
		OPTION("survival_ai_traits grenades"),
		OPTION("survival_ai_traits equipment drop"),
		OPTION("survival_ai_traits ai assassination immunity"),
		OPTION("survival_ai_traits ai headshot immunity"),
		OPTION("survival_ai_traits ai damage resistance"),
		OPTION("survival_ai_traits ai damage modifier"),
		OPTION("survival_round_0 skull0"),
		OPTION("survival_round_0 skull1"),
		OPTION("survival_round_0 skull2"),
		OPTION("survival_round_0 skull3"),
		OPTION("survival_round_0 skull4"),
		OPTION("survival_round_0 skull5"),
		OPTION("survival_round_0 skull6"),
		OPTION("survival_round_0 skull7"),
		OPTION("survival_round_0 skull8"),
		OPTION("survival_round_0 skull9"),
		OPTION("survival_round_0 skull10"),
		OPTION("survival_round_0 skull11"),
		OPTION("survival_round_0 skull12"),
		OPTION("survival_round_0 skull13"),
		OPTION("survival_round_0 skull14"),
		OPTION("survival_round_0 skull15"),
		OPTION("survival_round_0 skull16"),
		OPTION("survival_round_0 skull17"),
		OPTION("survival round_0_initial_wave delivered via dropship"),
		OPTION("survival round_0_initial_wave wave squad advance type"),
		OPTION("survival_round_0_initial_wave squad type0"),
		OPTION("survival_round_0_initial_wave squad type1"),
		OPTION("survival_round_0_initial_wave squad type2"),
		OPTION("survival_round_0_initial_wave squad type3"),
		OPTION("survival_round_0_initial_wave squad type4"),
		OPTION("survival_round_0_initial_wave squad type5"),
		OPTION("survival_round_0_initial_wave squad type6"),
		OPTION("survival_round_0_initial_wave squad type7"),
		OPTION("survival_round_0_initial_wave squad type8"),
		OPTION("survival_round_0_initial_wave squad type9"),
		OPTION("survival_round_0_initial_wave squad type10"),
		OPTION("survival_round_0_initial_wave squad type11"),
		OPTION("survival round_0_primary_wave delivered via dropship"),
		OPTION("survival round_0_primary_wave wave squad advance type"),
		OPTION("survival_round_0_primary_wave squad type0"),
		OPTION("survival_round_0_primary_wave squad type1"),
		OPTION("survival_round_0_primary_wave squad type2"),
		OPTION("survival_round_0_primary_wave squad type3"),
		OPTION("survival_round_0_primary_wave squad type4"),
		OPTION("survival_round_0_primary_wave squad type5"),
		OPTION("survival_round_0_primary_wave squad type6"),
		OPTION("survival_round_0_primary_wave squad type7"),
		OPTION("survival_round_0_primary_wave squad type8"),
		OPTION("survival_round_0_primary_wave squad type9"),
		OPTION("survival_round_0_primary_wave squad type10"),
		OPTION("survival_round_0_primary_wave squad type11"),
		OPTION("survival round_0_boss_wave delivered via dropship"),
		OPTION("survival round_0_boss_wave wave squad advance type"),
		OPTION("survival_round_0_boss_wave squad type0"),
		OPTION("survival_round_0_boss_wave squad type1"),
		OPTION("survival_round_0_boss_wave squad type2"),
		OPTION("survival_round_0_boss_wave squad type3"),
		OPTION("survival_round_0_boss_wave squad type4"),
		OPTION("survival_round_0_boss_wave squad type5"),
		OPTION("survival_round_0_boss_wave squad type6"),
		OPTION("survival_round_0_boss_wave squad type7"),
		OPTION("survival_round_0_boss_wave squad type8"),
		OPTION("survival_round_0_boss_wave squad type9"),
		OPTION("survival_round_0_boss_wave squad type10"),
		OPTION("survival_round_0_boss_wave squad type11"),
		OPTION("survival_round_1 skull0"),
		OPTION("survival_round_1 skull1"),
		OPTION("survival_round_1 skull2"),
		OPTION("survival_round_1 skull3"),
		OPTION("survival_round_1 skull4"),
		OPTION("survival_round_1 skull5"),
		OPTION("survival_round_1 skull6"),
		OPTION("survival_round_1 skull7"),
		OPTION("survival_round_1 skull8"),
		OPTION("survival_round_1 skull9"),
		OPTION("survival_round_1 skull10"),
		OPTION("survival_round_1 skull11"),
		OPTION("survival_round_1 skull12"),
		OPTION("survival_round_1 skull13"),
		OPTION("survival_round_1 skull14"),
		OPTION("survival_round_1 skull15"),
		OPTION("survival_round_1 skull16"),
		OPTION("survival_round_1 skull17"),
		OPTION("survival round_1_initial_wave delivered via dropship"),
		OPTION("survival round_1_initial_wave wave squad advance type"),
		OPTION("survival_round_1_initial_wave squad type0"),
		OPTION("survival_round_1_initial_wave squad type1"),
		OPTION("survival_round_1_initial_wave squad type2"),
		OPTION("survival_round_1_initial_wave squad type3"),
		OPTION("survival_round_1_initial_wave squad type4"),
		OPTION("survival_round_1_initial_wave squad type5"),
		OPTION("survival_round_1_initial_wave squad type6"),
		OPTION("survival_round_1_initial_wave squad type7"),
		OPTION("survival_round_1_initial_wave squad type8"),
		OPTION("survival_round_1_initial_wave squad type9"),
		OPTION("survival_round_1_initial_wave squad type10"),
		OPTION("survival_round_1_initial_wave squad type11"),
		OPTION("survival round_1_primary_wave delivered via dropship"),
		OPTION("survival round_1_primary_wave wave squad advance type"),
		OPTION("survival_round_1_primary_wave squad type0"),
		OPTION("survival_round_1_primary_wave squad type1"),
		OPTION("survival_round_1_primary_wave squad type2"),
		OPTION("survival_round_1_primary_wave squad type3"),
		OPTION("survival_round_1_primary_wave squad type4"),
		OPTION("survival_round_1_primary_wave squad type5"),
		OPTION("survival_round_1_primary_wave squad type6"),
		OPTION("survival_round_1_primary_wave squad type7"),
		OPTION("survival_round_1_primary_wave squad type8"),
		OPTION("survival_round_1_primary_wave squad type9"),
		OPTION("survival_round_1_primary_wave squad type10"),
		OPTION("survival_round_1_primary_wave squad type11"),
		OPTION("survival round_1_boss_wave delivered via dropship"),
		OPTION("survival round_1_boss_wave wave squad advance type"),
		OPTION("survival_round_1_boss_wave squad type0"),
		OPTION("survival_round_1_boss_wave squad type1"),
		OPTION("survival_round_1_boss_wave squad type2"),
		OPTION("survival_round_1_boss_wave squad type3"),
		OPTION("survival_round_1_boss_wave squad type4"),
		OPTION("survival_round_1_boss_wave squad type5"),
		OPTION("survival_round_1_boss_wave squad type6"),
		OPTION("survival_round_1_boss_wave squad type7"),
		OPTION("survival_round_1_boss_wave squad type8"),
		OPTION("survival_round_1_boss_wave squad type9"),
		OPTION("survival_round_1_boss_wave squad type10"),
		OPTION("survival_round_1_boss_wave squad type11"),
		OPTION("survival_round_2 skull0"),
		OPTION("survival_round_2 skull1"),
		OPTION("survival_round_2 skull2"),
		OPTION("survival_round_2 skull3"),
		OPTION("survival_round_2 skull4"),
		OPTION("survival_round_2 skull5"),
		OPTION("survival_round_2 skull6"),
		OPTION("survival_round_2 skull7"),
		OPTION("survival_round_2 skull8"),
		OPTION("survival_round_2 skull9"),
		OPTION("survival_round_2 skull10"),
		OPTION("survival_round_2 skull11"),
		OPTION("survival_round_2 skull12"),
		OPTION("survival_round_2 skull13"),
		OPTION("survival_round_2 skull14"),
		OPTION("survival_round_2 skull15"),
		OPTION("survival_round_2 skull16"),
		OPTION("survival_round_2 skull17"),
		OPTION("survival round_2_initial_wave delivered via dropship"),
		OPTION("survival round_2_initial_wave wave squad advance type"),
		OPTION("survival_round_2_initial_wave squad type0"),
		OPTION("survival_round_2_initial_wave squad type1"),
		OPTION("survival_round_2_initial_wave squad type2"),
		OPTION("survival_round_2_initial_wave squad type3"),
		OPTION("survival_round_2_initial_wave squad type4"),
		OPTION("survival_round_2_initial_wave squad type5"),
		OPTION("survival_round_2_initial_wave squad type6"),
		OPTION("survival_round_2_initial_wave squad type7"),
		OPTION("survival_round_2_initial_wave squad type8"),
		OPTION("survival_round_2_initial_wave squad type9"),
		OPTION("survival_round_2_initial_wave squad type10"),
		OPTION("survival_round_2_initial_wave squad type11"),
		OPTION("survival round_2_primary_wave delivered via dropship"),
		OPTION("survival round_2_primary_wave wave squad advance type"),
		OPTION("survival_round_2_primary_wave squad type0"),
		OPTION("survival_round_2_primary_wave squad type1"),
		OPTION("survival_round_2_primary_wave squad type2"),
		OPTION("survival_round_2_primary_wave squad type3"),
		OPTION("survival_round_2_primary_wave squad type4"),
		OPTION("survival_round_2_primary_wave squad type5"),
		OPTION("survival_round_2_primary_wave squad type6"),
		OPTION("survival_round_2_primary_wave squad type7"),
		OPTION("survival_round_2_primary_wave squad type8"),
		OPTION("survival_round_2_primary_wave squad type9"),
		OPTION("survival_round_2_primary_wave squad type10"),
		OPTION("survival_round_2_primary_wave squad type11"),
		OPTION("survival round_2_boss_wave delivered via dropship"),
		OPTION("survival round_2_boss_wave wave squad advance type"),
		OPTION("survival_round_2_boss_wave squad type0"),
		OPTION("survival_round_2_boss_wave squad type1"),
		OPTION("survival_round_2_boss_wave squad type2"),
		OPTION("survival_round_2_boss_wave squad type3"),
		OPTION("survival_round_2_boss_wave squad type4"),
		OPTION("survival_round_2_boss_wave squad type5"),
		OPTION("survival_round_2_boss_wave squad type6"),
		OPTION("survival_round_2_boss_wave squad type7"),
		OPTION("survival_round_2_boss_wave squad type8"),
		OPTION("survival_round_2_boss_wave squad type9"),
		OPTION("survival_round_2_boss_wave squad type10"),
		OPTION("survival_round_2_boss_wave squad type11"),
		OPTION("survival bonus_wave duration"),
		OPTION("survival_bonus_wave skull0"),
		OPTION("survival_bonus_wave skull1"),
		OPTION("survival_bonus_wave skull2"),
		OPTION("survival_bonus_wave skull3"),
		OPTION("survival_bonus_wave skull4"),
		OPTION("survival_bonus_wave skull5"),
		OPTION("survival_bonus_wave skull6"),
		OPTION("survival_bonus_wave skull7"),
		OPTION("survival_bonus_wave skull8"),
		OPTION("survival_bonus_wave skull9"),
		OPTION("survival_bonus_wave skull10"),
		OPTION("survival_bonus_wave skull11"),
		OPTION("survival_bonus_wave skull12"),
		OPTION("survival_bonus_wave skull13"),
		OPTION("survival_bonus_wave skull14"),
		OPTION("survival_bonus_wave skull15"),
		OPTION("survival_bonus_wave skull16"),
		OPTION("survival_bonus_wave skull17"),
		OPTION("survival bonus_wave delivered via dropship"),
		OPTION("survival bonus_wave wave squad advance type"),
		OPTION("survival_bonus_wave squad type0"),
		OPTION("survival_bonus_wave squad type1"),
		OPTION("survival_bonus_wave squad type2"),
		OPTION("survival_bonus_wave squad type3"),
		OPTION("survival_bonus_wave squad type4"),
		OPTION("survival_bonus_wave squad type5"),
		OPTION("survival_bonus_wave squad type6"),
		OPTION("survival_bonus_wave squad type7"),
		OPTION("survival_bonus_wave squad type8"),
		OPTION("survival_bonus_wave squad type9"),
		OPTION("survival_bonus_wave squad type10"),
		OPTION("survival_bonus_wave squad type11"),
		OPTION("red_skull_ai_traits vision"),
		OPTION("red_skull_ai_traits hearing"),
		OPTION("red_skull_ai_traits luck"),
		OPTION("red_skull_ai_traits weapon"),
		OPTION("red_skull_ai_traits grenades"),
		OPTION("red_skull_ai_traits equipment drop"),
		OPTION("red_skull_ai_traits ai assassination immunity"),
		OPTION("red_skull_ai_traits ai headshot immunity"),
		OPTION("red_skull_ai_traits ai damage resistance"),
		OPTION("red_skull_ai_traits ai damage modifier"),
		OPTION("yellow_skull_ai_traits vision"),
		OPTION("yellow_skull_ai_traits hearing"),
		OPTION("yellow_skull_ai_traits luck"),
		OPTION("yellow_skull_ai_traits weapon"),
		OPTION("yellow_skull_ai_traits grenades"),
		OPTION("yellow_skull_ai_traits equipment drop"),
		OPTION("yellow_skull_ai_traits ai assassination immunity"),
		OPTION("yellow_skull_ai_traits ai headshot immunity"),
		OPTION("yellow_skull_ai_traits ai damage resistance"),
		OPTION("yellow_skull_ai_traits ai damage modifier"),
		OPTION("blue_skull_ai_traits vision"),
		OPTION("blue_skull_ai_traits hearing"),
		OPTION("blue_skull_ai_traits luck"),
		OPTION("blue_skull_ai_traits weapon"),
		OPTION("blue_skull_ai_traits grenades"),
		OPTION("blue_skull_ai_traits equipment drop"),
		OPTION("blue_skull_ai_traits ai assassination immunity"),
		OPTION("blue_skull_ai_traits ai headshot immunity"),
		OPTION("blue_skull_ai_traits ai damage resistance"),
		OPTION("blue_skull_ai_traits ai damage modifier"),
		OPTION("survival_round_template skull0"),
		OPTION("survival_round_template skull1"),
		OPTION("survival_round_template skull2"),
		OPTION("survival_round_template skull3"),
		OPTION("survival_round_template skull4"),
		OPTION("survival_round_template skull5"),
		OPTION("survival_round_template skull6"),
		OPTION("survival_round_template skull7"),
		OPTION("survival_round_template skull8"),
		OPTION("survival_round_template skull9"),
		OPTION("survival_round_template skull10"),
		OPTION("survival_round_template skull11"),
		OPTION("survival_round_template skull12"),
		OPTION("survival_round_template skull13"),
		OPTION("survival_round_template skull14"),
		OPTION("survival_round_template skull15"),
		OPTION("survival_round_template skull16"),
		OPTION("survival_round_template skull17"),
		OPTION("survival round_template_initial_wave delivered via dropship"),
		OPTION("survival round_template_initial_wave wave squad advance type"),
		OPTION("survival_round_template_initial_wave squad type0"),
		OPTION("survival_round_template_initial_wave squad type1"),
		OPTION("survival_round_template_initial_wave squad type2"),
		OPTION("survival_round_template_initial_wave squad type3"),
		OPTION("survival_round_template_initial_wave squad type4"),
		OPTION("survival_round_template_initial_wave squad type5"),
		OPTION("survival_round_template_initial_wave squad type6"),
		OPTION("survival_round_template_initial_wave squad type7"),
		OPTION("survival_round_template_initial_wave squad type8"),
		OPTION("survival_round_template_initial_wave squad type9"),
		OPTION("survival_round_template_initial_wave squad type10"),
		OPTION("survival_round_template_initial_wave squad type11"),
		OPTION("survival round_template_primary_wave delivered via dropship"),
		OPTION("survival round_template_primary_wave wave squad advance type"),
		OPTION("survival_round_template_primary_wave squad type0"),
		OPTION("survival_round_template_primary_wave squad type1"),
		OPTION("survival_round_template_primary_wave squad type2"),
		OPTION("survival_round_template_primary_wave squad type3"),
		OPTION("survival_round_template_primary_wave squad type4"),
		OPTION("survival_round_template_primary_wave squad type5"),
		OPTION("survival_round_template_primary_wave squad type6"),
		OPTION("survival_round_template_primary_wave squad type7"),
		OPTION("survival_round_template_primary_wave squad type8"),
		OPTION("survival_round_template_primary_wave squad type9"),
		OPTION("survival_round_template_primary_wave squad type10"),
		OPTION("survival_round_template_primary_wave squad type11"),
		OPTION("survival round_template_boss_wave delivered via dropship"),
		OPTION("survival round_template_boss_wave wave squad advance type"),
		OPTION("survival_round_template_boss_wave squad type0"),
		OPTION("survival_round_template_boss_wave squad type1"),
		OPTION("survival_round_template_boss_wave squad type2"),
		OPTION("survival_round_template_boss_wave squad type3"),
		OPTION("survival_round_template_boss_wave squad type4"),
		OPTION("survival_round_template_boss_wave squad type5"),
		OPTION("survival_round_template_boss_wave squad type6"),
		OPTION("survival_round_template_boss_wave squad type7"),
		OPTION("survival_round_template_boss_wave squad type8"),
		OPTION("survival_round_template_boss_wave squad type9"),
		OPTION("survival_round_template_boss_wave squad type10"),
		OPTION("survival_round_template_boss_wave squad type11"),
		OPTION("custom loadouts enabled"),
		OPTION("spartan loadouts enabled"),
		OPTION("spartan_loadouts_tier1_loadout0 enabled"),
		OPTION("spartan_loadouts_tier1_loadout0 name"),
		OPTION("spartan_loadouts_tier1_loadout0 primary"),
		OPTION("spartan_loadouts_tier1_loadout0 secondary"),
		OPTION("spartan_loadouts_tier1_loadout0 equipment"),
		OPTION("spartan_loadouts_tier1_loadout0 tactical package"),
		OPTION("spartan_loadouts_tier1_loadout0 support upgrade"),
		OPTION("spartan_loadouts_tier1_loadout0 grenades"),
		OPTION("spartan_loadouts_tier1_loadout1 enabled"),
		OPTION("spartan_loadouts_tier1_loadout1 name"),
		OPTION("spartan_loadouts_tier1_loadout1 primary"),
		OPTION("spartan_loadouts_tier1_loadout1 secondary"),
		OPTION("spartan_loadouts_tier1_loadout1 equipment"),
		OPTION("spartan_loadouts_tier1_loadout1 tactical package"),
		OPTION("spartan_loadouts_tier1_loadout1 support upgrade"),
		OPTION("spartan_loadouts_tier1_loadout1 grenades"),
		OPTION("spartan_loadouts_tier1_loadout2 enabled"),
		OPTION("spartan_loadouts_tier1_loadout2 name"),
		OPTION("spartan_loadouts_tier1_loadout2 primary"),
		OPTION("spartan_loadouts_tier1_loadout2 secondary"),
		OPTION("spartan_loadouts_tier1_loadout2 equipment"),
		OPTION("spartan_loadouts_tier1_loadout2 tactical package"),
		OPTION("spartan_loadouts_tier1_loadout2 support upgrade"),
		OPTION("spartan_loadouts_tier1_loadout2 grenades"),
		OPTION("spartan_loadouts_tier1_loadout3 enabled"),
		OPTION("spartan_loadouts_tier1_loadout3 name"),
		OPTION("spartan_loadouts_tier1_loadout3 primary"),
		OPTION("spartan_loadouts_tier1_loadout3 secondary"),
		OPTION("spartan_loadouts_tier1_loadout3 equipment"),
		OPTION("spartan_loadouts_tier1_loadout3 tactical package"),
		OPTION("spartan_loadouts_tier1_loadout3 support upgrade"),
		OPTION("spartan_loadouts_tier1_loadout3 grenades"),
		OPTION("spartan_loadouts_tier1_loadout4 enabled"),
		OPTION("spartan_loadouts_tier1_loadout4 name"),
		OPTION("spartan_loadouts_tier1_loadout4 primary"),
		OPTION("spartan_loadouts_tier1_loadout4 secondary"),
		OPTION("spartan_loadouts_tier1_loadout4 equipment"),
		OPTION("spartan_loadouts_tier1_loadout4 tactical package"),
		OPTION("spartan_loadouts_tier1_loadout4 support upgrade"),
		OPTION("spartan_loadouts_tier1_loadout4 grenades"),
		OPTION("spartan_loadouts_tier2_loadout0 enabled"),
		OPTION("spartan_loadouts_tier2_loadout0 name"),
		OPTION("spartan_loadouts_tier2_loadout0 primary"),
		OPTION("spartan_loadouts_tier2_loadout0 secondary"),
		OPTION("spartan_loadouts_tier2_loadout0 equipment"),
		OPTION("spartan_loadouts_tier2_loadout0 tactical package"),
		OPTION("spartan_loadouts_tier2_loadout0 support upgrade"),
		OPTION("spartan_loadouts_tier2_loadout0 grenades"),
		OPTION("spartan_loadouts_tier2_loadout1 enabled"),
		OPTION("spartan_loadouts_tier2_loadout1 name"),
		OPTION("spartan_loadouts_tier2_loadout1 primary"),
		OPTION("spartan_loadouts_tier2_loadout1 secondary"),
		OPTION("spartan_loadouts_tier2_loadout1 equipment"),
		OPTION("spartan_loadouts_tier2_loadout1 tactical package"),
		OPTION("spartan_loadouts_tier2_loadout1 support upgrade"),
		OPTION("spartan_loadouts_tier2_loadout1 grenades"),
		OPTION("spartan_loadouts_tier2_loadout2 enabled"),
		OPTION("spartan_loadouts_tier2_loadout2 name"),
		OPTION("spartan_loadouts_tier2_loadout2 primary"),
		OPTION("spartan_loadouts_tier2_loadout2 secondary"),
		OPTION("spartan_loadouts_tier2_loadout2 equipment"),
		OPTION("spartan_loadouts_tier2_loadout2 tactical package"),
		OPTION("spartan_loadouts_tier2_loadout2 support upgrade"),
		OPTION("spartan_loadouts_tier2_loadout2 grenades"),
		OPTION("spartan_loadouts_tier2_loadout3 enabled"),
		OPTION("spartan_loadouts_tier2_loadout3 name"),
		OPTION("spartan_loadouts_tier2_loadout3 primary"),
		OPTION("spartan_loadouts_tier2_loadout3 secondary"),
		OPTION("spartan_loadouts_tier2_loadout3 equipment"),
		OPTION("spartan_loadouts_tier2_loadout3 tactical package"),
		OPTION("spartan_loadouts_tier2_loadout3 support upgrade"),
		OPTION("spartan_loadouts_tier2_loadout3 grenades"),
		OPTION("spartan_loadouts_tier2_loadout4 enabled"),
		OPTION("spartan_loadouts_tier2_loadout4 name"),
		OPTION("spartan_loadouts_tier2_loadout4 primary"),
		OPTION("spartan_loadouts_tier2_loadout4 secondary"),
		OPTION("spartan_loadouts_tier2_loadout4 equipment"),
		OPTION("spartan_loadouts_tier2_loadout4 tactical package"),
		OPTION("spartan_loadouts_tier2_loadout4 support upgrade"),
		OPTION("spartan_loadouts_tier2_loadout4 grenades"),
		OPTION("spartan_loadouts_tier3_loadout0 enabled"),
		OPTION("spartan_loadouts_tier3_loadout0 name"),
		OPTION("spartan_loadouts_tier3_loadout0 primary"),
		OPTION("spartan_loadouts_tier3_loadout0 secondary"),
		OPTION("spartan_loadouts_tier3_loadout0 equipment"),
		OPTION("spartan_loadouts_tier3_loadout0 tactical package"),
		OPTION("spartan_loadouts_tier3_loadout0 support upgrade"),
		OPTION("spartan_loadouts_tier3_loadout0 grenades"),
		OPTION("spartan_loadouts_tier3_loadout1 enabled"),
		OPTION("spartan_loadouts_tier3_loadout1 name"),
		OPTION("spartan_loadouts_tier3_loadout1 primary"),
		OPTION("spartan_loadouts_tier3_loadout1 secondary"),
		OPTION("spartan_loadouts_tier3_loadout1 equipment"),
		OPTION("spartan_loadouts_tier3_loadout1 tactical package"),
		OPTION("spartan_loadouts_tier3_loadout1 support upgrade"),
		OPTION("spartan_loadouts_tier3_loadout1 grenades"),
		OPTION("spartan_loadouts_tier3_loadout2 enabled"),
		OPTION("spartan_loadouts_tier3_loadout2 name"),
		OPTION("spartan_loadouts_tier3_loadout2 primary"),
		OPTION("spartan_loadouts_tier3_loadout2 secondary"),
		OPTION("spartan_loadouts_tier3_loadout2 equipment"),
		OPTION("spartan_loadouts_tier3_loadout2 tactical package"),
		OPTION("spartan_loadouts_tier3_loadout2 support upgrade"),
		OPTION("spartan_loadouts_tier3_loadout2 grenades"),
		OPTION("spartan_loadouts_tier3_loadout3 enabled"),
		OPTION("spartan_loadouts_tier3_loadout3 name"),
		OPTION("spartan_loadouts_tier3_loadout3 primary"),
		OPTION("spartan_loadouts_tier3_loadout3 secondary"),
		OPTION("spartan_loadouts_tier3_loadout3 equipment"),
		OPTION("spartan_loadouts_tier3_loadout3 tactical package"),
		OPTION("spartan_loadouts_tier3_loadout3 support upgrade"),
		OPTION("spartan_loadouts_tier3_loadout3 grenades"),
		OPTION("spartan_loadouts_tier3_loadout4 enabled"),
		OPTION("spartan_loadouts_tier3_loadout4 name"),
		OPTION("spartan_loadouts_tier3_loadout4 primary"),
		OPTION("spartan_loadouts_tier3_loadout4 secondary"),
		OPTION("spartan_loadouts_tier3_loadout4 equipment"),
		OPTION("spartan_loadouts_tier3_loadout4 tactical package"),
		OPTION("spartan_loadouts_tier3_loadout4 support upgrade"),
		OPTION("spartan_loadouts_tier3_loadout4 grenades"),
		OPTION("elite loadouts enabled"),
		OPTION("elite_loadouts_tier1_loadout0 enabled"),
		OPTION("elite_loadouts_tier1_loadout0 name"),
		OPTION("elite_loadouts_tier1_loadout0 primary"),
		OPTION("elite_loadouts_tier1_loadout0 secondary"),
		OPTION("elite_loadouts_tier1_loadout0 equipment"),
		OPTION("elite_loadouts_tier1_loadout0 tactical package"),
		OPTION("elite_loadouts_tier1_loadout0 support upgrade"),
		OPTION("elite_loadouts_tier1_loadout0 grenades"),
		OPTION("elite_loadouts_tier1_loadout1 enabled"),
		OPTION("elite_loadouts_tier1_loadout1 name"),
		OPTION("elite_loadouts_tier1_loadout1 primary"),
		OPTION("elite_loadouts_tier1_loadout1 secondary"),
		OPTION("elite_loadouts_tier1_loadout1 equipment"),
		OPTION("elite_loadouts_tier1_loadout1 tactical package"),
		OPTION("elite_loadouts_tier1_loadout1 support upgrade"),
		OPTION("elite_loadouts_tier1_loadout1 grenades"),
		OPTION("elite_loadouts_tier1_loadout2 enabled"),
		OPTION("elite_loadouts_tier1_loadout2 name"),
		OPTION("elite_loadouts_tier1_loadout2 primary"),
		OPTION("elite_loadouts_tier1_loadout2 secondary"),
		OPTION("elite_loadouts_tier1_loadout2 equipment"),
		OPTION("elite_loadouts_tier1_loadout2 tactical package"),
		OPTION("elite_loadouts_tier1_loadout2 support upgrade"),
		OPTION("elite_loadouts_tier1_loadout2 grenades"),
		OPTION("elite_loadouts_tier1_loadout3 enabled"),
		OPTION("elite_loadouts_tier1_loadout3 name"),
		OPTION("elite_loadouts_tier1_loadout3 primary"),
		OPTION("elite_loadouts_tier1_loadout3 secondary"),
		OPTION("elite_loadouts_tier1_loadout3 equipment"),
		OPTION("elite_loadouts_tier1_loadout3 tactical package"),
		OPTION("elite_loadouts_tier1_loadout3 support upgrade"),
		OPTION("elite_loadouts_tier1_loadout3 grenades"),
		OPTION("elite_loadouts_tier1_loadout4 enabled"),
		OPTION("elite_loadouts_tier1_loadout4 name"),
		OPTION("elite_loadouts_tier1_loadout4 primary"),
		OPTION("elite_loadouts_tier1_loadout4 secondary"),
		OPTION("elite_loadouts_tier1_loadout4 equipment"),
		OPTION("elite_loadouts_tier1_loadout4 tactical package"),
		OPTION("elite_loadouts_tier1_loadout4 support upgrade"),
		OPTION("elite_loadouts_tier1_loadout4 grenades"),
		OPTION("elite_loadouts_tier2_loadout0 enabled"),
		OPTION("elite_loadouts_tier2_loadout0 name"),
		OPTION("elite_loadouts_tier2_loadout0 primary"),
		OPTION("elite_loadouts_tier2_loadout0 secondary"),
		OPTION("elite_loadouts_tier2_loadout0 equipment"),
		OPTION("elite_loadouts_tier2_loadout0 tactical package"),
		OPTION("elite_loadouts_tier2_loadout0 support upgrade"),
		OPTION("elite_loadouts_tier2_loadout0 grenades"),
		OPTION("elite_loadouts_tier2_loadout1 enabled"),
		OPTION("elite_loadouts_tier2_loadout1 name"),
		OPTION("elite_loadouts_tier2_loadout1 primary"),
		OPTION("elite_loadouts_tier2_loadout1 secondary"),
		OPTION("elite_loadouts_tier2_loadout1 equipment"),
		OPTION("elite_loadouts_tier2_loadout1 tactical package"),
		OPTION("elite_loadouts_tier2_loadout1 support upgrade"),
		OPTION("elite_loadouts_tier2_loadout1 grenades"),
		OPTION("elite_loadouts_tier2_loadout2 enabled"),
		OPTION("elite_loadouts_tier2_loadout2 name"),
		OPTION("elite_loadouts_tier2_loadout2 primary"),
		OPTION("elite_loadouts_tier2_loadout2 secondary"),
		OPTION("elite_loadouts_tier2_loadout2 equipment"),
		OPTION("elite_loadouts_tier2_loadout2 tactical package"),
		OPTION("elite_loadouts_tier2_loadout2 support upgrade"),
		OPTION("elite_loadouts_tier2_loadout2 grenades"),
		OPTION("elite_loadouts_tier2_loadout3 enabled"),
		OPTION("elite_loadouts_tier2_loadout3 name"),
		OPTION("elite_loadouts_tier2_loadout3 primary"),
		OPTION("elite_loadouts_tier2_loadout3 secondary"),
		OPTION("elite_loadouts_tier2_loadout3 equipment"),
		OPTION("elite_loadouts_tier2_loadout3 tactical package"),
		OPTION("elite_loadouts_tier2_loadout3 support upgrade"),
		OPTION("elite_loadouts_tier2_loadout3 grenades"),
		OPTION("elite_loadouts_tier2_loadout4 enabled"),
		OPTION("elite_loadouts_tier2_loadout4 name"),
		OPTION("elite_loadouts_tier2_loadout4 primary"),
		OPTION("elite_loadouts_tier2_loadout4 secondary"),
		OPTION("elite_loadouts_tier2_loadout4 equipment"),
		OPTION("elite_loadouts_tier2_loadout4 tactical package"),
		OPTION("elite_loadouts_tier2_loadout4 support upgrade"),
		OPTION("elite_loadouts_tier2_loadout4 grenades"),
		OPTION("elite_loadouts_tier3_loadout0 enabled"),
		OPTION("elite_loadouts_tier3_loadout0 name"),
		OPTION("elite_loadouts_tier3_loadout0 primary"),
		OPTION("elite_loadouts_tier3_loadout0 secondary"),
		OPTION("elite_loadouts_tier3_loadout0 equipment"),
		OPTION("elite_loadouts_tier3_loadout0 tactical package"),
		OPTION("elite_loadouts_tier3_loadout0 support upgrade"),
		OPTION("elite_loadouts_tier3_loadout0 grenades"),
		OPTION("elite_loadouts_tier3_loadout1 enabled"),
		OPTION("elite_loadouts_tier3_loadout1 name"),
		OPTION("elite_loadouts_tier3_loadout1 primary"),
		OPTION("elite_loadouts_tier3_loadout1 secondary"),
		OPTION("elite_loadouts_tier3_loadout1 equipment"),
		OPTION("elite_loadouts_tier3_loadout1 tactical package"),
		OPTION("elite_loadouts_tier3_loadout1 support upgrade"),
		OPTION("elite_loadouts_tier3_loadout1 grenades"),
		OPTION("elite_loadouts_tier3_loadout2 enabled"),
		OPTION("elite_loadouts_tier3_loadout2 name"),
		OPTION("elite_loadouts_tier3_loadout2 primary"),
		OPTION("elite_loadouts_tier3_loadout2 secondary"),
		OPTION("elite_loadouts_tier3_loadout2 equipment"),
		OPTION("elite_loadouts_tier3_loadout2 tactical package"),
		OPTION("elite_loadouts_tier3_loadout2 support upgrade"),
		OPTION("elite_loadouts_tier3_loadout2 grenades"),
		OPTION("elite_loadouts_tier3_loadout3 enabled"),
		OPTION("elite_loadouts_tier3_loadout3 name"),
		OPTION("elite_loadouts_tier3_loadout3 primary"),
		OPTION("elite_loadouts_tier3_loadout3 secondary"),
		OPTION("elite_loadouts_tier3_loadout3 equipment"),
		OPTION("elite_loadouts_tier3_loadout3 tactical package"),
		OPTION("elite_loadouts_tier3_loadout3 support upgrade"),
		OPTION("elite_loadouts_tier3_loadout3 grenades"),
		OPTION("elite_loadouts_tier3_loadout4 enabled"),
		OPTION("elite_loadouts_tier3_loadout4 name"),
		OPTION("elite_loadouts_tier3_loadout4 primary"),
		OPTION("elite_loadouts_tier3_loadout4 secondary"),
		OPTION("elite_loadouts_tier3_loadout4 equipment"),
		OPTION("elite_loadouts_tier3_loadout4 tactical package"),
		OPTION("elite_loadouts_tier3_loadout4 support upgrade"),
		OPTION("elite_loadouts_tier3_loadout4 grenades"),
		OPTION("ordnance initial drops enabled"),
		OPTION("ordnance random drops enabled"),
		OPTION("ordnance objective drops enabled"),
		OPTION("ordnance player drops enabled"),
		OPTION("ordnance non-player drops enabled"),
		OPTION("map loadouts enabled"),
		OPTION("ordnance random drop minimum delay"),
		OPTION("ordnance random drop maximum delay"),
		OPTION("ordnance cost"),
		OPTION("ordnance cost multiplier"),
		OPTION("custom player ordnance"),
		OPTION("right_slot1 type_name"),
		OPTION("right_slot1 weight"),
		OPTION("right_slot2 type_name"),
		OPTION("right_slot2 weight"),
		OPTION("right_slot3 type_name"),
		OPTION("right_slot3 weight"),
		OPTION("right_slot4 type_name"),
		OPTION("right_slot4 weight"),
		OPTION("right_slot5 type_name"),
		OPTION("right_slot5 weight"),
		OPTION("right_slot6 type_name"),
		OPTION("right_slot6 weight"),
		OPTION("right_slot7 type_name"),
		OPTION("right_slot7 weight"),
		OPTION("right_slot8 type_name"),
		OPTION("right_slot8 weight"),
		OPTION("left_slot1 type_name"),
		OPTION("left_slot1 weight"),
		OPTION("left_slot2 type_name"),
		OPTION("left_slot2 weight"),
		OPTION("left_slot3 type_name"),
		OPTION("left_slot3 weight"),
		OPTION("left_slot4 type_name"),
		OPTION("left_slot4 weight"),
		OPTION("left_slot5 type_name"),
		OPTION("left_slot5 weight"),
		OPTION("left_slot6 type_name"),
		OPTION("left_slot6 weight"),
		OPTION("left_slot7 type_name"),
		OPTION("left_slot7 weight"),
		OPTION("left_slot8 type_name"),
		OPTION("left_slot8 weight"),
		OPTION("down_slot1 type_name"),
		OPTION("down_slot1 weight"),
		OPTION("down_slot2 type_name"),
		OPTION("down_slot2 weight"),
		OPTION("down_slot3 type_name"),
		OPTION("down_slot3 weight"),
		OPTION("down_slot4 type_name"),
		OPTION("down_slot4 weight"),
		OPTION("down_slot5 type_name"),
		OPTION("down_slot5 weight"),
		OPTION("down_slot6 type_name"),
		OPTION("down_slot6 weight"),
		OPTION("down_slot7 type_name"),
		OPTION("down_slot7 weight"),
		OPTION("down_slot8 type_name"),
		OPTION("down_slot8 weight"),
		OPTION("ordnance remapping table"),
		OPTION("template player trait damage resistance"),
		OPTION("template player trait shield multiplier"),
		OPTION("template player trait body multiplier"),
		OPTION("template player trait shield stun duration"),
		OPTION("template player trait shield recharge rate"),
		OPTION("template player trait body recharge rate"),
		OPTION("template player trait overshield recharge rate"),
		OPTION("template player trait vampirism percent"),
		OPTION("template player trait explosive damage resistance"),
		OPTION("template player trait wheelman armor vehicle stun time modifier"),
		OPTION("template player trait wheelman armor vehicle recharge time modifier"),
		OPTION("template player trait wheelman armor vehicle emp disabled time modifier"),
		OPTION("template player trait fall damage multiplier"),
		OPTION("template player trait headshot immunity"),
		OPTION("template player trait assassination immunity"),
		OPTION("template player trait deathless"),
		OPTION("template player trait fast track armor"),
		OPTION("template player trait powerup cancellation"),
		OPTION("template player trait damage multiplier"),
		OPTION("template player trait melee damage multiplier"),
		OPTION("template player trait grenade recharge seconds frag"),
		OPTION("template player trait grenade recharge seconds plasma"),
		OPTION("template player trait grenade recharge seconds spike"),
		OPTION("template player trait hero equipment energy use rate modifier"),
		OPTION("template player trait hero equipment energy recharge delay modifier"),
		OPTION("template player trait hero equipment energy recharge rate modifier"),
		OPTION("template player trait hero equipment initial energy modifier"),
		OPTION("template player trait equipment energy use rate modifier"),
		OPTION("template player trait equipment energy recharge delay modifier"),
		OPTION("template player trait equipment energy use recharge rate modifier"),
		OPTION("template player trait equipment energy initial energy modifier"),
		OPTION("template player trait switch speed modifier"),
		OPTION("template player trait reload speed modifier"),
		OPTION("template player trait ordnance points modifier"),
		OPTION("template player trait explosive area of effect radius modifier"),
		OPTION("template player trait gunner armor modifier"),
		OPTION("template player trait stability armor modifier"),
		OPTION("template player trait drop recon warning seconds"),
		OPTION("template player trait drop recon distance modifier"),
		OPTION("template player trait assassination speed modifier"),
		OPTION("template player trait weapon pickup allowed"),
		OPTION("template player trait initial grenade count"),
		OPTION("template player trait infinite ammo"),
		OPTION("template player trait equipment usage"),
		OPTION("template player trait equipment usage excepting auto turret"),
		OPTION("template player trait equipment drop"),
		OPTION("template player trait infinite equipment"),
		OPTION("template player trait initial primary weapon"),
		OPTION("template player trait initial secondary weapon"),
		OPTION("template player trait initial equipment"),
		OPTION("template player trait initial tactical package"),
		OPTION("template player trait initial support upgrade"),
		OPTION("template player trait weapons ammopack"),
		OPTION("template player trait weapons grenadier"),
		OPTION("template player trait weapons explode on death armormod"),
		OPTION("template player trait ordnance markers visible"),
		OPTION("template player trait weapons ordnance reroll available"),
		OPTION("template player trait weapons resourceful"),
		OPTION("template player trait weapons well equipped"),
		OPTION("template player trait ordnance disabled"),
		OPTION("template player trait speed"),
		OPTION("template player trait gravity multiplier"),
		OPTION("template player trait jump multiplier"),
		OPTION("template player trait turn speed multiplier"),
		OPTION("template player trait vehicle usage"),
		OPTION("template player trait double jump"),
		OPTION("template player trait sprint usage"),
		OPTION("template player trait automatic momentum usage"),
		OPTION("template player trait vaulting enabled"),
		OPTION("template player trait stealthy"),
		OPTION("template player trait player scale"),
		OPTION("template player trait active camo"),
		OPTION("template player trait waypoint"),
		OPTION("template player trait gamertag visible"),
		OPTION("template player trait aura"),
		OPTION("template player trait primary color"),
		OPTION("template player trait secondary color"),
		OPTION("template player trait model variant"),
		OPTION("template player trait death effect"),
		OPTION("template player trait looping effect"),
		OPTION("template player trait shield hud"),
		OPTION("motion tracker range"),
		OPTION("nemesis duration"),
		OPTION("template player trait motion tracker"),
		OPTION("template player trait motion tracker while zoomed"),
		OPTION("template player trait directional damage indicator"),
		OPTION("template player trait vision mode"),
		OPTION("template player trait battle awareness"),
		OPTION("template player trait threat view"),
		OPTION("template player trait aural enhancement"),
		OPTION("template player trait nemesis"),
	};

	TAG_ENUM(text_value_pair_flags, 2)
	{
		OPTION("default setting"),
		OPTION("real value \"unchanged\""),
	};

	TAG_ENUM(text_value_pair_parameter_type, 4)
	{
		OPTION("integer"),
		OPTION("string id"),
		OPTION("real range"),
		OPTION("real"),
	};

	TAG_GROUP_FROM_BLOCK(multiplayer_variant_settings_interface_definition, MULTIPLAYER_VARIANT_SETTINGS_INTERFACE_DEFINITION_TAG, multiplayer_variant_settings_interface_definition_block_block );

	TAG_GROUP_FROM_BLOCK(sandbox_text_value_pair_definition, SANDBOX_TEXT_VALUE_PAIR_DEFINITION_TAG, sandbox_text_value_pair_definition_block_block );

	TAG_GROUP_FROM_BLOCK(text_value_pair_definition, TEXT_VALUE_PAIR_DEFINITION_TAG, text_value_pair_definition_block_block );

	TAG_BLOCK_FROM_STRUCT(multiplayer_variant_settings_interface_definition_block, 1, multiplayer_variant_settings_interface_definition_struct_definition_struct_definition );

	TAG_BLOCK_FROM_STRUCT(sandbox_text_value_pair_definition_block, 1, sandbox_text_value_pair_definition_struct_definition_struct_definition );

	TAG_BLOCK_FROM_STRUCT(text_value_pair_definition_block, 1, text_value_pair_definition_struct_definition_struct_definition );

	TAG_BLOCK(variant_setting_edit_reference_block, k_maximum_game_setting_blocks)
	{
		FIELD( _field_string_id, "name" ),
		FIELD( _field_long_enum, "setting category^", &game_engine_settings ),
		FIELD( _field_block, "options", &variant_option_block_block ),
		FIELD( _field_terminator )
	};

	TAG_BLOCK(variant_option_block, k_maximum_variant_category_blocks)
	{
		FIELD( _field_explanation, "SUB-CATEGORY" ),
		FIELD( _field_tag_reference, "sub-category" ),
		FIELD( _field_explanation, "PLAYER TRAIT" ),
		FIELD( _field_tag_reference, "player trait ui" ),
		FIELD( _field_long_enum, "player trait category", &game_engine_settings ),
		FIELD( _field_explanation, "CATEGORY NAME" ),
		FIELD( _field_string_id, "category name" ),
		FIELD( _field_explanation, "CATEGORY DESCRIPTION" ),
		FIELD( _field_string_id, "category description" ),
		FIELD( _field_explanation, "VALUE-PAIRS" ),
		FIELD( _field_tag_reference, "value pairs" ),
		FIELD( _field_terminator )
	};

	TAG_BLOCK(sandbox_property_allowed_values_reference_block, k_maximum_sandbox_property_values)
	{
		FIELD( _field_string_id, "property name" ),
		FIELD( _field_char_enum, "parameter_type", &text_value_pair_parameter_type ),
		FIELD( _field_pad, "blug", 3 ),
		FIELD( _field_block, "allowed values", &text_value_pair_reference_block_block ),
		FIELD( _field_terminator )
	};

	TAG_BLOCK(text_value_pair_reference_block, k_maximum_text_value_pairs_per_block)
	{
		FIELD( _field_byte_flags, "flags", &text_value_pair_flags ),
		FIELD( _field_pad, "grug", 3 ),
		FIELD( _field_long_integer, "enumerated value" ),
		FIELD( _field_real, "real value" ),
		FIELD( _field_string_id, "string_id value" ),
		FIELD( _field_string_id, "label string id" ),
		FIELD( _field_string_id, "description string id" ),
		FIELD( _field_terminator )
	};

TAG_STRUCT(multiplayer_variant_settings_interface_definition_struct_definition)
{
		FIELD( _field_string_id, "name (unused)" ),
		FIELD( _field_block, "game engine settings", &variant_setting_edit_reference_block_block ),
		FIELD( _field_terminator )
};

TAG_STRUCT(sandbox_text_value_pair_definition_struct_definition)
{
		FIELD( _field_block, "property values", &sandbox_property_allowed_values_reference_block_block ),
		FIELD( _field_terminator )
};

TAG_STRUCT(text_value_pair_definition_struct_definition)
{
		FIELD( _field_long_enum, "parameter", &game_variant_parameters ),
		FIELD( _field_string_id, "name" ),
		FIELD( _field_string_id, "description text" ),
		FIELD( _field_char_enum, "parameter_type", &text_value_pair_parameter_type ),
		FIELD( _field_pad, "shrug", 3 ),
		FIELD( _field_block, "text value pairs", &text_value_pair_reference_block_block ),
		FIELD( _field_terminator )
};

} // namespace blofeld

