#pragma once

namespace blofeld
{

extern s_tag_struct InfinityUIImages_struct_definition_struct_definition;
extern s_tag_struct pgcr_enemy_to_category_mapping_definition_struct_definition_struct_definition;
extern s_tag_struct pgcr_damage_type_image_mapping_definition_struct_definition_struct_definition;
extern s_tag_struct portrait_poses_definition_struct_definition_struct_definition;
extern s_tag_struct user_interface_sounds_definition_struct_definition_struct_definition;
extern s_tag_struct user_interface_globals_definition_struct_definition_struct_definition;
extern s_tag_struct user_interface_shared_globals_definition_struct_definition_struct_definition;

extern s_tag_struct InfinityMissionSeasonImagesDefinition_struct_definition;
extern s_tag_block_definition InfinityMissionSeasonImagesDefinition;
extern s_tag_struct InfinityMissionImagesDefinition_struct_definition;
extern s_tag_block_definition InfinityMissionImagesDefinition;
extern s_tag_struct pgcr_enemy_to_category_list_block_struct_definition;
extern s_tag_block_definition pgcr_enemy_to_category_list_block;
extern s_tag_struct pgcr_player_to_category_entry_block_struct_definition;
extern s_tag_block_definition pgcr_player_to_category_entry_block;
extern s_tag_struct pgcr_enemy_to_category_entry_block_struct_definition;
extern s_tag_block_definition pgcr_enemy_to_category_entry_block;
extern s_tag_struct pgcr_damage_type_image_block_struct_definition;
extern s_tag_block_definition pgcr_damage_type_image_block;
extern s_tag_struct gui_portrait_pose_block_struct_definition;
extern s_tag_block_definition gui_portrait_pose_block;
extern s_tag_struct cui_component_screen_reference_block_definition_struct_definition;
extern s_tag_block_definition cui_component_screen_reference_block_definition;
extern s_tag_struct cui_overlay_camera_block_definition_struct_definition;
extern s_tag_block_definition cui_overlay_camera_block_definition;
extern s_tag_struct cui_player_model_camera_settings_definition_struct_definition;
extern s_tag_block_definition cui_player_model_camera_settings_definition;
extern s_tag_struct cui_player_model_controller_settings_definition_struct_definition;
extern s_tag_block_definition cui_player_model_controller_settings_definition;
extern s_tag_struct cui_player_model_transition_settings_definition_struct_definition;
extern s_tag_block_definition cui_player_model_transition_settings_definition;
extern s_tag_struct cui_active_roster_settings_block_struct_definition;
extern s_tag_block_definition cui_active_roster_settings_block;
extern s_tag_struct campaign_state_screen_script_block_definition_struct_definition;
extern s_tag_block_definition campaign_state_screen_script_block_definition;
extern s_tag_struct UserInterfaceGameScreenSequenceStepDefinition_struct_definition;
extern s_tag_block_definition UserInterfaceGameScreenSequenceStepDefinition;
extern s_tag_struct SwapTagReferenceDefinition_struct_definition;
extern s_tag_block_definition SwapTagReferenceDefinition;
extern s_tag_struct color_presets_block_struct_definition;
extern s_tag_block_definition color_presets_block;
extern s_tag_struct tint_colors_block_struct_definition;
extern s_tag_block_definition tint_colors_block;
extern s_tag_struct color_list_block_struct_definition;
extern s_tag_block_definition color_list_block;
extern s_tag_struct gui_alert_description_block_struct_definition;
extern s_tag_block_definition gui_alert_description_block;
extern s_tag_struct gui_dialog_description_block_struct_definition;
extern s_tag_block_definition gui_dialog_description_block;
extern s_tag_struct pgcr_incident_block_struct_struct_definition;
extern s_tag_block_definition pgcr_incident_block;

constexpr unsigned long INFINITYUIIMAGES_TAG = 'iuii';

extern s_tag_block_definition InfinityUIImages_block;
extern s_tag_group InfinityUIImages_group;
constexpr unsigned long PGCR_ENEMY_TO_CATEGORY_MAPPING_DEFINITION_TAG = 'pcec';

extern s_tag_block_definition pgcr_enemy_to_category_mapping_definition_block;
extern s_tag_group pgcr_enemy_to_category_mapping_definition_group;
constexpr unsigned long PGCR_DAMAGE_TYPE_IMAGE_MAPPING_DEFINITION_TAG = 'pdti';

extern s_tag_block_definition pgcr_damage_type_image_mapping_definition_block;
extern s_tag_group pgcr_damage_type_image_mapping_definition_group;
constexpr unsigned long PORTRAIT_POSES_DEFINITION_TAG = 'ppod';

extern s_tag_block_definition portrait_poses_definition_block;
extern s_tag_group portrait_poses_definition_group;
constexpr unsigned long USER_INTERFACE_SOUNDS_DEFINITION_TAG = 'uise';

extern s_tag_block_definition user_interface_sounds_definition_block;
extern s_tag_group user_interface_sounds_definition_group;
constexpr unsigned long USER_INTERFACE_GLOBALS_DEFINITION_TAG = 'wgtz';

extern s_tag_block_definition user_interface_globals_definition_block;
extern s_tag_group user_interface_globals_definition_group;
constexpr unsigned long USER_INTERFACE_SHARED_GLOBALS_DEFINITION_TAG = 'wigl';

extern s_tag_block_definition user_interface_shared_globals_definition_block;
extern s_tag_group user_interface_shared_globals_definition_group;
} // namespace blofeld

