git mv halo2_tools_pc32/halo2_tools_pc32_definition_manager.h									   halo2_tools_pc64/halo2_tools_pc64_definition_manager.h										
git mv halo2_tools_pc32/halo2_tools_pc32_field_type.cpp                                            halo2_tools_pc64/halo2_tools_pc64_field_type.cpp
git mv halo2_tools_pc32/halo2_tools_pc32_field_type.h                                              halo2_tools_pc64/halo2_tools_pc64_field_type.h
git mv halo2_tools_pc32/halo2_tools_pc32_tag_array_definition.cpp                                  halo2_tools_pc64/halo2_tools_pc64_tag_array_definition.cpp
git mv halo2_tools_pc32/halo2_tools_pc32_tag_array_definition.h                                    halo2_tools_pc64/halo2_tools_pc64_tag_array_definition.h
git mv halo2_tools_pc32/halo2_tools_pc32_tag_array_struct_definition.cpp                           halo2_tools_pc64/halo2_tools_pc64_tag_array_struct_definition.cpp
git mv halo2_tools_pc32/halo2_tools_pc32_tag_array_struct_definition.h                             halo2_tools_pc64/halo2_tools_pc64_tag_array_struct_definition.h
git mv halo2_tools_pc32/halo2_tools_pc32_tag_block_definition.cpp                                  halo2_tools_pc64/halo2_tools_pc64_tag_block_definition.cpp
git mv halo2_tools_pc32/halo2_tools_pc32_tag_block_definition.h                                    halo2_tools_pc64/halo2_tools_pc64_tag_block_definition.h
git mv halo2_tools_pc32/halo2_tools_pc32_tag_block_index_custom_search_definition.cpp              halo2_tools_pc64/halo2_tools_pc64_tag_block_index_custom_search_definition.cpp
git mv halo2_tools_pc32/halo2_tools_pc32_tag_block_index_custom_search_definition.h                halo2_tools_pc64/halo2_tools_pc64_tag_block_index_custom_search_definition.h
git mv halo2_tools_pc32/halo2_tools_pc32_tag_data_definition.cpp                                   halo2_tools_pc64/halo2_tools_pc64_tag_data_definition.cpp
git mv halo2_tools_pc32/halo2_tools_pc32_tag_data_definition.h                                     halo2_tools_pc64/halo2_tools_pc64_tag_data_definition.h
git mv halo2_tools_pc32/halo2_tools_pc32_tag_explanation_definition.cpp                            halo2_tools_pc64/halo2_tools_pc64_tag_explanation_definition.cpp
git mv halo2_tools_pc32/halo2_tools_pc32_tag_explanation_definition.h                              halo2_tools_pc64/halo2_tools_pc64_tag_explanation_definition.h
git mv halo2_tools_pc32/halo2_tools_pc32_tag_field.cpp                                             halo2_tools_pc64/halo2_tools_pc64_tag_field.cpp
git mv halo2_tools_pc32/halo2_tools_pc32_tag_field.h                                               halo2_tools_pc64/halo2_tools_pc64_tag_field.h
git mv halo2_tools_pc32/halo2_tools_pc32_tag_group_definition.cpp                                  halo2_tools_pc64/halo2_tools_pc64_tag_group_definition.cpp
git mv halo2_tools_pc32/halo2_tools_pc32_tag_group_definition.h                                    halo2_tools_pc64/halo2_tools_pc64_tag_group_definition.h
git mv halo2_tools_pc32/halo2_tools_pc32_tag_reference_definition.cpp                              halo2_tools_pc64/halo2_tools_pc64_tag_reference_definition.cpp
git mv halo2_tools_pc32/halo2_tools_pc32_tag_reference_definition.h                                halo2_tools_pc64/halo2_tools_pc64_tag_reference_definition.h
git mv halo2_tools_pc32/halo2_tools_pc32_tag_string_list_definition.cpp                            halo2_tools_pc64/halo2_tools_pc64_tag_string_list_definition.cpp
git mv halo2_tools_pc32/halo2_tools_pc32_tag_string_list_definition.h                              halo2_tools_pc64/halo2_tools_pc64_tag_string_list_definition.h
git mv halo2_tools_pc32/halo2_tools_pc32_tag_struct_definition.cpp                                 halo2_tools_pc64/halo2_tools_pc64_tag_struct_definition.cpp
git mv halo2_tools_pc32/halo2_tools_pc32_tag_struct_definition.h                                   halo2_tools_pc64/halo2_tools_pc64_tag_struct_definition.h
git mv halo2_tools_pc32/halo2_tools_pc32.cpp                                                       halo2_tools_pc64/halo2_tools_pc64.cpp
git mv halo2_tools_pc32/halo2_tools_pc32.h                                                         halo2_tools_pc64/halo2_tools_pc64.h
git mv halo2_tools_pc32/halo2_tools_pc32_definition_manager.cpp                                    halo2_tools_pc64/halo2_tools_pc64_definition_manager.cpp
git mv                                                                                             
git mv halo1_tools_pc32/halo1_tools_pc32_field_type.h                                              halo1_tools_pc64/halo1_tools_pc64_field_type.h
git mv halo1_tools_pc32/halo1_tools_pc32_tag_array_definition.cpp                                  halo1_tools_pc64/halo1_tools_pc64_tag_array_definition.cpp
git mv halo1_tools_pc32/halo1_tools_pc32_tag_array_definition.h                                    halo1_tools_pc64/halo1_tools_pc64_tag_array_definition.h
git mv halo1_tools_pc32/halo1_tools_pc32_tag_array_struct_definition.cpp                           halo1_tools_pc64/halo1_tools_pc64_tag_array_struct_definition.cpp
git mv halo1_tools_pc32/halo1_tools_pc32_tag_array_struct_definition.h                             halo1_tools_pc64/halo1_tools_pc64_tag_array_struct_definition.h
git mv halo1_tools_pc32/halo1_tools_pc32_tag_block_definition.cpp                                  halo1_tools_pc64/halo1_tools_pc64_tag_block_definition.cpp
git mv halo1_tools_pc32/halo1_tools_pc32_tag_block_definition.h                                    halo1_tools_pc64/halo1_tools_pc64_tag_block_definition.h
git mv halo1_tools_pc32/halo1_tools_pc32_tag_block_index_custom_search_definition.cpp              halo1_tools_pc64/halo1_tools_pc64_tag_block_index_custom_search_definition.cpp
git mv halo1_tools_pc32/halo1_tools_pc32_tag_block_index_custom_search_definition.h                halo1_tools_pc64/halo1_tools_pc64_tag_block_index_custom_search_definition.h
git mv halo1_tools_pc32/halo1_tools_pc32_tag_data_definition.cpp                                   halo1_tools_pc64/halo1_tools_pc64_tag_data_definition.cpp
git mv halo1_tools_pc32/halo1_tools_pc32_tag_data_definition.h                                     halo1_tools_pc64/halo1_tools_pc64_tag_data_definition.h
git mv halo1_tools_pc32/halo1_tools_pc32_tag_explanation_definition.cpp                            halo1_tools_pc64/halo1_tools_pc64_tag_explanation_definition.cpp
git mv halo1_tools_pc32/halo1_tools_pc32_tag_explanation_definition.h                              halo1_tools_pc64/halo1_tools_pc64_tag_explanation_definition.h
git mv halo1_tools_pc32/halo1_tools_pc32_tag_field.cpp                                             halo1_tools_pc64/halo1_tools_pc64_tag_field.cpp
git mv halo1_tools_pc32/halo1_tools_pc32_tag_field.h                                               halo1_tools_pc64/halo1_tools_pc64_tag_field.h
git mv halo1_tools_pc32/halo1_tools_pc32_tag_group_definition.cpp                                  halo1_tools_pc64/halo1_tools_pc64_tag_group_definition.cpp
git mv halo1_tools_pc32/halo1_tools_pc32_tag_group_definition.h                                    halo1_tools_pc64/halo1_tools_pc64_tag_group_definition.h
git mv halo1_tools_pc32/halo1_tools_pc32_tag_reference_definition.cpp                              halo1_tools_pc64/halo1_tools_pc64_tag_reference_definition.cpp
git mv halo1_tools_pc32/halo1_tools_pc32_tag_reference_definition.h                                halo1_tools_pc64/halo1_tools_pc64_tag_reference_definition.h
git mv halo1_tools_pc32/halo1_tools_pc32_tag_string_list_definition.cpp                            halo1_tools_pc64/halo1_tools_pc64_tag_string_list_definition.cpp
git mv halo1_tools_pc32/halo1_tools_pc32_tag_string_list_definition.h                              halo1_tools_pc64/halo1_tools_pc64_tag_string_list_definition.h
git mv halo1_tools_pc32/halo1_tools_pc32_tag_struct_definition.cpp                                 halo1_tools_pc64/halo1_tools_pc64_tag_struct_definition.cpp
git mv halo1_tools_pc32/halo1_tools_pc32_tag_struct_definition.h                                   halo1_tools_pc64/halo1_tools_pc64_tag_struct_definition.h
git mv halo1_tools_pc32/halo1_tools_pc32.cpp                                                       halo1_tools_pc64/halo1_tools_pc64.cpp
git mv halo1_tools_pc32/halo1_tools_pc32.h                                                         halo1_tools_pc64/halo1_tools_pc64.h
git mv halo1_tools_pc32/halo1_tools_pc32_definition_manager.cpp                                    halo1_tools_pc64/halo1_tools_pc64_definition_manager.cpp
git mv halo1_tools_pc32/halo1_tools_pc32_definition_manager.h                                      halo1_tools_pc64/halo1_tools_pc64_definition_manager.h
git mv halo1_tools_pc32/halo1_tools_pc32_field_type.cpp                                            halo1_tools_pc64/halo1_tools_pc64_field_type.cpp