#pragma once

namespace blofeld
{

extern s_tag_struct cue_distribution_struct_struct_definition;
extern s_tag_struct cue_stimulus_distribution_struct_struct_definition;
extern s_tag_struct cue_payload_struct_struct_definition;

extern s_tag_struct ai_cue_template_block_struct_struct_definition;
extern s_tag_block_definition ai_cue_template_block;
extern s_tag_struct firing_point_payload_block_struct_struct_definition;
extern s_tag_block_definition firing_point_payload_block;
extern s_tag_struct stimulus_payload_block_struct_struct_definition;
extern s_tag_block_definition stimulus_payload_block;
extern s_tag_struct combat_cue_payload_block_struct_struct_definition;
extern s_tag_block_definition combat_cue_payload_block;
extern s_tag_struct ai_cue_block_struct_struct_definition;
extern s_tag_block_definition ai_cue_block;
extern s_tag_struct task_distribution_block_struct_struct_definition;
extern s_tag_block_definition task_distribution_block;
extern s_tag_struct script_payload_block_struct_struct_definition;
extern s_tag_block_definition script_payload_block;
extern s_tag_struct combat_sync_action_group_payload_block_struct_struct_definition;
extern s_tag_block_definition combat_sync_action_group_payload_block;
extern s_tag_struct ai_full_cue_block_struct_struct_definition;
extern s_tag_block_definition ai_full_cue_block;
extern s_tag_struct ai_quick_cue_block_struct_struct_definition;
extern s_tag_block_definition ai_quick_cue_block;

} // namespace blofeld

