#pragma once

namespace blofeld
{

constexpr unsigned long AI_DIALOGUE_GLOBALS_TAG = 'adlg';

extern s_tag_group ai_dialogue_globals_group;

extern s_tag_block_definition ai_dialogue_globals_block_block;
extern s_tag_struct default_stimulus_suppressor_block_block_struct;
extern s_tag_block_definition default_stimulus_suppressor_block_block;
extern s_tag_struct vocalization_definitions_block_block_struct;
extern s_tag_block_definition vocalization_definitions_block_block;
extern s_tag_struct response_block_block_struct;
extern s_tag_block_definition response_block_block;
extern s_tag_struct vocalization_patterns_block_block_struct;
extern s_tag_block_definition vocalization_patterns_block_block;
extern s_tag_struct dialogue_data_block_block_struct;
extern s_tag_block_definition dialogue_data_block_block;
extern s_tag_struct involuntary_data_block_block_struct;
extern s_tag_block_definition involuntary_data_block_block;
extern s_tag_struct predicted_data_block_block_struct;
extern s_tag_block_definition predicted_data_block_block;

extern s_tag_struct ai_dialogue_globals_struct_definition_struct_definition; // tag group

} // namespace blofeld

