#pragma once

namespace blofeld
{


	constexpr unsigned long AI_GLOBALS_TAG = 'aigl';

	extern s_tag_group ai_globals_group;

	extern s_tag_block_definition ai_globals_block_block;
	extern s_tag_struct ai_globals_data_block_block_struct;
	extern s_tag_block_definition ai_globals_data_block_block;
	extern s_tag_struct ai_globals_gravemind_block_block_struct;
	extern s_tag_block_definition ai_globals_gravemind_block_block;
	extern s_tag_struct ai_globals_formation_block_block_struct;
	extern s_tag_block_definition ai_globals_formation_block_block;
	extern s_tag_struct ai_globals_squad_template_folder_block_block_struct;
	extern s_tag_block_definition ai_globals_squad_template_folder_block_block;
	extern s_tag_struct ai_globals_squad_template_sub_folder_block_block_struct;
	extern s_tag_block_definition ai_globals_squad_template_sub_folder_block_block;
	extern s_tag_struct ai_globals_squad_template_block_block_struct;
	extern s_tag_block_definition ai_globals_squad_template_block_block;
	extern s_tag_struct ai_globals_performance_template_folder_block_block_struct;
	extern s_tag_block_definition ai_globals_performance_template_folder_block_block;
	extern s_tag_struct ai_globals_performance_template_sub_folder_block_block_struct;
	extern s_tag_block_definition ai_globals_performance_template_sub_folder_block_block;
	extern s_tag_struct ai_globals_performance_template_block_block_struct;
	extern s_tag_block_definition ai_globals_performance_template_block_block;
	extern s_tag_struct ai_globals_custom_stimuli_block_block_struct;
	extern s_tag_block_definition ai_globals_custom_stimuli_block_block;
	extern s_tag_struct ai_trait_vision_block_block_struct;
	extern s_tag_block_definition ai_trait_vision_block_block;
	extern s_tag_struct ai_trait_sound_block_block_struct;
	extern s_tag_block_definition ai_trait_sound_block_block;
	extern s_tag_struct ai_trait_luck_block_block_struct;
	extern s_tag_block_definition ai_trait_luck_block_block;
	extern s_tag_struct ai_trait_grenade_block_block_struct;
	extern s_tag_block_definition ai_trait_grenade_block_block;

	extern s_tag_struct ai_globals_struct_definition_struct_definition; // tag group

} // namespace blofeld

