#pragma once

namespace blofeld
{

extern s_tag_struct ai_globals_struct_definition_struct_definition;

extern s_tag_struct ai_globals_data_block_struct_struct_definition;
extern s_tag_block_definition ai_globals_data_block;
extern s_tag_struct ai_globals_gravemind_block_struct_definition;
extern s_tag_block_definition ai_globals_gravemind_block;
extern s_tag_struct ai_globals_formation_block_struct_definition;
extern s_tag_block_definition ai_globals_formation_block;
extern s_tag_struct ai_globals_squad_template_folder_block_struct_struct_definition;
extern s_tag_block_definition ai_globals_squad_template_folder_block;
extern s_tag_struct ai_globals_squad_template_sub_folder_block_struct_struct_definition;
extern s_tag_block_definition ai_globals_squad_template_sub_folder_block;
extern s_tag_struct ai_globals_squad_template_block_struct_definition;
extern s_tag_block_definition ai_globals_squad_template_block;
extern s_tag_struct ai_globals_performance_template_folder_block_struct_struct_definition;
extern s_tag_block_definition ai_globals_performance_template_folder_block;
extern s_tag_struct ai_globals_performance_template_sub_folder_block_struct_struct_definition;
extern s_tag_block_definition ai_globals_performance_template_sub_folder_block;
extern s_tag_struct ai_globals_performance_template_block_struct_definition;
extern s_tag_block_definition ai_globals_performance_template_block;
extern s_tag_struct ai_globals_custom_stimuli_block_struct_definition;
extern s_tag_block_definition ai_globals_custom_stimuli_block;
extern s_tag_struct ai_trait_vision_block_struct_struct_definition;
extern s_tag_block_definition ai_trait_vision_block;
extern s_tag_struct ai_trait_sound_block_struct_struct_definition;
extern s_tag_block_definition ai_trait_sound_block;
extern s_tag_struct ai_trait_luck_block_struct_struct_definition;
extern s_tag_block_definition ai_trait_luck_block;
extern s_tag_struct ai_trait_grenade_block_struct_struct_definition;
extern s_tag_block_definition ai_trait_grenade_block;

constexpr unsigned long AI_GLOBALS_TAG = 'aigl';

extern s_tag_block_definition ai_globals_block;
extern s_tag_group ai_globals_group;
} // namespace blofeld

