#pragma once

namespace blofeld
{

extern s_tag_struct user_hint_volume_avoidance_struct_struct_definition;

extern s_tag_struct user_hint_block_struct_definition;
extern s_tag_block_definition user_hint_block;
extern s_tag_struct user_hint_line_segment_block_struct_definition;
extern s_tag_block_definition user_hint_line_segment_block;
extern s_tag_struct user_hint_parallelogram_block_struct_definition;
extern s_tag_block_definition user_hint_parallelogram_block;
extern s_tag_struct user_hint_jump_block_struct_definition;
extern s_tag_block_definition user_hint_jump_block;
extern s_tag_struct hint_vertex_block_struct_definition;
extern s_tag_block_definition hint_vertex_block;
extern s_tag_struct user_hint_climb_block_struct_definition;
extern s_tag_block_definition user_hint_climb_block;
extern s_tag_struct user_hint_well_block_struct_definition;
extern s_tag_block_definition user_hint_well_block;
extern s_tag_struct user_hint_well_point_block_struct_definition;
extern s_tag_block_definition user_hint_well_point_block;
extern s_tag_struct user_hint_flight_block_struct_definition;
extern s_tag_block_definition user_hint_flight_block;
extern s_tag_struct user_hint_flight_point_block_struct_definition;
extern s_tag_block_definition user_hint_flight_point_block;
extern s_tag_block_definition user_hint_volume_avoidance;
extern s_tag_struct user_hint_spline_block_struct_definition;
extern s_tag_block_definition user_hint_spline_block;
extern s_tag_struct user_hint_spline_control_point_block_struct_struct_definition;
extern s_tag_block_definition user_hint_spline_control_point_block;
extern s_tag_struct user_hint_spline_intersect_point_block_struct_struct_definition;
extern s_tag_block_definition user_hint_spline_intersect_point_block;
extern s_tag_struct user_hint_cookie_cutter_block_struct_struct_definition;
extern s_tag_block_definition user_hint_cookie_cutter_block;
extern s_tag_struct user_hint_sector_point_block_struct_definition;
extern s_tag_block_definition user_hint_sector_point_block;
extern s_tag_struct hint_object_id_block_struct_definition;
extern s_tag_block_definition hint_object_id_block;
extern s_tag_struct user_hint_navmesh_area_block_struct_struct_definition;
extern s_tag_block_definition user_hint_navmesh_area_block;
extern s_tag_struct user_hint_giant_block_struct_definition;
extern s_tag_block_definition user_hint_giant_block;
extern s_tag_struct user_hint_giant_sector_block_struct_definition;
extern s_tag_block_definition user_hint_giant_sector_block;
extern s_tag_struct user_hint_giant_rail_block_struct_definition;
extern s_tag_block_definition user_hint_giant_rail_block;
extern s_tag_struct user_hint_flood_block_struct_definition;
extern s_tag_block_definition user_hint_flood_block;
extern s_tag_struct user_hint_flood_sector_block_struct_definition;
extern s_tag_block_definition user_hint_flood_sector_block;
extern s_tag_struct special_movement_block_struct_definition;
extern s_tag_block_definition special_movement_block;

} // namespace blofeld

