#pragma once

namespace blofeld
{


	extern s_tag_block_definition PuppetPathPointBlock_block;
	extern s_tag_struct_definition PuppetActionBlock_block_struct;
	extern s_tag_block_definition PuppetActionBlock_block;
	extern s_tag_struct_definition PuppetSubActionBranchElementBlock_block_struct;
	extern s_tag_block_definition PuppetSubActionBranchElementBlock_block;
	extern s_tag_struct_definition PuppetScriptTextBlock_block_struct;
	extern s_tag_block_definition PuppetScriptTextBlock_block;
	extern s_tag_struct_definition PuppetSubActionBlock_block_struct;
	extern s_tag_block_definition PuppetSubActionBlock_block;
	extern s_tag_struct_definition SubTracksBlock_block_struct;
	extern s_tag_block_definition SubTracksBlock_block;
	extern s_tag_struct_definition PuppetBlock_block_struct;
	extern s_tag_block_definition PuppetBlock_block;
	extern s_tag_block_definition PuppetHeaderBlock_block;
	extern s_tag_block_definition PuppetActionHeaderBlock_block;
	extern s_tag_block_definition PuppetSubActionHeaderBlock_block;
	extern s_tag_block_definition PuppetAnimationBlock_block;
	extern s_tag_block_definition PuppetPathBlock_block;
	extern s_tag_block_definition PuppetPointBlock_block;
	extern s_tag_block_definition PuppetBranchBlock_block;
	extern s_tag_block_definition PuppetScriptBlock_block;
	extern s_tag_struct_definition CommentsBlock_block_struct;
	extern s_tag_block_definition CommentsBlock_block;
	extern s_tag_struct_definition PuppetShowsBlock_block_struct;
	extern s_tag_block_definition PuppetShowsBlock_block;


	extern s_tag_struct_definition PuppetHeaderStruct_struct_definition;
	extern s_tag_struct_definition PuppetPathPointStruct_struct_definition;
	extern s_tag_struct_definition PuppetActionHeaderStruct_struct_definition;
	extern s_tag_struct_definition PuppetActionAnimationStruct_struct_definition;
	extern s_tag_struct_definition PuppetActionPathStruct_struct_definition;
	extern s_tag_struct_definition PuppetSubActionHeaderStruct_struct_definition;
	extern s_tag_struct_definition PuppetSubActionPointStruct_struct_definition;
	extern s_tag_struct_definition PuppetSubActionBranchStruct_struct_definition;
	extern s_tag_struct_definition PuppetSubActionScriptStruct_struct_definition;

	extern const char* PuppetIndexTypeEnum_strings[];
	extern s_string_list_definition PuppetIndexTypeEnum;
	extern const char* PuppetActionTypeEnum_strings[];
	extern s_string_list_definition PuppetActionTypeEnum;
	extern const char* PuppetActionBlendTypeEnum_strings[];
	extern s_string_list_definition PuppetActionBlendTypeEnum;
	extern const char* PuppetSubActionTypeEnum_strings[];
	extern s_string_list_definition PuppetSubActionTypeEnum;
	extern const char* SubActionTimeTypeEnum_strings[];
	extern s_string_list_definition SubActionTimeTypeEnum;
	extern const char* PuppetPathPointTypeEnum_strings[];
	extern s_string_list_definition PuppetPathPointTypeEnum;
	extern const char* AnimPositionTypeEnum_strings[];
	extern s_string_list_definition AnimPositionTypeEnum;
	extern const char* PuppetPathPointFlagsDefinition_strings[];
	extern s_string_list_definition PuppetPathPointFlagsDefinition;
	extern const char* PuppetFlagsDefinition_strings[];
	extern s_string_list_definition PuppetFlagsDefinition;
	extern const char* PuppetShowFlagsDefinition_strings[];
	extern s_string_list_definition PuppetShowFlagsDefinition;
	extern const char* PuppetAnimationFlagsDefinition_strings[];
	extern s_string_list_definition PuppetAnimationFlagsDefinition;
	extern const char* SubActionPointFlagsDefinition_strings[];
	extern s_string_list_definition SubActionPointFlagsDefinition;
	extern const char* PuppetEditorFlagsDefinition_strings[];
	extern s_string_list_definition PuppetEditorFlagsDefinition;

} // namespace blofeld

