#pragma once

namespace blofeld
{

extern s_tag_struct PuppetPathPointStruct_struct_definition;
extern s_tag_struct PuppetHeaderStruct_struct_definition;
extern s_tag_struct PuppetActionHeaderStruct_struct_definition;
extern s_tag_struct PuppetSubActionHeaderStruct_struct_definition;
extern s_tag_struct PuppetActionAnimationStruct_struct_definition;
extern s_tag_struct PuppetActionPathStruct_struct_definition;
extern s_tag_struct PuppetSubActionPointStruct_struct_definition;
extern s_tag_struct PuppetSubActionBranchStruct_struct_definition;
extern s_tag_struct PuppetSubActionScriptStruct_struct_definition;

extern s_tag_struct PuppetShowsBlock_struct_definition;
extern s_tag_block_definition PuppetShowsBlock;
extern s_tag_struct PuppetBlock_struct_definition;
extern s_tag_block_definition PuppetBlock;
extern s_tag_struct PuppetActionBlock_struct_definition;
extern s_tag_block_definition PuppetActionBlock;
extern s_tag_block_definition PuppetPathPointBlock;
extern s_tag_struct PuppetSubActionBlock_struct_definition;
extern s_tag_block_definition PuppetSubActionBlock;
extern s_tag_struct PuppetSubActionBranchElementBlock_struct_definition;
extern s_tag_block_definition PuppetSubActionBranchElementBlock;
extern s_tag_struct PuppetScriptTextBlock_struct_definition;
extern s_tag_block_definition PuppetScriptTextBlock;
extern s_tag_struct SubTracksBlock_struct_definition;
extern s_tag_block_definition SubTracksBlock;
extern s_tag_block_definition PuppetHeaderBlock;
extern s_tag_block_definition PuppetActionHeaderBlock;
extern s_tag_block_definition PuppetSubActionHeaderBlock;
extern s_tag_block_definition PuppetAnimationBlock;
extern s_tag_block_definition PuppetPathBlock;
extern s_tag_block_definition PuppetPointBlock;
extern s_tag_block_definition PuppetBranchBlock;
extern s_tag_block_definition PuppetScriptBlock;
extern s_tag_struct CommentsBlock_struct_definition;
extern s_tag_block_definition CommentsBlock;

} // namespace blofeld

