#pragma once

namespace blofeld
{


extern s_tag_struct PuppetShowsBlock_block_struct;
extern s_tag_block_definition PuppetShowsBlock_block;
extern s_tag_struct PuppetBlock_block_struct;
extern s_tag_block_definition PuppetBlock_block;
extern s_tag_struct PuppetActionBlock_block_struct;
extern s_tag_block_definition PuppetActionBlock_block;
extern s_tag_block_definition PuppetPathPointBlock_block;
extern s_tag_struct PuppetSubActionBlock_block_struct;
extern s_tag_block_definition PuppetSubActionBlock_block;
extern s_tag_struct PuppetSubActionBranchElementBlock_block_struct;
extern s_tag_block_definition PuppetSubActionBranchElementBlock_block;
extern s_tag_struct PuppetScriptTextBlock_block_struct;
extern s_tag_block_definition PuppetScriptTextBlock_block;
extern s_tag_struct SubTracksBlock_block_struct;
extern s_tag_block_definition SubTracksBlock_block;
extern s_tag_block_definition PuppetHeaderBlock_block;
extern s_tag_block_definition PuppetActionHeaderBlock_block;
extern s_tag_block_definition PuppetSubActionHeaderBlock_block;
extern s_tag_block_definition PuppetAnimationBlock_block;
extern s_tag_block_definition PuppetPathBlock_block;
extern s_tag_block_definition PuppetPointBlock_block;
extern s_tag_block_definition PuppetBranchBlock_block;
extern s_tag_block_definition PuppetScriptBlock_block;
extern s_tag_struct CommentsBlock_block_struct;
extern s_tag_block_definition CommentsBlock_block;

extern s_tag_struct PuppetHeaderStruct_struct_definition;
extern s_tag_struct PuppetPathPointStruct_struct_definition;
extern s_tag_struct PuppetActionHeaderStruct_struct_definition;
extern s_tag_struct PuppetActionAnimationStruct_struct_definition;
extern s_tag_struct PuppetActionPathStruct_struct_definition;
extern s_tag_struct PuppetSubActionHeaderStruct_struct_definition;
extern s_tag_struct PuppetSubActionPointStruct_struct_definition;
extern s_tag_struct PuppetSubActionBranchStruct_struct_definition;
extern s_tag_struct PuppetSubActionScriptStruct_struct_definition;

} // namespace blofeld

