#pragma once

namespace blofeld
{

	extern s_tag_struct_definition squad_patrol_member_block_block_struct;
	extern s_tag_block_definition squad_patrol_member_block_block;
	extern s_tag_struct_definition squad_patrol_point_block_block_struct;
	extern s_tag_block_definition squad_patrol_point_block_block;
	extern s_tag_struct_definition squad_patrol_waypoint_block_block_struct;
	extern s_tag_block_definition squad_patrol_waypoint_block_block;
	extern s_tag_struct_definition squad_patrol_transition_block_block_struct;
	extern s_tag_block_definition squad_patrol_transition_block_block;
	extern s_tag_struct_definition squad_patrol_block_block_struct;
	extern s_tag_block_definition squad_patrol_block_block;


} // namespace blofeld

