#pragma once

namespace blofeld
{


extern s_tag_struct zone_block_block_struct;
extern s_tag_block_definition zone_block_block;
extern s_tag_struct areas_block_block_struct;
extern s_tag_block_definition areas_block_block;
extern s_tag_struct NavMeshAttachmentBlock_block_struct;
extern s_tag_block_definition NavMeshAttachmentBlock_block;
extern s_tag_struct flight_reference_block_block_struct;
extern s_tag_block_definition flight_reference_block_block;
extern s_tag_struct area_sector_point_block_block_struct;
extern s_tag_block_definition area_sector_point_block_block;

extern s_tag_struct NavMeshAttachmentsStruct_struct_definition;

} // namespace blofeld

