//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Resource.rc
//

typedef enum _RESOURCE_IDS
{
	#define IDI_ICON_APPLICATION 100
	#define IDI_ICON_BLAM_CREATION_SUITE 101
	#define IDI_ICON_MANDRILL 102
	#define IDR_FONT_COUSINE_REGULAR 200
	#define IDR_FONT_FONT_AWESOME_REGULAR 201
	#define IDR_FONT_FONT_AWESOME_SOLID 202
	#define IDR_FONT_FONT_AWESOME_BRANDS 203
	IDR_MAPDATABASE = 300,
	IDR_BOXSHADERPS,
	IDR_BOXSHADERVS,
	IDR_VIEWPORT_P_SHADER_VS,
	IDR_VIEWPORT_PC_SHADER_VS,
	IDR_VIEWPORT_PTCN_SHADER_VS,
	IDR_VIEWPORT_DEBUG_SHADER_PS,
	IDR_VIEWPORT_DEFAULT_SHADER_PS,
	IDR_GENERIC_INFINITE_VERTEX_SHADER,
	IDR_GENERIC_INFINITE_PIXEL_SHADER,
	IDR_GENERIC_LIGHTMAP_DEBUG_VERTEX_SHADER,
	IDR_GENERIC_LIGHTMAP_DEBUG_PIXEL_SHADER,
	IDR_GENERIC_LIGHTMAP_COMPUTE_TEST_SHADER,
} RESOURCE_IDS;

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        104
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
