#pragma once

namespace blofeld
{

extern s_tag_struct structureIOHavokDataBlock_struct_struct_definition;
extern s_tag_struct SerializedHavokGeometryDataBlock_struct_struct_definition;

extern s_tag_struct global_render_model_instance_placement_block_struct_definition;
extern s_tag_block_definition global_render_model_instance_placement_block;
extern s_tag_struct structure_bsp_instanced_geometry_instances_block_struct_definition;
extern s_tag_block_definition structure_bsp_instanced_geometry_instances_block;
extern s_tag_struct structure_bsp_instanced_geometry_instances_names_block_struct_definition;
extern s_tag_block_definition structure_bsp_instanced_geometry_instances_names_block;
extern s_tag_struct structure_bsp_instanced_geometry_definition_block_struct_definition;
extern s_tag_block_definition structure_bsp_instanced_geometry_definition_block;
extern s_tag_block_definition structureIOHavokDataBlock;
extern s_tag_block_definition SerializedHavokGeometryDataBlock;

} // namespace blofeld

