#pragma once

namespace blofeld
{

extern s_tag_struct instance_imposter_definition_struct_definition_struct_definition;

extern s_tag_struct instance_imposter_block_struct_definition;
extern s_tag_block_definition instance_imposter_block;
extern s_tag_struct instance_imposter_checksum_block_struct_definition;
extern s_tag_block_definition instance_imposter_checksum_block;

constexpr unsigned long INSTANCE_IMPOSTER_DEFINITION_TAG = 'iimz';

extern s_tag_block_definition instance_imposter_definition_block;
extern s_tag_group instance_imposter_definition_group;
} // namespace blofeld

