#pragma once

namespace blofeld
{


extern s_tag_struct structure_portal_device_mapping_block_struct_definition;
extern s_tag_block_definition structure_portal_device_mapping_block;
extern s_tag_struct structure_device_portal_association_block_struct_definition;
extern s_tag_block_definition structure_device_portal_association_block;
extern s_tag_struct game_portal_to_portal_mapping_block_struct_definition;
extern s_tag_block_definition game_portal_to_portal_mapping_block;
extern s_tag_struct occluding_portal_to_portal_mapping_block_struct_definition;
extern s_tag_block_definition occluding_portal_to_portal_mapping_block;

} // namespace blofeld

