#pragma once

namespace blofeld
{

extern s_tag_struct scenario_structure_lighting_info_struct_definition_struct_definition;
extern s_tag_struct structureLightingCinematicLightInstanceBlock_struct_struct_definition;

extern s_tag_struct structure_lighting_generic_light_definition_block_struct_definition;
extern s_tag_block_definition structure_lighting_generic_light_definition_block;
extern s_tag_struct structure_lighting_generic_light_instance_block_struct_definition;
extern s_tag_block_definition structure_lighting_generic_light_instance_block;
extern s_tag_struct screen_space_light_shader_override_block_struct_definition;
extern s_tag_block_definition screen_space_light_shader_override_block;
extern s_tag_block_definition structureLightingCinematicLightInstanceBlock;
extern s_tag_struct structureLightingCinematicObjectBlock_struct_definition;
extern s_tag_block_definition structureLightingCinematicObjectBlock;

constexpr unsigned long SCENARIO_STRUCTURE_LIGHTING_INFO_TAG = 'stli';

extern s_tag_block_definition scenario_structure_lighting_info_block;
extern s_tag_group scenario_structure_lighting_info_group;
} // namespace blofeld

