#pragma once

namespace blofeld
{

extern s_tag_struct structure_seams_struct_definition_struct_definition;
extern s_tag_struct structure_seam_identifier_struct_struct_definition;
extern s_tag_struct structure_seam_original_geometry_struct_struct_definition;
extern s_tag_struct structure_seam_final_geometry_struct_struct_definition;

extern s_tag_struct structure_seam_mapping_block_struct_definition;
extern s_tag_block_definition structure_seam_mapping_block;
extern s_tag_struct structure_seam_edge_mapping_block_struct_definition;
extern s_tag_block_definition structure_seam_edge_mapping_block;
extern s_tag_struct structure_seam_cluster_mapping_block_struct_definition;
extern s_tag_block_definition structure_seam_cluster_mapping_block;
extern s_tag_struct structure_seam_block_struct_definition;
extern s_tag_block_definition structure_seam_block;
extern s_tag_struct structure_seam_original_vertex_block_struct_definition;
extern s_tag_block_definition structure_seam_original_vertex_block;
extern s_tag_struct structure_seam_original_vertex_plane_normals_block_struct_definition;
extern s_tag_block_definition structure_seam_original_vertex_plane_normals_block;
extern s_tag_struct structure_seam_final_planes_block_struct_definition;
extern s_tag_block_definition structure_seam_final_planes_block;
extern s_tag_struct structure_seam_final_points_block_struct_definition;
extern s_tag_block_definition structure_seam_final_points_block;
extern s_tag_struct structure_seam_final_triangles_block_struct_definition;
extern s_tag_block_definition structure_seam_final_triangles_block;
extern s_tag_struct structure_seam_final_edges_block_struct_definition;
extern s_tag_block_definition structure_seam_final_edges_block;

constexpr unsigned long STRUCTURE_SEAMS_TAG = 'stse';

extern s_tag_block_definition structure_seams_block;
extern s_tag_group structure_seams_group;
} // namespace blofeld

