#pragma once

namespace blofeld
{

constexpr unsigned long PREFAB_TAG = 'prfb';

extern s_tag_group prefab_group;
constexpr unsigned long SCENARIO_STRUCTURE_BSP_TAG = 'sbsp';

extern s_tag_struct scenario_structure_bsp_block_struct;
extern s_tag_block_definition scenario_structure_bsp_block;
extern s_tag_group scenario_structure_bsp_group;

extern s_tag_block_definition prefab_block_block;
extern s_tag_struct structure_edge_to_seam_edge_mapping_block_block_struct;
extern s_tag_block_definition structure_edge_to_seam_edge_mapping_block_block;
extern s_tag_struct structure_collision_materials_block_block_struct;
extern s_tag_block_definition structure_collision_materials_block_block;
extern s_tag_struct structure_bsp_leaf_block_block_struct;
extern s_tag_block_definition structure_bsp_leaf_block_block;
extern s_tag_struct structure_super_node_aabbs_block_block_struct;
extern s_tag_block_definition structure_super_node_aabbs_block_block;
extern s_tag_struct super_node_mappings_block_block_struct;
extern s_tag_block_definition super_node_mappings_block_block;
extern s_tag_struct super_node_recursable_masks_block_block_struct;
extern s_tag_block_definition super_node_recursable_masks_block_block;
extern s_tag_struct structure_super_node_traversal_geometry_block_block_struct;
extern s_tag_block_definition structure_super_node_traversal_geometry_block_block;
extern s_tag_struct structure_super_node_traversal_geometry_indices_block_block_struct;
extern s_tag_block_definition structure_super_node_traversal_geometry_indices_block_block;
extern s_tag_struct structure_surface_block_block_struct;
extern s_tag_block_definition structure_surface_block_block;
extern s_tag_struct structure_surface_to_triangle_mapping_block_block_struct;
extern s_tag_block_definition structure_surface_to_triangle_mapping_block_block;
extern s_tag_struct structure_bsp_cluster_portal_block_block_struct;
extern s_tag_block_definition structure_bsp_cluster_portal_block_block;
extern s_tag_struct structure_bsp_cluster_portal_vertex_block_block_struct;
extern s_tag_block_definition structure_bsp_cluster_portal_vertex_block_block;
extern s_tag_struct structure_bsp_detail_object_data_block_block_struct;
extern s_tag_block_definition structure_bsp_detail_object_data_block_block;
extern s_tag_struct structure_bsp_cluster_block_block_struct;
extern s_tag_block_definition structure_bsp_cluster_block_block;
extern s_tag_struct structure_bsp_cluster_portal_index_block_block_struct;
extern s_tag_block_definition structure_bsp_cluster_portal_index_block_block;
extern s_tag_struct seam_indices_block_definition_block_struct;
extern s_tag_block_definition seam_indices_block_definition_block;
extern s_tag_struct cheap_light_marker_ref_block_block_struct;
extern s_tag_block_definition cheap_light_marker_ref_block_block;
extern s_tag_struct pvs_bound_object_identifiers_block_block_struct;
extern s_tag_block_definition pvs_bound_object_identifiers_block_block;
extern s_tag_struct pvs_bound_object_references_block_block_struct;
extern s_tag_block_definition pvs_bound_object_references_block_block;
extern s_tag_struct structure_material_lighting_info_block_block_struct;
extern s_tag_block_definition structure_material_lighting_info_block_block;
extern s_tag_struct structure_bsp_sky_owner_cluster_block_block_struct;
extern s_tag_block_definition structure_bsp_sky_owner_cluster_block_block;
extern s_tag_struct structure_bsp_conveyor_surface_block_block_struct;
extern s_tag_block_definition structure_bsp_conveyor_surface_block_block;
extern s_tag_struct structure_cookie_cutter_definition_block_struct;
extern s_tag_block_definition structure_cookie_cutter_definition_block;
extern s_tag_struct structure_bsp_marker_block_block_struct;
extern s_tag_block_definition structure_bsp_marker_block_block;
extern s_tag_struct structure_bsp_marker_light_palette_block_struct;
extern s_tag_block_definition structure_bsp_marker_light_palette_block;
extern s_tag_struct structure_bsp_marker_light_index_block_struct;
extern s_tag_block_definition structure_bsp_marker_light_index_block;
extern s_tag_struct structure_bsp_runtime_decal_block_block_struct;
extern s_tag_block_definition structure_bsp_runtime_decal_block_block;
extern s_tag_struct structure_bsp_environment_object_palette_block_block_struct;
extern s_tag_block_definition structure_bsp_environment_object_palette_block_block;
extern s_tag_struct structure_bsp_environment_object_block_block_struct;
extern s_tag_block_definition structure_bsp_environment_object_block_block;
extern s_tag_struct structure_instance_cluster_definition_block_struct;
extern s_tag_block_definition structure_instance_cluster_definition_block;
extern s_tag_struct index_list_block_block_struct;
extern s_tag_block_definition index_list_block_block;
extern s_tag_struct structure_instance_group_definition_block_struct;
extern s_tag_block_definition structure_instance_group_definition_block;
extern s_tag_struct structure_instance_imposter_info_block_block_struct;
extern s_tag_block_definition structure_instance_imposter_info_block_block;
extern s_tag_struct runtime_decorator_set_block_block_struct;
extern s_tag_block_definition runtime_decorator_set_block_block;
extern s_tag_struct bsp_preplaced_decal_set_reference_block_block_struct;
extern s_tag_block_definition bsp_preplaced_decal_set_reference_block_block;
extern s_tag_struct bsp_preplaced_decal_reference_block_block_struct;
extern s_tag_block_definition bsp_preplaced_decal_reference_block_block;
extern s_tag_struct transparent_planes_block_block_struct;
extern s_tag_block_definition transparent_planes_block_block;
extern s_tag_struct structure_bsp_debug_info_block_block_struct;
extern s_tag_block_definition structure_bsp_debug_info_block_block;
extern s_tag_struct structure_bsp_cluster_debug_info_block_block_struct;
extern s_tag_block_definition structure_bsp_cluster_debug_info_block_block;
extern s_tag_struct structure_bsp_debug_info_render_line_block_block_struct;
extern s_tag_block_definition structure_bsp_debug_info_render_line_block_block;
extern s_tag_struct structure_bsp_debug_info_indices_block_block_struct;
extern s_tag_block_definition structure_bsp_debug_info_indices_block_block;
extern s_tag_struct structure_bsp_fog_plane_debug_info_block_block_struct;
extern s_tag_block_definition structure_bsp_fog_plane_debug_info_block_block;
extern s_tag_struct structure_bsp_fog_zone_debug_info_block_block_struct;
extern s_tag_block_definition structure_bsp_fog_zone_debug_info_block_block;
extern s_tag_struct widget_reference_block_block_struct;
extern s_tag_block_definition widget_reference_block_block;
extern s_tag_struct cheap_light_reference_block_block_struct;
extern s_tag_block_definition cheap_light_reference_block_block;
extern s_tag_struct structure_bsp_raw_resources_block_struct;
extern s_tag_block_definition structure_bsp_raw_resources_block;
extern s_tag_struct structure_external_instanced_geometry_references_block_block_struct;
extern s_tag_block_definition structure_external_instanced_geometry_references_block_block;
extern s_tag_struct structure_bsp_obb_volume_block_block_struct;
extern s_tag_block_definition structure_bsp_obb_volume_block_block;
extern s_tag_struct AnimGraphDependencyBlock_block_struct;
extern s_tag_block_definition AnimGraphDependencyBlock_block;
extern s_tag_struct structureBspFxMarkerBlock_block_struct;
extern s_tag_block_definition structureBspFxMarkerBlock_block;
extern s_tag_struct structureMetadataLightConeMarkerBlock_block_struct;
extern s_tag_block_definition structureMetadataLightConeMarkerBlock_block;

extern s_tag_struct prefab_struct_definition_struct_definition; // tag group
extern s_tag_struct structure_bsp_cluster_portal_oriented_bounds_block_struct_definition;
extern s_tag_struct structure_bsp_resource_interface_struct_definition;
extern s_tag_struct structure_bsp_resource_struct_struct_definition;

} // namespace blofeld

