#pragma once

namespace blofeld
{

extern s_tag_struct cinematic_scene_struct_definition_struct_definition;
extern s_tag_struct cinematic_scene_data_struct_definition_struct_definition;
extern s_tag_struct cinematicSceneDataObjectBlock_struct_struct_definition;
extern s_tag_struct scenario_cutscene_title_struct_struct_definition;
extern s_tag_struct cinematic_playback_data_block_struct_definition;
extern s_tag_struct scenario_and_zone_set_struct_struct_definition;
extern s_tag_struct cinematic_custom_script_block_struct_definition;
extern s_tag_struct camera_frame_struct_struct_definition;
extern s_tag_struct camera_frame_dynamic_struct_struct_definition;
extern s_tag_struct camera_frame_constant_struct_struct_definition;
extern s_tag_struct cinematic_transition_element_block_struct_definition;
extern s_tag_struct cinematic_transition_global_fade_block_struct_definition;

extern s_tag_struct cinematic_shot_playback_data_block_struct_definition;
extern s_tag_block_definition cinematic_shot_playback_data_block;
extern s_tag_struct cinematic_scene_reference_block_struct_definition;
extern s_tag_block_definition cinematic_scene_reference_block;
extern s_tag_struct cinematic_scene_object_block_struct_struct_definition;
extern s_tag_block_definition cinematic_scene_object_block;
extern s_tag_struct scene_object_attachment_block_struct_definition;
extern s_tag_block_definition scene_object_attachment_block;
extern s_tag_struct cinematic_shot_block_struct_struct_definition;
extern s_tag_block_definition cinematic_shot_block;
extern s_tag_struct cinematic_shot_lighting_block_struct_definition;
extern s_tag_block_definition cinematic_shot_lighting_block;
extern s_tag_struct cinematic_shot_clip_block_struct_definition;
extern s_tag_block_definition cinematic_shot_clip_block;
extern s_tag_struct cinematic_shot_clip_subject_block_struct_definition;
extern s_tag_block_definition cinematic_shot_clip_subject_block;
extern s_tag_struct cinematic_shot_music_block_struct_definition;
extern s_tag_block_definition cinematic_shot_music_block;
extern s_tag_struct cinematic_shot_object_function_block_struct_definition;
extern s_tag_block_definition cinematic_shot_object_function_block;
extern s_tag_struct cinematic_shot_object_function_keyframe_block_struct_definition;
extern s_tag_block_definition cinematic_shot_object_function_keyframe_block;
extern s_tag_struct cinematic_shot_screen_effect_block_struct_definition;
extern s_tag_block_definition cinematic_shot_screen_effect_block;
extern s_tag_struct cinematic_shot_user_input_constraints_block_struct_definition;
extern s_tag_block_definition cinematic_shot_user_input_constraints_block;
extern s_tag_struct cinematicShotTextureMovieBlock_struct_definition;
extern s_tag_block_definition cinematicShotTextureMovieBlock;
extern s_tag_struct cinematicStructureLightingBlock_struct_definition;
extern s_tag_block_definition cinematicStructureLightingBlock;
extern s_tag_block_definition cinematicSceneDataObjectBlock;
extern s_tag_struct cinematicDataShotBlock_struct_definition;
extern s_tag_block_definition cinematicDataShotBlock;
extern s_tag_struct cinematic_shot_dialogue_block_struct_definition;
extern s_tag_block_definition cinematic_shot_dialogue_block;
extern s_tag_struct cinematic_shot_effect_block_struct_definition;
extern s_tag_block_definition cinematic_shot_effect_block;
extern s_tag_struct cinematic_shot_custom_script_block_struct_definition;
extern s_tag_block_definition cinematic_shot_custom_script_block;
extern s_tag_struct cinematic_shot_frame_block_struct_definition;
extern s_tag_block_definition cinematic_shot_frame_block;
extern s_tag_struct cinematic_shot_frame_dynamic_block_struct_definition;
extern s_tag_block_definition cinematic_shot_frame_dynamic_block;
extern s_tag_struct cinematic_shot_frame_constant_block_struct_definition;
extern s_tag_block_definition cinematic_shot_frame_constant_block;
extern s_tag_struct cinematic_shot_extra_camera_block_struct_definition;
extern s_tag_block_definition cinematic_shot_extra_camera_block;
extern s_tag_struct cinematic_extra_camera_shot_block_struct_definition;
extern s_tag_block_definition cinematic_extra_camera_shot_block;
extern s_tag_struct cinematic_extra_camera_frame_block_struct_definition;
extern s_tag_block_definition cinematic_extra_camera_frame_block;
extern s_tag_struct cinematic_transition_global_gain_block_struct_struct_definition;
extern s_tag_block_definition cinematic_transition_global_gain_block;
extern s_tag_struct cinematic_transition_sound_class_gain_block_struct_struct_definition;
extern s_tag_block_definition cinematic_transition_sound_class_gain_block;
extern s_tag_struct cinematic_transition_sound_reference_block_struct_struct_definition;
extern s_tag_block_definition cinematic_transition_sound_reference_block;
extern s_tag_struct cinematic_transition_looping_sound_reference_block_struct_struct_definition;
extern s_tag_block_definition cinematic_transition_looping_sound_reference_block;
extern s_tag_struct cinematic_transition_looping_sound_state_block_struct_struct_definition;
extern s_tag_block_definition cinematic_transition_looping_sound_state_block;
extern s_tag_struct cinematics_globals_block_struct_definition;
extern s_tag_block_definition cinematics_globals_block;
extern s_tag_struct cinematic_characters_block_struct_definition;
extern s_tag_block_definition cinematic_characters_block;
extern s_tag_block_definition scenario_cutscene_title_block;
extern s_tag_struct scenario_cinematics_block_struct_definition;
extern s_tag_block_definition scenario_cinematics_block;

constexpr unsigned long CINEMATIC_TAG = 'cine';

extern s_tag_block_definition cinematic_block;
extern s_tag_group cinematic_group;
constexpr unsigned long CINEMATIC_SCENE_TAG = 'cisc';

extern s_tag_block_definition cinematic_scene_block;
extern s_tag_group cinematic_scene_group;
constexpr unsigned long CINEMATIC_SCENE_DATA_TAG = 'cisd';

extern s_tag_block_definition cinematic_scene_data_block;
extern s_tag_group cinematic_scene_data_group;
constexpr unsigned long CINEMATIC_TRANSITION_TAG = 'citr';

extern s_tag_block_definition cinematic_transition_block;
extern s_tag_group cinematic_transition_group;
} // namespace blofeld

