#pragma once

namespace blofeld
{

constexpr unsigned long CINEMATIC_TAG = 'cine';

extern s_tag_struct cinematic_block_struct;
extern s_tag_block_definition cinematic_block;
extern s_tag_group cinematic_group;
constexpr unsigned long CINEMATIC_SCENE_TAG = 'cisc';

extern s_tag_group cinematic_scene_group;
constexpr unsigned long CINEMATIC_SCENE_DATA_TAG = 'cisd';

extern s_tag_group cinematic_scene_data_group;
constexpr unsigned long CINEMATIC_TRANSITION_TAG = 'citr';

extern s_tag_struct cinematic_transition_block_struct;
extern s_tag_block_definition cinematic_transition_block;
extern s_tag_group cinematic_transition_group;

extern s_tag_block_definition cinematic_scene_block_block;
extern s_tag_block_definition cinematic_scene_data_block_block;
extern s_tag_struct cinematic_shot_playback_data_block_block_struct;
extern s_tag_block_definition cinematic_shot_playback_data_block_block;
extern s_tag_struct cinematic_scene_reference_block_block_struct;
extern s_tag_block_definition cinematic_scene_reference_block_block;
extern s_tag_struct cinematic_scene_object_block_block_struct;
extern s_tag_block_definition cinematic_scene_object_block_block;
extern s_tag_struct scene_object_attachment_block_block_struct;
extern s_tag_block_definition scene_object_attachment_block_block;
extern s_tag_struct cinematic_shot_block_block_struct;
extern s_tag_block_definition cinematic_shot_block_block;
extern s_tag_struct cinematic_shot_lighting_block_block_struct;
extern s_tag_block_definition cinematic_shot_lighting_block_block;
extern s_tag_struct cinematic_shot_clip_block_block_struct;
extern s_tag_block_definition cinematic_shot_clip_block_block;
extern s_tag_struct cinematic_shot_clip_subject_block_block_struct;
extern s_tag_block_definition cinematic_shot_clip_subject_block_block;
extern s_tag_struct cinematic_shot_music_block_block_struct;
extern s_tag_block_definition cinematic_shot_music_block_block;
extern s_tag_struct cinematic_shot_object_function_block_block_struct;
extern s_tag_block_definition cinematic_shot_object_function_block_block;
extern s_tag_struct cinematic_shot_object_function_keyframe_block_block_struct;
extern s_tag_block_definition cinematic_shot_object_function_keyframe_block_block;
extern s_tag_struct cinematic_shot_screen_effect_block_block_struct;
extern s_tag_block_definition cinematic_shot_screen_effect_block_block;
extern s_tag_struct cinematic_shot_user_input_constraints_block_block_struct;
extern s_tag_block_definition cinematic_shot_user_input_constraints_block_block;
extern s_tag_struct cinematicShotTextureMovieBlock_block_struct;
extern s_tag_block_definition cinematicShotTextureMovieBlock_block;
extern s_tag_struct cinematicStructureLightingBlock_block_struct;
extern s_tag_block_definition cinematicStructureLightingBlock_block;
extern s_tag_block_definition cinematicSceneDataObjectBlock_block;
extern s_tag_struct cinematicDataShotBlock_block_struct;
extern s_tag_block_definition cinematicDataShotBlock_block;
extern s_tag_struct cinematic_shot_dialogue_block_block_struct;
extern s_tag_block_definition cinematic_shot_dialogue_block_block;
extern s_tag_struct cinematic_shot_effect_block_block_struct;
extern s_tag_block_definition cinematic_shot_effect_block_block;
extern s_tag_struct cinematic_shot_custom_script_block_block_struct;
extern s_tag_block_definition cinematic_shot_custom_script_block_block;
extern s_tag_struct cinematic_shot_frame_block_block_struct;
extern s_tag_block_definition cinematic_shot_frame_block_block;
extern s_tag_struct cinematic_shot_frame_dynamic_block_block_struct;
extern s_tag_block_definition cinematic_shot_frame_dynamic_block_block;
extern s_tag_struct cinematic_shot_frame_constant_block_block_struct;
extern s_tag_block_definition cinematic_shot_frame_constant_block_block;
extern s_tag_struct cinematic_shot_extra_camera_block_block_struct;
extern s_tag_block_definition cinematic_shot_extra_camera_block_block;
extern s_tag_struct cinematic_extra_camera_shot_block_block_struct;
extern s_tag_block_definition cinematic_extra_camera_shot_block_block;
extern s_tag_struct cinematic_extra_camera_frame_block_block_struct;
extern s_tag_block_definition cinematic_extra_camera_frame_block_block;
extern s_tag_struct cinematic_transition_global_gain_block_block_struct;
extern s_tag_block_definition cinematic_transition_global_gain_block_block;
extern s_tag_struct cinematic_transition_sound_class_gain_block_block_struct;
extern s_tag_block_definition cinematic_transition_sound_class_gain_block_block;
extern s_tag_struct cinematic_transition_sound_reference_block_block_struct;
extern s_tag_block_definition cinematic_transition_sound_reference_block_block;
extern s_tag_struct cinematic_transition_looping_sound_reference_block_block_struct;
extern s_tag_block_definition cinematic_transition_looping_sound_reference_block_block;
extern s_tag_struct cinematic_transition_looping_sound_state_block_block_struct;
extern s_tag_block_definition cinematic_transition_looping_sound_state_block_block;
extern s_tag_struct cinematics_globals_block_block_struct;
extern s_tag_block_definition cinematics_globals_block_block;
extern s_tag_struct cinematic_characters_block_block_struct;
extern s_tag_block_definition cinematic_characters_block_block;
extern s_tag_block_definition scenario_cutscene_title_block_block;
extern s_tag_struct scenario_cinematics_block_block_struct;
extern s_tag_block_definition scenario_cinematics_block_block;

extern s_tag_struct cinematic_scene_struct_definition_struct_definition; // tag group
extern s_tag_struct cinematic_scene_data_struct_definition_struct_definition; // tag group
extern s_tag_struct cinematicSceneDataObjectBlock_struct_struct_definition;
extern s_tag_struct scenario_cutscene_title_struct_struct_definition;
extern s_tag_struct cinematic_playback_data_block_struct_definition;
extern s_tag_struct scenario_and_zone_set_struct_struct_definition;
extern s_tag_struct cinematic_custom_script_block_struct_definition;
extern s_tag_struct camera_frame_struct_struct_definition;
extern s_tag_struct camera_frame_dynamic_struct_struct_definition;
extern s_tag_struct camera_frame_constant_struct_struct_definition;
extern s_tag_struct cinematic_transition_element_block_struct_definition;
extern s_tag_struct cinematic_transition_global_fade_block_struct_definition;

} // namespace blofeld

