#pragma once

namespace blofeld
{



	constexpr unsigned long EQUIPMENT_TAG = 'eqip';
	extern s_tag_group equipment_group; // equipment_block


	extern s_tag_block_definition equipment_block;
	extern s_tag_block_definition optionalUnitCameraBlock_block;
	extern s_tag_struct_definition optionalUnitCameraBlock_block_struct_definition; // optionalUnitCameraBlock_block
	extern s_tag_block_definition equipmentAbilityDatum_block;
	extern s_tag_struct_definition equipmentAbilityDatum_block_struct_definition; // equipmentAbilityDatum_block
	extern s_tag_block_definition equipmentAbilityTypeMultiplayerPowerupBlock_block;
	extern s_tag_struct_definition equipmentAbilityTypeMultiplayerPowerupBlock_block_struct_definition; // equipmentAbilityTypeMultiplayerPowerupBlock_block
	extern s_tag_block_definition equipmentAbilityTypeSpawnerBlock_block;
	extern s_tag_struct_definition equipmentAbilityTypeSpawnerBlock_block_struct_definition; // equipmentAbilityTypeSpawnerBlock_block
	extern s_tag_block_definition equipmentAbilityTypeAiSpawnerBlock_block;
	extern s_tag_struct_definition equipmentAbilityTypeAiSpawnerBlock_block_struct_definition; // equipmentAbilityTypeAiSpawnerBlock_block
	extern s_tag_block_definition equipmentAbilityTypeProximityMineBlock_block;
	extern s_tag_struct_definition equipmentAbilityTypeProximityMineBlock_block_struct_definition; // equipmentAbilityTypeProximityMineBlock_block
	extern s_tag_block_definition equipmentAbilityTypeMotionTrackerNoiseBlock_block;
	extern s_tag_struct_definition equipmentAbilityTypeMotionTrackerNoiseBlock_block_struct_definition; // equipmentAbilityTypeMotionTrackerNoiseBlock_block
	extern s_tag_block_definition equipmentAbilityTypeInvincibilityBlock_block;
	extern s_tag_struct_definition equipmentAbilityTypeInvincibilityBlock_block_struct_definition; // equipmentAbilityTypeInvincibilityBlock_block
	extern s_tag_block_definition equipmentEffectWithThresholdBlock_block;
	extern s_tag_struct_definition equipmentEffectWithThresholdBlock_block_struct_definition; // equipmentEffectWithThresholdBlock_block
	extern s_tag_block_definition equipmentAbilityTypeTreeOfLifeBlock_block;
	extern s_tag_struct_definition equipmentAbilityTypeTreeOfLifeBlock_block_struct_definition; // equipmentAbilityTypeTreeOfLifeBlock_block
	extern s_tag_block_definition equipmentAbilityTypeShapeshifterBlock_block;
	extern s_tag_struct_definition equipmentAbilityTypeShapeshifterBlock_block_struct_definition; // equipmentAbilityTypeShapeshifterBlock_block
	extern s_tag_block_definition equipmentAbilityTypePlayerTraitFieldBlock_block;
	extern s_tag_struct_definition equipmentAbilityTypePlayerTraitFieldBlock_block_struct_definition; // equipmentAbilityTypePlayerTraitFieldBlock_block
	extern s_tag_block_definition equipmentAbilityTypeAiTraitFieldBlock_block;
	extern s_tag_struct_definition equipmentAbilityTypeAiTraitFieldBlock_block_struct_definition; // equipmentAbilityTypeAiTraitFieldBlock_block
	extern s_tag_block_definition aiEquipmentTraitsBlock_block;
	extern s_tag_struct_definition aiEquipmentTraitsBlock_block_struct_definition; // aiEquipmentTraitsBlock_block
	extern s_tag_block_definition aiEquipmentTraitAppearanceBlock_block;
	extern s_tag_struct_definition aiEquipmentTraitAppearanceBlock_block_struct_definition; // aiEquipmentTraitAppearanceBlock_block
	extern s_tag_block_definition equipmentAbilityTypeRepulsorFieldBlock_block;
	extern s_tag_struct_definition equipmentAbilityTypeRepulsorFieldBlock_block_struct_definition; // equipmentAbilityTypeRepulsorFieldBlock_block
	extern s_tag_block_definition equipmentAbilityTypeStasisFieldBlock_block;
	extern s_tag_struct_definition equipmentAbilityTypeStasisFieldBlock_block_struct_definition; // equipmentAbilityTypeStasisFieldBlock_block
	extern s_tag_block_definition equipmentAbilityTypeBallLightningBlock_block;
	extern s_tag_struct_definition equipmentAbilityTypeBallLightningBlock_block_struct_definition; // equipmentAbilityTypeBallLightningBlock_block
	extern s_tag_block_definition equipmentAbilityTypeDaddyBlock_block;
	extern s_tag_struct_definition equipmentAbilityTypeDaddyBlock_block_struct_definition; // equipmentAbilityTypeDaddyBlock_block
	extern s_tag_block_definition equipmentAbilityTypeLaserDesignationBlock_block;
	extern s_tag_struct_definition equipmentAbilityTypeLaserDesignationBlock_block_struct_definition; // equipmentAbilityTypeLaserDesignationBlock_block
	extern s_tag_block_definition equipmentAbilityTypeSuperJumpBlock_block;
	extern s_tag_struct_definition equipmentAbilityTypeSuperJumpBlock_block_struct_definition; // equipmentAbilityTypeSuperJumpBlock_block
	extern s_tag_block_definition equipmentAbilityTypeAmmoPackBlock_block;
	extern s_tag_struct_definition equipmentAbilityTypeAmmoPackBlock_block_struct_definition; // equipmentAbilityTypeAmmoPackBlock_block
	extern s_tag_block_definition equipmentAbilityTypePowerFistBlock_block;
	extern s_tag_struct_definition equipmentAbilityTypePowerFistBlock_block_struct_definition; // equipmentAbilityTypePowerFistBlock_block
	extern s_tag_block_definition equipmentAbilityTypeHealthPackBlock_block;
	extern s_tag_struct_definition equipmentAbilityTypeHealthPackBlock_block_struct_definition; // equipmentAbilityTypeHealthPackBlock_block
	extern s_tag_block_definition equipmentAbilityTypeJetPackBlock_block;
	extern s_tag_struct_definition equipmentAbilityTypeJetPackBlock_block_struct_definition; // equipmentAbilityTypeJetPackBlock_block
	extern s_tag_block_definition equipmentAbilityPartCowCatcherBlock_block;
	extern s_tag_struct_definition equipmentAbilityPartCowCatcherBlock_block_struct_definition; // equipmentAbilityPartCowCatcherBlock_block
	extern s_tag_block_definition equipmentAbilityTypeHologramBlock_block;
	extern s_tag_struct_definition equipmentAbilityTypeHologramBlock_block_struct_definition; // equipmentAbilityTypeHologramBlock_block
	extern s_tag_block_definition equipmentAbilityTypeSpecialWeaponBlock_block;
	extern s_tag_struct_definition equipmentAbilityTypeSpecialWeaponBlock_block_struct_definition; // equipmentAbilityTypeSpecialWeaponBlock_block
	extern s_tag_block_definition equipmentAbilityTypeSpecialMoveBlock_block;
	extern s_tag_struct_definition equipmentAbilityTypeSpecialMoveBlock_block_struct_definition; // equipmentAbilityTypeSpecialMoveBlock_block
	extern s_tag_block_definition equipmentAbilityTypeEngineerShieldsBlock_block;
	extern s_tag_struct_definition equipmentAbilityTypeEngineerShieldsBlock_block_struct_definition; // equipmentAbilityTypeEngineerShieldsBlock_block
	extern s_tag_block_definition equipmentAbilityTypeSprintBlock_block;
	extern s_tag_struct_definition equipmentAbilityTypeSprintBlock_block_struct_definition; // equipmentAbilityTypeSprintBlock_block
	extern s_tag_block_definition equipmentAbilityTypeTeleporterBlock_block;
	extern s_tag_struct_definition equipmentAbilityTypeTeleporterBlock_block_struct_definition; // equipmentAbilityTypeTeleporterBlock_block
	extern s_tag_block_definition equipmentAbilityTypeAutoTurretBlock_block;
	extern s_tag_struct_definition equipmentAbilityTypeAutoTurretBlock_block_struct_definition; // equipmentAbilityTypeAutoTurretBlock_block
	extern s_tag_block_definition equipmentAbilityTypeVisionModeBlock_block;
	extern s_tag_struct_definition equipmentAbilityTypeVisionModeBlock_block_struct_definition; // equipmentAbilityTypeVisionModeBlock_block
	extern s_tag_block_definition equipmentAbilityTypeShieldProjectorBlock_block;
	extern s_tag_struct_definition equipmentAbilityTypeShieldProjectorBlock_block_struct_definition; // equipmentAbilityTypeShieldProjectorBlock_block
	extern s_tag_block_definition equipmentAbilityTypeProjectileCollectorBlock_block;
	extern s_tag_struct_definition equipmentAbilityTypeProjectileCollectorBlock_block_struct_definition; // equipmentAbilityTypeProjectileCollectorBlock_block
	extern s_tag_block_definition equipmentAbilityTypeRemoteStrikeBlock_block;
	extern s_tag_struct_definition equipmentAbilityTypeRemoteStrikeBlock_block_struct_definition; // equipmentAbilityTypeRemoteStrikeBlock_block
	extern s_tag_block_definition equipmentAbilityTypeEquipmentHackerBlock_block;
	extern s_tag_struct_definition equipmentAbilityTypeEquipmentHackerBlock_block_struct_definition; // equipmentAbilityTypeEquipmentHackerBlock_block
	extern s_tag_block_definition equipmentHackerDrainLevel_block;
	extern s_tag_struct_definition equipmentHackerDrainLevel_block_struct_definition; // equipmentHackerDrainLevel_block
	extern s_tag_block_definition equipmentAbilityTypeRemoteVehicleBlock_block;
	extern s_tag_struct_definition equipmentAbilityTypeRemoteVehicleBlock_block_struct_definition; // equipmentAbilityTypeRemoteVehicleBlock_block
	extern s_tag_block_definition equipmentAbilityTypeSuicideBombBlock_block;
	extern s_tag_struct_definition equipmentAbilityTypeSuicideBombBlock_block_struct_definition; // equipmentAbilityTypeSuicideBombBlock_block
	extern s_tag_block_definition equipmentAbilityTypeActiveShieldBlock_block;
	extern s_tag_struct_definition equipmentAbilityTypeActiveShieldBlock_block_struct_definition; // equipmentAbilityTypeActiveShieldBlock_block
	extern s_tag_block_definition EquipmentSoundRTPCBlock_block;
	extern s_tag_struct_definition EquipmentSoundRTPCBlock_block_struct_definition; // EquipmentSoundRTPCBlock_block
	extern s_tag_block_definition EquipmentSoundSweetenerBlock_block;
	extern s_tag_struct_definition EquipmentSoundSweetenerBlock_block_struct_definition; // EquipmentSoundSweetenerBlock_block

	extern s_tag_struct_definition equipment_struct_definition; // tag group

	extern s_string_list_definition multiplayer_powerup_flavor;
	extern s_string_list_definition equipment_spawner_spawn_type;
	extern s_string_list_definition equipmentAbilityType_MotionTrackerNoise_flags;
	extern s_string_list_definition equipmentAbilityType_treeoflife_flags;
	extern s_string_list_definition repulsor_field_flags;
	extern s_string_list_definition equipmentAbilityTypeDaddyVisibleFlags;
	extern s_string_list_definition equipmentAbilityTypeJetPackFlags;
	extern s_string_list_definition equipmentAbilityTypeHologramFlags;
	extern s_string_list_definition equipment_auto_turret_flags;
	extern s_string_list_definition equipment_remote_strike_flags;
	extern s_string_list_definition EquipmentSpecialMoveDefaultDirectionDefinition;
	extern s_string_list_definition equipment_engineer_shields_flags;
	extern s_string_list_definition activeShieldFlags;
	extern s_string_list_definition teleporterFlags;
	extern s_string_list_definition equipmentVisionModeFlags;
	extern s_string_list_definition equipmentHackerFlags;
	extern s_string_list_definition equipment_flags;
	extern s_string_list_definition equipment_activation_flags;
	extern s_string_list_definition equipmentActivationSecondaryFlags;
	extern s_string_list_definition equipment_activation_mode;
	extern s_string_list_definition equipment_pickup_behavior;

	extern s_tag_reference_definition global_equipment_reference;



} // namespace blofeld

