#pragma once

namespace blofeld
{


extern s_tag_struct bitmap_texture_interop_block_struct_struct_definition;
extern s_tag_block_definition bitmap_texture_interop_block;
extern s_tag_struct stitchable_bitmap_texture_interop_block_struct_struct_definition;
extern s_tag_block_definition stitchable_bitmap_texture_interop_block;
extern s_tag_struct bitmap_texture_interleaved_interop_block_struct_struct_definition;
extern s_tag_block_definition bitmap_texture_interleaved_interop_block;

constexpr unsigned long BITMAP_TAG = 'bitm';

extern s_tag_block_definition bitmap_block;
extern s_tag_group bitmap_group;
} // namespace blofeld

