#pragma once

namespace blofeld
{

namespace macaque
{

	constexpr unsigned long SCENARIO_LIGHTMAP_BSP_DATA_TAG = 'Lbsp';
	extern s_tag_group scenario_lightmap_bsp_data_group; // scenario_lightmap_bsp_data_block
	extern s_tag_block_definition scenario_lightmap_bsp_data_block;
	extern s_tag_struct_definition scenario_lightmap_bsp_data; // scenario_lightmap_bsp_data_block

	constexpr unsigned long SCENARIO_LIGHTMAP_TAG = 'sLdT';
	extern s_tag_group scenario_lightmap_group; // scenario_lightmap_block
	extern s_tag_block_definition scenario_lightmap_block;
	extern s_tag_struct_definition scenario_lightmap; // scenario_lightmap_block

	constexpr unsigned long SCENARIO_WETNESS_BSP_DATA_TAG = 'wetn';
	extern s_tag_group scenario_wetness_bsp_data_group; // scenario_wetness_bsp_data_block


	extern s_tag_block_definition scenario_wetness_bsp_data_block;
	extern s_tag_block_definition scenario_lightmap_cluster_data_block;
	extern s_tag_struct_definition scenario_lightmap_cluster_data_block_struct_definition; // scenario_lightmap_cluster_data_block
	extern s_tag_block_definition scenario_lightmap_instance_data_block;
	extern s_tag_struct_definition scenario_lightmap_instance_data_block_struct_definition; // scenario_lightmap_instance_data_block
	extern s_tag_block_definition scenario_lightmap_lightprobe_value_block;
	extern s_tag_struct_definition scenario_lightmap_lightprobe_value_block_struct_definition; // scenario_lightmap_lightprobe_value_block
	extern s_tag_block_definition scenario_lightmap_instance_index_block;
	extern s_tag_struct_definition scenario_lightmap_instance_index_block_struct_definition; // scenario_lightmap_instance_index_block
	extern s_tag_block_definition scenario_lightmap_global_perpixel_padding_data_block;
	extern s_tag_struct_definition scenario_lightmap_global_perpixel_padding_data_block_struct_definition; // scenario_lightmap_global_perpixel_padding_data_block
	extern s_tag_block_definition scenario_lightmap_rasterized_chart_data_block;
	extern s_tag_struct_definition scenario_lightmap_rasterized_chart_data_block_struct_definition; // scenario_lightmap_rasterized_chart_data_block
	extern s_tag_block_definition scenario_lightmap_rasterized_chart_source_block;
	extern s_tag_struct_definition scenario_lightmap_rasterized_chart_source_block_struct_definition; // scenario_lightmap_rasterized_chart_source_block
	extern s_tag_block_definition scenario_lightmap_rasterized_chart_element_block;
	extern s_tag_struct_definition scenario_lightmap_rasterized_chart_element_block_struct_definition; // scenario_lightmap_rasterized_chart_element_block
	extern s_tag_block_definition scenario_lightmap_new_ao_data_block;
	extern s_tag_struct_definition scenario_lightmap_new_ao_data_block_struct_definition; // scenario_lightmap_new_ao_data_block
	extern s_tag_block_definition scenario_lightmap_adjacent_bounce_vertex_block;
	extern s_tag_struct_definition scenario_lightmap_adjacent_bounce_vertex_block_struct_definition; // scenario_lightmap_adjacent_bounce_vertex_block
	extern s_tag_block_definition scenario_lightmap_adjacent_bounce_index_block;
	extern s_tag_struct_definition scenario_lightmap_adjacent_bounce_index_block_struct_definition; // scenario_lightmap_adjacent_bounce_index_block
	extern s_tag_block_definition triangle_mapping_per_mesh_block;
	extern s_tag_struct_definition triangle_mapping_per_mesh_block_struct_definition; // triangle_mapping_per_mesh_block
	extern s_tag_block_definition triangle_mapping_block;
	extern s_tag_struct_definition triangle_mapping_block_struct_definition; // triangle_mapping_block
	extern s_tag_block_definition scenario_lightmap_dynamic_light_instance_block;
	extern s_tag_struct_definition scenario_lightmap_dynamic_light_instance_block_struct_definition; // scenario_lightmap_dynamic_light_instance_block
	extern s_tag_block_definition scenario_lightmap_dynamic_light_instance_data_block;
	extern s_tag_struct_definition scenario_lightmap_dynamic_light_instance_data_block_struct_definition; // scenario_lightmap_dynamic_light_instance_data_block
	extern s_tag_block_definition scenario_lightmap_structure_light_instance_block;
	extern s_tag_struct_definition scenario_lightmap_structure_light_instance_block_struct_definition; // scenario_lightmap_structure_light_instance_block
	extern s_tag_block_definition s_scenario_lightmap_silhouette_vertex_block;
	extern s_tag_struct_definition s_scenario_lightmap_silhouette_vertex_block_struct_definition; // s_scenario_lightmap_silhouette_vertex_block
	extern s_tag_block_definition s_scenario_lightmap_silhouette_edge_block;
	extern s_tag_struct_definition s_scenario_lightmap_silhouette_edge_block_struct_definition; // s_scenario_lightmap_silhouette_edge_block
	extern s_tag_block_definition s_scenario_lightmap_silhouette_group_block;
	extern s_tag_struct_definition s_scenario_lightmap_silhouette_group_block_struct_definition; // s_scenario_lightmap_silhouette_group_block
	extern s_tag_block_definition scenario_lightmap_airprobe_value_block;
	extern s_tag_struct_definition scenario_lightmap_airprobe_value_block_struct_definition; // scenario_lightmap_airprobe_value_block
	extern s_tag_block_definition scenario_lightmap_bsp_data_reference_block;
	extern s_tag_struct_definition scenario_lightmap_bsp_data_reference_block_struct_definition; // scenario_lightmap_bsp_data_reference_block
	extern s_tag_block_definition wentness_bit_vector_block;
	extern s_tag_struct_definition wentness_bit_vector_block_struct_definition; // wentness_bit_vector_block
	extern s_tag_block_definition wentness_byte_vector_block;
	extern s_tag_struct_definition wentness_byte_vector_block_struct_definition; // wentness_byte_vector_block
	extern s_tag_block_definition cluster_wetness_offset_block;
	extern s_tag_struct_definition cluster_wetness_offset_block_struct_definition; // cluster_wetness_offset_block
	extern s_tag_block_definition instance_wetness_instance_block;
	extern s_tag_struct_definition instance_wetness_instance_block_struct_definition; // instance_wetness_instance_block

	extern s_tag_struct_definition dual_vmf_terms_array_struct_definition;
	extern s_tag_array_definition dual_vmf_terms_array;
	extern s_tag_struct_definition scenario_wetness_bsp_data_struct_definition; // tag group

	extern c_versioned_string_list lightmapDebugUVPolicyDefinition_strings;
	extern s_string_list_definition lightmapDebugUVPolicyDefinition;
	extern c_versioned_string_list scenario_lightmap_bsp_flags_strings;
	extern s_string_list_definition scenario_lightmap_bsp_flags;

	extern s_tag_reference_definition scenario_lightmap_bsp_data_reference;

} // namespace macaque

} // namespace blofeld

