#pragma once

namespace blofeld
{

namespace macaque
{

	extern s_tag_block_definition scenario_designer_zone_block;
	extern s_tag_struct_definition scenario_designer_zone_block_struct_definition; // scenario_designer_zone_block
	extern s_tag_block_definition scenarioDesignerZoneTagReferenceBlock_block;
	extern s_tag_struct_definition scenarioDesignerZoneTagReferenceBlock_block_struct_definition; // scenarioDesignerZoneTagReferenceBlock_block
	extern s_tag_block_definition biped_block_index_flags_block;
	extern s_tag_struct_definition biped_block_index_flags_block_struct_definition; // biped_block_index_flags_block
	extern s_tag_block_definition vehicle_block_index_flags_block;
	extern s_tag_struct_definition vehicle_block_index_flags_block_struct_definition; // vehicle_block_index_flags_block
	extern s_tag_block_definition weapon_block_index_flags_block;
	extern s_tag_struct_definition weapon_block_index_flags_block_struct_definition; // weapon_block_index_flags_block
	extern s_tag_block_definition equipment_block_index_flags_block;
	extern s_tag_struct_definition equipment_block_index_flags_block_struct_definition; // equipment_block_index_flags_block
	extern s_tag_block_definition scenery_block_index_flags_block;
	extern s_tag_struct_definition scenery_block_index_flags_block_struct_definition; // scenery_block_index_flags_block
	extern s_tag_block_definition machine_block_index_flags_block;
	extern s_tag_struct_definition machine_block_index_flags_block_struct_definition; // machine_block_index_flags_block
	extern s_tag_block_definition terminal_block_index_flags_block;
	extern s_tag_struct_definition terminal_block_index_flags_block_struct_definition; // terminal_block_index_flags_block
	extern s_tag_block_definition control_block_index_flags_block;
	extern s_tag_struct_definition control_block_index_flags_block_struct_definition; // control_block_index_flags_block
	extern s_tag_block_definition dispenser_block_index_flags_block;
	extern s_tag_struct_definition dispenser_block_index_flags_block_struct_definition; // dispenser_block_index_flags_block
	extern s_tag_block_definition sound_scenery_block_index_flags_block;
	extern s_tag_struct_definition sound_scenery_block_index_flags_block_struct_definition; // sound_scenery_block_index_flags_block
	extern s_tag_block_definition crate_block_index_flags_block;
	extern s_tag_struct_definition crate_block_index_flags_block_struct_definition; // crate_block_index_flags_block
	extern s_tag_block_definition creature_block_index_flags_block;
	extern s_tag_struct_definition creature_block_index_flags_block_struct_definition; // creature_block_index_flags_block
	extern s_tag_block_definition giant_block_index_flags_block;
	extern s_tag_struct_definition giant_block_index_flags_block_struct_definition; // giant_block_index_flags_block
	extern s_tag_block_definition effect_scenery_block_index_flags_block;
	extern s_tag_struct_definition effect_scenery_block_index_flags_block_struct_definition; // effect_scenery_block_index_flags_block
	extern s_tag_block_definition character_block_index_flags_block;
	extern s_tag_struct_definition character_block_index_flags_block_struct_definition; // character_block_index_flags_block
	extern s_tag_block_definition spawner_block_index_flags_block;
	extern s_tag_struct_definition spawner_block_index_flags_block_struct_definition; // spawner_block_index_flags_block
	extern s_tag_block_definition budget_reference_block_index_flags_block;
	extern s_tag_struct_definition budget_reference_block_index_flags_block_struct_definition; // budget_reference_block_index_flags_block
	extern s_tag_block_definition bink_block_index_flags_block;
	extern s_tag_struct_definition bink_block_index_flags_block_struct_definition; // bink_block_index_flags_block
	extern s_tag_block_definition scenarioDesignerResourceDependenciesBlock_block;
	extern s_tag_struct_definition scenarioDesignerResourceDependenciesBlock_block_struct_definition; // scenarioDesignerResourceDependenciesBlock_block


} // namespace macaque

} // namespace blofeld

