#pragma once

namespace blofeld
{


extern s_tag_struct scenario_designer_zone_block_block_struct;
extern s_tag_block_definition scenario_designer_zone_block_block;
extern s_tag_struct scenarioDesignerZoneTagReferenceBlock_block_struct;
extern s_tag_block_definition scenarioDesignerZoneTagReferenceBlock_block;
extern s_tag_struct biped_block_index_flags_block_block_struct;
extern s_tag_block_definition biped_block_index_flags_block_block;
extern s_tag_struct vehicle_block_index_flags_block_block_struct;
extern s_tag_block_definition vehicle_block_index_flags_block_block;
extern s_tag_struct weapon_block_index_flags_block_block_struct;
extern s_tag_block_definition weapon_block_index_flags_block_block;
extern s_tag_struct equipment_block_index_flags_block_block_struct;
extern s_tag_block_definition equipment_block_index_flags_block_block;
extern s_tag_struct scenery_block_index_flags_block_block_struct;
extern s_tag_block_definition scenery_block_index_flags_block_block;
extern s_tag_struct machine_block_index_flags_block_block_struct;
extern s_tag_block_definition machine_block_index_flags_block_block;
extern s_tag_struct terminal_block_index_flags_block_block_struct;
extern s_tag_block_definition terminal_block_index_flags_block_block;
extern s_tag_struct control_block_index_flags_block_block_struct;
extern s_tag_block_definition control_block_index_flags_block_block;
extern s_tag_struct dispenser_block_index_flags_block_block_struct;
extern s_tag_block_definition dispenser_block_index_flags_block_block;
extern s_tag_struct sound_scenery_block_index_flags_block_block_struct;
extern s_tag_block_definition sound_scenery_block_index_flags_block_block;
extern s_tag_struct crate_block_index_flags_block_block_struct;
extern s_tag_block_definition crate_block_index_flags_block_block;
extern s_tag_struct creature_block_index_flags_block_block_struct;
extern s_tag_block_definition creature_block_index_flags_block_block;
extern s_tag_struct giant_block_index_flags_block_block_struct;
extern s_tag_block_definition giant_block_index_flags_block_block;
extern s_tag_struct effect_scenery_block_index_flags_block_block_struct;
extern s_tag_block_definition effect_scenery_block_index_flags_block_block;
extern s_tag_struct character_block_index_flags_block_block_struct;
extern s_tag_block_definition character_block_index_flags_block_block;
extern s_tag_struct spawner_block_index_flags_block_block_struct;
extern s_tag_block_definition spawner_block_index_flags_block_block;
extern s_tag_struct budget_reference_block_index_flags_block_block_struct;
extern s_tag_block_definition budget_reference_block_index_flags_block_block;
extern s_tag_struct bink_block_index_flags_block_block_struct;
extern s_tag_block_definition bink_block_index_flags_block_block;
extern s_tag_struct scenarioDesignerResourceDependenciesBlock_block_struct;
extern s_tag_block_definition scenarioDesignerResourceDependenciesBlock_block;


} // namespace blofeld

