#pragma once

namespace blofeld
{


extern s_tag_struct structure_cluster_cubemap_struct_definition;
extern s_tag_block_definition structure_cluster_cubemap;
extern s_tag_struct cubemap_reference_points_block_struct_definition;
extern s_tag_block_definition cubemap_reference_points_block;
extern s_tag_struct scenario_cubemap_block_struct_definition;
extern s_tag_block_definition scenario_cubemap_block;

} // namespace blofeld

