#pragma once

namespace blofeld
{

extern s_tag_struct scenario_wetness_bsp_data_struct_definition_struct_definition;

extern s_tag_struct scenario_lightmap_cluster_data_struct_definition;
extern s_tag_block_definition scenario_lightmap_cluster_data;
extern s_tag_struct scenario_lightmap_instance_data_struct_definition;
extern s_tag_block_definition scenario_lightmap_instance_data;
extern s_tag_struct scenario_lightmap_lightprobe_value_struct_definition;
extern s_tag_block_definition scenario_lightmap_lightprobe_value;
extern s_tag_struct scenario_lightmap_instance_index_block_struct_definition;
extern s_tag_block_definition scenario_lightmap_instance_index_block;
extern s_tag_struct scenario_lightmap_global_perpixel_padding_data_struct_definition;
extern s_tag_block_definition scenario_lightmap_global_perpixel_padding_data;
extern s_tag_struct scenario_lightmap_rasterized_chart_data_struct_definition;
extern s_tag_block_definition scenario_lightmap_rasterized_chart_data;
extern s_tag_struct scenario_lightmap_rasterized_chart_source_struct_definition;
extern s_tag_block_definition scenario_lightmap_rasterized_chart_source;
extern s_tag_struct scenario_lightmap_rasterized_chart_element_struct_definition;
extern s_tag_block_definition scenario_lightmap_rasterized_chart_element;
extern s_tag_struct scenario_lightmap_new_ao_data_block_struct_definition;
extern s_tag_block_definition scenario_lightmap_new_ao_data_block;
extern s_tag_struct scenario_lightmap_adjacent_bounce_vertex_block_struct_definition;
extern s_tag_block_definition scenario_lightmap_adjacent_bounce_vertex_block;
extern s_tag_struct scenario_lightmap_adjacent_bounce_index_block_struct_definition;
extern s_tag_block_definition scenario_lightmap_adjacent_bounce_index_block;
extern s_tag_struct triangle_mapping_per_mesh_block_struct_definition;
extern s_tag_block_definition triangle_mapping_per_mesh_block;
extern s_tag_struct triangle_mapping_block_struct_definition;
extern s_tag_block_definition triangle_mapping_block;
extern s_tag_struct scenario_lightmap_dynamic_light_instance_struct_definition;
extern s_tag_block_definition scenario_lightmap_dynamic_light_instance;
extern s_tag_struct scenario_lightmap_dynamic_light_instance_data_block_struct_definition;
extern s_tag_block_definition scenario_lightmap_dynamic_light_instance_data_block;
extern s_tag_struct scenario_lightmap_structure_light_instance_struct_definition;
extern s_tag_block_definition scenario_lightmap_structure_light_instance;
extern s_tag_struct s_scenario_lightmap_silhouette_vertex_struct_definition;
extern s_tag_block_definition s_scenario_lightmap_silhouette_vertex;
extern s_tag_struct s_scenario_lightmap_silhouette_edge_struct_definition;
extern s_tag_block_definition s_scenario_lightmap_silhouette_edge;
extern s_tag_struct s_scenario_lightmap_silhouette_group_struct_definition;
extern s_tag_block_definition s_scenario_lightmap_silhouette_group;
extern s_tag_struct scenario_lightmap_airprobe_value_struct_definition;
extern s_tag_block_definition scenario_lightmap_airprobe_value;
extern s_tag_struct scenario_lightmap_bsp_data_reference_block_struct_definition;
extern s_tag_block_definition scenario_lightmap_bsp_data_reference_block;
extern s_tag_struct wentness_bit_vector_struct_definition;
extern s_tag_block_definition wentness_bit_vector;
extern s_tag_struct wentness_byte_vector_struct_definition;
extern s_tag_block_definition wentness_byte_vector;
extern s_tag_struct cluster_wetness_offset_block_struct_definition;
extern s_tag_block_definition cluster_wetness_offset_block;
extern s_tag_struct instance_wetness_instance_block_struct_definition;
extern s_tag_block_definition instance_wetness_instance_block;

constexpr unsigned long SCENARIO_LIGHTMAP_BSP_DATA_TAG = 'Lbsp';

extern s_tag_block_definition scenario_lightmap_bsp_data_block;
extern s_tag_group scenario_lightmap_bsp_data_group;
constexpr unsigned long SCENARIO_LIGHTMAP_TAG = 'sLdT';

extern s_tag_block_definition scenario_lightmap_block;
extern s_tag_group scenario_lightmap_group;
constexpr unsigned long SCENARIO_WETNESS_BSP_DATA_TAG = 'wetn';

extern s_tag_block_definition scenario_wetness_bsp_data_block;
extern s_tag_group scenario_wetness_bsp_data_group;
} // namespace blofeld

