#pragma once

namespace blofeld
{


extern s_tag_struct scenario_named_location_volume_block_struct_struct_definition;
extern s_tag_block_definition scenario_named_location_volume_block;
extern s_tag_struct named_location_volume_point_block_struct_definition;
extern s_tag_block_definition named_location_volume_point_block;

} // namespace blofeld

