#pragma once

namespace blofeld
{


extern s_tag_struct scenario_decorator_block_block_struct;
extern s_tag_block_definition scenario_decorator_block_block;
extern s_tag_struct decorator_palette_block_struct;
extern s_tag_block_definition decorator_palette_block;
extern s_tag_struct decorator_scenario_set_block_block_struct;
extern s_tag_block_definition decorator_scenario_set_block_block;
extern s_tag_struct global_decorator_placement_block_block_struct;
extern s_tag_block_definition global_decorator_placement_block_block;

extern s_tag_struct decorator_brush_struct_struct_definition;

} // namespace blofeld

