#pragma once

namespace blofeld
{


extern s_tag_struct scenario_scenery_block_block_struct;
extern s_tag_block_definition scenario_scenery_block_block;
extern s_tag_struct scenario_object_node_orientations_block_block_struct;
extern s_tag_block_definition scenario_object_node_orientations_block_block;
extern s_tag_struct scenario_object_node_orientations_bit_vector_block_block_struct;
extern s_tag_block_definition scenario_object_node_orientations_bit_vector_block_block;
extern s_tag_struct scenario_object_node_orientations_orientations_block_block_struct;
extern s_tag_block_definition scenario_object_node_orientations_orientations_block_block;
extern s_tag_struct scriptListBlock_block_struct;
extern s_tag_block_definition scriptListBlock_block;
extern s_tag_struct commandLinkBlock_block_struct;
extern s_tag_block_definition commandLinkBlock_block;
extern s_tag_struct pathfinding_object_index_list_block_block_struct;
extern s_tag_block_definition pathfinding_object_index_list_block_block;
extern s_tag_struct scenario_scenery_palette_block_block_struct;
extern s_tag_block_definition scenario_scenery_palette_block_block;
extern s_tag_struct scenario_biped_block_block_struct;
extern s_tag_block_definition scenario_biped_block_block;
extern s_tag_struct scenario_biped_palette_block_block_struct;
extern s_tag_block_definition scenario_biped_palette_block_block;
extern s_tag_struct scenario_vehicle_block_block_struct;
extern s_tag_block_definition scenario_vehicle_block_block;
extern s_tag_struct scenario_vehicle_palette_block_block_struct;
extern s_tag_block_definition scenario_vehicle_palette_block_block;
extern s_tag_struct scenario_equipment_block_block_struct;
extern s_tag_block_definition scenario_equipment_block_block;
extern s_tag_struct scenario_equipment_palette_block_block_struct;
extern s_tag_block_definition scenario_equipment_palette_block_block;
extern s_tag_struct scenario_weapon_block_block_struct;
extern s_tag_block_definition scenario_weapon_block_block;
extern s_tag_struct scenario_weapon_palette_block_block_struct;
extern s_tag_block_definition scenario_weapon_palette_block_block;
extern s_tag_struct device_group_block_block_struct;
extern s_tag_block_definition device_group_block_block;
extern s_tag_struct scenario_machine_block_block_struct;
extern s_tag_block_definition scenario_machine_block_block;
extern s_tag_struct scenario_machine_palette_block_block_struct;
extern s_tag_block_definition scenario_machine_palette_block_block;
extern s_tag_struct scenario_terminal_block_block_struct;
extern s_tag_block_definition scenario_terminal_block_block;
extern s_tag_struct scenario_terminal_palette_block_block_struct;
extern s_tag_block_definition scenario_terminal_palette_block_block;
extern s_tag_struct scenario_control_block_block_struct;
extern s_tag_block_definition scenario_control_block_block;
extern s_tag_struct scenario_control_palette_block_block_struct;
extern s_tag_block_definition scenario_control_palette_block_block;
extern s_tag_struct ScenarioDispenserBlock_block_struct;
extern s_tag_block_definition ScenarioDispenserBlock_block;
extern s_tag_struct ScenarioDispenserPaletteBlock_block_struct;
extern s_tag_block_definition ScenarioDispenserPaletteBlock_block;
extern s_tag_struct scenario_sound_scenery_block_block_struct;
extern s_tag_block_definition scenario_sound_scenery_block_block;
extern s_tag_struct scenario_sound_scenery_palette_block_block_struct;
extern s_tag_block_definition scenario_sound_scenery_palette_block_block;
extern s_tag_struct scenario_giant_block_block_struct;
extern s_tag_block_definition scenario_giant_block_block;
extern s_tag_struct scenario_giant_palette_block_block_struct;
extern s_tag_block_definition scenario_giant_palette_block_block;
extern s_tag_struct scenario_effect_scenery_block_block_struct;
extern s_tag_block_definition scenario_effect_scenery_block_block;
extern s_tag_struct scenario_effect_scenery_palette_block_block_struct;
extern s_tag_block_definition scenario_effect_scenery_palette_block_block;
extern s_tag_struct scenario_spawner_block_block_struct;
extern s_tag_block_definition scenario_spawner_block_block;
extern s_tag_struct scenario_spawner_palette_block_block_struct;
extern s_tag_block_definition scenario_spawner_palette_block_block;
extern s_tag_struct scenario_requisition_palette_block_block_struct;
extern s_tag_block_definition scenario_requisition_palette_block_block;
extern s_tag_struct scenario_crate_block_block_struct;
extern s_tag_block_definition scenario_crate_block_block;
extern s_tag_struct scenario_crate_palette_block_block_struct;
extern s_tag_block_definition scenario_crate_palette_block_block;
extern s_tag_struct scenario_creature_block_block_struct;
extern s_tag_block_definition scenario_creature_block_block;
extern s_tag_struct scenario_creature_palette_block_block_struct;
extern s_tag_block_definition scenario_creature_palette_block_block;

extern s_tag_struct scenario_object_id_struct_struct_definition;
extern s_tag_struct scenario_object_reference_struct_struct_definition;
extern s_tag_struct scenario_object_datum_struct_struct_definition;
extern s_tag_struct scenario_object_parent_struct_struct_definition;
extern s_tag_struct scenario_object_permutation_struct_struct_definition;
extern s_tag_struct scenario_scenery_datum_struct_v4_struct_definition;
extern s_tag_struct scenario_multiplayer_object_struct_struct_definition;
extern s_tag_struct scenario_unit_struct_struct_definition;
extern s_tag_struct scenario_vehicle_datum_struct_struct_definition;
extern s_tag_struct scenario_equipment_datum_struct_struct_definition;
extern s_tag_struct scenario_weapon_datum_struct_struct_definition;
extern s_tag_struct scenario_device_struct_struct_definition;
extern s_tag_struct scenario_machine_struct_v3_struct_definition;
extern s_tag_struct scenario_terminal_struct_struct_definition;
extern s_tag_struct scenario_control_struct_struct_definition;
extern s_tag_struct ScenarioDispenserStruct_struct_definition;
extern s_tag_struct sound_scenery_datum_struct_struct_definition;
extern s_tag_struct scenario_giant_datum_struct_struct_definition;
extern s_tag_struct scenario_effect_scenery_datum_struct_struct_definition;
extern s_tag_struct ScenarioEntityStruct_struct_definition;
extern s_tag_struct ScenarioSpawnerStruct_struct_definition;
extern s_tag_struct scenario_crate_datum_struct_struct_definition;

} // namespace blofeld

