#pragma once

namespace blofeld
{

	extern s_tag_struct_definition looping_sound_track_block_block_struct;
	extern s_tag_block_definition looping_sound_track_block_block;


	extern c_versioned_string_list looping_sound_fade_modes_strings;
	extern s_string_list_definition looping_sound_fade_modes;
	extern c_versioned_string_list looping_sound_layers_strings;
	extern s_string_list_definition looping_sound_layers;
	extern c_versioned_string_list looping_sound_track_flags_strings;
	extern s_string_list_definition looping_sound_track_flags;
	extern c_versioned_string_list looping_sound_track_layer_flags_strings;
	extern s_string_list_definition looping_sound_track_layer_flags;

} // namespace blofeld

