#pragma once

namespace blofeld
{



	extern s_tag_block_definition structure_bsp_sound_cluster_block;
	extern s_tag_struct_definition structure_bsp_sound_cluster_block_struct_definition; // structure_bsp_sound_cluster_block
	extern s_tag_block_definition structure_sound_cluster_portal_designators_block;
	extern s_tag_struct_definition structure_sound_cluster_portal_designators_block_struct_definition; // structure_sound_cluster_portal_designators_block
	extern s_tag_block_definition structure_sound_cluster_interior_cluster_indices_block;
	extern s_tag_struct_definition structure_sound_cluster_interior_cluster_indices_block_struct_definition; // structure_sound_cluster_interior_cluster_indices_block




} // namespace blofeld

