#pragma once

namespace blofeld
{


extern s_tag_struct game_incident_response_block_block_struct;
extern s_tag_block_definition game_incident_response_block_block;
extern s_tag_struct game_incident_daily_challenge_to_increment_block_block_struct;
extern s_tag_block_definition game_incident_daily_challenge_to_increment_block_block;
extern s_tag_struct specialized_incident_fanfare_block_block_struct;
extern s_tag_block_definition specialized_incident_fanfare_block_block;


} // namespace blofeld

