#pragma once

namespace blofeld
{

	extern const char* numeric_comparison_flags_strings[];
	extern s_string_list_definition numeric_comparison_flags;
	extern const char* suppressed_incident_flags_strings[];
	extern s_string_list_definition suppressed_incident_flags;
	extern const char* incident_definition_flags_strings[];
	extern s_string_list_definition incident_definition_flags;
	extern const char* specialized_incident_kill_bucket_flags_strings[];
	extern s_string_list_definition specialized_incident_kill_bucket_flags;
	extern const char* specializedIncidentGameOverFlags_strings[];
	extern s_string_list_definition specializedIncidentGameOverFlags;
	extern const char* specialized_incident_special_kill_type_enum_strings[];
	extern s_string_list_definition specialized_incident_special_kill_type_enum;
	extern const char* incident_accumulator_reset_enum_strings[];
	extern s_string_list_definition incident_accumulator_reset_enum;
	extern const char* incident_accumulator_aggregation_method_enum_strings[];
	extern s_string_list_definition incident_accumulator_aggregation_method_enum;

	constexpr unsigned long INCIDENT_GLOBAL_PROPERTIES_DEFINITION_TAG = 'igpd';

	extern s_tag_group incident_global_properties_definition_group;
	constexpr unsigned long INCIDENT_GLOBALS_DEFINITION_TAG = 'ingd';

	extern s_tag_struct incident_globals_definition_block_struct;
	extern s_tag_block_definition incident_globals_definition_block;
	extern s_tag_group incident_globals_definition_group;
	constexpr unsigned long SUPPRESSEDINCIDENT_TAG = 'sigd';

	extern s_tag_group SuppressedIncident_group;

	extern s_tag_block_definition incident_global_properties_definition_block_block;
	extern s_tag_block_definition SuppressedIncident_block_block;
	extern s_tag_struct incident_definition_block_block_struct;
	extern s_tag_block_definition incident_definition_block_block;
	extern s_tag_struct suppressed_incident_block_block_struct;
	extern s_tag_block_definition suppressed_incident_block_block;
	extern s_tag_struct SuppressedIncidentBlockReferenceDefinition_block_struct;
	extern s_tag_block_definition SuppressedIncidentBlockReferenceDefinition_block;
	extern s_tag_struct specialized_incident_block_block_struct;
	extern s_tag_block_definition specialized_incident_block_block;
	extern s_tag_struct specialized_incident_kill_implement_block_block_struct;
	extern s_tag_block_definition specialized_incident_kill_implement_block_block;
	extern s_tag_struct specialized_incident_object_properties_block_block_struct;
	extern s_tag_block_definition specialized_incident_object_properties_block_block;
	extern s_tag_struct specialized_incident_object_riding_in_vehicle_properties_block_block_struct;
	extern s_tag_block_definition specialized_incident_object_riding_in_vehicle_properties_block_block;
	extern s_tag_struct specialized_incident_special_kill_type_block_block_struct;
	extern s_tag_block_definition specialized_incident_special_kill_type_block_block;
	extern s_tag_struct specializedIncidentGameOverBlock_block_struct;
	extern s_tag_block_definition specializedIncidentGameOverBlock_block;
	extern s_tag_struct specializedIncidentRandomOrdnanceBlock_block_struct;
	extern s_tag_block_definition specializedIncidentRandomOrdnanceBlock_block;
	extern s_tag_struct specializedIncidentCustomDataFilterBlock_block_struct;
	extern s_tag_block_definition specializedIncidentCustomDataFilterBlock_block;
	extern s_tag_struct specializedIncidentDistanceFilterBlock_block_struct;
	extern s_tag_block_definition specializedIncidentDistanceFilterBlock_block;
	extern s_tag_struct incident_accumulator_block_block_struct;
	extern s_tag_block_definition incident_accumulator_block_block;
	extern s_tag_struct incident_accumulator_child_incident_block_block_struct;
	extern s_tag_block_definition incident_accumulator_child_incident_block_block;
	extern s_tag_struct incident_sum_accumulator_block_block_struct;
	extern s_tag_block_definition incident_sum_accumulator_block_block;
	extern s_tag_struct incident_sum_accumulator_child_incident_block_block_struct;
	extern s_tag_block_definition incident_sum_accumulator_child_incident_block_block;

	extern s_tag_struct incident_global_properties_definition_struct_definition_struct_definition; // tag group
	extern s_tag_struct SuppressedIncident_struct_definition_struct_definition; // tag group

} // namespace blofeld

