#pragma once

namespace blofeld
{


extern s_tag_struct game_incident_response_block_struct_struct_definition;
extern s_tag_block_definition game_incident_response_block;
extern s_tag_struct game_incident_daily_challenge_to_increment_block_struct_definition;
extern s_tag_block_definition game_incident_daily_challenge_to_increment_block;
extern s_tag_struct specialized_incident_fanfare_block_struct_definition;
extern s_tag_block_definition specialized_incident_fanfare_block;

} // namespace blofeld

