#pragma once

namespace blofeld
{

extern s_tag_struct incident_global_properties_definition_struct_definition_struct_definition;
extern s_tag_struct SuppressedIncident_struct_definition_struct_definition;

extern s_tag_struct incident_definition_block_struct_struct_definition;
extern s_tag_block_definition incident_definition_block;
extern s_tag_struct suppressed_incident_block_struct_definition;
extern s_tag_block_definition suppressed_incident_block;
extern s_tag_struct SuppressedIncidentBlockReferenceDefinition_struct_definition;
extern s_tag_block_definition SuppressedIncidentBlockReferenceDefinition;
extern s_tag_struct specialized_incident_block_struct_definition;
extern s_tag_block_definition specialized_incident_block;
extern s_tag_struct specialized_incident_kill_implement_block_struct_definition;
extern s_tag_block_definition specialized_incident_kill_implement_block;
extern s_tag_struct specialized_incident_object_properties_block_struct_definition;
extern s_tag_block_definition specialized_incident_object_properties_block;
extern s_tag_struct specialized_incident_object_riding_in_vehicle_properties_block_struct_definition;
extern s_tag_block_definition specialized_incident_object_riding_in_vehicle_properties_block;
extern s_tag_struct specialized_incident_special_kill_type_block_struct_definition;
extern s_tag_block_definition specialized_incident_special_kill_type_block;
extern s_tag_struct specializedIncidentGameOverBlock_struct_definition;
extern s_tag_block_definition specializedIncidentGameOverBlock;
extern s_tag_struct specializedIncidentRandomOrdnanceBlock_struct_definition;
extern s_tag_block_definition specializedIncidentRandomOrdnanceBlock;
extern s_tag_struct specializedIncidentCustomDataFilterBlock_struct_definition;
extern s_tag_block_definition specializedIncidentCustomDataFilterBlock;
extern s_tag_struct specializedIncidentDistanceFilterBlock_struct_definition;
extern s_tag_block_definition specializedIncidentDistanceFilterBlock;
extern s_tag_struct incident_accumulator_block_struct_definition;
extern s_tag_block_definition incident_accumulator_block;
extern s_tag_struct incident_accumulator_child_incident_block_struct_definition;
extern s_tag_block_definition incident_accumulator_child_incident_block;
extern s_tag_struct incident_sum_accumulator_block_struct_definition;
extern s_tag_block_definition incident_sum_accumulator_block;
extern s_tag_struct incident_sum_accumulator_child_incident_block_struct_definition;
extern s_tag_block_definition incident_sum_accumulator_child_incident_block;

constexpr unsigned long INCIDENT_GLOBAL_PROPERTIES_DEFINITION_TAG = 'igpd';

extern s_tag_block_definition incident_global_properties_definition_block;
extern s_tag_group incident_global_properties_definition_group;
constexpr unsigned long INCIDENT_GLOBALS_DEFINITION_TAG = 'ingd';

extern s_tag_block_definition incident_globals_definition_block;
extern s_tag_group incident_globals_definition_group;
constexpr unsigned long SUPPRESSEDINCIDENT_TAG = 'sigd';

extern s_tag_block_definition SuppressedIncident_block;
extern s_tag_group SuppressedIncident_group;
} // namespace blofeld

